### ISSUE TITLE
Suggestion for Integer in Standard library

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda-stdlib#1]
Reported by mechvel@botik.ru, Jan 10, 2014

The following is suggested for  Data.Sign.Properties  and
                                Data.Integer, Data.Integer.Properties.
1. For  Data.Sign :
   
   _s-assoc : Associative __s_
   _s-comm  : Commutative __s_
   *s-invol : (s : Sign) → s *s s ≡ Sign.+

This is for  _*s_ = Sign._*_.
I use these lemmata, and they are evidently of a general use.
1. For  Data.Integer, Data.Integer.Properties :

_divMod_  is desirable for division with remainder, with proofs.

It can be lifted from  Nat.DivMod._divMod_.
But this lift still needs implementation.

For example, I need

  decDivide : (x y : ℤ) → Dec $ RightQuotient intSetoid _*_ x y

-- which also returns proof/disprove for     \exist \q -> y \* q == y.
It can be either by calling  Integer._divMod_ 
or by lifting to ℤ from a similar  decDivide-Nat  for Nat.
My implementation for this lifting takes about 200 lines
(despite that the subject looks trivial).

I think,  Integer._divMod_  will help in this and in many other cases,
and I suspect that its lifting to  ℤ  will take not less than 100 lines.
1. The following are useful :
   
   negneg : (x : ℤ) → - (- x) ≡ + x
   
   x+◃ : (m : ℕ) → (Sign.+ ◃ m) ≡ + m
   -◃  : (m : ℕ) → (Sign.- ◃ m) ≡ - (+ m)
   
   +m*+n= : (m n : ℕ) → (+ m) \* (+ n) ≡ + (m *n n)
   
   -*- : (x y : ℤ) → (- x) \* (- y) ≡ x \* y
   
   s◃m*s'◃n : (s s' : Sign) → (m n : ℕ) →
                              (s ◃ m ) \* (s' ◃ n) ≡ (s *s s') ◃ (m *n n)

(for the last one I have a proof of about 30 lines).

**Comment by MatthewDaggitt** [comment]
The requested lemmas have been added in 1695680e09a4f45a2b476010bfcdb25295ac329c and 994655630cbe137bcdde8b8071c8bd61ee1e6162
