### ISSUE TITLE
Add aliases for `refl`, `sym` and `prep` which do not require equalities in `Permutation.Setoid`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#1004]

**Comment by JacquesCarette** [comment]
Could you give an actual description? Right now, I think you might be the only one who really understands the intent of this issue. I feel like I ought to, but I don't.

**Comment by MatthewDaggitt** [comment]
Ah sorry! At the moment I'm writing a lot of code of the form `swap refl refl p` and `prep refl p`. I'd quite like some shortcuts that would just allow me to write `prep′ p` and `swap′ p` for when the first elements are propositionally equal..

**Comment by MatthewDaggitt** [comment]
Fixed with 06c14ea
