### ISSUE TITLE
Official releases

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-stdlib#1005]
If I go to https://github.com/agda/agda-stdlib/releases then, by default, it shows the 'current release' as v1.0, and I have to click through to expand things to see that v1.2 even exists. That's probably a git configuration issue - but it kind of threw me for a loop.  Does anyone know how to fix that?

**Comment by MatthewDaggitt** [comment]
Just added  `v1.1` and `v1.2` releases now. Just added a note to the release guide as well in 91bdfdbd.

(Fastest ever issue resolution time of 5 minutes :smile:)
