### ISSUE TITLE
Port Firsov and Uustalu's Dependently typed programming with finite sets

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#1024]
In this paper Firsov and Uustalu give different definitions of "finite set"
and formally study their relationships. They also provide combinators to
define functions on finite sets & prove formulas quantified over finite sets.

https://dl.acm.org/citation.cfm?id=2808102

[Paper on Firsov's page](http://firsov.ee/finset/finset.pdf)

**Comment by MatthewDaggitt** [comment]
This should probably be a suggestion in #863 rather than a new issue?
