### ISSUE TITLE
a strange Algebra.Morphism.Definitions

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1025]
Algebra.Morphism.Definitions  puts ``Morphism = A → B``,
while there is a more classical word  `Map`.
Further, it puts  ``Homomorphic₁ : Morphism → Fun₁ A → Op₁ B → Set _``

`Fun₁` and `Op₁` are defined in different modules, and their definitions differ only in renaming variables. Am I missing something? What does this all mean?

For example, the definition 
```
  Homomorphic₂ : Morphism → Fun₂ A → Op₂ B → Set _      
  Homomorphic₂ ⟦_⟧ _∙_ _∘_ = ∀ x y → ⟦ x ∙ y ⟧ ≈ (⟦ x ⟧ ∘ ⟦ y ⟧)
```
will be more clear to the reader in the form of 
```
  Homomorphic₂ :  (A → B) → Op₂ A → Op₂ B → Set _      
  Homomorphic₂ ⟦_⟧ _∙_ _∘_ = ∀ x y → ⟦ x ∙ y ⟧ ≈ (⟦ x ⟧ ∘ ⟦ y ⟧)
```
-- ?

**Comment by JacquesCarette** [comment]
I agree that the proposed 
```agda
Homomorphic₂ :  (A → B) → Op₂ A → Op₂ B → Set _ 
```
is much more readable/evocative.  The hiding of `A` and `B` under `Morphism` (or `Map`) is distinctly unhelpful.

**Comment by riz0id** [comment]
can we also go ahead and combine the redundant definitions [`Algebra.Core`](https://github.com/agda/agda-stdlib/blob/master/src/Algebra/Core.agda) and [`Function.Core`](https://github.com/agda/agda-stdlib/blob/master/src/Function/Core.agda). `Funₙ` is more truthful in name but is never used outside of `Algebra.Morphism.Definition` and of course `Opₙ` is scattered all throughout `Relation`

**Comment by MatthewDaggitt** [comment]
> can we also go ahead and combine the redundant definitions Algebra.Core and Function.Core. Funₙ is more truthful in name but is never used outside of Algebra.Morphism.Definition and of course Opₙ is scattered all throughout Relation

In my opinion it's the definition of `Fun` that is both not general enough and at the same time completely useless as we have the arrow notation built into Agda.
