### ISSUE TITLE
Update instructions for `fix-agda-whitespace`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#1040]
In:
- HACKING.md
- GNUmakefile

**Comment by gallais** [comment]
[In this PR](https://github.com/agda/agda-stdlib/pull/1048) I have updated the makefile and it works for me.
In the `HACKING.md` we basically need to tell people to install https://github.com/agda/fix-whitespace

**Comment by MatthewDaggitt** [comment]
Hmm so I've installed `fix-whitespace` from the repository and am trying to run it but it's not picking up any of the whitespace problems. All of the below seem to exit without complaint even when there is a whitespace problem:
```
fix-whitespace
fix-whitespace --check
cabal exec -- fix-whitespace --check
```
Anyone have any idea what I'm doing wrong? Pinging @L-TChen in particular!

**Comment by L-TChen** [comment]
Do you have a configuration `fix-whitespace.yaml` in the working directory?

**Comment by gallais** [comment]
In the PR mentioned above I have put a yaml file in the `travis/` directory.
It should maybe be moved to the main directory (or `fix-whitespace` should be
made to accept a command line argument pointing at the location of such a file).

**Comment by MatthewDaggitt** [comment]
> It should maybe be moved to the main directory

I'd vote for this solution. We don't want to make contributing to the library any more complicated than necessary...

**Comment by L-TChen** [comment]
I will add an option for specifying a location in the future anyway.
