### ISSUE TITLE
`tabulate` disappeared?

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1043]
The following was in old standard library releases, but I do not find it in lib-1.2:
```
tabulate : ∀ {a p} {A : Set a} {P : A → Set p} {xs} → (∀ {x} → x ∈ xs → P x) → All P xs
```
(I think, it needs to be for a Setoid and its related `_∈_`).
Am I missing something?
The thing is widely usable.

**Comment by gallais** [comment]
[I can see it](https://agda.github.io/agda-stdlib/Data.List.Relation.Unary.All.html#2367)

**Comment by mechvel** [comment]
I see, thank you.
