### ISSUE TITLE
Update `README.Data.Nat/Integer` with new reasoning and tactics

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#1049]
After the ring solver has been merged in (#922), we should update the README to demonstrate the new equational reasoning (instead of propositional reasoning) and the solvers.

**Comment by jamesmckinna** [comment]
Fixed since #1090 (and possibly others, but this seems to be the main one)? Close now?

**Comment by JacquesCarette** [comment]
I agree that #1090 fixes it - I think two pair of eyes agreeing this is done should be enough, closing.
