### ISSUE TITLE
inclusion of Function.BiInverse

### ISSUE THREAD

**Issue by pnlph** [agda/agda-stdlib#1055]
Hi,

i would like to add the definition of equivalence from [Jesper Cockx's thesis](https://limo.libis.be/primo-explore/fulldisplay?docid=LIRIAS1656778&context=L&vid=Lirias&search_scope=Lirias&tab=default_tab&lang=en_US). There is already a module named `Function.Equivalence` so we could call this module `Function.BiInverse`

What do you think? Any suggestions?

**Comment by jespercockx** [comment]
I want to mention that I suggested the name BiInverse because that is what the concept is called in the HoTT book (https://hott.github.io/book/nightly/hott-online-1239-g9a4dadb.pdf#page=148)

**Comment by MatthewDaggitt** [comment]
Any chance you could give the definition and/or a page reference?

(Probably) no objections to adding it, however we're trying to deprecate the `Function.Equivalence/Injection/Surjection/...` modules in favour of the new `Function.Structures` and `Function.Bundles` modules so it should probably live in there.

**Comment by pnlph** [comment]
Yes, you can take a look at [BiInverse.agda](https://gist.github.com/pnlph/5908275291bc1d62b346962c19b65ffa)

**Comment by MatthewDaggitt** [comment]
Yup, no objections to adding to `IsBiInverse` to `Function.Structures` and `BiInverse` to `Function.Bundles`. 

Unsure what sort of arrow symbol we'd use to represent the propositional bundle. Personally I'd be favour of `_↩↪_` which is the composition of the symbols we use for the left and right inverses
