### ISSUE TITLE
Add rounding operations to `Data.Rational`

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#1063]
[This interesting article](https://ren.zone/articles/safe-money) suggests useful operations we may want to have on rational numbers:

```agda
round floor ceiling truncate : ℚ → ℤ × ℚ
```

together with the proofs of their properties, of course.

**Comment by MatthewDaggitt** [comment]
Hmm I'd be tempted to have the standard signature `ℚ → ℤ` for those operations then have another operator `frac : ℚ →ℚ` that returns the fractional part. Presumably they're simply going to be implemented by the `_/_` and `_%_` operators respectively so it's not like they have any computational overlap.

**Comment by barrettj12** [comment]
I've just opened a PR #1585 which implements the suggested functions. I have not been able to prove any properties about said functions. Should we open a new issue for the implementation of those properties?
