### ISSUE TITLE
`check-whitespace' failed in _master_

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1074]
The current _master_ is not type-checked in my local tree.
``... make test`` reports

cabal: The program 'fix-whitespace' is required but it could not be found.

Plesae, see my report in #1026.

**Comment by gallais** [comment]
See [HACKING.md](https://github.com/agda/agda-stdlib/blob/master/HACKING.md#installing-fix-whitespace)

**Comment by mechvel** [comment]
This occurs new that it requires  fix-whitespace !

Well, I install  fix-whitespace,
and now ``make test`` ends with

-----------------------------------------
/home/mechvel/agda/stLib/agda-stdlib-fork/src/Data/Table/Base.agda:11,5: 
Parse error
WARNING_ON_IMPORT<ERROR>

"Data.Table.Base was deprecat...
-----------------------------------------

?

**Comment by gallais** [comment]
`master` now requires Agda 2.6.1 as we are catching up with the development
version to release both Agda and the standard library at the same time in
the very near future.
