### ISSUE TITLE
deprecated Data.Table.Base in master

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1075]
The current _master_ is not type-checked,
because Data.Table.Base is used in several places, and this module is deprecated.
- ?

Also HACKING.md suggests  fix-whitespace, which is used in ``make test``.
But before  ``make test`` one needs to command ``> fix-agda-whitespace``
(while fix-whitespace is not found). And HACKING.md does not mention fix-agda-whitespace.
Does HACKING.md need correction at this point?

**Comment by MatthewDaggitt** [comment]
> The current master is not type-checked,
> because Data.Table.Base is used in several places, and this module is deprecated.

It is type-checked, it just has warnings attached to it. We already have an issue open: #870. 

> Also HACKING.md suggests fix-whitespace, which is used in make test.
> But before make test one needs to command > fix-agda-whitespace
> (while fix-whitespace is not found). And HACKING.md does not mention fix-agda-whitespace.
> Does HACKING.md need correction at this point?

`fix-agda-whitespace` has been removed in favour of `fix-whitespace`. The instructions in HACKING.md are correct (see #1040).
