### ISSUE TITLE
Make naming of decidability proofs for in `Data.X.Relation` consistent

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#1082]
`Data.List.Relation.Unary.All/Any` have `any`/`all` but the others all have `linked?`/`allPairs?`/`unique?` etc.

I think I'm in favour of the latter and so propose to rename `any`/`all` to `any?`/`all?`.

**Comment by umazalakain** [comment]
I'd be happy to get this through if that's ok?

**Comment by MatthewDaggitt** [comment]
Go for it 🎉  You'll need to deprecate the old names using the `WARNING_ON_USAGE` pragmas as seen elsewhere in the library and then chase down the uses of the old names. Let us know if you have any problems or questions.
