### ISSUE TITLE
Type error in Data.Erased

### ISSUE THREAD

**Issue by nad** [agda/agda-stdlib#1093]
According to a recent commit (d67e53e09c577695b1100d17d22a27fbe0396c2a) "both the `master` and the `experimental` branches currently require the latest development version of Agda". However, the master branch lacks some commits from the experimental branch, leading to a type error in `Data.Erased`.

**Comment by MatthewDaggitt** [comment]
Ah I'd missed that some things were being added to `experimental`. Until Agda 2.6.1 is released, nothing should be being added to experimental at all. I'll fix it now.

**Comment by MatthewDaggitt** [comment]
Fixed with 71c8a5023bccbdb70f8425d57fc5d5860d435909. `master` should work again now :+1:
