### ISSUE TITLE
new EqReasoning 

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1102]
This is about the Development stdlib of March 5, 2020.
Please, return the old version of EqReasoning in a setoid !

1) Renaming the constructors like ``_≈⟨_⟩_`` has become a messy, brain-twisting  matter.
2) In some situations it is difficult to arrange things without the above renaming.
For example, consider an equality (``_=fr_``) proof for Fraction over A that also uses an equality proof for  A (``_≈_``).  With renaming constructors, it is written naturally: 
```  
foo  f g =   
  begin-fr  f *fr g       =fr[ =fr-refl {f *fr g}  ]    -- proof in Fraction
                ...
  end-fr
  where
  ...
  eq = begin n₁ * n₂     ≈⟨ *-cong n₁≈n₁'g₁ n₂≈n₂'g₂ ⟩   -- proof in A
                     ...
         ∎    
```
(I wonder how to fix here indentation in this GitHub editor).
Without renaming, the first "begin" is under  ``open (SetoidReasoning fraction-setoid)``,
and the second "begin" is under  ``open (SetoidReasoning A-setoid)``.
And their name spaces overlap.
This can be fixed by writing  
```
foo  f g = eq'
   where
   eq' = ...
   ...
   eq = ...
```
But this code looks worse that the initial one.

**Comment by MatthewDaggitt** [comment]
In the case where you want to use equational reasoning over different setoids in one file, you shouldn't be opening and renaming multiple instances of `Reasoning.Setoid` but instead be using ['Reasoning.MultiSetoid'](https://github.com/agda/agda-stdlib/blob/master/src/Relation/Binary/Reasoning/MultiSetoid.agda) which has support for using multiple different setoids built-in. I'll add a note in the changelog referring to it.

Yes renaming the combinators becomes a bit harder using the new design, but I think the trade-offs are worth it. In particular the improved type-checking speed should be helpful for your project which takes over an hour to type-check!

**Comment by WolframKahl** [comment]
In `Reasoning.MultiSetoid`, is it intentional that the syntax for `step-≈˘` has the converse symbol inside the hint bracket instead of outside?
````agda
  syntax step-≈˘ x y∼z y≈x = x ≈⟨˘ y≈x ⟩ y∼z
  syntax step-≡˘ x y≡z y≡x = x ≡˘⟨ y≡x ⟩ y≡z
````

**Comment by MatthewDaggitt** [comment]
No it's not. That should be changed.

(As an aside, I wish I had put the converse symbol inside the bracket when we added this notation, as the brackets align everything so much better... but that ship has long sailed!)

**Comment by MatthewDaggitt** [comment]
Fixed with b69dc60e3dc0a02a48a9f22354279e399823dc2e

**Comment by mechvel** [comment]
On 2020-03-08 11:16, MatthewDaggitt wrote:
> In the case where you want to use equational reasoning over different
> setoids in one file, you shouldn't be opening and renaming multiple
> instances of Reasoning.Setoid but instead be using
> 'Reasoning.MultiSetoid' [1] which has support for using multiple
> different setoids built-in. I'll add a note in the changelog referring
> to it.
> 
> Yes renaming the combinators becomes a bit harder using the new
> design, but I think the trade-offs are worth it. In particular the
> improved type-checking speed should be helpful for your project which
> takes over an hour to type-check!
> 


1) As I wrote, "built-in" sounds suspicious.
2) With Reasoning.MultiSetoid, I have now

   ++assoc (x ∷ xs) ys zs =
              begin⟨ PE.setoid (List A) ⟩             -- for  _≡_ on List 
A
                ...
                x ∷ ((xs ++ ys) ++ zs)    ≈⟨ cong (_∷_ x) (++assoc xs ys 
zs) ⟩
                ...
              ∎

   length-xs≤length-xs++ :  ∀ xs {ys : List A} → lng xs ≤ lng (xs ++ ys)
   length-xs≤length-xs++ xs {ys} =
                         begin lng xs             ≤⟨ m≤m+n (lng xs) (lng 
ys) ⟩
                               lng xs + lng ys    ≡⟨ sym (length-++ xs) ⟩
                               lng (xs ++ ys)
                         ∎
                         where open ≤-Reasoning

And Agda 2.6.1 reports
Ambiguous name step-≡. It could refer to any one of
   ≤-Reasoning.step-≡ ...
   Relation.Binary.Reasoning.MultiSetoid.step-≡  ...

Please, what would you advise?

------
Sergei

**Comment by MatthewDaggitt** [comment]
>  As I wrote, "built-in" sounds suspicious.

@gallais has addressed this point. I was using the word "built-in" in the general sense rather than the Agda specific sense.

> Please, what would you advise?

I would do as the standard library does everywhere and simply open them on a per proof basis.

```agda
++assoc (x ∷ xs) ys zs =
  ...
  where open import Relation.Binary.Reasoning.MultiSetoid

length-xs≤length-xs++ xs {ys} =
  ...
  where open ≤-Reasoning
```

Hope that helps!

**Comment by mechvel** [comment]
I  have done the example  with  ``..Reasoning.Multisetoid  + Data.Nat.Properties.≤-Reasoning``.
And now the problem is  with using ``PreorderReasoning``  in
```
import  Relation.Binary.Reasoning.Preorder as PreorderReasoning
...
module OfMax {α α= α≤} (dto : DecTotalOrder α α= α≤) 
  where
  open DecTotalOrder dto using (preorder; isPreorder; total; _≈_; _≤_;  ...)
   ...   
  max2-monot :  ∀ {x x' y y'} → x ≤ x' → y ≤ y' → max2 x y ≤ max2 x' y'
  max2-monot {x} {x'} {y} {y'} x≤x' y≤y'   with  extMax x y | extMax x' y'
  ...  | maxᶜ m (inj₁ m≡x) _ | maxᶜ m' _ (x'≤m' , _) =  
                                               begin m     ≡⟨ m≡x ⟩
                                                         x      ~⟨ x≤x' ⟩
                                                         x'     ~⟨ x'≤m' ⟩ 
                                                        m'
                                               ∎
         where  open PreorderReasoning preorder 
```
This latter follows the comment in  "Example uses: ..." in the beginning of 
Relation/Binary/Reasoning/Preorder.agda.
And it is not parsed, probably due to not recognizing the operators  ``begin, ∎,  ≡⟨_⟩``.
I lib-1.2, the program renamed the combinators, may be not nicely, but at least it worked.
And now I am confused with denotations.

**Comment by gallais** [comment]
> And it is not parsed

What is the error message? Hard to diagnose without more context.

**Comment by mechvel** [comment]
```
/home/mechvel/inAgda/poly/0.2/List/L2.agda:351,48-355,49
Could not parse the application
begin m ≡⟨ m≡x ⟩ x ~⟨ x≤x' ⟩ x' ~⟨ x'≤m' ⟩ m' ∎
Operators used in the grammar:
  ∎     (postfix operator, level 3) [_∎ (/home/mechvel/agda/stLib/1.3/src/Relation/Binary/Reasoning/Base/Double.agda:106,1-3)]   
  begin (prefix operator, level 1)  [begin_ (/home/mechvel/agda/stLib/1.3/src/Relation/Binary/Reasoning/Base/Double.agda:64,1-7)]
  ≡⟨_⟩  (infixr notation, level 2)  [step-≡ (/home/mechvel/agda/stLib/1.3/src/Relation/Binary/Reasoning/Base/Double.agda:90,1-7)]
when scope checking begin m ≡⟨ m≡x ⟩ x ~⟨ x≤x' ⟩ x' ~⟨ x'≤m' ⟩ m' ∎
```

**Comment by gallais** [comment]
`_~⟨_⟩_` is not listed here so it is not in scope. It may be that you are using
`\~` instead of `~` (or the other way around). Can you try to swap these around?

**Comment by mechvel** [comment]
Yes,  ``\~`` does work!  Thank you.

``~`` is easier to enter, why not to choose it?

**Comment by MatthewDaggitt** [comment]
Have to confess I'm unsure. The `\~` symbol was widely used before my time. Maybe @nad would remember the reason?

**Comment by nad** [comment]
I don't remember exactly. The Unicode standard lists "similar to" as one of the meanings of `∼` (TILDE OPERATOR). In the font that I typically use for Agda the two glyphs are clearly distinct, and TILDE OPERATOR looks more like the mathematical operator `\sim` typeset in LaTeX.

By the way, one alternative to renaming operators is to use qualified names.
