### ISSUE TITLE
+-*-semiring vs *-+-semiring 

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1103]
In Development stdlib of March 5, 2020, I see
``Integer.Properties.+-*-semiring``  and 
``Nat.Properties.*-+-semiring``.

Probably, a uniformity is needed here and everywhere (Binary ...),
and for IsSemiring too. 
I vote for  ``+-*``.

**Comment by MatthewDaggitt** [comment]
Agreed. I also prefer `+-*`.
