### ISSUE TITLE
agda 2.6.1 RC2, experimental branch check failure on Windows

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-stdlib#1107]
Using Agda-2.6.0.1.20200307 against commit 393c57a of experimental, most of it typechecks, but eventually I get

```
   Checking Data.Table.Properties (C:\Users\jacqu\agda-stdlib\src\Data\Table\Properties.agda).
C:\Users\jacqu\agda-stdlib\src\Algebra\Properties\CommutativeMonoid.agda:27,13-32
Data.Table was deprecated in v1.2.
Use Data.Vec.Functional instead.
when scope checking the declaration
  open import Data.Table as Table
C:\Users\jacqu\agda-stdlib\src\Algebra\Properties\CommutativeMonoid.agda:28,13-66
Data.Table.Relation.Binary.Equality was deprecated in v1.2.
Use Data.Vec.Functional.Relation.Binary.Pointwise instead.
when scope checking the declaration
  open import Data.Table.Relation.Binary.Equality as TE using (_C:\Users\jacqu\agda-stdlib\Everything.agda:126,1-44
<stdout>: commitBuffer: invalid argument (invalid character)
```
where things choke on the `≗` character.

[I should be testing `experimental`, not `master`, right?]

**Comment by JacquesCarette** [comment]
Follow-up: `master` worked.

**Comment by gallais** [comment]
Is this related? https://github.com/agda/agda/issues/4506#issuecomment-596589291

**Comment by JacquesCarette** [comment]
I believe that it is the exact same bug.  I thought it was a library-side issue, but it might be an agda-side problem.  [Though why it arises with `experimental` but not `master` is puzzling].  Feel free to close this as a 'duplicate'.

**Comment by asr** [comment]
> Though why it arises with `experimental` but not `master` is puzzling

The issue didn't arise in `master` because the deprecation warnings are silenced by
https://github.com/agda/agda-stdlib/blob/ef78949859cabb29b56beed778bce25b4dae2073/src/Algebra/Properties/CommutativeMonoid.agda#L9-L10

**Comment by JacquesCarette** [comment]
Ok, then this is definitely a duplicate - closing.
