### ISSUE TITLE
List permutations performance suffers from 'dumb' trans 

### ISSUE THREAD

**Issue by ajrouvoet** [agda/agda-stdlib#1113]
The inductive definition of permutations in the stdlib uses the transitivity constructor as the implementation of 'trans':

https://github.com/agda/agda-stdlib/blob/b69dc60e3dc0a02a48a9f22354279e399823dc2e/src/Data/List/Relation/Binary/Permutation/Propositional.agda#L49

This can quickly explode to unnecessarily big terms. Imagine the following for 200k lines long:

![image](https://user-images.githubusercontent.com/475738/76530189-a9bd6600-6473-11ea-8f2d-e6efa157a78c.png)

This can easily be improved by defining a smart trans, that checks for refl appearing the left and right hand side:

```
trans : xs ↭ ys → ys ↭ zs → xs ↭ zs
trans refl ρ₂ = ρ₂
trans ρ₁ refl = ρ₁
trans ρ₁ ρ₂ = ↭-trans ρ₁ ρ₂
```

IMO this should be used by default and in the the IsEquivalence instance for Permutations. 
By switching from the 'dumb' to the 'smart' one, the term spanning 200k lines was reduced to one spanning a mere 1k. Because the smart one does not fully normalize permutations, it is computationally quite cheap.

**Comment by MatthewDaggitt** [comment]
Squeezed this into the `v1.3` release
