### ISSUE TITLE
Function.Base does not typecheck

### ISSUE THREAD

**Issue by pnlph** [agda/agda-stdlib#1114]
Hi, I get an error when typechecking the latest `Function/Base.agda`:
[Function/Base.agda#L181](../tree/master/src/Function/Base.agda#L181)

Error message:
```
⦃ A ⦄ cannot appear by itself. It needs to be the argument to a
function expecting an instance argument.
when scope checking ⦃ A ⦄
```

Agda version 2.6.0.1
Atom 1.45.0
agda-mode 0.9.10

**Comment by gallais** [comment]
The current `master` requires Agda 2.6.1. We have temporarily moved away from
being compatible with the released version of Agda because the release of 2.6.1
is imminent. As soon as it happens, we will be able to release the new stdlib
version too.
