### ISSUE TITLE
In the case where you want to use equational reasoning over different setoids in one file ...

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1121]
In the case where you want to use equational reasoning over different setoids in one file, you shouldn't be opening and renaming multiple instances of `Reasoning.Setoid` but instead be using ['Reasoning.MultiSetoid'](https://github.com/agda/agda-stdlib/blob/master/src/Relation/Binary/Reasoning/MultiSetoid.agda) which has support for using multiple different setoids built-in. I'll add a note in the changelog referring to it.

Yes renaming the combinators becomes a bit harder using the new design, but I think the trade-offs are worth it. In particular the improved type-checking speed should be helpful for your project which takes over an hour to type-check!

_Originally posted by @MatthewDaggitt in https://github.com/agda/agda-stdlib/issues/1102#issuecomment-596178673_

**Comment by mechvel** [comment]
I am  not sure, but have an impression that the old design was better.
It is better to have a thing programmed in the Language rather than built-in.
(?)

**Comment by gallais** [comment]
It's still only library code except that it's library code that's designed to
handle multiple setoids. You can check actually check the sources and see that
it does not make use of `BUILTIN` nor `primitive`:
http://agda.github.io/agda-stdlib/Relation.Binary.Reasoning.MultiSetoid.html

What Matthew meant is that we have built the support for multiple setoid directly
into the definitions we have devised.

**Comment by MatthewDaggitt** [comment]
Note: @mechvel you can still comment on closed issues and everyone will still receive the notifications. It will be better to continue the conversation in #1102 rather than open up a new issue.
