### ISSUE TITLE
..Reasoning.Preorder in lib-1.3

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1122]
I have learned of using Reasoning.MultiSetoid,
and now trying to accommodate to  Relation.Binary.Reasoning.Preorder  of lib-1.3.
I have 
```
import Relation.Binary.Reasoning.MultiSetoid as MSetoidReasoning
import Relation.Binary.Reasoning.Preorder as PreorderReasoning
```
in one file. And apply further
```
  open PreorderReasoning preorder using () 
                                renaming (begin_ to begin≤_; _∎ to _end≤; 
                                                _∼⟨_⟩_ to _≤[_]_; _≈⟨_⟩_ to _≈≤[_]_)
```
for  ``lib-1.2``.
And Agda-2.6.1 reports
The module _ doesn't export the following: ``_∼⟨_⟩_, _≈⟨_⟩_``.
It is difficult to find what are the needed names.
I do not see the subject in CHANGELOG.md
Please, advise.

**Comment by MatthewDaggitt** [comment]
See my comment in #1121. If you would like to discuss this issue, please post your message in #1102.
