### ISSUE TITLE
Use `using` when publicly re-exporting module contents

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1126]
Standard library modules import items in such a way that it is difficult to find a module where an item 
is defined.
For example,   Algebra.Consequences.Propositional   exports  ``comm+distrˡ⇒distrʳ ``.
Where to find a definition for  ``comm+distrˡ⇒distrʳ `` ?
This also makes it difficult to avoid overlaps (before type checking).
May be, it is better to use ``using`` ?

**Comment by MatthewDaggitt** [comment]
The problem with listing re-exports using `using` (that's a bizarre sentence) is that it doesn't scale very well. If you add a new item in the base module, it's not automatically re-exported. This makes it very easy to accidentally break things.

Having said that I assume you don't know about the emacs command `ctrl-.` (press `ctrl` and `.` at the same time)? If you press it on top of a term, emacs will take you to the location of its definition!

**Comment by mechvel** [comment]
I try this on  Data.Nat.Properties, on the term  ``Rel``
in 
``data  _≤_ : Rel ℕ ...``
I position the cursor at the first letter of ``Rel`` and press "Ctrl -.".
emacs reports 
            "C-.  is undefined"

On the other hand, i type-check modules under emacs, it is under agda-mode and customized.
?

**Comment by gallais** [comment]
The shortcut is actually `Alt-.` (NB: not `Alt Gr`).

**Comment by MatthewDaggitt** [comment]
Apologies, next time I'll wait until I get home to try and answer!

**Comment by mechvel** [comment]
``Alt-.``  (Alt and period in the same time) does not produce any effect at all.
And I edit and type-check modules under emacs, it is under agda-mode, and customized.
