### ISSUE TITLE
Use the BUILTIN Maybe

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#1128]
Following https://github.com/agda/agda/commit/1eec63b1c5566b252c0a4a815ce1df99a772c475 we have a BUILTIN maybe type constructor.
We should re-export this one rather than defining our own. We can then get rid
of the support for `Maybe` in `Foreign/Haskell`.

This work should be done on the **experimental** branch.

**Comment by MatthewDaggitt** [comment]
I think this has landed on `experimental`. @gallais if not then feel free to unclose.
