### ISSUE TITLE
Add `All.lookup` over setoid membership

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1132]
This is a question on lib-1.3.
I have a proof
```
All-P→∀∈xs-P :  ∀ {p} {P : C → Set p} {xs} → P Respects _≈_ → All P xs → 
                                     (∀ {x} → x ∈ xs → P x)
```
for  x and ``∈`` being of  Setoid.
I see its simple analogue   Data.List.Relation.Unary.All.lookup.
But there  ``∈`` is from Propositional (so that `Respects` is omitted).
Has lib-1.3 the version for ``∈`` being of Setoid?

A similar question is for  ``tabulate``.

**Comment by MatthewDaggitt** [comment]
No there isn't. Feel free to add it in a PR. It should be an almost trivial application of `All.lookupWith`
