### ISSUE TITLE
`∈-++⁻` in lib-1.3

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1133]
What is the mnemonic of the suffix ``⁻`` in ``Data.List.Membership.Setoid.Properties.∈-++⁻`` ?
Is not ``∈-++⊎`` more sensible?
As to me, I like  ``∈++⇒⊎``.

**Comment by gallais** [comment]
In the `Properties` file for a property `P` we have these two suffixes: `⁻` and `⁺`.

- `f⁺` is a lemma of the form `Precondition -> P (f)`
- `f⁻` is a lemma of the form `P(f) -> Postcondition`

The logic behind the name is that `⁺` makes `f` appear in the conclusion while
`⁻` makes it disappear from the hypothesis.

**Comment by JacquesCarette** [comment]
That's a nice convention - I don't remember seeing it documented? [I might have missed it!]

**Comment by mechvel** [comment]
1) I understand your "Precondition" as "condition" and "Postcondition" as "conclusion".
Probably this is simpler - if only I understand your sentence correct.   
2) Most people (and myself) would suffer of such mnemonic.
Too slight relevance to intuition.
For example,  ``∈-++⁻`` has P on both sides, and the difference is that ``⊎`` is on the right hand side. 
The main issue in most examples will be mentioning a relation of ``f``  to other operations and not of whether P appears on RHS or not. 
In our case  ``∈`` is related to ``++`` and to ``⊎``, and inserting ``⇒`` into the name defines more clearly the nature of this relation. 
I suggest a similar approach in general. Somewhat like this:
to denote in the name which main functions are related, and setting ``⇒`` in an appropriate place.

**Comment by gallais** [comment]
> For example, ∈-++⁻ has P on both sides

It's not about `P` it's about `f`, here `++`.

**Comment by mechvel** [comment]
Consider
```
even-n⇒¬even-suc-n :  {n : ℕ} → IsEven n -> ¬ IsEven (succ n)
```
Really, would you name it ``even-suc⁺``, or ``even-suc⁻`` ?
Consider also 
"If the sum of decimal digits in n is a multiple of 3, then n is a multiple of 3":
```
3|digitSum-n⇒3|n :   3 ∣ sum (digits n) → 3 ∣ n
```
Would you call it   ``3|digitSum⁺`` or ``3|digitSum⁻`` ?

**Comment by gallais** [comment]
This naming scheme is for boring lemmas. I do not deny that it is not applicable
to every single situation. In particular:

> Really, would you name it even-suc⁺, or even-suc⁻ ?

I would probably prove something else to be honest because I prefer a positive
lemma to one proving a contradiction. Something like this instead:

```agda
even-suc-inv : Even (suc n) -> Odd n
```

`inv` stand for 'inversion'.

> Would you call it 3|digitSum⁺ or 3|digitSum⁻ ?

Neither as `sum (digit n)` is not a single standard function. I would probably
give a more descriptive name like `divisibility-rule-3`.

**Comment by gallais** [comment]
> That's a nice convention - I don't remember seeing it documented? [I might have missed it!]

[Matthew has done the job!](https://github.com/agda/agda-stdlib/blob/master/notes/style-guide.md#functions-and-relations-over-specific-datatypes)

**Comment by JacquesCarette** [comment]
Not surprised that @MatthewDaggitt had indeed done so.  However, you've used very different wording above to describe the convention than in the linked page, which is probably why I didn't recognize it as being documented. I can now re-construct that they are indeed the same, but it took me a bit.  Perhaps adding some extra words (as per above) would be helpful?

**Comment by mechvel** [comment]
@gallais writes
> The name is not about P it's about f, here ++. The fact we are in the
>  P.Properties module already tells you these are properties about P.

Still the fact that ``++`` is or is not on RHS is much less informative than the fact that 
``x ∈ xs ++ ys``  is related to ``⊎``. 
Generally, in any statement, the main information is: 
which main operations (or relations) are considered as related.
And then, there can be added details, where it is set  ``⇒`` and so on.
If a related operation is too easy for the reader to guess of, then it may have sense to skip it.

**Comment by MatthewDaggitt** [comment]
Updated the style guide entry with @gallais's wording. @mechvel as mentioned above, this is a simple and predictable naming scheme that has so far worked extremely well across the library. Therefore we won't be changing it anytime soon.
