### ISSUE TITLE
``2n≡n+n`` 

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1153]
I do not see in Data.Nat.Properties the lemma ``2 * n ≡ n + n``.
On the other hand, it  a) is widely used  b)  is not proved by ``refl``.
If I am not missing something then it probably has sense to add  the lemma ``2n≡n+n``.
(?)

**Comment by gallais** [comment]
My suggestion: write a more annoying multiplication with a special case
for one and prove the more general lemma saying it is equal to standard
multiplication.

```agda
0     *' n = 0
1     *' n = n
suc m *' n = n + m *' n
```

This way you get all of `2n≡n+n`, `3n≡n+n+n`, etc. in one go.

**Comment by mechvel** [comment]
Yes, this looks nice.
After proving   ``*as*' :  ∀ m n → m * n ≡ m *' n``
(choose an appropriate name),
we have that ``2 * n ≡ n + n`` is proved by ``*as*' 2 n``,
 ``3 * n ≡ n + (n + n)`` is proved by ``*as*' 3 n``,  and so on.

**Comment by MatthewDaggitt** [comment]
This seems kind of specialised. I'm not sure we really want to be adding such operations just for their alternative reduction behaviour. If people do need them for whatever reason then they can add them in their own code. Marking as closed for now, but feel free to reopen if you want to continue the discussion.
