### ISSUE TITLE
`pred n  ≤ n` and others

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1157]
Probably it has sense to add the following to Data.Nat.Properties:
```
pred-n≤n :  ∀ n → pred n ≤ n
1+n≮0 : ∀ {n} → suc n ≮ 0
1+n≰0 : ∀ {n} → suc n ≰ 0
```

**Comment by EdNutting** [comment]
Should only `n≮0 : ∀ {n} → n ≮ 0` be added? The other two cases are trivial from that?

**Comment by mechvel** [comment]
I prove ``pred-n≤n`` in two patterns.
``1+n≮0`` and  ``1+n≰0``  are proved by ``()``.
But it is often more clear to read  ``1+n≰0``  a programs  than just ``()``.
I am not so sure, though.

**Comment by umazalakain** [comment]
The former can be found in https://github.com/agda/agda-stdlib/blob/master/src/Data/Nat/Properties.agda#L1571
The latter two can be obtained via https://github.com/agda/agda-stdlib/blob/master/src/Data/Nat/Properties.agda#L245
