### ISSUE TITLE
Missing lemmas for `_/_`

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#1165]
Stumbled upon [this SO post](https://stackoverflow.com/questions/59914212/how-to-prove-that-division-is-cancellative/61322112) asking how to prove

```agda
/-cancelˡ : ∀ c a b {b≢0} {b*c≢0} → ((c * a) / (c * b)) {b*c≢0} ≡ (a / b) {b≢0}
```

We should probably have it in the stdlib too.

**Comment by MatthewDaggitt** [comment]
Even with the invariants, working with `div-helper` is a complete nightmare and I wouldn't wish it on anyone! I keep vaguely hoping that we'll reach a point where we've proved everything we need to using it, and everything else will be derivable from other lemmas. Not sure if that's the case for this one, will have a play at some point.
