### ISSUE TITLE
rename Algebra.Properties ?

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1176]
May be rename this folder to ``Algebra.Theories`` or ``Algebra.Items`` ?
Because the modules stored in this folder are likely to have not only property definitions and their
proofs, but may be also various types, and functions for ordinary computations.  
For example, for Algebra.Theories.Monoid,  I would expect of it to keep, generally, some items related to an arbitrary  Monoid. Besides property proofs for Monoid, it may contain, for example, the powering function ``_^_``, the ``product`` function to multiply a list of elements.
For Algebra.Theories.Semiring, I would expect of it to keep the ``sum`` function to sum a list of elements.
?

**Comment by MatthewDaggitt** [comment]
We now have a consistent scheme for where things like sum, products and exponentiation live, and @mechvel has been part of the discussions so closing.
