### ISSUE TITLE
Strange multiple warning pragmas for the same function in Data.Nat.Properties

### ISSUE THREAD

**Issue by elsanussi-s-mneina** [agda/agda-stdlib#1180]
The line 

{-# WARNING_ON_USAGE n∸m≤∣n-m∣

should not occur 3 times in the file /src/Data/Nat/Properties.agda .

My understanding from looking at the code is that it is a copy-paste error. That is that two of those lines are not what the programmer meant. Is there a different explanation?

**Comment by elsanussi-s-mneina** [comment]
Should I close this issue, now that there is another issue for fixing it?

**Comment by elsanussi-s-mneina** [comment]
Another issue was opened to fix this issue. I will close this one.
 https://github.com/agda/agda-stdlib/issues/1185

**Comment by MatthewDaggitt** [comment]
Apologies, I missed that you'd opened this issue. Thanks for tidying up after me and closing it!
