### ISSUE TITLE
Question on the `Sublist` definition  in lib-1.3

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1183]
```
module Data.List.Relation.Binary.Sublist.Heterogeneous.Core                       
       {a b r} {A : Set a} {B : Set b} (R : REL A B r)                            
``` 
defines 
```
data Sublist : REL (List A) (List B) (a ⊔ b ⊔ r) where                            
   []   : Sublist [] []                                                            
   _∷ʳ_ : ∀ {xs ys} → ∀ y → Sublist xs ys → Sublist xs (y ∷ ys)                    
   _∷_  : ∀ {x xs y ys} → R x y → Sublist xs ys → Sublist (x ∷ xs) (y ∷ ys)        
```
Why not set  ``[]  : ∀ {xs} → Sublist [] xs``
as the first pattern?
Some proofs will become shorter,
and the lemma    ``∀ {xs} → Sublist [] xs``   will not be needed.
For example, for ``Nat._≤_`` the library sets  ``z≤n`` rather than ``0≤0``.
?

**Comment by gallais** [comment]
You would not be able to prove [`Sublist-[]-irrelevant`](http://agda.github.io/agda-stdlib/Data.List.Relation.Binary.Sublist.Heterogeneous.Properties.html#12875)

**Comment by mechvel** [comment]
What is irrelevance in this case? Is it that  the property that a proof for ``Sublist []  xs`` 
to be unique? I think, indeed, for ``Sublist []  (x :: xs)`` it is not unique. 
Such uniqueness is not necessary, but may be, indeed,  it has some importance.

**Comment by ajrouvoet** [comment]
@mechvel Generic Agda questions on how to approach a problem are better asked on one of the community channels (IRC, the mailing list, gitter).

**Comment by MatthewDaggitt** [comment]
> What is irrelevance in this case? Is it the property that a proof for Sublist [] xs
to be unique?

Yes https://github.com/agda/agda-stdlib/blob/9bf441fc15bda8d1beb9226a43cc5e08a704c60d/src/Relation/Unary.agda#L175

> There is also a certain question about irrelevance.

@ajrouvoet is right, this question is better asked on the mailing list rather than in the standard library issue tracker.

The original question has been answered so I'm closing the issue.
