### ISSUE TITLE
Confusion about _↔_ (Function.Inverse and Function.Bundles)

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-stdlib#1187]
There are two definitions of `_↔_` in the library, at Function.Inverse and Function.Bundles. They are closely related, but different. 

First, one must be careful to not import both `Function` (which re-exports `Function.Bundles`) and `Function.Inverse` in the same module, else all sorts of clashes on `Inverse` ensures.

As far as I can tell, the one in `Function.Bundles` is newer, and likely the one to be used in the future.

However, internally the library uses the one from `Function.Inverse` a lot more.  In particular, `Function.Related.TypeIsomorphisms`.

So: which `_↔_` should I be using?  [The answer will lead to a bunch of follow-up questions...]

**Comment by ajrouvoet** [comment]
I ran into the same yesterday.

I believe you are correct that `Function/Function.Definitions/Function.Structures/Function.Bundles` are the new modules. AFAI can tell, the TypeIsomorphisms have just not yet been ported to the new hierarchy. I suspect that the fact that the std. lib has not yet ported its proofs is the main reason that the old modules have not yet been properly deprecated.

Personally I would recommend using the new hierarchy regardless. It is much easier to handle IMO.

**Comment by MatthewDaggitt** [comment]
Yes apologies, this is my fault. I failed to add sufficient documentation and this has tripped several people up recently. As @ajrouvoet says, `Function(.Definitions/Structures/Bundles)` is the new code and it's use is encouraged. 

I've opened #1188 to add this information to the files.

> Personally I would recommend using the new hierarchy, even if you need to port some proofs from the std lib. It is much easier to work with IMO.

That's fantastic to hear that you've found it easier to use :tada: If you have ported any proofs using the new hierarchy any PRs would be greatly appreciated. I've got several lurking around in branches that I need to tidy up and submit.

**Comment by MatthewDaggitt** [comment]
> The answer will lead to a bunch of follow-up questions...

I should have added: bring on the follow-up questions!

**Comment by ajrouvoet** [comment]
>  That's fantastic to hear that you've found it easier to use

For sure! Having quick access to the `f` and its inverse is so much more pleasant. And finding what you're looking for is much easier.

> If you have ported any proofs using the new hierarchy

I haven't, but of course!

**Comment by ajrouvoet** [comment]
@MatthewDaggitt Should what used to be in TypeIsomorphisms not just be in the appropriate Properties modules of various type formers?

I would expect the following for example in Data.Sum.Properties:

```
⊎-isMagma      : IsMagma _↔_ _⊎_
⊎-isSemigroup : IsSemigroup _↔_ _⊎_
⊎-isMonoid      : IsMonoid _↔_ _⊎_ ⊥
```

etc

**Comment by MatthewDaggitt** [comment]
> Should what used to be in TypeIsomorphisms not just be in the appropriate Properties modules of various type formers?

They should definitely be under the type formers directory. I think as we discussed in #1141 it would be more appropriate for them to go under `Data.Sum.Function`

**Comment by MatthewDaggitt** [comment]
Sorry I meant `Data.Sum.Algebra`

**Comment by ajrouvoet** [comment]
I have some of these around now, using the new function hierarchy and will make a PR sometime soon.

**Comment by MatthewDaggitt** [comment]
By the way, what do you think of @alexarice's suggestion in #1156? His definitions seem to make the properties compose much better? We could still export the existing definitions from the structures and bundles for use?

**Comment by JacquesCarette** [comment]
@ajrouvoet could you post here which ones you do have?  I have some too, and I don't want to duplicate the work. [Mine need a lot of work to submit as PR as they're embedded in an old library.]

**Comment by ajrouvoet** [comment]
Not many, just the once I needed. Which was (for now) just the CommutativeMonoid structure of \uplus and its dependencies.

**Comment by ajrouvoet** [comment]
> By the way, what do you think of @alexarice's suggestion in #1156?

Looks nice; I haven't used the new setup enough to have run in the issues this solves, so I can't really say something useful.

**Comment by JacquesCarette** [comment]
Ok, I've got up to CommutativeSemiring (well, Symmetric Rig Groupoid, to be fancy) in pi-dual. I've been meaning to port. My time is finally freeing up a bit, so I think I might be able to do it.

**Comment by ajrouvoet** [comment]
There is always a bigger fish :) I'll wait for your PR then, since I have what I need and am not in a hurry.

**Comment by JacquesCarette** [comment]
Sorry to take a while on this. The biggest follow-up question was indeed where to put the ported routines.  `Data.Sum.Algebra` and `Data.Product.Algebra` are good.  Where should distributivity go?

Also, I was going to try hard to 'deconstruct' the `Inverse` witnesses into its component parts, as the routines (and proofs) are often independently useful. Some of these will belong under `Data.Sum` and `Data.Product`, but again the distributivity-related ones don't have a natural home.
