### ISSUE TITLE
Suggestion to rename the folders Structures and Bundles

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1194]
I suggest to improve  the terminology related to  _structures_ and _bundles_.
Currently `classical algebraic structures` (Magma, Semigroup, ..., Ring ...)
are called _bundles_. And there is a folder Bundles.
I think, it is more appropriate to call them ``classical structures``, and to rename this folder to
ClassicalStructures.  This word at least explains something.
Currently the folder Structures keeps certain auxiliary structures: IsMagma, IsSemigroup, ...,
which have not a mathematical meaning, but have a special technical meaning for dependently typed programming.
It it better to rename it to AuxStructures.

**Comment by ajrouvoet** [comment]
As far as I know the current names are pretty standard and unsurprising among the standard libraries for various proof assistants.

The most important thing is that the standard library (and with it hopefully the Agda ecosystem) is internally consistent. When you pick up a language you learn its idioms. Perhaps you'll be surprised once, but if it is internally consistent, this is not a problem. 

In general, renaming things in the stdlib comes with deprecating and a lot of annoyance from all downstream uses. The proposed change probably breaks every Agda user's code.

**Comment by MatthewDaggitt** [comment]
> I think, it is more appropriate to call them classical structures, and to rename this folder to
ClassicalStructures. This word at least explains something.

I have no idea what you mean by "This word at least explains something".

I think the point you're overlooking is that your names only work for the `Algebra` hierarchy, whereas the current names work for all hierarchies, e.g. `Function.Bundles/Structures` and `Relation.Binary.Bundles/Structures`. Predictability across the library is key.

As @ajrouvoet says, it would be a huge backwards incompatible change as well.
