### ISSUE TITLE
Definition of morphism

### ISSUE THREAD

**Issue by pnlph** [agda/agda-stdlib#1206]
Hi, I read the [definition of morphism in nlab](https://ncatlab.org/nlab/show/morphism) and tried to find a counterpart in our `stdlib`.

When reading [the changelog v1.3](https://github.com/agda/agda-stdlib/blob/master/CHANGELOG/v1.3.md) I found that the type `Morphism A B` has been deprecated from the modules `Algebra.Morphism.Definitions` and `Relation.Binary.Morphism.Definitions` in favor of the standard function notation `A → B`.

Could we not keep the definition of morphism, just for pedagogical purposes?

I would also propose the following formulation making explicit the source and target objects, so it can be read as the morphism from A to B:
```agda
Morphism : ∀ {a} → ∀ {b} → Set a → Set b → Set _
Morphism A B = A → B
```
Just a suggestion, don't know if it complies with the direction towards that you aim to develop the `stdlib`.

**Comment by MatthewDaggitt** [comment]
The discussion that lead to it being deprecated is in https://github.com/agda/agda-stdlib/issues/1025. The feeling was that actually using the definition outside of the module was more trouble than it was worth. I guess if there are users for it, we can de-deprecate it again 😄 
I'm not sure I'd want to go back to using it extensively in the standard library though.

You're right, the problem with the current definition is that it has an extra equality argument. I think the best option would be to move it to `Function.Core` and then re-export it publicly in `Algebra.Morphism.Definitions` and `Relation.Binary.Morphism.Definitions`. Does that sound reasonable?

**Comment by pnlph** [comment]
Yes, makes a lot of sense moving `Morphism` to `Function.Core`.

By publicly you mean adding this to `Algebra.Morphism.Definitions` and `Relation.Binary.Morphism.Definitions`?
```
open import Function.Core using (Morphism) public
```

**Comment by pnlph** [comment]
Another question, would you make explicit the sort of the codomain?
```agda
Morphism : ∀ {a} → ∀ {b} → Set a → Set b → Set a ⊔ b
Morphism A B = A → B
```
I think it is more clean, but in that case, the `_⊔_` operator should be in scope.

**Comment by MatthewDaggitt** [comment]
> By publicly you mean adding this to Algebra.Morphism.Definitions and Relation.Binary.Morphism.Definitions?

Yup, though the style guide prefers
```agda
open import Function.Core public
  using (Morphism) 
```

> Another question, would you make explicit the sort of the codomain?

You can if you want. I think the library is fairly agnostic on this subject. Sometimes we do and sometimes we don't and there are good arguments on either side.
