### ISSUE TITLE
Remove all v0.15 deprecation warnings?

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-stdlib#1209]
Since master will be v1.4, is it time to remove v0.15 deprecation warnings? What's the number of versions for which the warnings will be emitted? [It would be nice to remove v0.16 and v.17 too, but that' probably as far as can be done.]

**Comment by MatthewDaggitt** [comment]
Hmm so my personal secret plan that I haven't yet revealed to anybody before now is to remove the deprecated features once we are two major versions ahead, i.e. we'll remove everything deprecated in version 0 when we hit version 2 and remove everything deprecated in version 1 when (if?) we reach version 3. That seems more consistent with the semantic versioning scheme that we claim to use (but ignore when it's convenient for us).

Is there a reason why you'd particularly like to remove something or is just for tidiness? I agree that the `Data.X.Relation` folder causes me pain every time I navigate through it 😢

**Comment by JacquesCarette** [comment]
I think some of the older ones cause unnecessary dependencies.  I think 2 major versions is too much. I'd be happy with 4 releases of the library. v0.15 is 8 releases back with respect to future v1.4, if I'm counting properly. That seems to be a bit much.

**Comment by gallais** [comment]
I think the right metric to look at is the number of major releases of *Agda*
in between the deprecation and the current lib. I would not be surprised to
hear that some people only ever update to a newer stdlib once they install a
newer version of Agda.

v0.15 was compatible with 2.5.3 and we have had 2.5.4, 2.6.0 and are now on
2.6.1 since then. That seems like a reasonable amount of time to upgrade.
Then again as long as these deprecations do not cost us anything, I don't
mind keeping them around as they provide users with a clear upgrade path.*

> I think some of the older ones cause unnecessary dependencies.

That would be a very good justification for dropping some deprecations IMO.
May be worth keeping a copy of the now removed upgrade guidance in a `MIGRATION`
file parallel to the `CHANGELOG` one?

**Comment by JacquesCarette** [comment]
Yes, you're probably right that we should track the number of Agda releases as the 'right' metric.

Ok, I'll see which ones have a reason other than 'cleaning' and make a PR. Where was that upgrade guidance information?

**Comment by gallais** [comment]
> Where was that upgrade guidance information?

For identifiers, the `WARNING_ON_USAGE` pragmas tell users what the new name is.
For modules, the `WARNING_ON_IMPORT` pragmas tell users what to import instead.

**Comment by MatthewDaggitt** [comment]
> I think some of the older ones cause unnecessary dependencies. I think 2 major versions is too much.

> I think the right metric to look at is the number of major releases of Agda
in between the deprecation and the current lib.

Hmm I'm not sure. In my mind the whole point of minor versions is that we should avoid making breaking changes where possible, and only on the major version numbers are we "allowed" to implement large non-backwards compatible changes. It seems to me that, in the vast majority of cases, removing deprecated code is an unnecessary breaking change and therefore it should be reserved for major version numbers.

I'm more than happy to have a discussion about the interval. Maybe 2 major versions is too long, and perhaps we should make the official policy 1 major version instead? That would allow still allow us to belatedly remove everything from v0 in the next release if we wanted to.

**Comment by MatthewDaggitt** [comment]
> Ok, I'll see which ones have a reason other than 'cleaning' and make a PR. Where was that upgrade guidance information?

I've [looked through v0.15](https://github.com/agda/agda-stdlib/search?p=1&q=v0.15&unscoped_q=v0.15) and I can't see anything that looks like it would be causing unwanted dependencies. Do you have something particular in mind @JacquesCarette?

**Comment by JacquesCarette** [comment]
Turns out that no, indeed, nothing in that version leaps out. I thought I'd seen something, but it might have been from v0.16, and it made sense to start with v0.15 first.

One major release does seem to be quite sufficient!
