### ISSUE TITLE
Make Data.Container more level-polymorphic in the data argument

### ISSUE THREAD

**Issue by turion** [agda/agda-stdlib#121]
It's possible to generalise `Data.Container` slightly:

```
⟦_⟧ : ∀ {ℓ₁ ℓ₂} → Container ℓ₁ → Set ℓ₂ → Set (ℓ₁ ⊔ ℓ₂)
⟦ C ⟧ X = Σ[ s ∈ Shape C ] (Position C s → X)
```

The levels for the `Shape` and `Position` need not coincide with the level for the data it contains. I've generalised the type signature in a fork found at https://github.com/turion/agda-stdlib and fixed the metas that were undefined after the change.

**Comment by gallais** [comment]
You should probably open a Pull request instead (New pull request > compare across forks > pick "turion/agda-stdlib" for the second repo in the drop-down menu).

**Comment by turion** [comment]
Fine with me :) See here: #123

**Comment by andreasabel** [comment]
I merged and than reverted your PR.  
Some of the `Data.Container.*` modules do not compile.

**Comment by turion** [comment]
Sorry, this is my fault for not reporting back quickly enough. My `make test` currently fails, and therefore I haven't checked for all the problem that could occur in other parts of the module yet. This is my error:

```
$ make test
cabal clean && cabal install
cleaning...
Warning: The package list for 'hackage.haskell.org' is 88 days old.
Run 'cabal update' to get the latest list of available packages.
Resolving dependencies...
Notice: installing into a sandbox located at
/home/turion/e/informatisch/Agda/agda-stdlib/.cabal-sandbox
Configuring lib-0.13...
Building lib-0.13...
Installed lib-0.13
GenerateEverything
make: GenerateEverything: Command not found
make: *** [GNUmakefile:12: Everything.agda] Error 127
```

**Comment by asr** [comment]
> I'm running this in a sandbox.

The `GNUMakefile` file doesn't support the sandbox. You can move the `GenerateEverything` binary from your sanbdox path to your cabal path.

**Comment by turion** [comment]
@asr , I see. I don't get it fixed completely yet. I opened an issue here: https://github.com/agda/agda-stdlib/issues/126
