### ISSUE TITLE
Add `_≮_` and `_≰_` to bundles in the binary relation hierarchy.

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1214]
In lib-1.3 I see  ``_≉_`` in Setoid,
but I do not find  ``≰, ≮``
(I expect they to be defined via ``¬_``).
I grepped for it in Relation.Binary,  Relation.Binary.Construct, and do not find it.
Probably it needs to be in Preorder or in PartialOrder.
?

**Comment by MatthewDaggitt** [comment]
I'm not sure we have a good symbol for the negation of the order for `~`. I'd therefore probably add `_≰_` to `PartialOrder` and `_≮_` to `StrictPartialOrder` for now.

**Comment by MatthewDaggitt** [comment]
There is now a good symbol for `\~n` for negated tilde.

**Comment by jamesmckinna** [comment]
Any (potential) interaction with any candidate solution to issue #1635?

**Comment by MatthewDaggitt** [comment]
Hmm yes. The precedence of the candidate solution should be < 4 otherwise it will interfere with both this and the non-negated equality.

**Comment by jamesmckinna** [comment]
Precedence = 4 would suffice?

**Comment by jamesmckinna** [comment]
Oh, but this has turned out to be more complicated than I first realised...
... and immediately gives rise to the linked issue #2096 ... and hence (the need/desire for) further refactoring in the same spirit to introduced notation systematically for the `flip`ped relations
