### ISSUE TITLE
Upgrading build version?

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-stdlib#1237]
Any reason `.travis.yaml` uses xenial (i.e. Ubuntu 16.04) for testing rather than 20.04 (Focal Fossa), the latest LTS?  Would a PR to change that be welcome?

**Comment by asr** [comment]
I don't' know about the standard library, but a PR for Agda would be welcome.

**Comment by gallais** [comment]
No particular reason, it's what used to work. Feel free to open a PR.

**Comment by JacquesCarette** [comment]
I'm preparing one for Agda first, and then I'll do one for the library next.

**Comment by gallais** [comment]
Alternative proposal: move to github actions.
Cf. https://doisinkidney.com/posts/2020-11-18-agda-github-action.html

**Comment by JacquesCarette** [comment]
Right, I think the alternative is indeed better (now).  Do we have a label for `github-action` ?

**Comment by gallais** [comment]
I've just renamed the `travis` one to `continuous-integration`.

**Comment by gallais** [comment]
I got a build working: https://github.com/gallais/agda-stdlib/pull/1
I need to figure out how to deploy html docs & then we're good to go.
If I haven't done it by the Agda meeting then I'll start with that.
