### ISSUE TITLE
Lemmas related to `Data.List.reverse`

### ISSUE THREAD

**Issue by umazalakain** [agda/agda-stdlib#1246]
Would it be interesting to add any of the following lemmas to the stdlib?

```
Any-reverse : {xs : List A} → Any P xs → Any P (List.reverse xs)
reverse-Any : {xs : List A} → Any P (List.reverse xs) → Any P xs
reverse-injective : ∀ {xs ys : List A} → List.reverse xs ≡ List.reverse ys → xs ≡ ys
```

**Comment by gallais** [comment]
Looks good. The first two would be called `reverse⁺` and `reverse⁻`
cf. the [style guide](https://github.com/agda/agda-stdlib/blob/master/notes/style-guide.md#functions-and-relations-over-specific-datatypes).
