### ISSUE TITLE
Predicate `AllAcc (λ x xs → P x xs) xs` on vectors

### ISSUE THREAD

**Issue by umazalakain** [agda/agda-stdlib#1249]
Would it be of interest to add a pointwise predicate on vectors that also depends on the tail? This is similar to `Data.List.Fresh`, but it's on vectors and it doesn't bake in the induction-recursion. It allows for vectors with fresh elements to be modelled as AllAcc \_∉\_ xs.

**Comment by gallais** [comment]
We talked a bit about something like this for lists in #467;
nothing came of it but I think it makes sense to have something
like this. I would perhaps name it `AllCons` as it's applying `P`
to all cons nodes.

**Comment by umazalakain** [comment]
A possible course of action is to implement this for vectors, see how it goes, then decide whether to implement it for lists, and if so whether to rewrite List# and AllPairs in terms of AllCons

**Comment by umazalakain** [comment]
If we were to define `AllCons`, where would it be? Under `Data.Vec.Relation` I imagine, but `Binary` seems to usually be used for operands of the same type.

**Comment by gallais** [comment]
That would be a `Data.Vec.Relation.Unary` as it's talking about a single vector.

**Comment by umazalakain** [comment]
Closing in favor of `AllPairs` as in #1257
