### ISSUE TITLE
A problem with Semiring

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1253]
I wonder: how to express in Agda-2.6.1 + lib-1.3 the following discourse?
Let R and U be semirings having the same additive monoid (+-commutativeMonoid).
Denote * and *' the multiplication operators in R and U respectively,
1# and e  the unities in R and U respectively.  Prove in Agda that
```
for all x in R  it holds  (1# + 1#) * x ≈ (e + e) *' x     -- (I)
```
And let us assume that the lemma ``2*as+ :  ∀ x → (1# + 1#) * x ≈ x + x``
is proved in the module  OfSemiring  parameterized by Semiring (it is proved simply in 2-4 steps).
Mathematically, the statement (I) has sense.
And its proof is simple: the left hand side equals ``x + x`` by the laws of R; the right  hand side equals ``x + x`` by the laws of U, and this is the same element of their common Carrier.
The matter is not in the proof itself, it is in finding a valid formulation of the theorem (I) in Agda.
Can anybody, please, demonstrate?

**Comment by MatthewDaggitt** [comment]
This is not a question for the standard library. Best to ask this on the mailing list.
