### ISSUE TITLE
Make the `GNUmakefile` compatible with cabal sandboxes

### ISSUE THREAD

**Issue by turion** [agda/agda-stdlib#126]
I have a development version of agda-stdlib that I don't want to install globally, so I'm trying to build and test it in a `cabal sandbox`. However, the makefile is not fit for that. It will usually fail like this:

```
$ make clean && make test
find . -type f -name '*.agdai' -delete
cabal clean && cabal install
cleaning...
Warning: The package list for 'hackage.haskell.org' is 88 days old.
Run 'cabal update' to get the latest list of available packages.
Resolving dependencies...
Notice: installing into a sandbox located at
/home/turion/e/informatisch/Agda/agda-stdlib/.cabal-sandbox
Configuring lib-0.13...
Building lib-0.13...
Installed lib-0.13
GenerateEverything
make: GenerateEverything: Command not found
make: *** [GNUmakefile:12: Everything.agda] Error 127
```

This error can be easily fixed be replacing line 12 in `GNUmakefile` by:
```
	cabal exec -- GenerateEverything
```
But then I'm stuck with the following error:
```
$ make clean && make test
find . -type f -name '*.agdai' -delete
cabal clean && cabal install
cleaning...
Warning: The package list for 'hackage.haskell.org' is 88 days old.
Run 'cabal update' to get the latest list of available packages.
Resolving dependencies...
Notice: installing into a sandbox located at
/home/turion/e/informatisch/Agda/agda-stdlib/.cabal-sandbox
Configuring lib-0.13...
Building lib-0.13...
Installed lib-0.13
cabal exec -- GenerateEverything
fix-agda-whitespace --check
make: fix-agda-whitespace: Command not found
make: *** [GNUmakefile:4: test] Error 127
```
It seems it can't be solved by just putting `cabal exec` in line 4, and I'm out of ideas. How can the makefile be changed to support cabal sandboxes?

**Comment by asr** [comment]
> make: fix-agda-whitespace: Command not found

You need to install  `fix-agda-whitespace`:

```
$ cd your-agda-path/src/fix-agda-whitespace/
$ cabal install
```

**Comment by turion** [comment]
What is this package? Why is it not installed with agda? Is this whole build process described anywhere?

**Comment by asr** [comment]
> What is this package?

Run `fix-agda-whitespace --help`.

> Why is it not installed with agda?

See https://github.com/agda/agda/issues/2318.

**Comment by asr** [comment]
> I have a development version of agda-stdlib that I don't want to install globally, so I'm trying to build and test it in a `cabal sandbox`. 

The Agda library *isn't* a Haskell library, so its local/global installation isn't handle by the Cabal sandboxes.

**Comment by turion** [comment]
Thanks, I understand now! I've changed the makefile such that it works in a sandbox as well. If people think this is useful, there is a pull request: #127
