### ISSUE TITLE
Upload v1.3 release to gh-pages

### ISSUE THREAD

**Issue by WorldSEnder** [agda/agda-stdlib#1266]
Is there a reason why the released version 1.3 has not made its way to the [gh-pages](https://agda.github.io/agda-stdlib/) yet? This should be rather easily automatable using [this github event](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release).

**Comment by gallais** [comment]
> Is there a reason why the released version 1.3 has not made its way to the gh-pages yet?

So far I have been doing it by hand when I remember to do it.

> This should be rather easily automatable using this github event.

The new versions need to be added to a list of directories to `git checkout`
in the `.travis.yml` file so I am not sure it can be automated that easily.

**Comment by WorldSEnder** [comment]
If it's about these lines https://github.com/agda/agda-stdlib/blob/master/.travis.yml#L153-L158

It might be possible to do something like

        - if [[ $TRAVIS_BRANCH = "master" ]]; then
            # checkout all files that are not in the top-level directory
            git ls-tree -r --name-only gh-pages | awk -F / 'NF > 1' | git checkout HEAD --pathspec-from-file=- ;
          fi
        - if [[ $TRAVIS_BRANCH = "experimental" ]]; then
            # checkout all files that are not in the experimental directory
            git checkout HEAD -- :** :\!/experimental/** ;
          fi

so naming the versions directly is not required.
