### ISSUE TITLE
two "map" sections in Any.Properties.agda 

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1269]
In Data/List/Relation/Unary/Any/Properties.agda  there are two sections titled as "-- map", 
with a great distance between them.
For example, the user searches for something of the  `map⁺` functionality. One sees the "-- map" section,
with the functions ``map-id, map-∘``. Then one has quite a few chances to discover another section titled "-- map".

**Comment by MatthewDaggitt** [comment]
They're not the same function. One section is for `Any.map` and one section is for `List.map`. Perhaps the headings could be clearer though.
