### ISSUE TITLE
add the Any.Properties.gmap instance for f = id ? 

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1270]
Maybe Data.List.Relation.Unary.Any.Properties needs this one?
```
P⊆Q⇒Any-P⇒Any-Q :  ...  P ⊆ Q  ...  Any P xs → Any Q xs
```
It is derived from  `gmap`, but it needs an effort to find the expression.

**Comment by gallais** [comment]
Do you mean [map](https://agda.github.io/agda-stdlib/Data.List.Relation.Unary.Any.html#1696)?

**Comment by mechvel** [comment]
Yes. But have lost it.
I search it in ../Any/Properties.agda, and find there only `gmap`.
Now I see `map` in  Any.agda. Why are they in different modules, I wonder.

**Comment by gallais** [comment]
> Why are they in different modules, I wonder.

By analogy with data structures, `map` is seen more as a function more than a proof of a property.
For `List`, `Tree`, etc. it's always in the `.Base` module and so it is for `Any`, `All`, etc.
