### ISSUE TITLE
Look for missing stability lemmas

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#1275]
In #1267 we came across the fact we are missing:

```agda
cast : ∀ {xs} → (_∈ xs) Respects _≈_
cast x≈y = map (trans (sym x≈y))
```

in `Data.List.Membership.Setoid`. We should look at all of the `Setoid`
modules across the library and check whether we are missing similar
functions in them.

**Comment by MatthewDaggitt** [comment]
I think we already have this?

https://github.com/agda/agda-stdlib/blob/040979057edd6da40d574e078e2b1a7021f49221/src/Data/List/Membership/Setoid/Properties.agda#L51
