### ISSUE TITLE
Type errors in `Reflection.Pattern`

### ISSUE THREAD

**Issue by wenkokke** [agda/agda-stdlib#1276]
When compiling `Reflection.Pattern` with the latest version of Agda, I get an error:
```
/path/to/stdlib/src/Reflection/Pattern.agda:59,60-61
Agda.Builtin.Nat.Nat !=< String
when checking that the expression s has type String
```

**Comment by wenkokke** [comment]
It seems that the standard library wasn't updated after [changes](https://github.com/agda/agda/blob/master/CHANGELOG.md#reflection) were made to the builtin reflection module.

**Comment by jespercockx** [comment]
You should use the `experimental` branch of the standard library if you're using the `master` branch of Agda. The required changes are there already! The naming convention is a bit unfortunate.

**Comment by wenkokke** [comment]
Thanks, that makes sense! You know, I really wonder how I've never run into this problem before.
