### ISSUE TITLE
Change the order of arguments in `Data.List.Relation.Unary.All.cartesianProduct⁺`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#1288]
The `(∀ {x y} → x ∈₁ xs → y ∈₂ ys → P (x , y))` argument should come before the lists `xs`/`ys` the proof is being applied to

**Comment by gallais** [comment]
Doesn't sound well-scoped?

**Comment by MatthewDaggitt** [comment]
Doh of course. I must have generalised it when porting it from my own library!
