### ISSUE TITLE
Missing +-*-commutativeSemiring bundle for Integer

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1293]
I do not see ``+-*-commutativeSemiring`` in Data.Integer.Properties.

**Comment by gallais** [comment]
https://agda.github.io/agda-stdlib/v1.4/Data.Integer.Properties.html#40399

**Comment by gallais** [comment]
Right, we have the proof: https://agda.github.io/agda-stdlib/v1.4/Data.Integer.Properties.html#40399
but not the bundle

**Comment by MatthewDaggitt** [comment]
Fixed in #1336
