### ISSUE TITLE
Pair magmas etc

### ISSUE THREAD

**Issue by conal** [agda/agda-stdlib#1295]
Is there a library of constructions (or a convenient technique) for `IsMagma`, `Magma`, `IsMonoid`, `Monoid`, etc that turns pairs-of-magmas and functions-to-magmas into magmas on pairs and functions (and similarly for `Monoid` etc)? I can write just those I need, but it’s rather tedious, and I imagine others have wanted the same sort of thing.

**Comment by MatthewDaggitt** [comment]
In general such modules would live under `Algebra.Construct` (and for binary relations, `Relation.Binary.Construct`). Therefore for the pairs, I think you're looking for `Algebra.Construct.DirectProduct`. We don't yet have a corresponding module for lifting of magmas over functions. If I understand you correctly, I think such a module would be named `Algebra.Construct.On` and we'd welcome a pull request :+1:

**Comment by conal** [comment]
Thanks. And lovely code there!
