### ISSUE TITLE
sum and product for lists

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1298]
Data.List.Base  has `sum` and `product` for lists over Nat.

Probably it is better to replace this with a generic design:
```
module Algebra.Properties.Monoid  ... where
C = Carrier

Π₁ : C → List C → C   -- product of a nonempty list of elements                 
Π₁ x = foldr _∙_ x                                                              
                                                                                  
Π : List C → C         -- product of a list of elements                
Π = Π₁ ε                                                                        
    
----------------------------------------
module Algebra.Properties.Semiring ... where
...
sum1 : C → List C → C                                                           
sum1 = Algebra.Properties.Monoid.Π₁  +-0-monoid                                                            
                                                                                  
sum : List C → C                       
sum = Algebra.Properties.Monoid.Π  +-0-monoid 
```
with adding to Algebra.Properties the needed modules for Monoid and Semiring. 

?

**Comment by gallais** [comment]
cf. #1281

**Comment by mechvel** [comment]
I have an impression that  #1281 does not relate to what I am suggesting.
?
I suggest to have  the `product` function for a list (calling it  Π ) over any Monoid instead of only for list over Nat.
And to have `sum` via  Π  in +-0-monoid in Semiring.

**Comment by JacquesCarette** [comment]
That's exactly what ` fold                 : (M : Monoid) → List (Monoid.Carrier M) → Monoid.Carrier M` is. You can define `sum` and `product` as 1-liners from there, by specialization of the `Monoid` argument.
