### ISSUE TITLE
Standardising transitive closures

### ISSUE THREAD

**Issue by wenkokke** [agda/agda-stdlib#1310]
The `Induction.WellFounded` module introduces its own notion of a transitive closure:
https://github.com/agda/agda-stdlib/blob/master/src/Induction/WellFounded.agda#L171-L204

This should probably be replaced by `Relation.Binary.Construct.Closure.Transitive`:
https://github.com/agda/agda-stdlib/blob/master/src/Relation/Binary/Construct/Closure/Transitive.agda#L22-L27

**Comment by MatthewDaggitt** [comment]
Yup, this is a long standing issue. I did fix some of the other ones (see #611) but not all of them. I think this issue is probably a duplicate of #819?

**Comment by wenkokke** [comment]
Totally is, marking as such.
