### ISSUE TITLE
Proposal for naming style: reduce dash using in names

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1319]
This is proposed for the naming style.
I suggest to reduce dash using in names for new or not so old names - when a dash delimits a distinguished symbol. 
For example, to  denote   ``foo≈,  ∣resp``   rather than   ``foo-≈,  ∣-resp``. 

Motivation:
1. Anyone who wrote many proofs, sees that long names make proofs less readable.
2.  A distinguished symbol is a delimiter itself.
3. A dash also looks as subtraction.

**Comment by MatthewDaggitt** [comment]
Leaving aside any discussion of the pros/cons of this change, there's no way that we'll be changing the naming scheme for the entire library. It's just not practical.

**Comment by mechvel** [comment]
> there's no way that we'll be changing the naming scheme for the entire library. It's just not practical.

I do not mean entire library. I meant new contributions.

**Comment by MatthewDaggitt** [comment]
Yup, I realised that. It would lead to inconsistent names everywhere. For example it would lead to a situation where you would have `*-cancel` in `Data.Integer.Properties` and `*cancel` in `Data.Binary.Integer.Properties`. The ability of users to predict the names of proofs would greatly decrease.
