### ISSUE TITLE
Level-polymorphic Algebra.Module.Construct.Zero

### ISSUE THREAD

**Issue by conal** [agda/agda-stdlib#1321]
The `Algebra.Module.Construct.Zero` module provides zero-dimensional (singleton) module variants (left/right/bi, semi/full) only at level zero.

For instance,

``` agda
leftSemimodule : {R : Semiring r ℓr} → LeftSemimodule R 0ℓ 0ℓ
leftSemimodule = record
  { Carrierᴹ = ⊤
  ; _≈ᴹ_ = λ _ _ → ⊤
  }
```

It’s easy to generalize by adding level parameters to the module and importing *polymorphic* unit:

``` agda
module Algebra.Module.Construct.Zero {c ℓ : Level} where

open import Algebra.Bundles
open import Algebra.Module.Bundles
open import Data.Unit.Polymorphic

private
  variable
    r s ℓr ℓs : Level

leftSemimodule : {R : Semiring r ℓr} → LeftSemimodule R c ℓ
leftSemimodule = record
  { Carrierᴹ = ⊤
  ; _≈ᴹ_ = λ _ _ → ⊤
  }
```

and so on for the other definitions.

I can imagine three options for agda-stdlib:

1.  Add this polymorphic module, say as `Algebra.Module.Construct.Zero.Polymorphic`. (I’ve been using this variant.)
2.  Replace the current `Algebra.Module.Construct.Zero` module with this generalization as above.
3.  Add `Algebra.Module.Construct.Zero.Polymorphic`, and redefine `Algebra.Module.Construct.Zero` by importing the generalization, while specializing to level zero, and re-exporting.

Thoughts?

**Comment by JacquesCarette** [comment]
In the past, there were great sweeps of the library to generalize as many things as possible to be level polymorphic. Seems like that new module did not follow that trend. I think your 2nd option is the way to go.

**Comment by MatthewDaggitt** [comment]
Given that the modules in question were only added in the last version, I think I'm happy with option 2 as well. Not to mention `Relation.Binary.Construct.Always/Never` follow the same pattern.

@conal if you opened a PR making the change that'd be great!

**Comment by MatthewDaggitt** [comment]
I should add that `Algebra.Construct.Zero` will also need to be changed as well.
