### ISSUE TITLE
Overloading of 'just' in Data.Maybe causes problems

### ISSUE THREAD

**Issue by byorgey** [agda/agda-stdlib#133]
I discovered this while trying to prove that `just` is injective.

```
open import Data.Maybe using (Maybe ; just)
open import Relation.Binary.PropositionalEquality using (_≡_ ; refl)

bad : ∀ {a} {A : Set a} {x y : A} → (just x) ≡ (just y) → x ≡ y
bad p = {!!}

good : ∀ {a} {A : Set a} {x y : A} → (Maybe.just x) ≡ (Maybe.just y) → x ≡ y
good refl = refl
```

It's impossible to prove `bad`, but I had to ask in `#agda` before we figured out why.  As far as error messages go, it looks as though there are some unsolved metas in `just x ≡ just y`, but really the problem turns out to be that `just` is ambiguous, because it is defined as a constructor for not only `Maybe` but also `Any` and `All`, which are also defined in `Data.Maybe`.  I'm not really sure what the right solution is, but this seems like poor design on the part of the standard library (probably unintentional, but still).

**Comment by byorgey** [comment]
On second thought, the standard library is probably fine, I think the biggest problem here is the error messages (or lack thereof).  There was nothing that even hinted to me that the problem might be ambiguity.

**Comment by gallais** [comment]
> There was nothing that even hinted to me that the problem might be ambiguity.

In emacs the whole equality is highlighted in yellow and in the `*All Goals, Errors*` buffer there is an unsolved meta `_A` of type `Set _` associated to the propositional equality and two unsolved constraints:

> Failed to solve the following constraints:
  _6 := just x :? _A
  _8 := just y :? _A

It means that Agda was not able to infer the Set `_A` corresponding to the type of the left and right hand side of the equality. I suppose it would be nice to attach to unsolved constraints a reason for why they are unsolved (e.g. constructor ambiguity in your case). You could open an issue requesting this feature on https://github.com/agda/agda/issues.


One alternative to your solution of using a qualified name is to add a type annotation using `Function`'s `_∋_`:

    open import Function
    bad : ∀ {a} {A : Set a} {x y : A} → (Maybe A ∋ just x) ≡ (just y) → x ≡ y
    bad p = {!!}

**Comment by MatthewDaggitt** [comment]
Looks like this is solved.
