### ISSUE TITLE
Proposal for `\` intead  of  `\lambda`

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1331]
Probably it is better to write `\` instead of  `λ`, for the following reasons.
 
1)  `λ`  is specific to the area of functional programming. Many users do not know about lambda calculus.
    But most people know of anonymous functions, for example,  ``\ x -> x * x``. 

2) `\` is easier to type.

**Comment by gallais** [comment]
I think `λ` is not the biggest hurdle when you're starting to learn Agda.

**Comment by MatthewDaggitt** [comment]
> λ is specific to the area of functional programming.

In case you've missed it, Agda is a functional programming language so that seems an argument for `λ` rather than against :smile: 

Regardless, this another proposal that affects the entire library for no meaningful gain, so I'm afraid it's not going to happen.

**Comment by mechvel** [comment]
It does not effect any part of the library because ``\`` is already accepted as an equivalent to \lambda.
But all right, this is not very important, seven key strokes instead of two.

**Comment by MatthewDaggitt** [comment]
> But all right, this is not very important, seven key strokes instead of two.

I think you're optimising for the wrong metric. Design choices should not be made to make life easier for the library's developers, rather it should make it easier for the users.

> It does not effect any part of the library because \ is already accepted as an equivalent to \lambda.

@mechvel leaving aside the pros and cons of this particular issue, a key point that I think you might be missing is that gradually transitioning between two styles is not a good solution in general. Yes, for a single change it might be tolerable. However you've recently opened many issues proposing global stylistic changes. If we were gradually transitioning from one format to the other for each of your proposed changes the library would be a complete mess.

**Comment by gallais** [comment]
> seven key strokes instead of two.

`\Gl` works just fine at 3 keystrokes.

In general, you can use `C-u C-x =` to learn how to type the
unicode character under your cursor.
