### ISSUE TITLE
Big `Data.(Nat/Integer).Properties` wishlist

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1334]
* [x] Add [`⊔-mono-≤`](http://agda.github.io/agda-stdlib/Data.Nat.Properties.html#32000) and friends
* [ ] Make notations uniform for [`≤-<-trans `](http://agda.github.io/agda-stdlib/Data.Integer.Properties.html#6807) vs. [`<-transʳ`](http://agda.github.io/agda-stdlib/Data.Nat.Properties.html#8767)
* [x] `>⇒≢ : ∀ {m n} → m > n → m ≢ n`
* [x] `m+suc[n]≡suc[m]+n :  ∀ m n → m + suc n ≡ suc m + n` (already exists: `+-suc`)
* [x] `n≢1+n : ∀ {n} → n ≢ suc n` (already exists: `1+n≢n`)
* [x] `1<2+n :  ∀ n → 1 < 2 + n` (direct corollary of `m<m+n`)
* [x] `<1⇒≡0 :  ∀ {n} → n < 1 → n ≡ 0`
* [x] `n≤1⇒n≡0∨n≡1 : ∀ {n} → n ≤ 1 → n ≡ 0 ⊎ n ≡ 1`
* [x] `m<n⇒0<n : ∀ {m n} → m < n → 0 < n`
* [x] `pred-n≤n : ∀ {n} → pred n ≤ n`
* [x] `m≤n*m : ∀ m {n} → 0 < n → m ≤ n * m`
* [x] `m<n⇒n∸m>0 :  {m n : ℕ} → m < n → n ∸ m > 0` (already exists: `m<n⇒0<n∸m`)
* [x] `m*[1+n] :  ∀ m n → m * (suc n) ≡ m + m * n` (already exists: `*-suc`)
* [x] `upTo-n≤n :  ∀ n → All (_≤ n) (upTo n)` (stronger: `all-upTo : All (_< n) (upTo n)`)
* [ ] `length-upFrom : ∀ n c → length (upFrom n c) ≡ suc c`
* [ ] `length-from-to :  ∀ m n → length (from m to n) ≡ suc (n ∸ m)`

**Comment by mechvel** [comment]
Maybe join it with wishes for  Nat.Properties ?
("Big wish list for  Data.Nat(Integer).Properties"). 
For example, I had several wishes for Nat.Properties:
I am not sure, may be some of them do fit.
``
>⇒≢ : ∀ {m n} → m > n → m ≢ n                                                     
m+suc[n]≡suc[m]+n :  ∀ m n → m + suc n ≡ suc m + n                                       
n≢1+n : ∀ {n} → n ≢ suc n                                                                             
1<2+n :  ∀ n → 1 < 2 + n                                                                                                                                  
<1⇒≡0 :  ∀ {n} → n < 1 → n ≡ 0                                                    
n≤1⇒n≡0∨n≡1 : ∀ {n} → n ≤ 1 → n ≡ 0 ⊎ n ≡ 1                                       
m<n⇒0<n : ∀ {m n} → m < n → 0 < n                                                                                                                        
pred-n≤n : ∀ {n} → pred n ≤ n                                                                                        
m≤n*m : ∀ m {n} → 0 < n → m ≤ n * m                                
m<n⇒n∸m>0 :  {m n : ℕ} → m < n → n ∸ m > 0
m*[1+n] :  ∀ m n → m * (suc n) ≡ m + m * n 
``
There are also possible for Nat(Integer):   ``upFrom, upTo, downFrom, from_to_``,
with their properties in ..Properties:
``
upTo-n≤n :  ∀ n → All (_≤ n) (upTo n)
length-upFrom : ∀ n c → length (upFrom n c) ≡ suc c
length-from-to :  ∀ m n → length (from m to n) ≡ suc (n ∸ m) 
``
?

**Comment by mechvel** [comment]
May be, this one is useful:
```
pred-n<n : ∀ {n} → n ≢ 0 → pred n < n
pred-n<n {suc n} _   =  ≤-refl
pred-n<n {0}     0≢0 =  contradiction refl 0≢0
```

**Comment by gallais** [comment]
> m+suc[n]≡suc[m]+n :  ∀ m n → m + suc n ≡ suc m + n                                       

already exists: `+-suc : ∀ m n → m + suc n ≡ suc (m + n)`

**Comment by MatthewDaggitt** [comment]
Opened https://github.com/agda/agda-stdlib/issues/2087 to deal with the naming issue. I'm with @gallais in not understanding what the last two lemmas are supposed to be, and it's been two years with no reply so I'm going to close this one.
