### ISSUE TITLE
Data.Vec._⊛_ is overly/underly lazy

### ISSUE THREAD

**Issue by effectfully** [agda/agda-stdlib#1338]
`_⊛_` is defined as

```agda
_⊛_ : ∀ {n} → Vec (A → B) n → Vec A n → Vec B n
[]       ⊛ _        = []
(f ∷ fs) ⊛ (x ∷ xs) = f x ∷ (fs ⊛ xs)
```

and the lack of pattern matching on `[]` in the first clause caused me some head scratching, 'cause the second argument wasn't getting inferred where I was expecting it to (thanks to @andreasabel for pointing out what was causing the problem).

On the other hand it's kinda nice to be lazy and make `_⊛_` compute when the second argument is not definitionally `[]`. But then why stop there and not match only on `n` like that:

```agda
_⊛_ : ∀ {n} → Vec (A → B) n → Vec A n → Vec B n
_⊛_ {0}     _  _  = []
_⊛_ {suc _} fs xs = head fs (head xs) ∷ (tail fs ⊛ tail xs)
```

This would compute even better than the current definition.

So I think the current definition is a bit inconsistent as it's somewhere between these two options and it'll perhaps be an improvement to stick to a single strategy: either favor inference or computability.

**Comment by MatthewDaggitt** [comment]
Excellent question. You're right, the current definition is somewhat of a half-way house. I'm in favour of:
```agda
_⊛_ : ∀ {n} → Vec (A → B) n → Vec A n → Vec B n
[]       ⊛ []       = []
(f ∷ fs) ⊛ (x ∷ xs) = f x ∷ (fs ⊛ xs)
```
as i) it leads to a much more readable definition and ii) I haven't seen the alternative style of pattern matching only on implicit arguments to improve computability in use anywhere else in the library.

Please do feel free to submit a PR :+1:

**Comment by gallais** [comment]
> I haven't seen the alternative style of pattern matching
  only on implicit arguments to improve computability in
  use anywhere else in the library.

We do use it in e.g. [`fromℕ<`](https://agda.github.io/agda-stdlib/Data.Fin.Base.html#1985) so that it reduces when applied to a `suc m < suc n`
proof even if it is not `s≤s`-headed. Cf. #717 for that one in particular.
