### ISSUE TITLE
Suggestion:  `a` --> `α` for a Level variable

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1346]
`a` is likely to be used to denote an element of a type different from Level, say, Carrier.
And if the team agrees, the replacement  to `α` can be done by 
Find-and-replace  'a ℓ'  'α ℓ'   in  Foo.agda.

**Comment by gallais** [comment]
This would break backwards compatibility for very little benefit.
Let me [quote Matthew](https://github.com/agda/agda-stdlib/issues/1331#issuecomment-716321418):

> Regardless, this another proposal that affects the entire library for no meaningful gain, so I'm afraid it's not going to happen.
