### ISSUE TITLE
``Nat.Properties.≤-<-trans``

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1349]
``<-≤-trans`` and  ``≤-<-trans`` are usable for various ordering instances.  

For Nat,  ``<-≤-trans`` is proved by  ``≤-trans``.
But ``≤-<-trans`` may be needs to be proved in  Data.Nat.Properties.
Needs it?

Similar questions are for Integer.

**Comment by gallais** [comment]
Pretty sure that's:

```agda
<-transʳ : Trans _≤_ _<_ _<_
<-transˡ : Trans _<_ _≤_ _<_
```

Also we could maybe have a **single** issue with a checklist of all of
the requests for `Data.(Nat/Integer).Properties`? We're not going to
open one issue per lemma that is missing...

**Comment by gallais** [comment]
Edit #1334 to start a checklist
