### ISSUE TITLE
Inference difficulties

### ISSUE THREAD

**Issue by conal** [agda/agda-stdlib#1352]
I’ve been encountering inference difficulties working with agda-categories. I’ve whittled down the problem to a simplified example that doesn’t use agda-categories:

``` agda
open import Level
open import Algebra.Bundles using (Magma)
open import Relation.Binary using (Rel)
open import Function.Equality using (_⟶_) renaming (id to ⟶-id)

record Cat (o ℓ : Level) : Set (suc (o ⊔ ℓ)) where
  infix  4 _⇒_
  field
    Obj : Set o
    _⇒_ : Rel Obj ℓ
    id  : ∀ {A} → A ⇒ A
    -- ... elided

M : Cat _ _
M = record { Obj = Magma 0ℓ 0ℓ
           ; _⇒_ = λ A B → Magma.setoid A ⟶ Magma.setoid B
           ; id  = ⟶-id
           -- ...
           } 

open Cat M

_ : ∀ {A : Magma 0ℓ 0ℓ} → A ⇒ A
_ = id
```

The error message (referring to the use of `id` in the last line):

``` agda
__∙__27 : Algebra.Core.Op₂ (Magma.Carrier A)  [ at /Users/conal/Agda/cat-linear/src/T8.agda:24,5-7 ]
_∙-cong_30
  : Algebra.Definitions.Congruent₂ (λ z z₁ → (A Magma.≈ z) z₁)
    __∙__27  [ at /Users/conal/Agda/cat-linear/src/T8.agda:24,5-7 ]
```

If I replace `Magma` by a structure with more operations, such as `Ring`, I see more such errors, failing to infer each operation and associated property.

I’d appreciate any insights about causes and cures for error.

**Comment by conal** [comment]
This issue is based on https://github.com/agda/agda-categories/issues/217, replacing the agda-categories dependency with a whittled down version of `Category`.

**Comment by MatthewDaggitt** [comment]
I've tried using the new function hierarchy defined in #1353 and the same problem occurs, which rules out it being a problem with `⟶`...

In general these sort of open ended inference questions are better suited (and therefore more likely to get answers!) to the Agda mailing list. If the answer is that the one of the library definitions needs tweaking then opening an issue here is next thing to do :smile:

**Comment by conal** [comment]
I've asked on the Agda mailing list. Thanks for the suggestion.

**Comment by MatthewDaggitt** [comment]
Answered on the mailing list so closing.
