### ISSUE TITLE
No proof that _*_ has an inverse for ℚ

### ISSUE THREAD

**Issue by Taneb** [agda/agda-stdlib#1370]
`Data.Rational.Unnormalised.Properties` has `*-inverseˡ : ∀ p {p≢0 : ℤ.∣ ↥ p ∣ ≢0} → 1/_ p {p≢0} * p ≃ 1ℚᵘ` and `*-inverseʳ : ∀ p {p≢0 : ℤ.∣ ↥ p ∣ ≢0} → p * 1/_ p {p≢0} ≃ 1ℚᵘ` but no corresponding proofs exist in `Data.Rational.Properties`.

I made a brief attempt at proving `*-inverseˡ : ∀ p {p≢0 : ∣ ↥ p ∣ ≢0} → 1/_ p {p≢0} * p ≡ 1ℚ` in terms of the unnormalised version but I didn't succeed.

**Comment by uzytkownik** [comment]
It seems to be added by #1218 ?

**Comment by MatthewDaggitt** [comment]
> It seems to be added by #1218 ?

That only added it for unnormalised rationals.
