### ISSUE TITLE
Release of version 1.5

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#1386]
Definitely getting to a point where we have enough material for the release of 1.5. Couple of loose ends to tie up on the `Algebra` side of things, but I'll aim to make a release candidate mid-January.

**Comment by MatthewDaggitt** [comment]
Not accepting any more PRs for v1.5.

**Comment by JacquesCarette** [comment]
But we can go ahead and make new PRs, right? They'll just wait until you start on 1.6?

**Comment by gallais** [comment]
Yes, I think so.

I am hoping to get #1039 back in shape before we start merging PRs
for 1.6 though so that we finally get this done. IIRC it's mostly
a matter of handling errors gracefully.

**Comment by JacquesCarette** [comment]
Makes sense - those changes sure would be nice. I'll probably still go ahead and make some (tiny) PRs, and be ready to switch to this new mode whenever it goes live. I'd rather not have some long stale branches around for too long, I'll forget exactly what's in them!  I had to delete some recently because they didn't seem rescuable anymore.

**Comment by MatthewDaggitt** [comment]
Yes, new PRs are fine. I just won't be merging any more until `v1.5` is released.

**Comment by MatthewDaggitt** [comment]
Announced the first release candidate.

**Comment by mechvel** [comment]
I have an impression that  my old way to import ``_≉_`` has changed.
I see  ``_≉_``  defined in Relation.Binary.Bundles and also in Algebra.Bundles.RawMagma,
Does  the latter need to import it from the former ?
From where my application needs to take ``_≉_``  ?

**Comment by MatthewDaggitt** [comment]
So both the raw algebraic bundles and binary relation bundles define it. (Non-raw) algebraic bundles have switched from using the definition from the binary relation `Setoid` bundle to using the version from the raw algebraic bundles. This change should be backwards compatible as the two definitions are interchangeable as they both evaluate to the negation of the same shared equality relation. Please let me know if the change has broken your code?

In the case above you only have the option to take it from `Setoid` as you don't have an algebraic bundle available?

**Comment by mechvel** [comment]
It is broken. 

But in my particular case this occurs easy to fix. 
Many modules in my application do 
```
open import OfSetoid  setoid {public} using ( ...)
```
and also open-import  standard algebraic bundles. 
Now, in `lib-1.5-rc1`, this leads to overlap at  ``_≉_`` in many modules of application.
So, I comment out the definition of `OfSetoid._≉_`, and import it where it is needed from Setoid or from other modules
(of standard Algebra or applied). If it overlaps, then I set  ``hiding (_≉_)`` or remove it from the import of 
``open import Setoid ...``.
I see now that this does not spoil the code any essentially. 
Probably I also need to also replace the proofs ``≉sym,  ≉resp,  ≉respˡ,  ≉respʳ``  with standard imports. 
Where they are?

> In the case above you only have the option to take it from Setoid as you don't have an algebraic bundle available?

In a small basic   ``module OfSetoid {α α≈} (A : Setoid α α≈)``, 
I cannot import algebraic bundles. In almost each  other module some algebraic bundle can be imported.

**Comment by mechvel** [comment]
Another break is in my proofs for Integer:
```
⊖-via∸for-n<m :  {m n : ℕ} → n <ₙ m →  m ⊖ sucₙ n ≡ + (m ∸ (sucₙ n))
⊖-via∸for-m≤n :  {m n : ℕ} → m ≤ₙ n →  m ⊖ sucₙ n ≡ -[1+ (n ∸ m) ]
```
They are proved recursively. But the definition for  standard ``_⊖_`` has changed.
And I do not find, so far, how to prove these two lemmas, because the new definition for `_⊖_` is via  ``Nat.<ᵇ``,
and I do not understand how to compose proofs using  Booleans  and `T` (I think of them as of something unnatural).
If it was via ``Nat._<?_`` instead of   ``Nat.<ᵇ``, then all right.  
You see, `Nat._<?_` is also by built-in, it is fast, why do not use it? 
If its result is used as, say, ``(yes _) -> foo``, and the client does not compute `p`, then how can it be essentially slower than
``Nat.<ᵇ`` ?

**Comment by gallais** [comment]
> You see, Nat._<?_ is also by built-in, it is fast, why do not use it?

It's a matter of dependencies: `_⊖_` is defined in `Data.Integer.Base`
and that module relies on `Data.Nat.Base` but `_<?_` is only defined
in `Data.Nat.Properties`.

Your first lemma looks like an instance of the following one defined in
`Data.Integer.Properties`:

```agda
⊖-≥ : ∀ {m n} → m ℕ.≥ n → m ⊖ n ≡ + (m ∸ n)
```

The second seems to be a direct corollary of:

```agda
⊖-≰ : ∀ {m n} → n ℕ.≰ m → m ⊖ n ≡ - + (n ∸ m)
```

**Comment by mechvel** [comment]
> Your first lemma looks like an instance of the following one:
``` 
>  ⊖-≥ : ∀ {m n} → m ℕ.≥ n → m ⊖ n ≡ + (m ∸ n)
```
This works. Thank you.

**Comment by mechvel** [comment]
The next break is due to ``Data.List.Relation.Unary.All.Properties``.
Its prelude of
```                                                                                  
private                                                                           
  variable                                                                        
    a b c p q r ℓ ℓ₁ ℓ₂ : Level                                                   
    A : Set a                                                                     
    ...                                                                    
```
has changed. So that  ``filter⁺`` and probably several other functions need to be called in a different format.
For example,
```
    filter⁺  {P = IsNonzeroMon} {Q = (_< e) ∘ Mon.exp} nonzeroMon? mons'<e 
```
is not type-checked any more. One has to remove the implicit part.
I do not see this issue in CHANGELOG.md.

**Comment by mechvel** [comment]
I have finished my testing.
Only three breaks have been discovered, they are described above. 
To me personally, I work around them by changing the application code a bit.

**Comment by MatthewDaggitt** [comment]
> Probably I also need to replace the proofs ≉sym, ≉resp, ≉respˡ, ≉respʳ with standard imports.
Where they are?

https://github.com/agda/agda-stdlib/blob/f0c53d657d65a200be0879eeb92feaebdd3089fb/src/Relation/Binary/Properties/Setoid.agda#L36

> So that filter⁺ and probably several other functions need to be called in a different format.

Hmm so yes, so that's a result of overzealous generalisation in #1379. I'm a bit torn on this. Should we be ensuring backwards compatibility with implicit variable ordering even if those implicit variables are never needed? I guess we probably should...

**Comment by JacquesCarette** [comment]
On the last point, I disagree. If the variables were not needed, they should disappear from the calling conventions, the sooner the better. Unused variables should never affect anything - it's a bug if it is otherwise.

**Comment by gallais** [comment]
I think that we should not needlessly rename implicit variables
(I remember a PR where the level names were originally changed
purely for esthetics and we reverted that because it was a breaking
change) but we should also not prevent ourselves from cleaning up
the library because of such considerations.

**Comment by MatthewDaggitt** [comment]
> On the last point, I disagree. If the variables were not needed, they should disappear from the calling conventions, the sooner the better. Unused variables should never affect anything - it's a bug if it is otherwise.

Sorry I should have been clearer. The implicit variables are not "never needed", they are "never needed to be provided explicitly"

> I think that we should not needlessly rename implicit variables
(...) but we should also not prevent ourselves from cleaning up
the library because of such considerations.

I could get on board with that.

**Comment by MatthewDaggitt** [comment]
Hmm so tried to update the experimental branch in the main agda repo and ran into agda/agda#5147. Long story short, there's a regression in Agda on master that's causing the experimental branch not to type check. In theory it doesn't indicate anything is wrong with the standard library release, but obviously unsure if there's more issues down the line hidden behind that failure.

Current plan is to wait a couple of days to see if agda/agda#5147 is fixed quickly, otherwise will go ahead with the release as planned.

**Comment by MatthewDaggitt** [comment]
Release has been made. Thank you to everyone for their contributions!

**Comment by MatthewDaggitt** [comment]
@gallais I am struggling to follow the new post-release instructions to update the `gh-pages` branch. All the commands "work" up until the `git commit` instruction but they seem to nuke everything in the folder, in particular the `fix-whitespace.yaml` file so my commit hooks no longer work. 

Is it possible to generate the files in a subdirectory rather than putting everything at the top-level?

**Comment by MatthewDaggitt** [comment]
Just a heads up that with this release, we passed 100K loc. We're officially a medium sized development :grin:
