### ISSUE TITLE
Define exponentiation over a semiring as multiplication over the multiplicative monoid.

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1389]
module Algebra.Properties.Semiring.Exponentiation  
has
```
_^_ : Carrier → ℕ → Carrier                                                            
x ^ zero  = 1#                                                                         
x ^ suc n = x * x ^ n                                                                  
```
It is much more sensible to define this in a more general case, in  Algebra.Properties.Monoid, like this:
```
module Algebra.Properties.Monoid.Foo  {a ℓ} (M : Monoid a ℓ) where 
...
_^_ : Carrier → ℕ → Carrier                                                            
x ^ zero  =  ε                                                                       
x ^ suc n = x ∙ x ^ n                                                                  
```
``^-congˡ`` and many other useful properties to be proved there. 
As to Semiring R,  it has +-monoid and  *-monoid. And exponentiation over R is imported
from  ``Algebra.Properties.Monoid.Foo *-monoid``  with renaming `ε`  to 1#,   `_∙_` to `_*_`.
Further, multiplication  ``_×_``  by  a natural in R, is actually ``_^_`` imported from 
``Algebra.Properties.Monoid.Foo +-monoid``   with renaming ``_^_`` to ``_×_``,
only we need to swap the arguments in the  current definition of  ``_×_`` (as I recall).
There is no need to define these operations several times, one needs only to import them from one  place with  
renaming. The same is for the proofs for the properties of ``_^_``  and ``_×_``.

Further, product (Π) to be defined over Monoid, with using  `ε`  and ``_∙_``.
Importing it from    ``Algebra.Properties.Monoid.Foo *-monoid``    makes it a product (by `_*_`) 
in Semiring.
Importing it from    ``Algebra.Properties.Monoid.Foo +-monoid``   with renaming `Π` to `sum`
makes it a sum (by `_+_`) in Semiring. The proofs also are imported this way.

Useful  properties for exponentiation are likely to be, for example, 
``x ^ (m + n) ≈ x ^ m ∙ x ^ n``, and some of them related to divisibility.
 Useful  properties for product (Π) are likely to be 
``Π (xs ++ ys) ≈ ...``, and some of them related to divisibility.
If we define `^` and `Π` in one place, and prove their properties in one place, and import these items
to other places with renaming, we save proofs and avoid multiplying notions.

**Comment by JacquesCarette** [comment]
Strictly speaking, it could go into LeftUnitalSemigroup (which, AFAIK, doesn't exist yet, but it could!)  I'm not seriously suggesting this, just pointing out that if we're going for ultimate generality, that's where it goes.

**Comment by mechvel** [comment]
My suggestion is partly defined  in Algebra.Properties.Monoid.Multiplication.
But 
1) there it is for the additive denotation (``_+_``), while  ``_+_`` is traditionally used in algebra only for Commutative case,
2)  in other places (like Algebra.Properties.Semiring.Exponentiation) ``_^_`` is defined by new instead
     of importing the items with renaming from a single place of Monoid. It is not desirable to multiply notions. 

In this particular subject I have an experience and a working Agda code, for a long time.
Only it is needed to adopt it to Standard library.

**Comment by MatthewDaggitt** [comment]
@mechvel I already have a PR backed up behind #1387 that makes the very change that you suggest.

@JacquesCarette the design in #1387 is general enough such that if we do add a `LeftUnitalSemigroup` at some point then the operation can be "demoted" to it with no backwards compatibility issues.
