### ISSUE TITLE
Add proofs for `takeWhile` and `head` in `Data.List.Relation.Unary.All.Properties`

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1406]
In  lib-1.5,  Data.List   has takeWhile and dropWhile.
But where are their usable proofs, like 
```
all-taikeWhile :   ... (xs : List A) -> All P (takeWhile P? xs)

head?-dropWhile :  ... (xs : List A) →
                     let ys = dropWhile P? xs
                     in
                     ¬HasHead ys  ⊎  ∃ (\ (hh : HasHead ys) → ¬ P (head ys hh))
-- either ys is empty or  ¬ P (head ys)
```
?

**Comment by gallais** [comment]
I would write the second one `All (∁ P) (head (dropWhile P?))` where
`All` is from `Data.Maybe.Relation.Unary.All`.

**Comment by mechvel** [comment]
And where this `head` comes from?
As to me, I meant my home-made ``head : (xs : List A) -> HasHead xs  -> A``
(where HasHead  is HasElement which I have taken from  J. Carette).

**Comment by gallais** [comment]
From [`Data.List.Base`](http://agda.github.io/agda-stdlib/Data.List.Base.html#6784)

**Comment by mechvel** [comment]
> I would write the second one All (∁ P) (head (dropWhile P?)) 

This is similar to converting a maybe data to a list in ``(head (dropWhile P?))`` and then applying `All`.
(?) 
So far, I like my version better. But let the team decide.

How do you express the property 
 ```
P =   (xs is empty)  or  (head xs ≡ last xs)
```
?
I express it as 
```
P =  Null xs  ⊎  (∃ \ (hh : HasHead xs) → head xs hh ≡ last xs hh)
```

Also maybe it worth to
a) rename `List.Base.head` to  `mbHead`,
b) introduce ``head : (xs : List A) -> HasHead xs -> A``.

Similar questions concern  `tail`, `last`, `init`.

**Comment by gallais** [comment]
I would use [`Data.Maybe`'s `Pointwise`](http://agda.github.io/agda-stdlib/Data.Maybe.Relation.Binary.Pointwise.html#741) on `head xs` and `last xs`.


> b) introduce head : (xs : List A) -> HasHead xs -> A.

We already have `Data.List.NonEmpty` with these type of functions.

**Comment by JacquesCarette** [comment]
Right. My suggestion was mostly with respect to a specific problem that @mechvel posted on the mailing list. It's definitely better to use the pre-existing functions of the library in these cases. [They are not so easy to find, which is a problem. It's not that the library is not well organized, far from it, but rather that there's no decent equivalent to good old 'grep' or Hoogle.]

**Comment by MatthewDaggitt** [comment]
The function `takeWhile⁺` should be added next to:

https://github.com/agda/agda-stdlib/blob/decd916f6e9761e2d00fe676d1ecfc9a6518433f/src/Data/List/Relation/Unary/All/Properties.agda#L416

We should then add a function:

`head⁺ : All P xs -> Maybe.All P (head xs)`

to the same file.

The second proof `head?-dropWhile` should not be in the library at all as it's simply a composition of the first two.

**Comment by mechvel** [comment]
To my mind, it is simpler and more natural to use the HasHead argument for the `head` format
rather that using the NonEmpty record or Maybe.head or/and Maybe.All.

**Comment by gallais** [comment]
> The second proof head?-dropWhile should not be in the library at all as it's simply a composition of the first two.

I don't think that's true: `head-dropWhile` is about the predicate used in `dropWhile`
rather than whatever held of the list before it was dropWhile'd.

**Comment by MatthewDaggitt** [comment]
> I don't think that's true: head-dropWhile is about the predicate used in dropWhile
rather than whatever held of the list before it was dropWhile'd.

Ah yes of course! Because you don't have any guarantees about `tail (dropWhile ...)` so all you can do is reason about the `head`.
