### ISSUE TITLE
Builds being cancelled

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#1424]
Looks like all the [recent builds](https://travis-ci.org/github/agda/agda-stdlib/builds/758981338) on Travis have been "Cancelled". I'm guessing this might be to do with the upcoming Travis migration? Should we be making the jump to Github actions in the same way that the main Agda repo has?

**Comment by MatthewDaggitt** [comment]
Hmm but builds on pull requests still seem to be going through. Its just the ones on `master` that are being cancelled...

**Comment by gallais** [comment]
Fixed by #1516
