### ISSUE TITLE
Redefine as many numeric operations in terms of primitive ones as possible

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#1427]
Whilst discussing #581 it came up that several operations in `Data.Nat.Base` still evaluate using unary arithmetic. In version 2.0 it may be worth fixing these...
  - `_⊔_`
  - `_⊓_`
  - `∣_-_∣`

**Comment by andreasabel** [comment]
Do you need more builtins on the Agda side for this?  (There are no NATMAX, NATMIN etc. builtins atm.)

**Comment by gallais** [comment]
I think the plan is to use `_<ᵇ_`
