### ISSUE TITLE
Improve performance of `div` and `mod` over Integers

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1430]
I have  ``bₙ : ℕ;  bₙ≢0 : bₙ ≢ 0``,
and set
```
b : ℤ
b = + bₙ

b≢0 : b ≢ 0ℤ
b≢0 +bₙ≡+0 =  bₙ≢0 (ℤp.+-injective +bₙ≡+0) 

remₙ :  ℕ → (n : ℕ) → n ≢ 0 → ℕ
remₙ m n n≢0 =  _%_ m n {fromWitnessFalse n≢0}

remBₙ : ℕ → ℕ
remBₙ n =  remₙ n bₙ bₙ≢0

remB : ℤ → ℤ 
remB (+ n)    =  + (remBₙ n)
remB -[1+ n ] =  + (bₙ ∸ (remBₙ (suc n)))
```
And `remB` runs fast in a loop.
If I define  `remZ` as 
```
rem : ℤ → (y : ℤ) → y ≢ 0ℤ → ℤ
rem _ (+ 0)              0≢0 =  contradiction refl 0≢0 
rem x y@(+ (suc _)) _    =  + (x mod y) 
rem x y@(-[1+ _ ])    _    =  + (x mod y)

remZ : ℤ → ℤ 
remZ x =  rem x b b≢0 
```
then  `remZ` runs hundreds of  times slower than `remB` in the same loop.
Is there something wrong with  ``Integer.DivMod._mod_`` ?

**Comment by gallais** [comment]
I'm not sure why we are using [`NDM.divMod`](http://agda.github.io/agda-stdlib/Data.Integer.DivMod.html#1254) in the implementation,
it looks like we may be able to use [`_%_`](http://agda.github.io/agda-stdlib/Data.Nat.DivMod.html#1485) instead.

**Comment by mechvel** [comment]
Here is attached the test.
[ModTest.zip](https://github.com/agda/agda-stdlib/files/6015357/ModTest.zip)

It shows that Integer arithmetic runs 1000 times slower than of Nat.

sumRem  sums remainders on ``n : Nat`` by ``bN = 99991``  for n in 0, ..., 21000,
with also adding  ``rem (2+n) bN``  each time.
rem  is via  `Nat.DivMod._%_`. 

Also put  ``b = + bN : Integer``,
remZ  the remainder for Integer via applying `Integer.DivMod._mod_`
sumRemZ  sums   ``remZ (+ n) b``  for the same list of `n` as above,
with changing each sumand for "2+n" to  ``-[1+ n ]``.    

Printed is the value of sumRem (sumRemZ).  sumRemZ is 1000 times slower.

If we remove the negative numbers from the list, then  sumRemZ  becomes fast.

Maybe  Integer `_mod_` is slow on negative dividends, may be `_+_` on negatives is slow, I wonder.
 
It is evident that these two

**Comment by mechvel** [comment]
Probably  ``_mod_`` of Integer is responsible.
Because when I remove `mod` and change the clause to 
```
   (suc n) -->  (+ (suc n)) +ᵢ (-[1+ (2 * n) ] +ᵢ (sumZ n))
```
then the list is summed up fast.

**Comment by MatthewDaggitt** [comment]
Hmm we'd have to use both `_/_` and `_%_` but yes, easy enough to change. Changing it will invalidate the whole file though so I'm tempted to leave it to v2.0?

**Comment by gallais** [comment]
> Hmm we'd have to use both `_/_` and `_%_`

We're not using the `q` so that's why I was suggesting using `_%_` only.

**Comment by MatthewDaggitt** [comment]
Ah yes, sorry. I was looking at the definition of `div` not `mod`. The former requires both, but the latter only `_%_`.

**Comment by mechvel** [comment]
> Probably `_mod_` of Integer is responsible.
> [..]
> ``(suc n) -->  (+ (suc n)) +ᵢ (-[1+ (2 * n) ] +ᵢ (sumZ n))``

I meant the case when the dividend is negative.
Also I never tested `_/_` on Integer, may be it also needs improvement.

**Comment by mechvel** [comment]
I hope for lib-2.0 t improve the thing.
So that I would be able to cancel my home-made divRem.

**Comment by MatthewDaggitt** [comment]
I've opened a PR fixing it in #1573
