### ISSUE TITLE
Empty `where' block (ignored)

### ISSUE THREAD

**Issue by rzil** [agda/agda-stdlib#1432]
Sorry if this has already been raised, however, I can't find any issues tracking this. Agda is giving me this warning
```
$HOME/.agda/lib/agda-stdlib-1.5/src/Data/List/Relation/Unary/Any/Properties.agda:257,5-10
Empty `where' block (ignored)
when scope checking the declaration
  from∘to (p , q)
```
It is easy enough to drop the offending `where`. Is there a reason this is still in the standard library?

**Comment by gallais** [comment]
(Sorry about earlier, I was on my phone and pressed the wrong button)

It's still here: http://agda.github.io/agda-stdlib/Data.List.Relation.Unary.Any.Properties.html#9190

How did you get the warning? Is it new?
I am not getting anything right now when I load that module with 2.6.1.1

**Comment by rzil** [comment]
Hi, yes I am using master branch. I cannot recall why, but I had problems building the official release.

**Comment by MatthewDaggitt** [comment]
@rzil thanks for reporting. I've also come across this one myself, I'm pretty sure flagging empty `where` blocks is a new feature of Agda 2.6.2 as I only get it when using the dev version of Agda.

**Comment by MatthewDaggitt** [comment]
This is already fixed on the `experimental` branch so closing.
