### ISSUE TITLE
Fix equality combinator names in `Data.Rational.Unnormalised.Properties.≤-Reasoning` 

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#1437]
Currently the combinators use `≈` instead of `≃`

**Comment by JacquesCarette** [comment]
I don't know how to rename syntax declarations?

**Comment by jamesmckinna** [comment]
Ha! Is this an Agda issue, that syntax declarations have 'global' scope once imported/else are not Renamable like other imports... AFAICT, 'pattern' syntax isn't renamable either...?

**Comment by MatthewDaggitt** [comment]
Yes, it is an Agda problem, and it sucks. 

See the last bullet in the [v1.3 CHANGELOG](https://github.com/agda/agda-stdlib/blob/master/CHANGELOG/v1.3.md#changes-to-how-equational-reasoning-is-implemented) for how we rename syntax.
