### ISSUE TITLE
a little annoyance in PER reasoning

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-stdlib#1446]
At this moment, https://github.com/agda/agda-stdlib/blob/master/src/Relation/Binary/Reasoning/PartialSetoid.agda uses 
https://github.com/agda/agda-stdlib/blob/911b52d54d39939a78ba63a387e30cc90ad64163/src/Relation/Binary/Reasoning/Base/Partial.agda#L75-L76

as the terminator for reasoning. This is rather annoying, because consider a proof using transitivity in PER:
```
trans p1 p2
```
That's already a valid proof. But if we use reasoning API, we will get
```
begin
  foo ≈⟨ p1 ⟩
  bar ≈⟨ p2 ⟩
  baz ∎⟨ ??? ⟩
```
All of a sudden, we are obliged to provide another proof which is not necessary in the original proof. Are we able to get rid of this part of the API?

That actually points out a fact that all proofs using this reasoning API requires an unnecessary proof at the very end, which could be a redundant `refl` proof for `Setoid`.

**Comment by HuStmpHrrr** [comment]
A little twist seems does the job:
```
open import Level
open import Relation.Binary
open import Data.Bool

module Reasoning
  {a ℓ} {A : Set a} (_∼_ : Rel A ℓ) (trans : Transitive _∼_)
  where

  infix  3 _∎
  infixr 2 step-∼
  infix  1 begin_

  data [_]_IsRel_ : Bool → (x y : A) → Set (suc ℓ) where
    emp : ∀ x → [ false ] x IsRel x
    rel : ∀ {x y} → x ∼ y → [ true ] x IsRel y

  begin_ : ∀ {x y} → [ true ] x IsRel y → x ∼ y
  begin rel x∼y = x∼y

  step-∼ : ∀ x {b y z} → [ b ] y IsRel z → x ∼ y → [ true ] x IsRel z
  step-∼ _ (emp _) x∼y   = rel x∼y
  step-∼ _ (rel y∼z) x∼y = rel (trans x∼y y∼z)

  syntax step-∼  x y∼z x∼y = x ∼⟨  x∼y ⟩ y∼z

  _∎ : ∀ x → [ false ] x IsRel x
  _∎ x = emp x

  module Demo {x y z : A} (p : x ∼ y) (q : y ∼ z) where

    lem : x ∼ z
    lem = begin
      x ∼⟨ p ⟩
      y ∼⟨ q ⟩
      z ∎
```

**Comment by MatthewDaggitt** [comment]
Seems sensible to me! A PR would be very welcome. We should deprecate rather than remove the existing termination operator though.
