### ISSUE TITLE
Empty `Irrelevance` module

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#145]
It seems to be empty at the moment. Anybody have any plans to fill it with anything again? Otherwise I might remove it. As it's empty it's not playing any useful backwards-compatibility role...

**Comment by andreasabel** [comment]
It once contained a builtin axiom, but no longer.  I think it is ok to remove it.

**Comment by MatthewDaggitt** [comment]
Deleted it in e825415
