### ISSUE TITLE
Union of indexed containers not maximally universe-polymorphic

### ISSUE THREAD

**Issue by andreasabel** [agda/agda-stdlib#1452]
The union operation requires two containers of the same universe levels:
https://github.com/agda/agda-stdlib/blob/48ee0073e1fa0cda2327f00a3ec37068859a6bec/src/Data/Container/Indexed/Combinator.agda#L109-L110
However, the same code would work for containers of different levels.
I have an application where I need different levels.

TODO:
- check for similar restrictions other container operations

RFC.

**Comment by gallais** [comment]
In #346 I only dealt with the non-indexed case because that was already
quite a lot of boring work. Note that the position's level has to be the
same if you're going to use sum-elim to define it.
