### ISSUE TITLE
``-x*y, x*-y`` for Integer 

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1455]
Has the library something to replace the following for Integer ?
```
-x*y  :   ∀ x y → ((- x) * y) ≈ (- (x * y))                                                                                 
x*-y  :   ∀ x y → (x * (- y)) ≈ (- (x * y)) 
```
They also can be proved for Ring, and then this proof can be applied for Integer, after setting 
`+-*-ring` there.
?

**Comment by Taneb** [comment]
These are proven for arbitrary rings in [`Algebra.Properties.Ring`](http://agda.github.io/agda-stdlib/Algebra.Properties.Ring.html) as `-‿distribˡ-*` and `-‿distribʳ-*`, and for integers specifically in [`Data.Integer.Properties`](http://agda.github.io/agda-stdlib/Data.Integer.Properties.html) as `neg-distribˡ-*` and `neg-distribʳ-*`.

These equalities are backwards compared to what you were after, but they can be reversed by using `sym` either from the underlying setoid (in the case of an arbitrary ring) or from [`Relation.Binary.PropositionalEquality`](http://agda.github.io/agda-stdlib/Relation.Binary.PropositionalEquality.html) (in the case of integers)

**Comment by MatthewDaggitt** [comment]
Thanks @Taneb, closing.
