### ISSUE TITLE
https://agda.github.io/agda-stdlib links are broken

### ISSUE THREAD

**Issue by spall** [agda/agda-stdlib#1457]
https://agda.github.io/agda-stdlib links appear to be broken but are still referenced in README so I assume this is an error.

**Comment by gallais** [comment]
Looks like the latest travis update has decided to nuke everything?!

https://github.com/agda/agda-stdlib/commit/647f69f33f6081d699e59c9d74a605ea4d5c39bb

**Comment by gallais** [comment]
And all the old versions are also gone now. These are a PITA to regenerate as you
need a compatible version of Agda installed...

**Comment by gallais** [comment]
Okay everything should be back. I am not sure why it got nuked so I'm hoping it will not be removed again.
