### ISSUE TITLE
Unused arguments of ```Function.Properties.Inverse.isEquivalence``` and ```Function.Properties.Equivalence.isEquivalence```

### ISSUE THREAD

**Issue by XiaohuWang0921** [agda/agda-stdlib#1460]
For some reason both ```Funciton.Properties.Inverse.isEquivalence``` and ```Function.Properties.Equivalence.isEquivalence``` take two arguments ```(R : Setoid a ℓ₁)``` and ```(S : Setoid b ℓ₂)``` that are otherwise unused in their definitions. I tried to remove both arguments and the code works out just fine. Are they supposed to do something or just a mistake?

**Comment by MatthewDaggitt** [comment]
Yes, that's a bug. Nice spot! A PR fixing it would be most welcome!
