### ISSUE TITLE
Why does `Data.Container.FreeMonad` use --sized-types? 

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-stdlib#1466]
It does not seem to be used internally to the code. This infects `Data.Container` too.

**Comment by gallais** [comment]
`Data.Container` imports `Codata.M` to provide the greatest fixpoint
of a container:

```agda
ν : ∀ {s p} → Container s p → Set (s ⊔ p)
ν C = M C ∞
```

**Comment by JacquesCarette** [comment]
Ah, right, an even though FreeMonad is 'under', it imports that. I didn't immediately spot that 'inversion'.

Still, maybe we can consider splitting the fixpoint stuff out, to make `Data.Container` safe when `--sized-types` gets to be no longer considered safe?
