### ISSUE TITLE
Split `Relation.Binary.Lattice` out into standard hierarchy

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#1469]
In the same way that `Relation.Binary` is split into `Definitions/Structures/Bundles` so should `Relation.Binary.Lattice` be split into `Lattice.(Definitions/Structures/Bundles)`. This would allow some simplification by having the equality and order relations as module parameters to `Lattice.Definitions` and `Lattice.Structures`.

See also https://github.com/agda/agda-stdlib/pull/1108 which attempts to do the same thing for algebraic latttices

**Comment by Akshobhya1234** [comment]
@MatthewDaggitt  This means we need to pull from current `Relation.Binary.Lattice.agda` and create `Lattice.(Definitions/Structures/Bundles)` accordingly right? Nothing much I suppose.

**Comment by MatthewDaggitt** [comment]
Yes,  `Relation.Binary.Lattice.(Definitions/Structures/Bundles)`. A PR would be most welcome :smile:
