### ISSUE TITLE
Switch to using new fast well-founded definition in `Data.Nat.GCD`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#1476]
Should speed up normalised rationals.

**Comment by bobatkey** [comment]
Here's an example showing how slow normalised rationals get currently:
```agda
module q-sqrt where

open import Data.Nat using (ℕ; zero; suc)
open import Data.Rational.Unnormalised renaming (ℚᵘ to ℚ; 1ℚᵘ to 1ℚ)
-- open import Data.Rational

next : ℚ → ℚ → ℚ
next n x = ½ * (x + n * 1/ x)

approx-sqrt : ℕ → ℚ → ℚ
approx-sqrt zero    n = (1ℚ + n) * ½
approx-sqrt (suc k) n = next n (approx-sqrt k n)

approx-sqrt2 : ℕ → ℚ
approx-sqrt2 n = approx-sqrt n (1ℚ + 1ℚ)

_ : ℚ
_ = {!approx-sqrt2 3!}
```
(Ignoring the unsolved proof that `x != 0`)

Normalising the term in the hole works almost instantly for low numbers of iterations, and can handle 20 after a small pause. If you switch to using `Data.Rational` though, trying to normalise `approx-sqrt2 n` for `n = 2` takes a second or so and any `n > 2` doesn't seem to terminate in a reasonable time.

**Comment by MatthewDaggitt** [comment]
Yup, _massive_ increase in performance, see #1478 for details.
