### ISSUE TITLE
A dubious property of < that should be factored into two useful properties

### ISSUE THREAD

**Issue by andreasabel** [agda/agda-stdlib#1484]
Stumbled over property `m<n⇒m≤1+n : ∀ {m n} → m < n → m ≤ suc n` https://github.com/agda/agda-stdlib/blob/d2b0e9a435437f52e3bbacfbabe7d5ca34a118b1/src/Data/Nat/Properties.agda#L420-L422
when I was looking for (1)
```
m≤n⇒m≤1+n : ∀ {m n} → m ≤ n → m ≤ suc n
```
From also (2)
```
m < n → m ≤ n
```
the original property should be a simple composition of (1) after (2), no?

**Comment by gallais** [comment]
We have:

1. ≤-step : ∀ {m n} → m ≤ n → m ≤ 1 + n
2. <⇒≤ : _<_ ⇒ _≤_

We have quite a few of these simple corollaries in the stdlib because in big developments
it is a pain to constantly keep combining the same base lemmas to rederive these.

**Comment by andreasabel** [comment]
Thanks, @gallais!

I'd argue that if the property is kept, it should be proved by composition rather than this not-so-beautiful pattern matching (matches to depth 2, makes a recursive call by putting one constructor back).  [N.B.: The awkward proof already indicates a lack of _orthogonality_ of this property.]
