### ISSUE TITLE
Should `_$!_` be moved out of `Function.Base` ?

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-stdlib#1486]
Perhaps into `Function.Strict`, which could also be imported from `Function`. It's the only function that uses `Strict`, and it is rather rarely used, so this would help simplify the dependency graph.

**Comment by gallais** [comment]
Can we use this opportunity to add `_!|>_`?

**Comment by MatthewDaggitt** [comment]
> It's the only function that uses Strict, and it is rather rarely used, so this would help simplify the dependency graph.

`Strict` doesn't have many import dependencies, so this would only remove one module from the dependency graph right? Just checking I haven't misunderstood?

To be honest, I would like to consolidate everything and move the entire contents of `Strict` to `Function.Strict` **and** move all the strict combinators currently in `Function.Base` to `Function.Strict`.

This isn't a backwards compatible change though so I might be tempted to wait until version 2.0?

**Comment by JacquesCarette** [comment]
It's a minor thing, yes. I was going to try to be a bit more systematic about exploring the lower parts of the dependency graph, but I only had time to get started.

We could actually move `_$!_` to `Function.Strict` now, as that would be a compatible change if that's its eventual home anyways. It could be done in a non-breaking (but non-improving too) way, or as a slight break.

**Comment by MatthewDaggitt** [comment]
Yup, sounds good. A PR doing the following would be welcome:
 - Deprecate `Strict` and move contents to `Function.Strict`
 - Move `_$!_` from `Function.Base` to `Function.Strict`
 - Add `_!|>_` in `Function.Strict` as a special favour for @gallais 
 - Re-export `_$!_` from `Function.Strict` publicly in `Function.Base` to maintain backwards compatibility.

In v2.0 we can then cut the dependency between `Function.Base` and `Function.Strict` by removing the public export of `_$!_`.

**Comment by MatthewDaggitt** [comment]
To-do in v2.0
 - reverse the dependency between `Function.Strict` and `Function.Base` 
 - can then use `flip` more extensively in `Function.Strict`
