### ISSUE TITLE
Splitting `Agda.Builtin.Nat`

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-stdlib#1490]
Into `.Core` for just the type. `.Operations` for the operations, and `.Helpers` for `div-helper` and `mod-helper`.  Whether to split the relations out from `.Operations` into `.Properties` too, I'm not sure is worth it.

Quite a few things need just rather small parts of this file. The builtins should really be tiny and imported gingerly.

**Comment by MatthewDaggitt** [comment]
I'm a bit confused about this proposal. The standard library doesn't have control over `Agda.Builtin.Nat`. Did you mean to open this in the main Agda repository?

**Comment by JacquesCarette** [comment]
Probably, yeah. I was just reading things from the HTML version of the pages, so they all looked like they belonged together.
