### ISSUE TITLE
Names `f` and `g` in `Function.Bundles`

### ISSUE THREAD

**Issue by andreasabel** [agda/agda-stdlib#1493]
I came across `Function.Bundles` which is supposed to eventually replace `Function.Injection` etc.
I was surprised to see single-letter field names like `f` and `g` there, e.g.:
https://github.com/agda/agda-stdlib/blob/8bbaf40d1cc5454b28841cc5d2d808b5c65b817d/src/Function/Bundles.agda#L67-L71

I think that a record field should not have a single letter latin name.  Also, the naming scheme of the to-be-deprecated organization seems more systematic, using `to`, `from`, and `<$>`, see e.g.:
https://github.com/agda/agda-stdlib/blob/8bbaf40d1cc5454b28841cc5d2d808b5c65b817d/src/Function/Injection.agda#L36-L41
https://github.com/agda/agda-stdlib/blob/8bbaf40d1cc5454b28841cc5d2d808b5c65b817d/src/Function/Equality.agda#L25-L34

Maybe there was a reason for replacing the old names?  
Otherwise, shouldn't we go back to the previous naming scheme?

Maybe the infix field `_<$>_` was awkward sometimes, but it expressed that this field allows the _application_ of the given, e.g., injection.  With post-fix projections, such a field could be named `apply` and then we can write:
```agda
   ... (f : \Pi A B) (a : A .Carrier) ...
   ... f .apply a ...
   ... (g : Injection A B) ...
   ... g .to .apply a ...
```

**Comment by MatthewDaggitt** [comment]
I'm more than happy to rename `f`, `g` etc. to `to` and `from` etc., I have to confess we were more focused on how the records composed than the name of the fields. It will have to wait until 2.0 though as it's a seriously backwards incompatible change and there's currently no way of gracefully deprecating field names.

**Comment by andreasabel** [comment]
Btw, a pattern to keep the definition look nice (with names like `f` and `g` in the laws) could be this, with `private` aliases:
```agda
  record Inverse : Set (a ⊔ b ⊔ ℓ₁ ⊔ ℓ₂) where
    field
      to        : A → B
      from      : B → A
    private 
      f         = to 
      f⁻¹       = from
    field
      cong₁     : f Preserves _≈₁_ ⟶ _≈₂_
      cong₂     : f⁻¹ Preserves _≈₂_ ⟶ _≈₁_
      inverse   : Inverseᵇ f f⁻¹
```
