### ISSUE TITLE
fast divMod

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#150]
There is a problem of slow `divMod`.  
This function is highly usable. Most of Nat arithmetic is built in no. So, why do not make `divMod` fast by using built-in? 
A similar problem may concern `_≤?_` and `compare` for Nat and for Bin
(I am not sure that I recall correct).
Fast Bin is important. I cannot tell now how it is done, but  for any occasion: `compare`  and `_≤?_` for Bin must not evaluate via conversion to Nat.

**Comment by asr** [comment]
I couldn't find the `compare'` function. @mechvel, please fix issue's description and reopen it.

**Comment by mechvel** [comment]
I meant ``compare``.

**Comment by mechvel** [comment]
Concerning the last point about comparison for Bin:
I look now into  Bin.agda for  ``_<_``,  and into Bin.Properties for ``<-cmp, (compare)``.
The definition of  ``_<_`` uses conversion to Nat.
``<-cmp`` uses in the proof part certain witnesses for conversion to Nat.
It is implemented so that if a client function uses only the results ``tri< p,  tri≈ p,  tri> p``,  
without analizing the p value, then this comparison does not perform convertion to Nat, and it is fast at run-time.
Let people correct me if I mistake.
But analyzing the structure of the witness  p  will cost exponentially in the number of bits.

Probably, it has sense to define  ``_<_`` on Bin as the lexicographic order on bit lists.
And then to prove separately that  ``_<_`` on Bin is logically equivalent to ``_<_`` for the corresponding Nat values.
This will allow short and fast explicit witnesses for comparison on Bin.

**Comment by MatthewDaggitt** [comment]
> This function is highly usable. Most of Nat arithmetic is built in no. So, why do not make divMod fast by using built-in?

Someone please jump in if I have the wrong end of the stick, but as far as I understand it the problem with making the entire `_divMod_` function a built-in is that putting large functions into native Haskell, means that you have a singular monolithic function providing the reference implementation in Agda which is then very difficult to prove the properties about.

Currently some of the work for `_divMod_` **is** done natively in Haskell (namely the helper functions `div-helper` and `mod-helper`) and looking at the code, the `DivMod.property` proof is erased use `TrustMe.erase`, so the function shouldn't be too bad. What are you trying to do such that this is causing you performance problems?

> compare and _≤?_ for Bin must not evaluate via conversion to Nat. 

> Probably, it has sense to define _<_ on Bin as the lexicographic order on bit lists.
And then to prove separately that _<_ on Bin is logically equivalent to _<_ for the corresponding Nat values.

As discussed, I agree with this completely.

**Comment by UlfNorell** [comment]
I believe (but haven't checked the code) that the performance problem is caused by the use of well-founded induction. I'm jumping through some hoops in [agda-prelude](https://github.com/UlfNorell/agda-prelude/blob/master/src/Control/WellFounded.agda) to get fast well-ordering on natural numbers.

Compare for Nat is easy to get fast using the built-in boolean `_<_` from `Agda.Builtin.Nat`.

**Comment by mechvel** [comment]
> Looking at the code, currently some of the work for _divMod_ is done natively in Haskell (namely the 
> helper functions div-helper and mod-helper) and the DivMod.property proof is erased use 
> TrustMe.erase, so the function shouldn't be too bad. What are you trying to do such that this is
> causing you performance problems?

We wrote in June 2017:

 Ulf Norell , Mon Jun 19,     * Next message (by thread): [Agda] is divMod slow?
    
The divMod implementation of the standard library is indeed horribly slow.
If you need fast certified divMod (and gcd) you can check out the
implementation in the agda-prelude library [1].
/ Ulf
[1] https://github.com/UlfNorell/agda-prelude/tree/master/src/Numeric/Nat

**Comment by mechvel** [comment]
Anyway there are highly desirable for Standard library fast divMod and fast `compare' for Nat.

**Comment by mechvel** [comment]
A month ago I was in a hurry. I needed fast divMod for the aim of  testing the performance of gcd and certain rational arithmetic.
Now I look into the divMod problem. I think the matter is in that divMod needs to also return 
```
r<divisor :  r  <  divisor
```
If a client function starts analizing the data ``r<divisor`` for a real computation, then it can drown in billions of  the ``s<=s``  constructors. Agda Preude has ``_<'_`` instead, wich returns Bool. But my program relies on Standard library . So, I applied a certain  convertor ``<'-to-<``. This helped rational arithmetic  -- so far, for a particular example.
But, I expect, this is only so long as nobody looks into  the data of ``r<divisor`` for real computation
(this depends on the programming style for each particular application).
I am not sure, these are my guesses. 
Anyway, probably, it has sense to replace the divMod implementation with this trick with Boolean <' and conversion to < of Standard.

Also I think that it needs to be prepared for future a real  Nat arithmetic, with representation of a list of macrodigits.  
First, it is desirable to make Bin work in full -- to test the pproach. Comparizon for _<_ there needs to be the lexicographic comparison of digit lists. But many proofs are easy to arrange by using conversion to Nat. For example, there are needed  gcd  and rational arithmetic for Bin (to see of how does the approach work), termination proofs, how do inductive proofs work, how do it work proofs by conversion to Nat, what is the whole effect. 

After this  one can consider MacroNat, represented as  a list of Macrodigits.
The algorithms are similar to the ones of Bin, only +, *, divMod on small numbers (Int of Haskell,
a single-digit MacroNat) need to be built-in, several base properties for them to be postulated. For, example, comparison < on Int returns Bool, and comparison on MacroNat is programmed in Agda,
and it returns a proof, that follows lexicographic list comparison, and reduces the comparison to many built-in comparisons in Int).  The whole arithmetic impemented in Agda, similar as for Bin, with reduction down to built-in things for Int. 
MacroNat  to be called  Natural (ℕ), and the current ℕ to be renamed to UnaryNat.
UnaryNat  can be intensively used in proofs, but the most usable  Natural arithmetic needs to be of macrodigits, programmed in Agda in Standard  library, with full proofs. 

I could try this myself (a messy project), but I doubt greatly of whether it will ever come an appropriate day for this.
There is no new science in this project. But it is needed technically. Some bright person needs to do this, not for scientific papers, but somehow for industry. 
 
I wonder, what is the Coq approach to Natural arithmetic?

**Comment by MatthewDaggitt** [comment]
@mechvel has reported that this issue is solved by the new `_%_` and `_div_` operators that return `ℕ` instead of `Fin n`.
