### ISSUE TITLE
GenerateEverything: use of `last` falsely compiled by GHC >= 8.2

### ISSUE THREAD

**Issue by andreasabel** [agda/agda-stdlib#1510]
With a module not following the convention for the header, in particular using a block comment in the beginning, `GenerateEverything` crashes ungracefully:
```
cabal run GenerateEverything
Up to date
GenerateEverything: Prelude.last: empty list
```

For a start, purge all unsafe uses of `Prelude.last`, or better even _all_ uses of `last`, employing non-empty lists...

**Comment by gallais** [comment]
Last time I looked at this I was utterly puzzled: there is exactly one use
of `last` on a manifestly non-empty list.

**Comment by andreasabel** [comment]
Indeed, weird.  (Compiler bug?)

The MWE seems to be a module consisting just of
```agda
{-# OPTIONS --safe --without-K #-}
```

**Comment by andreasabel** [comment]
I managed to scare away the ghost by using the sacred `Data.List.NonEmpty` incantations.

**Comment by andreasabel** [comment]
> Indeed, weird. (Compiler bug?)

Yes: https://gitlab.haskell.org/ghc/ghc/-/issues/19917
