### ISSUE TITLE
Missing GHC 8.10.5 from `.github/workflows/haskell-ci.yml`

### ISSUE THREAD

**Issue by asr** [agda/agda-stdlib#1523]
I couldn't use GHC 8.10.5 in `.github/workflows/haskell-ci.yml` because it is not supported in GitHub actions when using the `*.yml` file generated by `haskell-ci`.

**Comment by MatthewDaggitt** [comment]
Hi @asr I'm unsure how this can be fixed on our end? As found in https://github.com/agda/agda-stdlib/pull/1685, Github CI doesn't seem to support GHC 8.10.5. 

I'm closing this now. But feel free to reopen if you have a concrete suggestion of how we can include support :+1:
