### ISSUE TITLE
Names for propositional proofs in `Function.Construct.(Identity/Symmetry/Composition)` are backwards

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#1527]
Should be `⤖-sym` rather than `sym-⤖` to be consistent with the rest of the library. The old names should be deprecated.

**Comment by Akshobhya1234** [comment]
F.C.Identity
 ` ↣-id : A ↣ A `
 `↣-id = injection (setoid A)`
F.C.Symmetry
 `⇔-sym : A ⇔ B → B ⇔ A`
`⇔-sym = equivalence`
F.C.Composition 
`↠_-_∘ : A ↠ B → B ↠ C → A ↠ C`
`↠_-_∘ = surjection`

@MatthewDaggitt  Is this the right way to do it?

**Comment by MatthewDaggitt** [comment]
Yes, except composition, which I think should be `_↠-∘_` rather than `↠_-_∘`
