### ISSUE TITLE
Incorrect definition of `Prime` in `Algebra.Definitions.RawSemiring`

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1543]
Algebra.Definitions.RawSemiring defines
```
record Prime (p : A) : Set (a ⊔ ℓ) where                                          
  constructor mkPrime                                                             
  field                                                                           
    p≉0     : p ≉ 0#                                                              
    split-∣ : ∀ {x y} → p ∣ x * y → p ∣ x ⊎ p ∣ y 
```
It is needed to insert the field   ``p∤1 :  p ∤ 1#``.
It has somehow escaped from the code.   
It means that a prime element must not be invertible.
In particular, it follows from the current definition that 1 is prime in Integer, which is very wrong.

And I have a certain question.
My project of inserting the GCD-related items for CancellativeCommutativeSemiring is stopped.
But the following ruin items remain in lib-1.7, which I would like to use as standard and which, I think, are widely usable.
1) The bundle CancellativeCommutativeSemiring.
2) The modules in ``Algebra/Definitions/``  define  ``_∣_ _∤_``  and several definitions concerning divisibility,
    the notions ``Irreducible, Prime, Coprime``.
3) Some of the modules in the sub-folders of ``Algebra/Properties/`` (like in Semiring/) implement  several simple lemmas
    about the above items.

Will they remain?

**Comment by MatthewDaggitt** [comment]
Thanks, yes, that should definitely be fixed. 

> Will they remain?

Yes. Except in very rare circumstances we do not remove code that has made it into the standard library.
