### ISSUE TITLE
Predicate equivalence?

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-stdlib#1547]
Is there any reason (other than no one has done it yet) that
```agda
 _≐_ : Pred 𝒜 ρ → Pred 𝒜 ρ → Type (α ⊔ ρ)
 P ≐ Q = (P ⊆ Q) × (Q ⊆ P)
```
isn't in `Relation.Unary` ? The fact that it's an equivalence relation should probably go in a to-be-created `Relation.Unary.Bundles` ?

**Comment by MatthewDaggitt** [comment]
I don't think there's any particular reason, no. 

Where the proofs about it should live is a more tricky question... `Bundles` is the wrong place as that name is reserved for record declarations that wrap up multiple proofs, e.g. we might later on have `DecidablePredicate` or `FinitePredicate` there.

I believe the canonical place for these proofs would be `Relation.Unary.Relation.Binary.Equality`. Feel free to scream :scream: 
We could of course mitigate this by having it's contents re-exported by `Relation.Unary` in v2.0?
