### ISSUE TITLE
``git clone ... make test`` does not work

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1549]
I clone and type-check the master branch following HACKING.md of lib-1.7,
and after ``make test`` it reports 
```
cabal run GenerateEverything
Up to date
cabal exec -- fix-whitespace --check
agda +RTS -M4.0G -H3.5G -A128M -RTS -i. -isrc README.agda
Checking README (/home/mechvel/agda/stLib/agda-stdlib-fork/README.agda).
 Checking README.Data (/home/mechvel/agda/stLib/agda-stdlib-fork/README/Data.agda).
  Checking README.Data.List (/home/mechvel/agda/stLib/agda-stdlib-fork/README/Data/List.agda).
   Checking README.Data.List.Relation.Binary.Equality (/home/mechvel/agda/stLib/agda-stdlib-fork/README/Data/List/Relation/Binary/Equality.agda).
/home/mechvel/agda/stLib/agda-stdlib-fork/README/Data/List/Relation/Binary/Equality.agda:7,1-47
You may only turn off benign warnings. The warning
MissingDefinitions is a non-fatal error and thus cannot be ignored.
See --help=warning.
when scope checking the declaration  import README.Data.List.Relation.Binary.Equality
```
I tried ``make test -W noerror``, but the effect is the same.
Please, how to fix?
(Agda 2.6.2, ghc-8.8.3, Ubuntu Linux 18.04).

**Comment by MatthewDaggitt** [comment]
@mechvel your version of the standard library is not up-to-date. The `MissingDefinitions` flag was removed from that file in this commit adb18526422277b7c9ec4cba5488232d81fba5ca in February so you're using a version that is at least 6 months old.

You need to run `git pull` to bring your local repo up-to-date.

**Comment by mechvel** [comment]
> You need to run git pull to bring your local repo up-to-date.

``git pull`` reports "already updated" (I translate from Russian). And it continues to talk about MissingDefinitions etc.

Probably I have forgotten to wipe out my last fork from agda-stdlib.
Now I wipe it out, then click Fork, and now ``make test`` succeeds.  
I do not know of why this helps, but it does. 
Thanks.

**Comment by gallais** [comment]
It could be that you were on a different branch (`git status` will report
`On branch [...]`) and that it was indeed up to date.
