### ISSUE TITLE
Fixing `Any-cong` dependencies on propositional membership

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#155]
A question for @nad. 

I'm trying to move the proofs about membership functions `find`, `lost` and `map-with-∈` out of `Data.List.Any.Properties` and into `Data.List.Any.Membership.Properties`. However at the moment two proofs `swap` and `Any-cong` in `Data.List.Any.Properties`, that depend on the bijection between propositional membership and `Any` instances, are preventing me from doing so.

I've managed to rewrite `swap` myself to avoid any use of `_∈_` in commit e827344c210521b2886d64b767f79646b73a0e86 but I'm struggling to do the same for `Any-cong` without proving it for every single type of relation. Do you have any ideas about how to go about doing this concisely?

**Comment by nad** [comment]
The old proofs work also in this setting. It doesn't matter that you use membership defined using propositional equality internally in the proofs, because the type signatures do not mention membership. I suggest that you revert commit e827344c210521b2886d64b767f79646b73a0e86.

**Comment by MatthewDaggitt** [comment]
Hmm, maybe I'm misunderstanding something or haven't manage to phrase the question properly.

1) I agree the proofs `Any-cong` and `swap` are in the right place in `Any.Properties`.
2) They currently depend on the proofs `∃∈-Any` and `Any↔` in `Any.Properties`. However these are in the wrong place and should be in `Any.Membership.Propositional.Properties` instead.
3) The `Any.Membership.Propositional.Properties` should depend on `Any.Properties` not the other way round.

I don't have a problem per-se with the fact that they use propositional membership internally, it's the cyclic dependency that it causes when everything is in the right place that is the issue.

**Comment by nad** [comment]
Cycles of this kind are easy to break, that's what the "Core" modules have been used for.

**Comment by MatthewDaggitt** [comment]
So you're suggesting the following dependency relationship `Any.Membership.Propositional.Properties` => `Any.Properties` => `Any.Membership.Propositional.Properties.Core`?

Seems more than a little convoluted in my opinion, not to mention as far as I'm aware its the first time that we would introduce a `Properties.Core` file. Okay I'll have a further think and explore the various possibilities.

**Comment by MatthewDaggitt** [comment]
Finally managed to squish the dependency. This has allowed me to start on the the 2nd part of the re-organisation of list membership that was started in v0.14.

The first changes in the new branch 'membership' should finally allow easy and logical access to four types of membership:
 - Setoid-based membership
 - Decidable setoid-based membership
 - Propositional membership
 - Decidable propositional membership

It's still a work in progress and probably won't be available in v0.15.

**Comment by MatthewDaggitt** [comment]
Closed with d9400f1
