### ISSUE TITLE
lib-1.7:  typo in  Algebra.Properties.CommutativeSemigroup

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1553]
The comment 
```
-------------------------------------------------------------------------------   
-- Partitions (2,2).                                                              
-- These proofs are by composing with the proofs for (2,1).                       
-------------------------------------------------------------------------------
```
in `Algebra.Properties.CommutativeSemigroup` needs to be removed. 
It was for the equalities for the permutations on 4 factors, but these equality proofs have been removed,
by the  team decision. 
(only this comment to be removed).

**Comment by Taneb** [comment]
This comment seems to reflect what's currently in the file. For example, `xy∙z≈yx∙z` is defined in terms of `xy∙z≈y∙xz` which is implemented under the Partitions (2, 1) header. Is there something I'm missing?

**Comment by mechvel** [comment]
I am sorry. I have forgotten the principle.
"Partitions (k,l)" means that on the left of equality k factors form the first group of arguments,
and on the right hand l factors  form the first group of arguments.
So this commentary has to remain,
and the item to be closed.
Thanks.
