### ISSUE TITLE
Question on sub-structures

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1555]
Has Standard library something for sub-structures?
In my program I define the constructor of  `subSetoid` which takes a `setoid` and any congruent membership predicate
`Member` on its carrier and returns the setoid structure for the subset of Carrier defined by `Member`.
Then, subMonoid is defined in a similar way, for certain extra conditions on `Member`. And so on.

Standard library is large, it is difficult to observe it contents. If it has the constructs for the sub-structures, then, 
can you, please, inform me?

**Comment by MatthewDaggitt** [comment]
They don't exist, see https://github.com/agda/agda-stdlib/issues/1404 for where @conal and I had a discussion about how best to implement them. Conal originally proposed decidable subsets but I suggested how it could be generalised to arbitrary subsets. Please continue the discussion in that issue.
