### ISSUE TITLE
Unify definitions of divisibility 

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1572]
lib-1.7 has a general divisibility notion  `_∣_`  for Magma.
But Data.Nat.Divisibility gives  a certain special definition for `_∣_` .
Probably `_|_` for Nat, Integer, Nat.Binary ... needs to be imported as the instance of the generic definition. 
?

**Comment by MatthewDaggitt** [comment]
Yes, we will try and fix this in version 2.0.

**Comment by MatthewDaggitt** [comment]
Duplicate of #679 so closing.
