### ISSUE TITLE
Remove remaining `map-with-∈` names in favour of the new `mapWith∈`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#1575]
While going through https://github.com/agda/agda-stdlib/pull/1569 I noticed that some of the proofs for `mapWith∈` are still using the old name `map-with-∈`

https://github.com/agda/agda-stdlib/blob/faa5a3cb7fde2f14cdfbd3b75ab8d08bbdc5e047/src/Data/List/Relation/Unary/Any/Properties.agda#L587

To be honest I think `mapWith∈` is a pretty hideous name anyway, even if it no longer uses hyphens. I propose to rename it to `mapMembers` in v2.0. Any thoughts or objections?

**Comment by omelkonian** [comment]
I have personally come to love this ugly bugger, so I propose we keep it as is (but remove `map-with-∈` ofc).

**Comment by MatthewDaggitt** [comment]
Okay, sounds good. I'll change the issue title to simply remove the old names.
