### ISSUE TITLE
Proposal with  NonZero, ButOne

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1577]
Currently I use this general definition under `Semiring`:
```
NonZero =  Σ Carrier (_≉ 0#)
```
And now I propose instead:  
```
data ButOne (b : Carrier) :  Set (α ⊔ α≈)         -- for (Raw)Setoid
    where
    butOne : {x : Carrier} → x ≉ b → ButOne b

NonZero : Set _                      -- for (Roaw)Semiring
NonZero = ButOne 0#
```
Example of usage:
```
f : NonZero → Carrier 
f (butOne {x} x≉0) =  x + x
```
It is also possible to first define ButOne and NonZero may be in Algebra.Definitions, for the Raw structures, etc. 

?

**Comment by MatthewDaggitt** [comment]
This is a discussion about how to extend https://github.com/agda/agda-stdlib/issues/1175. Please post this comment in there.
