### ISSUE TITLE
Update `HACKING.md` regarding step 7: `make clean` and `make test`

### ISSUE THREAD

**Issue by barrettj12** [agda/agda-stdlib#1586]
Step 7 of [`HACKING.md`](https://github.com/agda/agda-stdlib/blob/master/HACKING.md) currently reads:

> Ensure your changes are compatible with the rest of the library by running the commands
> ```
> make clean
> make test
> ```
> inside the `agda-stdlib-fork` folder. Continue to correct any bugs thrown up until the tests are passed.
> ...

As written, these steps cannot be executed on Windows, as the `make` tool is not installed by default. While it can be installed (e.g. [here](https://stackoverflow.com/a/32127632/15219560)), the tests still do not appear to work. When I installed `make` using Chocolatey and tried to run `make clean` on my Windows 10 Home 64-bit machine, I got the error message
```
find . -type f -name '*.agdai' -delete
File not found - *.agdai
make: *** [GNUmakefile:34: clean] Error 2
```

@jespercockx has suggested that someone should find out how these tests can be run on Windows, and add that information to the `HACKING.md` file. Alternatively, @MatthewDaggitt has suggested that the local testing steps can probably be removed from `HACKING.md`, due to the CI infrastructure that this project now has.

**Comment by MatthewDaggitt** [comment]
Closed with bc324e6c8
