### ISSUE TITLE
A `Codata` library based on `--guardedness`

### ISSUE THREAD

**Issue by XiaohuWang0921** [agda/agda-stdlib#1588]
Hi, I have been playing around with different ways of implementing coinductive types lately and have encountered some problems with sized types which had me convinced that coinductive records should be preferred to sized types, and therefore the library should support it. Here are the problems I encountered:

1. For some odd reason Agda (I am using 2.6.2) currently does not support `--sized-types` with `--safe` turned on, which means any code using coinduction with sized types cannot use `--safe`.

2. I have come up with a very simple implementation for the Cantor pairing function for streams as coinductive records:
```agda
{-# OPTIONS --safe --guardedness #-}

open import Level using (Level)

private
  variable
    a b c : Level
    A : Set a
    B : Set b
    C : Set c

record Stream (A : Set a) : Set a where
  coinductive
  constructor _∷_
  field
    head : A
    tail : Stream A
open Stream

zipWith : (A → B → C) → Stream A → Stream B → Stream C
zipWith f s t .head = f (s .head) (t .head)
zipWith f s t .tail = zipWith f (s .tail) (t .tail)

cantor : Stream (Stream A) → Stream A
cantor s .head = s .head .head
cantor s .tail = cantor (zipWith _∷_ (s .head .tail) (s .tail))
```
which is way simpler than `Codata.Stream.cantor` which involves two auxiliary functions. And this definition cannot be adapted to sized types, unless one defines an additional type for two-dimensional streams in the following way
```agda
private
  variable
    a : Level
    A : Set a
    i : Size

data Stream2 (A : Set a) (i : Size) : Set a where
  _∷_ : Stream A i → Thunk (Stream2 A) i → Stream2 A i

zipWith∷ : Stream A i → Stream2 A i → Stream2 A i
zipWith∷ (x ∷ xs) (l ∷ ls) =
  (x ∷ λ where .force → l) ∷ λ where .force → zipWith∷ (xs .force) (ls .force)

cantor : Stream2 A i → Stream A i
cantor ((x ∷ xs) ∷ ls) =
  x ∷ λ where .force → cantor (zipWith∷ (xs .force) (ls .force))
```
which is obviously less elegant. And there might be other useful functions that can be easily implemented with coinductive records but not with sized types.

One obvious problem for coinductive records though is that it currently does not support multiple constructors. The solution I came up with is to use sum types or `Data.Maybe.Maybe`. For example one could define `Colist`s like this:
```agda
record Colist {a} (A : Set a) : Set a where
  coinductive
  field
    force : Maybe (A × Colist A)
```

I am already starting to work on implementing common coinductive types using `--guardedness`, so if enough people are interested, I would hopefully create a pull request soon.

**Comment by gallais** [comment]
I have edited your message to add the required import & `OPTIONS` satements because without them:

1. the example does not check
2. the example is not accepted as being productive

> I have come up with a very simple implementation for the Cantor pairing function for streams as coinductive records:

But you can't, on the other hand, write something as simple as:
```agda
open import Data.Nat.Base

map : (A → B) → Stream A → Stream B
map f s .head = f (s .head)
map f s .tail = map f (s .tail)

natural : Stream ℕ
head natural = 0
tail natural = map suc natural
```
without getting a totality error. You then need to resort to [arcane tricks](http://www.cse.chalmers.se/~nad/publications/danielsson-productivity.html) to get this kind
of definition accepted.

I'm in favour of adding a codata library based on `--guardedness` but I wouldn't present it as panacea.

**Comment by XiaohuWang0921** [comment]
@gallais I am not sure what you are talking about. Here is the complete content of my file `Codata/Guardedness/Stream.agda` that typechecks without any error:
```agda
{-# OPTIONS --without-K --safe --guardedness #-}

module Codata.Guardedness.Stream where

open import Level using (Level)
open import Data.Nat.Base using (ℕ; zero; suc)
open import Function.Base using (_∘′_; _∘₂_; flip; id)
open import Data.List.Base using (List; []; _∷_)
open import Data.Product using (Σ; _,_; proj₁; proj₂; _×_; _,′_; map₁)
open import Data.Vec.Base using (Vec; []; _∷_)

private
  variable
    a b c : Level
    A : Set a
    B : Set b
    C : Set c

infixr 5 _∷_

record Stream (A : Set a) : Set a where
  coinductive
  constructor _∷_
  field
    head : A
    tail : Stream A

open Stream

lookup : ℕ → Stream A → A
lookup zero = head
lookup (suc n) = lookup n ∘′ tail

_[_] : Stream A → ℕ → A
_[_] = flip lookup

tabulate : (ℕ → A) → Stream A
tabulate f .head = f 0
tabulate f .tail = tabulate (f ∘′ suc)

infixr 5 _++_

_++_ : List A → Stream A → Stream A
[] ++ s = s
(x ∷ xs) ++ s = x ∷ xs ++ s

zipWith : (A → B → C) → Stream A → Stream B → Stream C
zipWith f s t .head = f (s .head) (t .head)
zipWith f s t .tail = zipWith f (s .tail) (t .tail)

map : (A → B) → Stream A → Stream B
map f s .head = f (s .head)
map f s .tail = map f (s .tail)

cantor : Stream (Stream A) → Stream A
cantor s .head = s .head .head
cantor s .tail = cantor (zipWith _∷_ (s .head .tail) (s .tail))

plane : {B : A → Set b} → Stream A → (∀ a → Stream (B a)) → Stream (Σ A B)
plane as bs = cantor (map (λ a → map (a ,_) (bs a)) as)

splitAt : ∀ n → Stream A → Vec A n × Stream A
splitAt zero s = [] ,′ s
splitAt (suc n) s = map₁ (s .head ∷_) (splitAt n (s .tail))

take : ∀ n → Stream A → Vec A n
take = proj₁ ∘₂ splitAt

drop : ℕ → Stream A → Stream A
drop = proj₂ ∘₂ splitAt
```
Perhaps you are using another version of Agda as me? As I stated I am using version 2.6.2, as the output of the command `agda --version` is "Agda version 2.6.2" for me.

Also, I do not understand why this definition should not be accepted, as all corecursive calls are the RHS of a copattern. I have also ported this definition to Coq, and it is also accepted with no error.

**Comment by gallais** [comment]
> Here is the complete content of my file Codata/Guardedness/Stream.agda that typechecks without any error:

I was talking about the not self-contained snippet you had posted in your original
message. You can use the drop down menu at the top of your original message to see
the edits that were made.

> Also, I do not understand why this definition should not be accepted,

I'm not saying it *should* not be accepted in an ideal world, I am saying it *is*
not with the current version of Agda. The reason why is explained in the paper I
have linked to but the gist of it is that you need to know that `map` only consumes
the head of its argument to compute the head of its output to know that it is safe
to define `natural .tail = map suc natural`. And that analysis is not performed by
the `--guardedness` mode (but is possible to express using sized types for instance).

**Comment by XiaohuWang0921** [comment]
@gallais I am still slightly confused by your comment. First of all, since I was talking about a coinductive library with `--guardedness` and since Agda now gives a warning for coinductive records without using `--guardedness`, I assumed it was clear that the code example I gave above required this flag, so I left it out since the purpose for the code snippet was just to present my definition for `cantor`. I apologise if that is what caused the misunderstanding.

> I'm not saying it _should_ not be accepted in an ideal world, I am saying it _is_
not with the current version of Agda. The reason why is explained in the paper I
have linked to but the gist of it is that you need to know that map only consumes
the head of its argument to compute the head of its output to know that it is safe
to define `natural .tail = map suc natural`.

But it is, with the `--guardedness` flag. In fact, I just checked and the current version of Agda does not accept _any_ corecursive function definition without `--guardedness`, not even the definitions of `map` and `natural` you gave above. So I don't see why my definition for `cantor` is any worse or different that of `map`. And yes, my definition for `cantor` also only consumes the head of its argument to compute the head of its output. Here is its definition again:
```agda
cantor : Stream (Stream A) → Stream A
cantor s .head = s .head .head
cantor s .tail = cantor (zipWith _∷_ (s .head .tail) (s .tail))
```
It also satisfies a quote from the abstract of the paper you linked to:
> Guarded corecursion is a form of recursion in which arbitrary recursive calls
are allowed, as long as they are guarded by a coinductive constructor.

Where the coinductive constructor here is not explicitly written out but implied by the copattern. So what is its problem?

> I'm in favour of adding a codata library based on `--guardedness` but I wouldn't present it as a panacea.

Well, neither would I. I just pointed out two advantages of using `--guardedness`, one being that `--sized-types` is no longer safe, the other being that it allows one to write certain functions such as `cantor` in a much simpler manner. I am not saying that it solves all problems.

**Comment by gallais** [comment]
Again: look at the diff. I copy/pasted the code you gave as an example in a buffer and
I got scope errors for `Level`, `.head`, `.tail`, and then a termination error because
`{-# OPTIONS --safe --guardedness #-}` were not set.

> I assumed it was clear that the code example I gave above required this flag

It is clear but it does not change the fact that it is annoying to deal with code snippets
that are not self contained & to be forced to figure out what `import`s, `open` and `OPTIONS`
statements are needed.

> So I don't see why my definition for cantor is any worse or different that of map.

I didn't compare the definition `cantor` to that of `map`, I replied to the implication
that `--guardedness` was superior to sized types because you could define `cantor` more
easily. My objection is that you cannot define something as simple as `natural` and that
both approaches have their respective advantages.

Also, it's not true `cantor` cannot be written this way using sized types:

```agda
{-# OPTIONS --sized-types #-}

open import Level using (Level)
open import Size using (Size)

open import Codata.Thunk
open import Codata.Stream as Stream using (Stream; _∷_)

private
  variable
    a : Level
    A : Set a
    i j : Size

zipWith∷ : Stream A i → Stream (Stream A j) i → Stream (Stream A j) i
zipWith∷ (x ∷ xs) (l ∷ ls) =
  (x ∷ λ where .force → l) ∷ λ where .force → zipWith∷ (xs .force) (ls .force)

cantor : Stream (Stream A i) i → Stream A i
cantor ((x ∷ xs) ∷ ls) =
  x ∷ λ where .force → cantor (zipWith∷ (xs .force) (ls .force))
```

**Comment by XiaohuWang0921** [comment]
> It is clear but it does not change the fact that it is annoying to deal with code snippets
that are not self contained & to be forced to figure out what `import`s, `open` and `OPTIONS`
statements are needed.

Again, I apologise, and promise I will not do it again.
> My objection is that you cannot define something as simple as natural and that
both approaches have their respective advantages.

I see now that I misunderstood your point earlier. Thank you for clarifying.
> Also, it's not true `cantor` cannot be written this way using sized types:

Well in this case I would argue that you still need to define a specialised version of `zipWith` for it to work, while with `--guardedness` you don't. Also it might be a good idea to change the definition of `Codata.Stream.cantor` in the standard library into this simpler version.

**Comment by gallais** [comment]
> Well in this case I would argue that you still need to define a specialised version of zipWith for it to work, while with --guardedness you don't. 

I was precisely thinking about this and just edited my answer to include a version reusing
the library's `zipWith`. The only reason I used `zipWith∷` originally is because I was
starting from your file and trying to find a type for it.

**Comment by MatthewDaggitt** [comment]
Hi @XiaohuWang0921 thanks for the suggestion. Don't worry about the code snippet too much, it's not a problem. I think in summary, yes we'd be interested in a modern "safe" codata library that used `--guardedness`. If you wanted to start putting together some PRs under `Codata.Guarded` then that would be very welcome!

**Comment by gallais** [comment]
This suggests to me that we should reorganise the whole `Codata.` hierarchy for 2.0.
We already have `Codata.Musical` for the old style, we could move the current developments
in `Codata.Sized` and then we can use `Codata.Guarded` for the new proposed library.

**Comment by MatthewDaggitt** [comment]
Makes sense to me!

**Comment by MatthewDaggitt** [comment]
Added in #1693 (though obviously room for expansion!)
