### ISSUE TITLE
Better names for `Fin` index manipulation functions in `Data.Fin.Base`

### ISSUE THREAD

**Issue by jamesmckinna** [agda/agda-stdlib#1589]
I'm not happy with the names 'raise' and 'inject+' for what are symmetric operations (but with broken argument order) on Fins
Can we agree on '+l' and '+r' for example, or some suitable alternative, but perhaps marking the defns so that the 'Fin' as opposed to 'Nat' args are easily identifiable. Eg.
```agda
_l⁺_ : ∀ {m} → Fin m → (n : ℕ) → Fin (m + n)
j l⁺ n = inject+ n j

_⁺r_ : ∀ {m} n → Fin m → Fin (n + m)
_⁺r_ = raise 
```

**Comment by MatthewDaggitt** [comment]
Hmm now that I look at the definitions, `inject+` and `raise` I'm not really sure I see the symmetry? Unlike `raise` the function `inject+` doesn't actually perform any addition, it just reconstructs the second argument. For example, ignoring the the types `3 l⁺ 7 = 7` but `3 ⁺r 7 = 10`.

I'm all for coming up with better/more consistent names for them though :+1:

**Comment by jamesmckinna** [comment]
Touch'e. Perhaps it is '+' that is the unfortunate symbol here, even if its use in 'inject+' is (arithmetically) sound wrt an underlying '+' on Nat. These 'shift' operations are, as it were, 'left-injection' and 'right-injection', and one of them needs to do addition on values, and the other only on the (Nat-index in the) type. 

FWIW, my objection is to their not being mnemonic/memorable enough, and as we've discussed in person, it's really their use in Data.Vec.Properties.lookup-++{l,r} which matters to me, in the context of regarding Data.Vec.lookup as a semantic function taking a Vec as 'environment', and Fin (as usual!) as a 'variable'
```agda
⟦_⟧_ : ∀ {ℓ A k} (j : Fin k) → (Ms : Vec {ℓ} A k) → A
⟦ j ⟧ Ms = lookup Ms j
```
So what I really want(ed) is to be able to write environment-manipulation functions based on Vec 'addition' (via '++'), and not - to have to - care about the underlying arithmetic (so long as 'it looks after itself') and have them behave in the 'obvious' way... and I was finding the names 'inject+', 'raise' to be a bad fit for this (distinguished? are there any other kinds of uses of lookup?) use case.

**Comment by gallais** [comment]
> I'm not really sure I see the symmetry?

The definition of [join](http://agda.github.io/agda-stdlib/Data.Fin.Base.html#4042) is maybe helpful in that respect:

```agda
join : ∀ m n → Fin m ⊎ Fin n → Fin (m ℕ.+ n)
join m n = [ inject+ n , raise {n} m ]′
```

I have similar functions to deal with variables in my generic-syntax library:

```agda
injectˡ : ∀ Δ → ∀[ Var σ ⇒ (_++ Δ) ⊢ Var σ ]
injectʳ : ∀ Δ → ∀[ Var σ ⇒ (Δ ++_) ⊢ Var σ ]
```

And you can define [a view](https://gallais.github.io/generic-syntax/Data.Environment.html#830) that takes any variable in `Γ ++ Δ`
and show it either lives in `Γ` or in `Δ` and is obtained by using
the appropriate raise / inject function.

**Comment by jamesmckinna** [comment]
Guillaume, 'inject^l', 'inject^r' seem as good names as any in this regard *on Fin itself*.
Would that a (good?) compromise suggestion instead?

**Comment by MatthewDaggitt** [comment]
I would be happy with `injectˡ` and `injectʳ`, as long as we had some nice explanatory comments on top of them explaining their behaviour and the reason for the names.

**Comment by jamesmckinna** [comment]
Hmmm, I've had time to sleep on this, and realise there's a flaw in my suggestion (not fixed by the adoption of @gallais's injectˡ and injectʳ) of simply deprecating the old names in favour of the new. I think the types should be more informative: that is the Nat argument should be on the left, resp. right of the Fin m argument, as I had it in my original statement of the issue. 
So: no deprecation reqd as such, but additional names, and with them, choices as to how/whether existing lemmas about inject+/raise be changed, or themselves also 'duplicated', to reflect these additional usages. Thoughts?

**Comment by MatthewDaggitt** [comment]
If I understand correctly, I think the best approach would be to add the new names with the better argument order, define the old ones in terms of them (reversing the argument order) and then deprecate the old ones.

**Comment by JacquesCarette** [comment]
I have some nagging doubts about this. Certainly the lack of symmetry in `join` argues for some kind of fix, i.e. that there ought to be some nice tuple of encoding functions better than (`inject+` , `raise`).

The main reason I have some doubts is that other functions (like `_+_` !) are themselves asymmetric in their definition, and that infects other things. This is not a good state of affairs, as `_+_` is *provably* symmetric, but not *definitionally* symmetric. So I'd want to see the actual ripple effect on a bunch of proofs of properties in the standard library before committing to this choice.

I could be entirely wrong - and that would actually be a good thing.

**Comment by jamesmckinna** [comment]
Jacques, agreed with your point re 'infection', hence my falling back to adding these new definitions before inviting comment on deprecating the old ones. FWIW, the severity of infection may be gauged from the following list below. AFAICT, the only substantive irritation would be in ```Data.Vec.Functional.agda```, where the definition
```agda
take : ∀ m {n} → Vector A (m ℕ.+ n) → Vector A m
take _ {n = n} xs = xs ∘ inject+ n
```
would no longer be available, in favour of the (marginally) uglier workaround ```agda take _ {n = n} xs = xs ∘ flip injectˡ n```

For ```raise/injectʳ``` and ```inject+/injectˡ```, the affected files are:
```agda
Data/Fin/Base.agda
Data/Fin/Properties.agda
Data/Vec/Functional.agda
Data/Vec/Properties.agda
Data/Vec/Functional/Properties.agda
Data/Vec/Functional/Relation/Binary/Pointwise/Properties.agda
Data/Vec/Functional/Relation/Unary/All/Properties.agda
```
The extent of the user base infection is harder to assess.

**Comment by jamesmckinna** [comment]
As for symmetry of the operations (or otherwise), and the companion problem of commutative addition having an asymmetric definition, I guess we either need to wait for type-checking modulo equations a la Frex, or else, as part of my proposal, accept that the asymmetry between the Fin/Nat arguments to these injections be reflected in the respective index argument positions in the resulting index sum, viz.: (with apologies; these are the infix versions of ```injectˡ``` resp. ```injectʳ``` and I think there's a separate, but related argument for saying that they *should* be infixes, rather than prefix operators)
```agda
_↑ˡ_ : ∀ {m} → Fin m → ∀ n → Fin (m + n)
j ↑ˡ n = inject+ n j

_↑ʳ_ : ∀ {m} n → Fin m → Fin (n + m)
_↑ʳ_ = raise
```

**Comment by MatthewDaggitt** [comment]
Hmm so as I understand it'd only be changing the argument order, and not the body of the definition. Therefore we won't run into the same sort of horrificness that would ensure if we changed `_+_` from left biased to right biased as @JacquesCarette mentions. I'm therefore reasonably sure that when people switched from the deprecated to the new definitions, they wouldn't have to do anything except swap the args.

As an aside, I like the infix names as well, possibly better than the `inject` ones!

**Comment by jamesmckinna** [comment]
Pull request issued. Hopefully this passes?!
