### ISSUE TITLE
Generilize `Congruent` ? 

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1590]
Consider 
```
_**_ :  List A → List A → A
```
for something like scalar product of two lists over a Semiring. 
I need to express  ``Congruent₂ _≋_ _**_``
for the pointwise equality `_≋_`.  
But the result type for  `_**_`   does no match.
So I wonder: has one to define the notion of  
``` 
Congruent₃ _~₁_ _~₂_ _~₃_ f
```
for  ``f : A → B → C`` ?
What is the Standard library relation to this?

**Comment by MatthewDaggitt** [comment]
See the 'Preserves' types in 'Relation.Binary.Definitions' re-exported by
'Relation.Binary'.

**Comment by mechvel** [comment]
I see. Thank you.
