### ISSUE TITLE
WellFounded for a Noetherian relation?

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1596]
This is a question.
Consider   ``dto : DecTotalOrder``  with its  ``_≤_, _<_ : Rel A _``,
which is Noetherian. That is there does not exist an infinite sequence in `A` which is descending with respect to `_<_`.
Let it be given even a proof for its constructive version:
```
noeth  :  (seq : ℕ → A) → ∃ (\ (i : ℕ) →  seq i ≤ seq (suc i))  
```
Let a function  f  be defined recursively and need to use  ``WellFounded _<_`` to prove the termination.
Is it possible to derive  ``WellFounded _<_``  from the `noeth` lemma?
Is there a function in Standard library for this?

**Comment by MatthewDaggitt** [comment]
The answers are "Unsure" and "No". As the standard library issue tracker isn't a great place for open-ended mathematical questions, and I've answered that it's not in the library I'm going to mark this issue as resolved. If do you come up with a proof of it then feel free to reopen this issue and/or add it to the library.

**Comment by gallais** [comment]
There are a few results on nLab: https://ncatlab.org/nlab/show/well-founded+relation

In particular:

>  In constructive mathematics, we may prove that a well-founded relation has no infinite descent (see Proposition 2.3), but not the converse

However the way they formulate "no infinite descent" is a bit less powerful than the
statement you picked. These things are pretty subtle so even though I do not see an
obvious proof, I'd hold off from making a definitive statement.

**Comment by mechvel** [comment]
On 2021-10-05 16:36, G. Allais wrote:
> There are a few results on nLab:
> https://ncatlab.org/nlab/show/well-founded+relation
> 
> In particular:
> 
>> In constructive mathematics, we may prove that a well-founded
>> relation has no infinite descent (see Proposition 2.3), but not the 
>> converse.


Thank you.
It would be interesting to see a counter-example for this converse.
I do not see such there.


> However the way they formulate "no infinite descent" is a bit less
> powerful than the statement you picked.

Yes, I choese a bit more constructive definition: an algorithm that for 
any
sequence returns the member No at which _>_ is broken.

I also agree to require
(a) _<_ to be DecTotalOrder,
(b) Carrier to be countable, and having an algorithmic bijection  
Carrier <--> ℕ.

So that one can count Carrier and put each first n elements into a 
linear order by _<_.

Usually I prove WellFounded by defining such a bijection Carrier <--> ℕ
which preserves the ordering.
And in this my case I do not see how to arrange this even basing on
Noetherian, DecTotalOrder, and (b).
To make  e  accessible by _<_, I count Carrier and insert each new 
element to the
current list according to _<_. This puts elements in "one line" 
according to _<_,
making the current linear order segment, but it may have gaps inside it.
Continuing this makes each gap filled at some step. Due to Noetherian, 
this process
produces only finitely many members smaller than  e  in _<_.
But I do not see how to solve whether the current list contains the full 
set of elements smaller than  e  in _<_.

Agda needs to decide on termination when it is given a proof for 
(Noetherian _<_)
-- rather than relying on (WellFounded _<_)
- ?
1-3 years ago I proposed a concrete approach.
The Agda people wrote that it somehow does not agree with Agda.
I did not understand their objections.
But I do not know, is it possible a correct approach to this?
At that time this was a theoretical consideration.
And now I have a concrete example to program in Agda.

--
SM

**Comment by mechvel** [comment]
On 2021-10-05 16:36, G. Allais wrote:
> There are a few results on nLab:
> https://ncatlab.org/nlab/show/well-founded+relation
> 
> In particular:
> 
>> In constructive mathematics, we may prove that a well-founded relation 
>> has no infinite descent
>> (see Proposition 2.3), but not the converse
> [..]

There it is also written
"
Remark 2.2. ...
On the other hand, the infinite descent condition is too weak to be of 
much use in constructive mathematics.
It is the inductive notion of well-foundedness that is just right.
"

I do not understand this.
I have a nice concrete example, where a nice termination proof is 
possible by using the
"infinite descent condition" (that is "_<_ is Noetherian") and where it 
is not visible any proof for
WellFounded _<_.
I am sure, there are many other such examples.
This "too weak to be of much use" sounds strange.

-- 
SM
