### ISSUE TITLE
toℕ-raise vs toℕ-inject+

### ISSUE THREAD

**Issue by conal** [agda/agda-stdlib#1603]
Is it accidental that `toℕ-raise` and `toℕ-inject+` have opposite orientations? From `Data.Fin.Properties`:

``` agda
toℕ-raise   : ∀ {m} n (i : Fin m) → toℕ (raise n i) ≡ n ℕ.+ toℕ i
toℕ-inject+ : ∀ {m} n (i : Fin m) → toℕ i ≡ toℕ (inject+ n i)
```

This difference trips me up sometimes and makes proofs a bit clumsier. I’d be happy to re-orient `toℕ-inject+` in a PR.

Thoughts?

**Comment by JacquesCarette** [comment]
`git blame` says @MatthewDaggitt was the last one to edit both of these (though they likely pre-date him).  And yes, the orientation of `toℕ-inject+` does seem to be backwards from the majority.

**Comment by MatthewDaggitt** [comment]
Sits in the library for 15 years and then two people try to change it within 2 weeks :grin: 

Having said that the CHANGELOG entry for this change needs some improvement, so reopening this issue temporarily.

**Comment by jamesmckinna** [comment]
How should the CHANGELOG entry be improved? cf. PR #1039 
The new/deprecated sections indicate the flipped argument order. 
Advice (offline) welcome!

**Comment by MatthewDaggitt** [comment]
Great question. Hmm actually looking at it again, I have no idea what I had in mind. Looks great to me as well. I  guess an excellent demonstration why writing more informative issues is a good idea :disappointed: Maybe it'll come back to me when I'm drafting the final changelog before the release.

Closing this issue in the meantime.
