### ISSUE TITLE
Relation.Binary.On strictTotalOrder and non-injective f

### ISSUE THREAD

**Issue by michalkonecny** [agda/agda-stdlib#161]
(I may be completely off here as I have been learning Agda for only a week or so.)

I am using Agda 2.5.2 with agda-stdlib 0.13.

I suspect that there is some problem in `Relation.Binary.On.isStrictTotalOrder`.
This function is used to give a proof of `IsStrictTotalOrder String` in module `Data.String`,
using `Data.String.Base.toList` as `f`.  I am not sure what is wrong but it seems to me
that one should not be able to prove `IsStrictTotalOrder String` without evidence that `toList` is injective.

I found this issue indirectly when I tried to use String as a key in Data.AVL:

```agda
  import Data.AVL
  import Data.String as S
  open import Relation.Binary
  module Context = Data.AVL {Key = S.String} (λ _ → S.String) (StrictTotalOrder.isStrictTotalOrder S.strictTotalOrder)
```

which led to the following error message:

```
Type mismatch:
expected: x .Agda.Builtin.Equality.≡ x
  actual: .Relation.Binary.List.Pointwise.Rel
(StrictTotalOrder._≈_ .Data.Char.strictTotalOrder) (S.toList x)
(S.toList x)
when checking that the expression StrictTotalOrder.isStrictTotalOrder S.strictTotalOrder
has type IsStrictTotalOrder .Agda.Builtin.Equality._≡_ __<__13
```

**Comment by gallais** [comment]
AVL is expecting a strict total order relying on propositional equality as its underlying notion of equivalence but `String`'s total order is based on the one induced by `toList` and the pointwise equivalence on `List`s.

To bridge the mismatch between the two we indeed need that `toList` is injective (but we know something stronger: `fromList` is its inverse!) but also that `toNat` which converts characters to natural numbers is. Then [something like this](https://stackoverflow.com/questions/36269333/agdas-standard-library-data-avl-sets-containing-data-string-as-values/36271248#36271248) will do.

As said in the comments on SO, it might be worth adding these notions of `rawIso` and stability of order structures under them to the standard library as they seem to pop up often.

**Comment by michalkonecny** [comment]
Thank you for the clarification and pointer to your helpful SO post.  Closing as the issue is not entirely valid.
