### ISSUE TITLE
Upper bounds of dependencies in `agda-stdlib-utils.cabal`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#1618]
The test suite is running into problems with the upper bounds of the dependencies (see the build problems in #1613). Is there a reason we have specific minor-version upper bounds (e.g `base >= 4.9.0.0 && < 4.16`) rather than major version upper bounds (e.g. `base >= 4.9.0.0 && < 5.0`)?

**Comment by MatthewDaggitt** [comment]
No answer from anyone, so I'm going to go ahead and bump the upper bounds to major version numbers and see if it all comes crashing down :grin:

**Comment by andreasabel** [comment]
>  minor-version upper bounds (e.g `base >= 4.9.0.0 && < 4.16`) rather than major version upper bounds (e.g. `base >= 4.9.0.0 && < 5.0`)?

According to https://pvp.haskell.org/ 4.16 is the major version (the first two positions are _major_, the third is _minor_, the fourth is _patch_).

A `base < 5` bound would mean you speculate that build will succeed with future major versions that are not "super-major".

**Comment by andreasabel** [comment]
> build problems in #1613

Something is wrong with this workflow:
- it claims to use GHC 8.6.5: https://github.com/agda/agda-stdlib/runs/4104448354?check_suite_focus=true#step:9:9
- however, it demands `base-4.16` which is GHC 9.2: https://github.com/agda/agda-stdlib/runs/4104448354?check_suite_focus=true#step:9:19

It seems like GHC 9.2.1 was added upstream: https://github.com/actions/virtual-environments/blob/7218e568f05e2e1b7a3273d9990fc571a0329c6b/images/linux/Ubuntu2004-README.md#haskell
Thus, it makes sense that the testsuite fails until 
- #1627 (PR #1622) is fixed

**Comment by MatthewDaggitt** [comment]
> According to https://pvp.haskell.org/ 4.16 is the major version (the first two positions are major, the third is minor, the fourth is patch). 

Ah thank you, wasn't aware of that convention, though it does now explain an awful lot.

> Thus, it makes sense that the testsuite fails until

Thank you for the detective work. Looks like we need to bump GHC version.
