### ISSUE TITLE
"Library 'standard-libary' not found."

### ISSUE THREAD

**Issue by joelburget** [agda/agda-stdlib#1620]
Hello, I tried following the installation instructions (https://github.com/agda/agda-stdlib/blob/master/notes/installation-guide.md), but when attempting to test the install I get the following error (note my `.agda/libraries` contains just `/Users/joel/code/agda/agda-stdlib-1.7/standard-library.agda-lib` and `.agda/defaults` contains just `standard-library-1.7`):

```
❯ agda nats.agda
 Library 'standard-libary-1.7' not found.
 Add the path to its .agda-lib file to
   '/Users/joel/.agda/libraries'
 to install.
 Installed libraries:
   standard-library-1.7
     (/Users/joel/code/agda/agda-stdlib-1.7/standard-library.agda-lib)
```

Funny to note that it says `standard-library-1.7` is not found while simultaneously saying it's installed. I tried editing both `.agda/defaults` to say `standard-library` and `/Users/joel/code/agda/agda-stdlib-1.7/standard-library.agda-lib` to say `standard-library` instead of `standard-library-1.7`:

```
❯ agda nats.agda
 Library 'standard-libary' not found.
 Add the path to its .agda-lib file to
   '/Users/joel/.agda/libraries'
 to install.
 Installed libraries:
   standard-library
     (/Users/joel/code/agda/agda-stdlib-1.7/standard-library.agda-lib)
```

Again, funny it says the library is missing while also reporting it's installed.

This is all on a fresh install.
* macOS 12.0.1
* Agda installed via `cabal install Agda`
* stdlib from https://github.com/agda/agda-stdlib/archive/v1.7.tar.gz, installed with `cabal install`

**Comment by joelburget** [comment]
Also, for the sake of completeness, I still get an error with `.agda/defaults` of `standard-libary` and `standard-library.agda-lib` of `standard-library-1.7`:

```
❯ agda nats.agda
 Library 'standard-libary' not found.
 Add the path to its .agda-lib file to
   '/Users/joel/.agda/libraries'
 to install.
 Installed libraries:
   standard-library-1.7
     (/Users/joel/code/agda/agda-stdlib-1.7/standard-library.agda-lib)
```

**Comment by fredrikNordvallForsberg** [comment]
Looks like you have a typo in your `.agda/defaults` file: "Library 'standard-**libary**' not found" -- note libary instead of lib**r**ary.

**Comment by joelburget** [comment]
You're right, that was the problem 🤦🏻‍♂️. Thank you, Fredrik.
