### ISSUE TITLE
Non-empty Fresh Lists?

### ISSUE THREAD

**Issue by fangyi-zhou** [agda/agda-stdlib#1623]
Is there any way to use Data.List.Fresh and Data.List.NonEmpty together for non-empty fresh lists?

**Comment by MatthewDaggitt** [comment]
Not obviously as `Data.List.Fresh` doesn't even use the `List` type. Maybe @gallais has a better idea(?) but I think your best bet that won't end up with you reproving a ton of freshness lemmas would be to lift the predicate `Data.List.Relation.Unary.Unique` to `NonEmpty` lists in a new module `Data.List.NonEmpty.Relation.Unary.Unique`. You could then from a `NonEmptyFreshList` by combining `Data.List.NonEmpty` with an (irrelevant?) uniqueness proof.

It would still require a fair bit of boilerplate but it would at least be mechanical. 

If you do go through with it, we'd welcome any PRs implementing the above suggestion :+1:

**Comment by gallais** [comment]
The easiest thing is probably to create `Data.List.Fresh.NonEmpty`
modeled after `Data.List.NonEmpty`: a simple record type corresponding
to a cons.

**Comment by MatthewDaggitt** [comment]
Doh, yes that would also work.

**Comment by fangyi-zhou** [comment]
So would it be easier to do Fresh.NonEmpty instead of NonEmpty.Fresh?

**Comment by MatthewDaggitt** [comment]
Yes.

**Comment by MatthewDaggitt** [comment]
Fixed with #1624
