### ISSUE TITLE
Rename Quasigroup and define as in Universal algebra?

### ISSUE THREAD

**Issue by Akshobhya1234** [agda/agda-stdlib#1625]
In stdlib, we define Quasigroup as magma with an inverse . But in [Ncatlab ](https://ncatlab.org/nlab/show/quasigroup)they mention that "In the absence of associativity, it is not enough to say that every element has an inverse element; instead, you must say that division is always possible." 

I was trying to define quasigroup as in the Universal Algebra section on [Wikipedia](https://en.wikipedia.org/wiki/Quasigroup) but currently IsGroup https://github.com/agda/agda-stdlib/blob/5df4931f548f3378da15927903bba4c38690c189/src/Algebra/Structures.agda#L246 has an instance of quasigroup and this won't fit with new definition. I found similar issue with renaming. 
https://github.com/agda/agda-stdlib/blob/5df4931f548f3378da15927903bba4c38690c189/src/Algebra/Structures.agda#L564

One way is to rename the existing quasigroup and introduce new definitions.

**Comment by MatthewDaggitt** [comment]
So concretely what are your proposed changes to the definitions?

**Comment by Akshobhya1234** [comment]
> So concretely what are your proposed changes to the definitions?

We define division operation as 
```
_LeftDivisionˡ_ : Op₂ A → Op₂ A → Set _
_*_ LeftDivisionˡ _\\_ = ∀ x y → (x * (x \\ y)) ≈ y

_LeftDivisionʳ_ : Op₂ A → Op₂ A → Set _
_*_ LeftDivisionʳ _\\_ = ∀ x y → (x \\ (x * y)) ≈ y

_RightDivisionˡ_ : Op₂ A → Op₂ A → Set _
_*_ RightDivisionˡ _//_ = ∀ x y → ((y // x) * x) ≈ y

_RightDivisionʳ_ : Op₂ A → Op₂ A → Set _
_*_ RightDivisionʳ _//_ = ∀ x y → ((y * x) // x) ≈ y
```

and define Quasigoup as 

```
 record IsQuasiGroup (∙ \\ // : Op₂ A) : Set (a ⊔ ℓ) where
  field
    isEquivalence  : IsEquivalence _≈_
    LeftDivisionˡ  : ∙ LeftDivisionˡ \\
    LeftDivisionʳ  : ∙ LeftDivisionʳ \\
    RightDivisionˡ : ∙ RightDivisionˡ //
    RightDivisionʳ : ∙ RightDivisionʳ //

  open IsEquivalence isEquivalence public
```

and define loop as

```
record IsLoop (∙ \\ // : Op₂ A) (ε : A) : Set (a ⊔ ℓ) where
  field
    isQuasiGroup : IsQuasiGroup ∙ \\ //
    identity : Identity ε ∙
  
  open IsQuasiGroup isQuasiGroup public
```

**Comment by MatthewDaggitt** [comment]
Seems reasonable to me. A PR would be welcome.

A few comments:
- I'm not so sure I'm keen on the infix notation for the `Division` definitions (as it's a noun not a verb). 
- The first letter of the names of the fields should be lower case.
- Maybe we should define a `LeftDivision`/`RightDivision` as well that combines the two subdefinitions. Like we do with `Identity`, `Inverse` etc.
