### ISSUE TITLE
Allow base-4.16 to support GHC 9.2

### ISSUE THREAD

**Issue by andreasabel** [agda/agda-stdlib#1627]
Please bump the upper bound on base to `< 4.17` and test with GHC 9.2:
https://github.com/agda/agda-stdlib/blob/5df4931f548f3378da15927903bba4c38690c189/agda-stdlib-utils.cabal#L20-L30
Would be nice to backport this to v1.7.

**Comment by andreasabel** [comment]
Thanks @MatthewDaggitt!
Could the fix be back-ported to `v1.7`?  
This can be done by branching off `v1.7`, cherry-picking the commit onto that branch, and then move the `v1.7` tag to the tip of this branch.

**Comment by MatthewDaggitt** [comment]
Do I actually need to move the `v1.7` tag? That seems like it'll break other people's repos. 

In my opinion I should probably use the branch with the cherry-picked commit to cut a new release `v1.7.1`?

**Comment by MatthewDaggitt** [comment]
Way more work, but seems like the morally right thing to do.

**Comment by MatthewDaggitt** [comment]
@andreasabel I have made a release under the `v1.7.1` tag, let me know if there's anything else I can do to help. Otherwise feel free to close the issue.

P.S. I'm not going to announce it...

**Comment by andreasabel** [comment]
@MatthewDaggitt : Thanks!  I shall have a look in connection with releasing Agda 2.6.2.1.

**Comment by andreasabel** [comment]
> Do I actually need to move the `v1.7` tag? That seems like it'll break other people's repos.

I have been told (in the meantime) that moving a tag is not a good idea, so thanks for releasing v1.7.1 instead.

I made Agda point to v1.7.1 instead of v1.7.
