### ISSUE TITLE
Rename Category.* modules to Control.* to avoid confusion with agda-categories

### ISSUE THREAD

**Issue by wenkokke** [agda/agda-stdlib#1636]
I am open to suggestions for better names then Control, it was merely chosen to imitate Haskell.

However, the current name is rather confusing given the existence of the agda-categories library, and the fact that these modules in the standard library do not implement categories in the general sense.

**Comment by wenkokke** [comment]
Using Control.* might conflict with the agda-hs library, but I suppose these two are never meant to be used in conjunction, @jespercockx?

**Comment by jespercockx** [comment]
The modules of the agda2hs library are all prefixed with `Haskell.`, so there is no problem with conflicts. I agree that `Categories` is a confusing name for this part of the library, though I must say that `Control` has always been a bit mysterious to me. I'm not sure what would be a better name though, perhaps `Computation`?

**Comment by JacquesCarette** [comment]
Well, `Category.*` implements 'categories internal to Agda', minus laws, a la Haskell. Its presence is why agda-categories uses `Categories.` as the main name-space!

I'm not super fond of `Control.` for this - but not against it either. I'd almost be tempted to use the name `Haskell.*` for this! [Part tongue-in-cheek, part serious.]  Yes, it would be in the same name space as agda2hs, but perhaps that would be a good thing.

`Computation` is an interesting suggestion indeed.

**Comment by wenkokke** [comment]
I mostly think that `Control.` is a good option because it is familiar to Haskell programmers. I think that using `Computation.` would be deeply confusing.

**Comment by jamesmckinna** [comment]
Effects.*?

**Comment by jamesmckinna** [comment]
So... no-one other than @wenkokke responded to my `Effect` suggested renaming. I'm pursuing this on a branch, and it raises the question (renaming in `git` is boring... but perhaps there's a way to do this automagically) as to whether the modules which use these notions, typically falling under `...Categorical` might beter be also renamed, viz as `...Effectful`. Thoughts?

**Comment by jamesmckinna** [comment]
Beside: this will definitely be a `label:breaking` change ;-)

**Comment by JacquesCarette** [comment]
`Effectful` is an interesting suggestion. So is `Effect`.

**Comment by jamesmckinna** [comment]
Branch at [`jamesmckinna/agda-stdlib:issue1636`](https://github.com/jamesmckinna/agda-stdlib/tree/issue1636).
TODO: follow-up with the `Categorical` to `Effectful` renaming, as per my speculative `CHANGELOG` entry.

**Comment by jamesmckinna** [comment]
I think this (and the above branch) is ready to go as a PR, so I'll make that and see what sparks, if any, fly! ;-)

**Comment by ulysses4ever** [comment]
I'd like to point out that "`Category.*`" in the title and discussion (as well as the PR, commit and Changelog) makes this change impossible to find when searching for a specific error about failing to import e.g. `Control.Monad` (as well as `Control.Functor` and `Control.Applicative`). I hope my comment improves the situation a bit.

**Comment by gallais** [comment]
The `CHANGELOG` is probably a better place to look at for version-specific breaking changes than a search through github issues.

**Comment by andreasabel** [comment]
Ah, too bad I am late to this party, not having followed the discussions on the library.
I think sticking to `Control` would be the best option for monad-like structures and monad transformers, as it is familiar from Haskell.
`Effect` is maybe more correct but unfortunately has strong connotations with _effect algebras_, so if I read `Effect` I am prone to expect an implementation of effect algebras rather than just "mundane" monads and monad transformers.
