### ISSUE TITLE
`Integer.Properties.-≡-decSetoid`

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#164]
`Integer` has not standard equalities other than `≡`.
So, why changing from `decSetoid` to `≡-decSetoid`
?

**Comment by MatthewDaggitt** [comment]
The aim is to keep naming conventions consistent across all data types. For other data there may be non-propositional equivalences available. We don't want users to have to guess the name.

**Comment by MatthewDaggitt** [comment]
Answered question so closing.
