### ISSUE TITLE
Alpha equality over reflected terms

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#1642]
I find myself reluctantly needing alpha rather than decidable equality over `Term` to solve some issues with the ring solver. Anyone have any bright ideas to avoid duplicating the quite frankly massive case split already in `Reflection.Term`?

**Comment by JacquesCarette** [comment]
Can you expand on the source of the problem, i.e. alpha vs decidable? Once you've reflected things, my intuition would be that you always need decidable equality.

**Comment by MatthewDaggitt** [comment]
I'm trying to make the ring solver compatible with `_-_` as per #1643. See #1318 for a description of the the problems trying to identify operator uses. 

Clearly the ring solver should just translate `_-_` into `\x y -> x + (- y)`, but I still have to identify the symbol that represents `_-_`. The trick is to normalise them both and then compare for equality. The problem is that the when I normalise e.g. `Data.Integer.Base._-_`, I get the expression `\i j -> i + (-j)` which isn't propositionally equal but is alpha equivalent to the term above.
