### ISSUE TITLE
A typo in the comment in `Reflection.Term`

### ISSUE THREAD

**Issue by Trebor-Huang** [agda/agda-stdlib#1649]
https://github.com/agda/agda-stdlib/blob/e023b9cdf5f43b90b3e806bc309ad851bc3ff567/src/Reflection/Term.agda#L73

`"n ⋯⟅∷⟆ xs"` should be `n  ⋯⟨∷⟩ xs`. Wasn't a serious issue, but it tripped me over on my way to learn reflection.

**Comment by MatthewDaggitt** [comment]
Thanks, nice spot!
