### ISSUE TITLE
Add `.vscode/*` to `.gitignore`?

### ISSUE THREAD

**Issue by Akshobhya1234** [agda/agda-stdlib#1651]
VisualStudioCode will create `.vscode/tasks.json` file. Instead of ignoring the changes every time, I think it should be added to gitignore.

**Comment by MatthewDaggitt** [comment]
Sounds good to me :+1: Anything else VSCode related we should add or is that it?

**Comment by Akshobhya1234** [comment]
Just `.vscode/` will ignore all the files that VSCode will create.
