### ISSUE TITLE
product of binary relations?

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#1657]
I see the following definition in a certain paper:
"
Given two relations R and S over sets A and B respectively, the product relation, `R × S` , over `A × B` is defined as
``(a, b) (R × S) (a', b') =  (a R a') & (b S b')``
".
May it have sense to add such a construct on binary relations to Relation.Binary.Construct ?
(may be with some of its properties proved).

**Comment by MatthewDaggitt** [comment]
Yes, this would live in `Relation.Binary.Construct.Product`. Surprised we don't have it already...

**Comment by JacquesCarette** [comment]
There's a whole slew of things in `Relation.Unary` that could be generalized. (Some of them already exist in `Relation.Nary`).

**Comment by Boarders** [comment]
I think this is essentially what is defined in `Data.Product.Relation.Binary.Pointwise.NonDependent` if I am not mistaken.

**Comment by MatthewDaggitt** [comment]
Yes, you're right! Nice spot. Closing.
