### ISSUE TITLE
Remove `--check` from fix-whitespace in Makefile?

### ISSUE THREAD

**Issue by Akshobhya1234** [agda/agda-stdlib#1666]
`make test` will only check if there are any whitespace violations. 

https://github.com/agda/agda-stdlib/blob/a0f334380d824ecf8cb6f05cbf5c10b3fff9d18f/GNUmakefile#L16-L17

Now we have to run 2 commands `fix-whitespace` and `make test` unless we setup `.git/hooks/pre-commit`

Instead we could remove `--check` to fix the whitespace violations with `make test`.

**Comment by gallais** [comment]
We've had instances of trailing whitespace that was actually intended and the fix
was not to run `fix-whitespace` but rather modify the `.yaml` file to add the file
to the list [`excluded-files`](https://github.com/agda/agda-stdlib/blob/master/fix-whitespace.yaml#L10).

**Comment by MatthewDaggitt** [comment]
I have a lot of sympathy with you @Akshobhya1234 as I also find running both slightly tedious, but I think overall I agree with @gallais on this one. Occasionally the white-space is intended. The solution is, as you say, to setup the hooks...

**Comment by MatthewDaggitt** [comment]
Is there a reason why you don't want to setup the hooks?

**Comment by Akshobhya1234** [comment]
Thanky you! Now I understand.
> Is there a reason why you don't want to setup the hooks?

Not really. I didn't want the "tedious" 2 step approach.
