### ISSUE TITLE
Ordered algebraic structures?

### ISSUE THREAD

**Issue by andreasabel** [agda/agda-stdlib#1694]
I was looking for _partially ordered monoid_ (`POMonoid`) but could not find it.  This is a chimera of a monoid and a partial order such that the composition operation of the monoid is monotone, i.e., we have `x*y <= x'*y'` whenever `x<=x'` and `y<=y'`.

Do we have ordered algebraic structures yet?
If not where should we place them in the module hierarchy?

**Comment by JacquesCarette** [comment]
No, they don't exist yet. I would be tempted to create an `Algebra.Ordered` hierarchy for them (yes, even though here the order is partial.)

**Comment by MatthewDaggitt** [comment]
Agreed. 'Algebra.Ordered' sounds good to me as well.

**Comment by laMudri** [comment]
I sense a combinatorial explosion, but as it happens I've also been using this specific combination (algebraic structures in the category of posets). Any plans for when people want more order features (e.g, meets, joins, decidability)?

**Comment by MatthewDaggitt** [comment]
@Taneb any reason why you closed this? I think best to keep it up until someone actually implements the said proposal!

**Comment by MatthewDaggitt** [comment]
> I sense a combinatorial explosion, but as it happens I've also been using this specific combination (algebraic structures in the category of posets). Any plans for when people want more order features (e.g, meets, joins, decidability)?

Well people haven't requested the decidable ones for even basic algebraic structures yet. Unsure about meets and joins, but I imagine we'd have a `.Decidable` sub-hierarchy, e.g. `Algebra.Decidable` and `Algebra.Ordered.Decidable`...

**Comment by Taneb** [comment]
> @Taneb any reason why you closed this? I think best to keep it up until someone actually implements the said proposal!

Oh, I didn't realise I had done that! I think I must have pressed the button accidentally on my phone. Many apologies.
