### ISSUE TITLE
Enrich properties on Data.List.NonEmpty

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-stdlib#1695]
I find that properties about Data.List.NonEmpty are very limited. I am working on a project which heavily uses it, so I am thinking to prove some properties as well as add some operations to it. I am writing this issue in case some other properties are placed in other folders for some whatever reasons.

**Comment by HuStmpHrrr** [comment]
I am not sure if v2.0 is the next release, but I would like to get this in before that happens.

**Comment by MatthewDaggitt** [comment]
Yes, v2.0 is the next release but its not imminent at the moment.
