### ISSUE TITLE
Are branches 2.4.2.1--2.4.2.6 stale?

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#171]
Are these 6 branches still needed or can they be deleted? I assume they're stale as we're way past Agda 2.4.2.

What about `revert-123-master`?

**Comment by asr** [comment]
You can erase the branches which *haven't* commits ahead of master. For the others branches, i.e. those *with* commits ahead of master, it is necessary to define if these commits should be cherry-picked into master before erasing the branch.

**Comment by MatthewDaggitt** [comment]
Deleted branches:
- `revert-123-master` - was a reversion removing universe levels from `Data.Container`, which has since been re-reverted.
- `2.4.2.1` - contained an obsolete version of `Data.Integer.Base` and the changes to `Function.Relation.TypeIsomorphisms` have already been integrated into `master`
- `2.4.2.2` - contained an obselete version of `Data.Integer.Base` and marked inactive by @asr 

Please could @andreasabel or @asr remove the protection from branches `2.4.2.4`, `2.4.2.5` and `2.4.2.6` as described [here](https://help.github.com/articles/configuring-protected-branches/)

**Comment by andreasabel** [comment]
Ok, I removed the protection.

Old releases of the std-lib should be reachable through the tags.

At some point, we decided to number the standard library releases separately from Agda.  But now I think this was stupid (including me on the side of "stupid").  It is not apparent now which version of the standard library one needs for which version of Agda.  
The rationale back then was that the library is maybe not well-designed enough to be called "standard library".  However, time has gotten the better of us.  De facto, it is the standard library, maybe we should make this official by numbering the releases in reference to the Agda versions.

**Comment by asr** [comment]
> The rationale back then was that the library is maybe not well-designed enough to be called "standard library".

AFAICT the rationale was that we could release new versions of the library (including bug-fixes ones) between releases of Agda. Currently, this rationale is even more valid because the library has a dedicated maintainer (@MatthewDaggitt, thanks for the great job!)

**Comment by andreasabel** [comment]
> AFAICT the rationale was that we could release new versions of the library (including bug-fixes ones) between releases of Agda. 

Ok, but this could still be done, using extra digits.  

Fine, I don't want to start the discussion again, we can leave it like it is.

@MatthewDaggitt : A bit thanks also from me!

**Comment by MatthewDaggitt** [comment]
Thanks!
