### ISSUE TITLE
Add properties of the quotient to Data.Nat.Divisibility

### ISSUE THREAD

**Issue by Taneb** [agda/agda-stdlib#1711]
I'd like there to be certain properties of the quotient of a proof of divisibility, for example:

```agda
foo : ∀ {m n} → (m∣n : m ∣ n) → quotient m∣n ∣ n
bar : ∀ {m n} (m∣n : m ∣ n) → m > 1 → quotient m∣n < n
```

I can't think of good names for these though

**Comment by jamesmckinna** [comment]
How about: `quotient-|` and `quotient-<`? or else `*-divides`, `*-less-than`?

**Comment by MatthewDaggitt** [comment]
I like `quotient-|` and `quotient-<`, better to include the name of the functions involved.

**Comment by jamesmckinna** [comment]
Did we do this?

**Comment by MatthewDaggitt** [comment]
Nope. Still open.

**Comment by jamesmckinna** [comment]
In the spirit of #1969 you probably also want
```agda
baz : ∀ {m n} (m∣n : m ∣ n) → m > 1 → n > 1 → quotient m∣n > 1
```
as, say, `quotient->1`?

**Comment by jamesmckinna** [comment]
And as a last thought: with the addition of `quotient≢0 : .{{NonZero n}} → NonZero quotient` to the `_|_` API, a number of arguments about involving possible-zero quotients might (hopefully) be automatically simplifiable by the typechecker, eg. eliminating [this case from `Data.Nat.Primality.euclidsLemma`](https://github.com/agda/agda-stdlib/blob/3a1bda24f1949c6fe0ba85d686745dcf246513a8/src/Data/Nat/Primality.agda#L107-L109)
