### ISSUE TITLE
`Data.Nat.DivMod`  doesn't type check using `Agda` master

### ISSUE THREAD

**Issue by csetzer** [agda/agda-stdlib#1716]
Data.Nat.DivMod  doesn't type check. agda-stdlib version v1.7-107-gf3b769906 (f3b7699)  agda version 2.6.3-cf7ea79

**Comment by gallais** [comment]
If you're using agda dev you're not supposed to use `master` but rather `experimental`.

**Comment by MatthewDaggitt** [comment]
Yup, there's an issue open on the Agda repo about it: https://github.com/agda/agda/issues/5611.

I keep hoping the powers that be are going to decide it is a bug rather than feature....

**Comment by gallais** [comment]
Strange, from #1614

> Closing as I think the offending code was disabled upstream.

Does that mean that the problem has been reintroduced since then?
https://github.com/agda/agda/commit/cf7ea79a8e6cb8fc62dd5a258f1d6317c5314cdd is only a few days old.

**Comment by MatthewDaggitt** [comment]
Or I was wrong and the offending code wasn't disabled upstream...

**Comment by uncle-betty** [comment]
I just noticed that https://github.com/agda/agda/issues/5611 was closed a while back.

So I tried type-checking today's stdlib `master` with today's Agda `master` - and it worked.

**Comment by MatthewDaggitt** [comment]
Nice spot, thanks!
