### ISSUE TITLE
Add injectivity proofs for data constructors

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#174]
`suc`, `_::_`, `inj1`, etc. are all injective. This is such a common thing to need that we ought to have these properties in the standard library.

There's a bit of leeway as to how we formalise this injectivity. I suppose the most general approach would be to reuse [`Function.Injection`](https://agda.github.io/agda-stdlib/Function.Injection.html) even though our statements will always involve the trivial setoid defined using propositional equality. I wonder how usable the lemma would be in that case.

**Comment by MatthewDaggitt** [comment]
I agree that these are very useful. As I go along, I have already been adding things like:
```agda
suc-injective : ∀ {m n} → suc m ≡ suc n → m ≡ n
suc-injective refl = refl
```
to `Nat`, `Fin`, `Integer` etc. but I certainly haven't made an effort to add them everywhere. This form is more useful to me than the `Injection` framework as it doesn't require unwrapping the module and messing around with setoids. I can see how it might be useful if you're doing much more general functional reasoning though. If we do use the `Injection` framework we should certainly leave the "raw" form in as well.

I'll add it to my list of things to do...

**Comment by gallais** [comment]
There's also the question of constructors taking multiple arguments: do we opt for multiple lemmas or one lemma returning a product of equalities?

**Comment by MatthewDaggitt** [comment]
Or both? Left and right are often useful separately.

**Comment by andreasabel** [comment]
I would produce one lemma per constructor argument.  Otherwise, one has to decompose the pair.  If we have a systematic naming scheme, separate lemmata are easier to work with.

**Comment by gallais** [comment]
This is what I have done in #177. For binary constructor with two "sides" I have used `ˡ` and `ʳ` as suffixes. Otherwise (e.g. `Data.W`'s `sup`) I have resorted to numeric indices except for `Data.AVL`'s lemmas where `-key` and `-bal` match the specific domain at hand.
