### ISSUE TITLE
Disastrous expansion of operations in `Data.Rational.Base`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#1753]
The operations such as addition and multiplication in `Data.Rational.Base` are defined in terms of the numerator and denominator projection operations, e.g.

https://github.com/agda/agda-stdlib/blob/650e05f3a5ef06cb938c3b91a4fc8b9b8d7c5ef2/src/Data/Rational/Base.agda#L206-L207

This is beautiful and elegant, and arguably the right way to define them. However, it does mean that Agda unfolds these definitions automatically. By the time you have an expression `x + y + z + a + b + c` the unfolded expression is over 200 lines long. 

This makes the rational numbers almost impossible to work with in large proofs. In [recent proofs](https://github.com/vehicle-lang/vehicle/blob/dev/examples/windController/agdaProof/AbstractRationals.agda) I've resorted to redefining everything that's needed under the `abstract` keyword.

**Comment by MatthewDaggitt** [comment]
See also the recent mailing list issue which was also caused by this problem.

**Comment by MatthewDaggitt** [comment]
Suggestion from @andreasabel: investigate using --no-eta-equality in record

**Comment by andreasabel** [comment]
```agda
module Data.Rational.Base where
...
record ℚ : Set where
  no-eta-equality; pattern
  constructor mkℚ
  ...

>-nonZero : ∀ {p} → p > 0ℚ → NonZero p
>-nonZero {p@(mkℚ _ _ _)} (*<* p<q) = ℚᵘ.>-nonZero {toℚᵘ p} (ℚᵘ.*<* p<q)

<-nonZero : ∀ {p} → p < 0ℚ → NonZero p
<-nonZero {p@(mkℚ _ _ _)} (*<* p<q) = ℚᵘ.<-nonZero {toℚᵘ p} (ℚᵘ.*<* p<q)

positive : ∀ {p} → p > 0ℚ → Positive p
positive {p@(mkℚ _ _ _)} (*<* p<q) = ℚᵘ.positive {toℚᵘ p} (ℚᵘ.*<* p<q)

negative : ∀ {p} → p < 0ℚ → Negative p
negative {p@(mkℚ _ _ _)} (*<* p<q) = ℚᵘ.negative {toℚᵘ p} (ℚᵘ.*<* p<q)

nonPositive : ∀ {p} → p ≤ 0ℚ → NonPositive p
nonPositive {p@(mkℚ _ _ _)} (*≤* p≤q) = ℚᵘ.nonPositive {toℚᵘ p} (ℚᵘ.*≤* p≤q)

nonNegative : ∀ {p} → p ≥ 0ℚ → NonNegative p
nonNegative {p@(mkℚ _ _ _)} (*≤* p≤q) = ℚᵘ.nonNegative {toℚᵘ p} (ℚᵘ.*≤* p≤q)
...

-- addition
_+_ : ℚ → ℚ → ℚ
p@(mkℚ _ _ _) + q@(mkℚ _ _ _) = (↥ p ℤ.* ↧ q ℤ.+ ↥ q ℤ.* ↧ p) / (↧ₙ p ℕ.* ↧ₙ q)

-- multiplication
_*_ : ℚ → ℚ → ℚ
p@(mkℚ _ _ _) * q@(mkℚ _ _ _) = (↥ p ℤ.* ↥ q) / (↧ₙ p ℕ.* ↧ₙ q)
...
```

**Comment by andreasabel** [comment]
Alternative way to force matching:  `x@record{}` (closer to Haskell, don't need to mention constructor name):
```agda
_+_ : ℚ → ℚ → ℚ
p@record{} + q@record{} = (↥ p ℤ.* ↧ q ℤ.+ ↥ q ℤ.* ↧ p) / (↧ₙ p ℕ.* ↧ₙ q)
```

**Comment by MatthewDaggitt** [comment]
Ooh that's even nicer. Yup, I'm happy with that solution.

**Comment by MatthewDaggitt** [comment]
Going to have a hack at this now.

**Comment by MatthewDaggitt** [comment]
Hmm, we have the same issue with multiplication in `Data.Integer` but that's appears harder to fix as there's no one constructor to pattern match on....
