### ISSUE TITLE
Move "raw" bundles to `Data.X.Base`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#1755]
Currently the raw bundles, e.g. `RawMagma` are defined in `Data.X.Properties` but they should really be defined in `Data.X.Base` as they don't require any properties.

**Comment by JacquesCarette** [comment]
Except that I see that this makes `Data.X.Base` now depend on `Algebra.Bundles`. That's not too too heavyweight, but do we want `Data.X.Base` to have quite so much in it? I'd prefer `Data.X.Bundles`, now that I look at the details of #1810 .

**Comment by Taneb** [comment]
I'd rather something like a new module `Algebra.RawBundles` or `Algebra.Bundles.Raw` containing the definitions of the raw bundles, which can be imported at much lower cost from `Data.X.Base`

**Comment by JacquesCarette** [comment]
But that would still leave `Data.X.Base` to depend on `Algebra.Bundles` if those are actually imported.

Won't `Algebra.RawBundles` (or equivalent) grow to something really large, as it would depend on all algebras? I certainly think that having these be defined in a module that mentions `X` in its name would help.

**Comment by Taneb** [comment]
I think I didn't explain myself right. I meant that the definition of the types `RawMagma`, `RawMonoid`, `RawGroup`, etc, be moved into the new module `Algebra.RawBundles`, and then `Data.X.Base` can import `Algebra.RawBundles` and we define `X-rawGroup` in `Data.X.Base`.

**Comment by MatthewDaggitt** [comment]
I agree with @Taneb (and would vote for `Algebra.Bundles.Raw`)

**Comment by Taneb** [comment]
I'm going to try to make a PR this evening moving the definitions of RawX to `Algebra.Bundles.Raw`

**Comment by 5xy1** [comment]
@Taneb Maybe I could help with this? I can update my PR today.
