### ISSUE TITLE
Unsolved implicits in Data.List.Relation.Ternary.Appending.Propositional

### ISSUE THREAD

**Issue by laMudri** [agda/agda-stdlib#1765]
The following code checks with unsolved implicit arguments – in particular a type `A` and its level – in both constructors of `Appending`. This seems to be an unused argument, because I can fill it with any old rubbish. I don't think anything similar affects the `.Setoid` module.

```agda
open import Data.List
open import Data.List.Relation.Ternary.Appending.Propositional
open import Data.List.Relation.Binary.Pointwise hiding (refl)
open import Data.Nat
open import Relation.Binary.PropositionalEquality

foo : Appending (3 ∷ []) (2 ∷ []) (3 ∷ 2 ∷ [])
foo = refl ∷ []++ refl ∷ []
```

Agda version 2.6.2.1, stdlib version 1.7.1.

**Comment by gallais** [comment]
That'll be
```agda
open General public
   hiding (Appending)
```
in [`Data.List.Relation.Ternary.Appending.Setoid`](http://agda.github.io/agda-stdlib/Data.List.Relation.Ternary.Appending.Setoid.html)
that re-exports the constructors withtout specialising them.
