### ISSUE TITLE
Camel case in Algebra.Ordered.X

### ISSUE THREAD

**Issue by Akshobhya1234** [agda/agda-stdlib#1766]
I noticed that camel case is missing in Algebra.Ordered.Structures and Algebra.Ordered.Bundles. 
I think we should keep the naming standard same as in Algebra.Structures

eg: 
https://github.com/agda/agda-stdlib/blob/ae0702e5f899db6622c02455c50e4446734ac051/src/Algebra/Ordered/Structures.agda#L36

I propose to keep it as ProMagma and so on.

**Comment by Taneb** [comment]
I read "promagma" as a single word, with a pro a prefix rather than an adjective. So to me, "IsPromagma" is correct camel case.

**Comment by HuStmpHrrr** [comment]
I suppose it has something to do with hyphening. quasigroup is not a word that I would put hyphen in between, but quasi-semi-metric is a bit difficult if there is no hyphen, regardless of actual casing. I think it's actually consistent, but I guess promagma is not frequently seen enough to know whether it belongs to the first category or the second one?

**Comment by MatthewDaggitt** [comment]
Going to mark this as won't fix, as I don't think anyone has a consistent scheme for fixing this.
