### ISSUE TITLE
Expose container combinator conversion functions separately from their correctness proofs

### ISSUE THREAD

**Issue by KislyjKisel** [agda/agda-stdlib#1778]
#### Description
Currently `Data.Container.Combinator.Properties` exposes `Inverse` records which provide both conversion functions and their correctness proofs. Proofs for `const` and `_×_` combinators require extensionality and thus disallow usage of corresponding conversions, which don't actually need extensionality.

**Comment by MatthewDaggitt** [comment]
Apologies for the delay in replying. Yes, this seems suboptimal. We'd welcome a PR fixing this. Maybe exposing the conversion functions for all the constructions under meaningful names?

**Comment by KislyjKisel** [comment]
Should conversion functions be put into `Data.Container.Combinator` module? About names - should symbolic names like `_⊎_-to` or `const[_]⟶_-from` be used?
