### ISSUE TITLE
Hedbergs Theorem

### ISSUE THREAD

**Issue by guilhermehas** [agda/agda-stdlib#1796]
The Hedbergs-Theorem says that every discrete data structure is a set. And it looks like it is not in the library.
So, I was thinking about creating a pull request to add it, but I have no idea which file I should prove this theorem.

**Comment by gallais** [comment]
Are you looking for https://agda.github.io/agda-stdlib/Axiom.UniquenessOfIdentityProofs.html ?

**Comment by guilhermehas** [comment]
Thanks. I have not found it. 
Is it a good idea to use this proof to add isSet in properties of common data structures such as Bool and Natural numbers?

**Comment by gallais** [comment]
We already have these corollaries but they're typically called [`≡-irrelevant`](http://agda.github.io/agda-stdlib/Data.Nat.Properties.html#3014).
I'm not convinced we should rename to `isSet` given that's homotopy-specific terminology
which clashes with `Set l` as used in the stdlib.

**Comment by guilhermehas** [comment]
I haven't found it because of the name.
