### ISSUE TITLE
Loop combinator for IO

### ISSUE THREAD

**Issue by Lysxia** [agda/agda-stdlib#1801]
agda-stdlib has one combinator for loops, `untilJust`, but it doesn't allow loops to be stateful (without some `IORef`). The following `untilRight` seems a natural enough generalization:

```
untilRight : ∀ {A B : Set} → (A → IO (A ⊎ B)) → A → IO B
untilRight f x = bind (♯ f x) λ where
  (inj₁ x′) → ♯ untilRight f x′
  (inj₂ y) → ♯ return y
```

Does that seem like a good addition to agda-stdlib or did I miss some other existing construct?

(Related is #1065 which is also about recursion in IO but seems much more heavyweight.)

**Comment by gallais** [comment]
This seems very sensible to me.
