### ISSUE TITLE
Build failure in test suite due to too advanced GHC

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#1804]
We've started getting the following failure when running the test suite:

> Warning: Unknown/unsupported 'ghc' version detected (Cabal 3.6.2.0 supports
'ghc' version < 9.4): /usr/local/.ghcup/bin/ghc is version 9.4.1
Resolving dependencies...

I'm a bit confused about how version 9.4.1 is sneaking in as in `ubuntu.ci` we have:
https://github.com/agda/agda-stdlib/blob/d6d6087cf4da0261239937e213b7ebe9fcd8796c/.github/workflows/ci-ubuntu.yml#L49

and indeed in the previous step `Install alex & happy` we are using 8.10.7

**Comment by gallais** [comment]
I suspect that the new environment comes with a more recent version of ghc & because we hit the cache
we don't bother reinstalling the one we're interested in, wrongly assuming it'll have been cached.

**Comment by gallais** [comment]
Fixed by #1804
