### ISSUE TITLE
`Data.Integer.Properties.+-isAbelianGroup` should be called `+-0-isAbelianGroup`

### ISSUE THREAD

**Issue by Taneb** [agda/agda-stdlib#1844]
This is consistent with the other names in the module as well as `Data.Rational.Properties`

**Comment by jamesmckinna** [comment]
Additionally, the raw bundles in `Data.Integer.Properties` should move to `Data.Integer.Base` as per issue #1755 PR #1810, etc.

**Comment by jamesmckinna** [comment]
Oh, and the *Monoids* in ``Rational.*` should have the names of their units added to the bundle names... sigh.
