### ISSUE TITLE
`Data.Nat.Base` is missing raw algebra bundles involving multiplication

### ISSUE THREAD

**Issue by Taneb** [agda/agda-stdlib#1858]
* `*-rawMagma`
* `*-1-rawMonoid`
* `+-*-rawNearSemiring`
* `+-*-rawSemiring`

**Comment by jamesmckinna** [comment]
Suggest I add these to the `Parity` PR #1852 (arrogantly presuming that mention of these omissions was prompted by those additions...)?

**Comment by MatthewDaggitt** [comment]
Nope, definitely open a separate PR! No need to wrap them up in the same one :+1:

**Comment by jamesmckinna** [comment]
OK, but I will move the raw bundles from `Data.Parity.Properties` to `Base`.

**Comment by jamesmckinna** [comment]
Done. PR #1861

**Comment by jamesmckinna** [comment]
Erroneous linkage to PR #1822 which I now don't seem able to unlink... :-(
