### ISSUE TITLE
Error when Cheking Data.Float.Base

### ISSUE THREAD

**Issue by Petkomat** [agda/agda-stdlib#1883]
Calling `agda imports.agda` where the content of the `imports.agda`

is only

```
module imports where

import Data.Float.Base
```

(since this is the minimal example that reproduces my problem) results in the error

```
C:\Users\petkomat\git\agda-stdlib\src>agda imports.agda
Checking imports (C:\Users\petkomat\git\agda-stdlib\src\imports.agda).
 Checking Data.Float.Base (C:\Users\petkomat\git\agda-stdlib\src\Data\Float\Base.agda).
C:\Users\petkomat\git\agda-stdlib\src\Data\Float\Base.agda:129,19-25
Agda.Builtin.Maybe.Maybe Word.Word64 !=< Word.Word64
when checking that the expression toWord has type
Float → Word.Word64
```

I tried to import every module that can be found in the standard library (hence the name `imports.agda`) and then removed the non-problematic modules. I am quite new to agda and I haven't the faintest idea of what I am doing wrong. 

I am using `Agda version 2.6.4` (installed via stack from the sources in the agda repository) and Windows 10.

**Comment by gallais** [comment]
Are you using the `experimental` branch? The `master` branch is kept compatible with
the latest *released* version of Agda. If you are using a development version then you
should switch to `experimental`.

**Comment by Petkomat** [comment]
I am sorry for not reading the README thoroughly. 

Indeed, I was not using the experimental branch of agda and once I switched to it, even the `agda imports.agda`  with the extended version of the imported modules finished without errors.

Thanks.
