### ISSUE TITLE
Update HACKING.md with up-to-date information

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#190]
I don't think we're doing any of the things in HACKING anymore.

Can we simply replace it with something saying that we make PRs
against master (and maybe a guide to naming conventions?).

**Comment by asr** [comment]
> I don't think we're doing any of the things in HACKING anymore.

I disagree but I recognise that some information is outdated. 

> saying that we make PRs against master

I guess you meant stable-X.Y.

**Comment by gallais** [comment]
> I guess you meant stable-X.Y.

On agda yes, but not on agda-stdlib.

**Comment by asr** [comment]
Please forget what I said. I thought I was reading an issue on Agda.

**Comment by andreasabel** [comment]
@gallais : Please go ahead to update the information to match the current practice.

**Comment by MatthewDaggitt** [comment]
I've updated HACKING (and README) with 0261318 and 3cab31d. Obviously the naming conventions aren't anywhere near exhaustive, I guess we can add to them as we get misunderstandings in pull requests. @gallais feel free to make any changes if I've left anything major out!

**Comment by MatthewDaggitt** [comment]
Thanks for the tweaks @asr. Closing.
