### ISSUE TITLE
`Zero` objects in the `Algebra.*` hierarchy

### ISSUE THREAD

**Issue by jamesmckinna** [agda/agda-stdlib#1906]
`Algebra.Construct.Zero` defines some zero objects (`magma`, `semiring`, `band`) which are *not* zero objects, only terminal ones. Correspondingly, true zero objects defined there should also be re-exported as *initial* objects. Suggest a refactor to put things 'in the right place': 
* define `Terminal` to introduce all the terminal algebras; 
* re-export the subset of those which *are* zero objects also in `Initial` and `Zero`; 
* define the true initial objects for `Magma`, `Semigroup`, `Band` in `Initial`

See PR #1902

**Comment by Taneb** [comment]
I think we should (not necessarily in the PR that closes this, but maybe) include the defining properties of these initial/terminal/zero objects, so for example for initial objects, that there is a unique homomorphism from them to any other object. Maybe this can go somewhere like `Algebra.Construct.Initial.Properties`?

**Comment by JacquesCarette** [comment]
1. Yes!
2. Next PR. Let's not achieve paralysis by drowning the great by requiring perfection.
