### ISSUE TITLE
Branch `release-v1.7.2`: Missing `Effect` modules

### ISSUE THREAD

**Issue by asr** [agda/agda-stdlib#1915]
@MatthewDaggitt, I'm preparing the release of Agda 2.6.3. Running the benchmark test (`make benchmark-without-logs`) I found that the following modules are missing from the `release-v1.7.2` branch:

```agda
Effect.Monad
Effect.Monad.State
```
Could you add these modules, please.

**Comment by MatthewDaggitt** [comment]
These modules should not exist in `v1.7.2`.... they're being introduced in `v2.0`

**Comment by asr** [comment]
Ah, I see. Thanks!
