### ISSUE TITLE
`Algebra.Bundles.SemiringWithoutOne` fails to export `setoid`?

### ISSUE THREAD

**Issue by jamesmckinna** [agda/agda-stdlib#1917]
More specifically, `Algebra.Bundles.Semiring` does indeed export all of its corresponding substructures (down to `setoid` derivable via `Algebra.Structures`), while `Algebra.Bundles.SemiringWithoutOne` appears not to. Not quite sure how to fix this, but will update if/when I do... with a minimum (non-)working example. 

EDITED: See the two `Test` files at `Algebra.Properties.Semiring{WithoutOne}` on [this branch](https://github.com/jamesmckinna/agda-stdlib/tree/SemiringWithoutOne) now minimised. 

UPDATE: the problem seems similar to that described/solved in issue #1159 / PR #1174, and I think I have a solution, but I'm conscious of being out of my depth as to the arcane define/public re-export structure of the `Algebra.*` hierarchy, so reluctant to issue a PR about this... Which raises a separate question: how 'high' (=fewest operations, axiomatic properties) in the `Structures` (and hence `Properties.BundleX.OperationY`) hierarchy do we want certain things to live: eg distributivity of `_*_` over `sum`, defined in #1462, placed it as a property of `Semiring`s; @uzytkownik 's original contribution (from a year earlier) under #1287 placed it under `SemiringWithoutOne`...  and AFAICT, it doesn't even need that much structure, only that of the theory pullback (which has no name) of `SemiringWithoutOne` and `SemiringWithoutAnnihilatingZero`. In pursuit of #1287, I'd be happy for everything to live under properties of `Semiring`, and leave the appropriate weakening of structure to subsequent refactoring... but I know that there are strong views about the ambient guiding principle of 'be no less general than you absolutely can', and I thought that this was worth flagging.

**Comment by jamesmckinna** [comment]
Will see if I can knock this off along the lines of @Taneb 's #1967 ... later.

**Comment by jamesmckinna** [comment]
Aaargh, this issue is really two: 
- [ ] exporting `setoid`
- [ ] adding more diamonds to find a home for eg distributivity of `_*_` over `sum`

The first might be easy (but I feel faint thinking about it), but the second?

**Comment by jamesmckinna** [comment]
Re: the first. In my 'success' test, viz.
```agda
open import Algebra.Bundles using (Semiring)

module Algebra.Properties.Semiring.Test {c} {ℓ} (R : Semiring c ℓ) where

open Semiring R
{- succeeds for Semiring -}
open import Relation.Binary.Reasoning.Setoid setoid
```
nevertheless is `emacs` if I do `C-c C-w` on `setoid` to find out why it is, indeed, in scope, `agda-mode` reports
```
setoid is not in scope.
```

Eh???

**Comment by jamesmckinna** [comment]
I now find myself in the uncomfortable position of having a solution, but one which I do not understand, and hence don't know if it will cause problems later if merged... :-(

But I definitely don't understand the `agda2-mode` behaviour as regards names brought into scope by `public` export... is *this* a bug?

**Comment by MatthewDaggitt** [comment]
> But I definitely don't understand the agda2-mode behaviour as regards names brought into scope by public export... is this a bug?

Looks like a bug to me. Report on the Agda repo?

**Comment by jamesmckinna** [comment]
Hmm, resolved after an `agda-mode compile`.
