### ISSUE TITLE
agda 2.6.3 build issue

### ISSUE THREAD

**Issue by chenrui333** [agda/agda-stdlib#1918]
👋 While trying to upgrade agda releases to 2.6.3, seeing some build issue as below:

```
/opt/homebrew/Cellar/agda/2.6.3/lib/agda/src/Data/Float/Base.agda:68,19-25
Agda.Builtin.Maybe.Maybe Word.Word64 !=< Word.Word64
when checking that the expression toWord has type
Float → Word.Word64
```

relates to https://github.com/Homebrew/homebrew-core/pull/121851
full build log, https://github.com/Homebrew/homebrew-core/actions/runs/4045207909/jobs/6956488764

---

Have not tried the latest head with agda 2.6.3 yet.

**Comment by Taneb** [comment]
Hi @chenrui333! `master` is designed to be used with the previous version of Agda, because we haven't updated it yet. The `experimental` branch has the changes needed for Agda 2.6.3

**Comment by chenrui333** [comment]
@Taneb can you point out the changes, we can try it/them on the homebrew side, thanks!

**Comment by cty12** [comment]
Are you on an Apple M machine? You may try branch `release-v1.7.2`.

**Comment by chenrui333** [comment]
Sounds good, thanks for the pointer!
