### ISSUE TITLE
Maybe `--cubical-compatible` is a mistake for stdlib 2.0?

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-stdlib#1939]
See [this issue](https://github.com/agda/agda/issues/6101#issuecomment-1492868971) about Agsy failing, and `--without-K` being the fix.

If cubical truly want to use `stdlib`, there is likely a need for a concerted effort to make them compatible (such as: remove the duplication!)

**Comment by gallais** [comment]
Do we have cubical customers (independently from the cubical lib)?
E.g. does @nad use the stdlib in combination with cubical features?

**Comment by jamesmckinna** [comment]
This is/appears to be currently a problem for all users during development (until and unless Agsy is upgraded to incorporate richer search spaces) but only for library developers/maintainers when merging PRs. 

Accordingly I think, but perhaps more fieldwork is required to confirm this, that the least worst solution/advice to users might be:
* use `--without-K` *during development* (especially if using `C-h a`) if cubical features are not used; 
* use `--cubical-compatible` *only* when merging into the library. 

Going backwards to `v1.7.2` would, I think, be a terrible mistake given the enormous amount of work over the last 2+ years in preparing v2.0 for (eventual) release. 
.

**Comment by jamesmckinna** [comment]
BTW/FWIW, I think that PR#1935 was premature, (we might at least have had a shot at releasing 2.0 before proceeding), but rolling it back would be ... also a mistake. 

I'm 'happy' to take a performance hit on typechecking --without-K only code, for the sake of maintaining a single active (and compatible!) Agda and stdlib release, even if that may require patience and some intelligent compromise.

**Comment by nad** [comment]
> E.g. does @nad use the stdlib in combination with cubical features?

Yes, I do.

We stopped supporting Agsy a long time ago. Another way to fix the problem would be to remove the Agsy code from Agda (perhaps in favour of [Mimer](https://github.com/agda/agda/pull/6410)).

**Comment by andreasabel** [comment]
It is not only Agsy which is affected by `--cubical-compatible`.  
E.g. Agda 2.6.3 also has an issue with extended lambdas:
- https://github.com/agda/agda/pull/6580

I am afraid more leaks of cubical stuff into regular Agda via `--cubical-compatible` will be uncovered in the future.
Thus, I lean towards a "hardware" separation of cubical from non-cubical Agda, via using `--without-K` rather than `--cubical-compatible` as the default.  (But, as I said before, we would need to change Agda so that `--with-K` can override `--cubical-compatible`.)

**Comment by andreasabel** [comment]
@jamesmckinna wrote:
> Accordingly I think, but perhaps more fieldwork is required to confirm this, that the least worst solution/advice to users might be:
> 
> * use `--without-K` _during development_ (especially if using `C-h a`) if cubical features are not used;
> * use `--cubical-compatible` _only_ when merging into the library.

I take this is the suggestion.  To make this work, one would need an easy way to switch the library between these two modes.
Currently, this is a 1000 file modification, as 1000 files have `{-# OPTIONS --cubical-compatible #-}` in the preamble which cannot be overwritten with giving `--without-K` in the `.agda-lib` file or at the command line (if I am not mistaken).

**Comment by jespercockx** [comment]
> I take this is the suggestion. To make this work, one would need an easy way to switch the library between these two modes.
Currently, this is a 1000 file modification, as 1000 files have {-# OPTIONS --cubical-compatible #-} in the preamble which cannot be overwritten with giving --without-K in the .agda-lib file or at the command line (if I am not mistaken).

Would it make sense to split the library into two folders, each with their own .agda-lib file? That way it would be a lot easier to switch between --without-K and --cubical-compatible for the part that does not use --with-K.

**Comment by nad** [comment]
> Ideally, one would just have `--without-K` in the files of the std-lib, but then the possibility to add a flag to the `standard-library.agda-lib` file that switches to `--cubical-compatible` where possible.

I don't think this is ideal. I don't want to rely on a locally patched variant of a library.

I think that at some point you suggested something like the following:

* Use separate build directories for Cubical Agda and non-cubical Agda.
* When importing non-cubical code from cubical code, build the non-cubical code with the extra cubical stuff, and put the interfaces in a Cubical Agda build directory.

With this approach we could merge `--without-K` and `--cubical-compatible`. The approach could in some cases lead to unnecessary waiting for users:

* You work on module `M1`, which does not use Cubical Agda. The module finishes type-checking.
* You switch to module `M2`, which uses Cubical Agda, and imports `M1`. Before you can start working Agda has to type-check `M1` from scratch, which in some cases could take significant time.

However, I still think this is preferable to making the (unpatched) standard library unusable for users of Cubical Agda.

**Comment by uhbif19** [comment]
> Use separate build directories for Cubical Agda and non-cubical Agda.

Why could not that be single directory, just tracking existence of additional "cubical" info in individual files instead? Like for non-cubical usage that info could be just dropped/tree-shaked while compiling. And otherwise AFAIU having that info during compilation is okay in `without-K` case.

**Comment by jamesmckinna** [comment]
Suggest we close, and accept that this particular ship has sailed? 

There are various other issues on the main tracker concerning performance... but such things also tend to get solved by waiting long enough (sic)...

**Comment by MatthewDaggitt** [comment]
Closing as suggested. I agree that we want to avoid duplicating the library at all costs.

> But, as I said before, we would need to change Agda so that --with-K can override --cubical-compatible

I agree with @andreasabel that this seems like the best upstream fix.

**Comment by andreasabel** [comment]
_The Return of The Without K_ featured in:
- #2792
