### ISSUE TITLE
BibTeX file to cite agda-stdlib

### ISSUE THREAD

**Issue by martinescardo** [agda/agda-stdlib#1952]
Please provide in the front page of this project a BibTeX file to cite the Agda standard library from a LaTeX article.

For the moment I have this in a paper with coauthors that will be published soon:

```
@misc{agda:stdlib,
title = {{A}gda Standard Library},
authors = {Community},
howpublished{\url{https://github.com/agda/agda-stdlib}}
}
```

If the `agda-stdlib` contributors are OK with this, I will go ahead with this. Otherwise please let me know how you would like to be cited. Maybe you already have a publicly available BibTeX file somewhere here, but search engines didn't help me to find it. Thanks!

**Comment by gallais** [comment]
Related: #1833

**Comment by martinescardo** [comment]
Thanks!
