### ISSUE TITLE
Remove `Algebra.Definitions.Core(1/2)`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#1970]
The module parameter setup just doesn't work. When you write
```
open import Function.Definitions
```
you still get e.g. `Surjective` in scope with _two_ equality parameters instead of one.

I think the best plan is to ditch the module parameters in `Function.Definitions` entirely, and fold `Core1` and `Core2` into it.

**Comment by jamesmckinna** [comment]
How is this affected by @alexarice 's PR #1156 for a 'better' notion of `Surjective`, which IIUC, *does* use the two equality relations?

**Comment by MatthewDaggitt** [comment]
Ack, you're right. That would also fix it. Okay, lets merge that instead!
