### ISSUE TITLE
Migrating `map` and `zip` from `Function.Inverse` to `Function.Construct.X`

### ISSUE THREAD

**Issue by Saransh-cpp** [agda/agda-stdlib#1980]
Related to #759

I am planning to move `zip` and `map` from `Function.Inverse` to `Function.Construct.X`, and I wanted to discuss their new module locations. `Function.Construct` right now includes `Symmetry`, `Identity`, and `Composition`, but I am not sure which of these files should `zip` and `map` be moved to, or if I should create a new file for them.

I also could not entirely understand `zip` and `map`. I do understand the standard `zip` and `map` but could not really understand the definitions in `Function.Inverse`.

Thanks!

**Comment by JacquesCarette** [comment]
The names of `map` and `zip` here are, at best, misleading. There's no real structure to `map` on to. (Well, `map` is a kind of homomorphism, but surely there's a nicer packaging of this.) 

Are these used anywhere?

**Comment by Saransh-cpp** [comment]
They aren't being used anywhere. Should they just be deprecated and removed, instead of moving them somewhere else?

**Comment by JacquesCarette** [comment]
That would be my feeling - but let's see what @MatthewDaggitt says.

**Comment by jamesmckinna** [comment]
We discussed this this morning, but I don't unfortunately recall what our eventual decision was...

**Comment by MatthewDaggitt** [comment]
Yup agreed. These are just weird, and they don't make much sense in the new hierarchy. Just going to leave them without alternatives and see if we get any complaints.
