### ISSUE TITLE
What to do with `Data.Nat` and `Data.Nat.Base`?

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#199]
Now that c5f5fe1 has removed the last misplaced proof, `Data.Nat` is now an empty file. I guess there are two options:

1. Move the entire contents of `Data.Nat.Base` into `Data.Nat`
2. Move the less "basic" content from `Data.Nat.Base` into `Data.Nat`. My suggestion for a list of things to move is:
    - `_<′_` and associated relations
    - `_≤″_` and associated relations
    - `_+⋎_`
    - `⌊_/2⌋` and `⌈_/2⌉`
    - `Ordering` and `compare`

Any thoughts on which it should be?

**Comment by andreasabel** [comment]
In my opinion, 2. would do, but maybe there are more opinions.

**Comment by gallais** [comment]
An alternative is to use `Data.Nat` as a meta-module re-exporting
everything you need to work with Nats à la #153

**Comment by MatthewDaggitt** [comment]
> An alternative is to use Data.Nat as a meta-module re-exporting
everything you need to work with Nats à la #153 

How would we maintain backwards compatibility if we did that?

**Comment by MatthewDaggitt** [comment]
Will probably leave this until v0.16 to decide what to do. `Data.Nat` being empty isn't doing any harm at the moment, it just looks a little odd.

**Comment by MatthewDaggitt** [comment]
@gallais has come up with the suggestion of moving the decidability proofs from `Data.Nat.Base` to `Data.Nat.Properties`, and then  using the currently empty `Data.Nat` module to re-export them publicly from `Data.Nat.Properties`.

The problem with the current location of the decidability proofs is that often require other properties to be lifted to the `Base` file as well. For instance `≤-pred` in `Nat` and `◃-cong` in `Int`. This would neatly get around this problem. It also satisfies my long-standing pet peeve that they're really properties :smile:

Anyone have any thoughts or foresee any problems?

**Comment by JacquesCarette** [comment]
Seems like a good idea to me.

**Comment by MatthewDaggitt** [comment]
Closed with 30ad1312229cab40e2dfc8f95f6af64cd4c92694
