### ISSUE TITLE
CHANGELOG "Other minor changes"

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-stdlib#1990]
This is pushing self-deprecation / undervaluing a little too far. This part of the CHANGELOG is enormous, and full of useful stuff.

Can we find more positive terminology? I know most devs hate marketing and PR, but this is kind of ridiculous!

**Comment by jamesmckinna** [comment]
"Other/Further enrichments"
... "... enhancements"
... ?

**Comment by Taneb** [comment]
For most of them, "New definitions in existing modules" describes the change adequately

**Comment by MatthewDaggitt** [comment]
`Additions in existing modules`?

**Comment by JacquesCarette** [comment]
I don't like 'Other'. Any of "Further enrichments / enhancements", "New definitions in existing modules" or "Additions in existing modules" would be a vast improvement.

**Comment by jamesmckinna** [comment]
'Additions to...', otherwise :+1:
@JacquesCarette can you be assigned this?

**Comment by JacquesCarette** [comment]
Sure - self-assigned now.

**Comment by jamesmckinna** [comment]
Can you knock this off for v2.0?

**Comment by JacquesCarette** [comment]
Depends on the timeline - my start of term has been brutal.

**Comment by jamesmckinna** [comment]
Commiserations!

**Comment by jamesmckinna** [comment]
But is #2094  the occasion to address anything else about `CHANGELOG` that 's easy to fix right now?
