### ISSUE TITLE
Dependencies of `System.Console.ANSI`

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#1993]
When loading `System.Console.ANSI` we're somehow typechecking
the following modules which seems ridiculous:

```agda
Function.HalfAdjointEquivalence
Data.Product.Function.Dependent.Propositional
```

**Comment by JacquesCarette** [comment]
Glad I'm not the only one who thinks that `stdlib` 's dependency graph is quite broken.

@Saransh-cpp you might enjoy trying to see what's going on here?

**Comment by Taneb** [comment]
The best thing to do here would be to replace the use of `Data.Nat.Show.show` in `encode` with building up the string "by hand" (which wouldn't be that much more complicated, frankly, and might actually be simpler)

**Comment by Saransh-cpp** [comment]
On it. Took some time to learn about how modules are structured in `agda`, but yes `agda -i. src/System/Console/ANSI.agda` shows that `Data.Nat.Show` is the culprit here.

I'll try replacing `Data.Nat.Show.show`'s usage such that we don't have to import it (as suggested by @Taneb, thanks!).

**Comment by Saransh-cpp** [comment]
I tried a few things, but I am not sure how to proceed ahead with this -
- Copying `show` and related functions to `ANSI` does work, but I think this won't be the ideal solution?
- Since `(layer l + colour c + intensity i)` is a Natural number, I could simply convert that to a String, but I guess that isn't very straightforward without using the `show` function 😬? I did find a nice [StackOverflow thread](https://stackoverflow.com/questions/22054510/how-to-convert-number-into-string-in-agda) for this, but I think it might be an overkill for this problem.
- Given how limited values `(layer l + colour c + intensity i)` can take, I thought about hardcoding a solution, but would that be too naive?

**Comment by gallais** [comment]
I don't think we should give up on code reuse to reduce the dependency graph:
if `Data.Nat.Show` imports these transitively then we should try to see whether
we can cut the imports down in that module.

**Comment by Saransh-cpp** [comment]
Thanks, @gallais!

Here is the chain of dependencies (for my future self) -

`Data.Product.Function.Dependent.Propositional` imports `Function.HalfAdjointEquivalence` (these 2 should be eliminated; hence, `Data.Product.Function.Dependent.Propositional` must be eliminated)

https://github.com/agda/agda-stdlib/blob/4fe94399710c22da9a0852d9b69514e911288c1a/src/Data/Product/Function/Dependent/Propositional.agda#L19

`Data.List.Relation.Unary.Any.Properties` imports `Data.Product.Function.Dependent.Propositional`

https://github.com/agda/agda-stdlib/blob/4fe94399710c22da9a0852d9b69514e911288c1a/src/Data/List/Relation/Unary/Any/Properties.agda#L33

`Data.List.Membership.Propositional.Properties` imports `Data.List.Relation.Unary.Any.Properties` (uses `map↔`)

https://github.com/agda/agda-stdlib/blob/4fe94399710c22da9a0852d9b69514e911288c1a/src/Data/List/Membership/Propositional/Properties.agda#L17

`Data.List.Extrema` imports `Data.List.Membership.Propositional.Properties` (can maybe eliminate here, check)

https://github.com/agda/agda-stdlib/blob/4fe94399710c22da9a0852d9b69514e911288c1a/src/Data/List/Extrema.agda#L20-L21

`Data.String` imports `Data.List.Extrema` (can maybe eliminate here, check)

https://github.com/agda/agda-stdlib/blob/4fe94399710c22da9a0852d9b69514e911288c1a/src/Data/String.agda#L18

`Data.Nat.Show` imports `Data.String`

https://github.com/agda/agda-stdlib/blob/4fe94399710c22da9a0852d9b69514e911288c1a/src/Data/Nat/Show.agda#L20

`System.Console.ANSI` imports `Data.Nat.Show` (can maybe eliminate here, check)

https://github.com/agda/agda-stdlib/blob/4fe94399710c22da9a0852d9b69514e911288c1a/src/System/Console/ANSI.agda#L13

**Comment by gallais** [comment]
Thanks, this is really helpful. Looking at `Data.Nat.Show`, it seems to me that
replacing the `Data.String` import with a `Data.String.Base` should be sufficient
as we only seem to be using `toList` and `fromList`.

**Comment by Saransh-cpp** [comment]
Nice!! That worked with a minor tweak! Thanks!
