### ISSUE TITLE
[Discussion]: adding more properties for `xor`

### ISSUE THREAD

**Issue by Saransh-cpp** [agda/agda-stdlib#2040]
XRef #2035

Most of the properties for `xor` are actually defined in `Algebra.Lattice.Properties.BooleanAlgebra` -

https://github.com/agda/agda-stdlib/blob/bfa4f8bc41da10bffaf69f5786301e587ae69c83/src/Algebra/Lattice/Properties/BooleanAlgebra.agda#L245-L532

but they look very different from the properties of `and` and `or` defined in `Data.Bool.Properties` . Additionally, `and`, `or`, and `not` have their properties defined both in `Algebra.Lattice.Properties.BooleanAlgebra` and `Data.Bool.Properties`, with overlapping names. For example, see -

https://github.com/agda/agda-stdlib/blob/bfa4f8bc41da10bffaf69f5786301e587ae69c83/src/Algebra/Lattice/Properties/BooleanAlgebra.agda#L54-L104

and -

https://github.com/agda/agda-stdlib/blob/bfa4f8bc41da10bffaf69f5786301e587ae69c83/src/Data/Bool/Properties.agda#L239-L257

https://github.com/agda/agda-stdlib/blob/bfa4f8bc41da10bffaf69f5786301e587ae69c83/src/Data/Bool/Properties.agda#L372-L390

#2035 aims to add more properties for `xor` in `Data.Bool.Properties`, similar to the properties present for `and` and `or`. I'm not sure if these properties should be added in or if the users should just be redirected to the properties defined in `Algebra.Lattice.Properties.BooleanAlgebra`; hence, the discussion. Please let me know if I should work on the PR or if it should be closed.

**Comment by JacquesCarette** [comment]
I'm personally thinking we should define the simple properties of `xor` using simple proofs in `Data.Bool.Properties`, even though that is redundant.

**Comment by jamesmckinna** [comment]
Hmmm... not sure I agree. If `Data.Bool.Properties` ends up having to import from `Algebra.Lattice.*`, then where is the gain from the redundancy? Unless we take a haskell type-class pov, and offer 'optimised' implementations in `Data.Bool.Properties` of a common API, with default implementations under `Algebra.Lattice.*`? 

IIRC/IIUC, there is some of Jacques' proposed redundant recoding in eg `Data.Nat.Properties`, (eg esp. wrt lattice properties) but increasingly that seems to be being refactored away? 

Contra myself, and at the cost of downstream maintenance, we could go for 'redundancy now; refactoring later'? Is that what you were suggesting @JacquesCarette ?
