### ISSUE TITLE
Renaming `Data.Bool.Properties.push-function-into-if`

### ISSUE THREAD

**Issue by jamesmckinna** [agda/agda-stdlib#2046]
Following existing library naming conventions regarding commutation properties, and (perhaps too generously) extending the notion of `map` to the degenerate case of function application, I would be very strongly tempted to rename
```agda
push-function-into-if : ∀ (f : A → B) x {y z} →
                        f (if x then y else z) ≡ (if x then f y else f z)
```
to the simpler, more memorable, `map-if`. Failing that, `apply-if`?

**Comment by JacquesCarette** [comment]
I'm quite happy with `map` being defined over all sorts of containers, but I start hesitating at extending it to computations.

`apply-if` is consistent with a number of other commutation properties. I don't especially like it, but I don't dislike it either.

**Comment by jamesmckinna** [comment]
Do you have other (better?) suggestions?

**Comment by JacquesCarette** [comment]
Unfortunately, I do not. We need a bigger pool of active participants on these discussions!

**Comment by Taneb** [comment]
I don't have any coherent reason for this but it feels `cong`-y to me

**Comment by jamesmckinna** [comment]
Ah! (re: `cong`-like behaviour): `if-cong`, then , or `cong-if`?

Regarding my invocation of `map`... for the record, I had been viewing function application as the degenerate instance of `map` for the `Identity` functor, and then... took it from there...

**Comment by gallais** [comment]
`cong` would be confusing as it's not the same head-symbol on both sides.
Feels more like a compiler optimisation type move.

Using the names from [Compiling without Continuation](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/11/compiling-without-continuations.pdf), it would be an `if-float`.

**Comment by jamesmckinna** [comment]
Hmmm... choices, choices! Do we use 
* `*-float` anywhere else in the library? (er, apparently not)
* `apply-*`? ditto. 

I suspect the original author of the function was similarly stuck for a good choice of name... so whatever we do here then sets a precedent?

**Comment by jamesmckinna** [comment]
I'd go for `-float` over `-context`... too much baggage associated with this last one?
