### ISSUE TITLE
monadic `join`

### ISSUE THREAD

**Issue by jamesmckinna** [agda/agda-stdlib#2065]
Apologies if I have missed something down the years, but why does `Effect.Monad.RawMonad` not also define monadic join
```agda
μ : F (F A) → F A
μ = _>>= id
```
(also: `join` or `μ` as preferred identifier for this?)

**Comment by gallais** [comment]
Remember that the functor is not necessarily an endofunctor level-wise:
`(F : Set f → Set g)`
We can only have `join` if `f = g`.

**Comment by jamesmckinna** [comment]
Oh dear... I see. And would `g ≤ f` work also?
But I suppose we could define `RawMonadWithJoin` for the special case...?

**Comment by jamesmckinna** [comment]
Revised design at #2079... via a `module` parametrised on a suitable instance of `RawMonad` ...

**Comment by jamesmckinna** [comment]
[Moved from the discussion of PR#2079]
> Do we need a whole new record or is it sufficient to have a module parametrised by a monad and deriving join from bind?

Good question! ... you're probably right, something along the lines of : in module `Effect.Monad`
```agda
module Join {F : Set f → Set f} {{M : RawMonad F}} where
  join : F (F A) → F A
  join = _>>= id where open RawMonad M
```
... and then for downstream `RawMonad` instances `monad`:
```agda
join = Join.join where instance _ = monad
```
