### ISSUE TITLE
 ×-wellFounded' without symmetry of  _≈₁_

### ISSUE THREAD

**Issue by jwaldmann** [agda/agda-stdlib#2075]
Hi. 

I needed a version of ×-wellFounded' from https://agda.github.io/agda-stdlib/Data.Product.Relation.Binary.Lex.Strict.html#6946 that does not have the symmetry requirement on _≈₁_ . Transitivity is enough to get the theorem, and I don't have symmetry in my application (relative termination). 

So I cobbled together this version of the code: https://gitlab.imn.htwk-leipzig.de/waldmann/pure-matchbox/-/blob/d75cbfd1bb364a2e2b48ff7af2ba75be35e0b1b4/cert/R.agda#L208  (application: see end of that file).

I'm sure my code looks terrible (as I am learning the language as I go along) but perhaps you can use it somehow (or tell me how to rewrite it so that you can use it).

**Comment by jamesmckinna** [comment]
Johannes, Thanks for drawing attention to this! 

It seems like a clear win, to be able to simplify a theorem/proof in the library.
(Modulo the pain associated with deprecating the old proof in favour of the new, to avoid non-backwards -compatible breaking changes... which might require some discussion/negotiation)

It would be great if you were to submit it as a PR (see `HACKING.md`), but if you're learning Agda as you go, that might be too much to ask for. 

If you're not confident about doing so, though,  then I'll see what I can do.

**Comment by jamesmckinna** [comment]
And: your code doesn't look "terrible"!

**Comment by jamesmckinna** [comment]
@jwaldmann  Suggest that you look at the PR #2077 I just opened,and see if it does what you want (it's the bare bones for the time being). Other improvements might be possible, but let's start with this?
As you will see,I took the liberty of renaming your `weak` lemma on `Acc`essibility in `Induction.WellFounded`, but otherwise, it's your code (and its various consequences, for eg `Data.Vec.Relation.Binary.Lex.Strict`)...

**Comment by Seiryn21** [comment]
Aahh, Acc-resp-weak-≈  is nice, sorry i didn't thought about it when writing this proof.

**Comment by jamesmckinna** [comment]
No problem! We advance slowly, and can only see further by standing on one another's shoulders... giants or not!

**Comment by jamesmckinna** [comment]
For the rest of your associated development, @jwaldmann you may wish to also see `Relation.Binary.Rewriting` in the library since commit [e86b564](https://github.com/agda/agda-stdlib/commit/e86b56443b68df7d79d440f2c804adaa5ff14820) (2019-04-29)

**Comment by MatthewDaggitt** [comment]
Fixed by #2077
