### ISSUE TITLE
Increase universe polymorphism for _⟨⊎⟩_ in Relation.Unary

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#208]

**Comment by gallais** [comment]
I had a look at it and it looks to me like this is not possible without introducing
some `Lift`s. Which we shouldn't do (in the case where `ℓ₁` equals `ℓ₂`, that'd
add some noise).

**Comment by MatthewDaggitt** [comment]
Hmm, yes I think you're right. Didn't realise that it would require lifts. 

I think the datatype definition would confuse people... especially the shadowing of the names `inj₁` and `inj₂`. Probably best to leave as is.
