### ISSUE TITLE
Definition of `Induction.WellFounded.WfRec`

### ISSUE THREAD

**Issue by jamesmckinna** [agda/agda-stdlib#2083]
Currently, the definition:
```agda
WfRec : Rel A r → ∀ {ℓ} → RecStruct A ℓ _
WfRec _<_ P x = ∀ y → y < x → P y
```
suffers from two (unfortunate) defects:
* the use of the name `RecStruct`, when this type is nothing more or less than that of `PredicateTransformer` (or: what you will...) which only really takes on the role of being a structure-for-recursion once a given such `T : PredicateTransformer`  is accompanied by a *proof* that `T P ⊆′ P` for suitable `P`...;
* the *explicit* quantification over `y` in `WfRec`, which leads, infectively, to a profusion of (almost-?)always-inferrable arguments when working with subsequent `Acc`essibility and `WellFounded`ness proofs. ADDRESSED by #2084 

The first of these is, indeed, unfortunate but ignorable.

The second is, frankly, a complete pain, but likewise (almost) completely avoidable. 

PROPOSAL: to make the *breaking* change for v2.0 that the definition be changed to:
```agda
WfRec _<_ P x = ∀ {y} → y < x → P y
```
together with all of its downstream consequences... including the in-progress #2077 #2082 etc.

**Comment by jamesmckinna** [comment]
A separate issue exposed by this proposal: in `Data.Vec.Relation.Binary.Lex.Strict`, the following lemma proposed in #602 and added in #1648 and its immediate corollary
```agda
  xs≮[] : ∀ {n} (xs : Vec A n) → ¬ xs < []
  xs≮[] _ (base ())

  ¬[]<[] : ¬ [] < []
  ¬[]<[] = xs≮[] []
```
should, likewise, make the `xs` argument implicit.

**Comment by JacquesCarette** [comment]
Both of these explicit proposals make sense to me.

**Comment by MatthewDaggitt** [comment]
> the explicit quantification over y in WfRec, which leads, infectively, to a profusion of (almost-?)always-inferrable arguments when working with subsequent Accessibility and WellFoundedness proofs. FIXED by https://github.com/agda/agda-stdlib/pull/2084

I'm not sure I agree with this. What happens when `A` is a record type and `<` is a strict _partial_ order over it that only inspects some of the fields? Then you're not going to be able to infer the values of the missing fields right?

**Comment by jamesmckinna** [comment]
Well, actually, the `...flip...` proof introduced in #2077 is an example of the phenomenon, and was handled there by deploying 2/8 instances where an implicit argument needed to be supplied. Compared to nearly 90 others in stdlib which justify the 'almost-always-inferrable' claim... so it is a trade-off, to be sure. But your corner case is/seems 'rare' in practice. 

'In the wild'... I'm not sure.

**Comment by jamesmckinna** [comment]
So, I have been thinking/trying to think through the substance of @MatthewDaggitt 's critique, and I think there is something I don't understand about his thought experiment: suppose we do define a strict partial order on a record based only on some of its fields. Then, in any subsequent `wfRec` definition wrt such an ordering, aren't we *really* defining a recursion on the *derived* notion of `WF` for that record type obtained via `Relation.Binary.Construct.On.wellFounded`?

That is to say, there should be no consideration of trying to *reconstruct* any fields: the relevant wellfoundedness obtains by projection, and hence the relevant recursion/recursor only need focus on the fileds of the *projected* record... Or am I (still) missing something here?

**Comment by MatthewDaggitt** [comment]
> That is to say, (I think that) there should be no consideration of trying to reconstruct any fields at all: the relevant wellfoundedness obtains by projection, and hence the relevant recursion/recursor only need focus on the fields of the projected record... Or am I (still) missing something here?

Agreed that's what should be going on! But my question was really is Agda smart enough to realise that it doesn't need to re-infer the "irrelevant" information. The fact that it goes through the library fine, suggests that it is in most cases...

**Comment by jamesmckinna** [comment]
I'm crossing my fingers! 
But non-existence of counterexamples does not constitute proof, alas, only suggestive anecdotal evidence towards the conjecture!
