### ISSUE TITLE
Generated Agda standard library HTML has no version information

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#2086]
@jwaldmann writes

> NB - I found it (mildly) confusing that there is no version information (in the url) at
https://agda.github.io/agda-stdlib/Data.Product.Relation.Binary.Lex.Strict.html

I wonder how we can add version information to the generated HTML? Ideally we don't really want the URL to change every time we make a release as that would make linking a nightmare....

**Comment by gallais** [comment]
Well we already have

* http://agda.github.io/agda-stdlib/experimental/Data.Product.Relation.Binary.Lex.Strict.html

so we could have

* http://agda.github.io/agda-stdlib/main/Data.Product.Relation.Binary.Lex.Strict.html

under the same logic. It would be good to also get back to uploading the stable versions like we did for a while (e.g. [v0.17](http://agda.github.io/agda-stdlib/v0.17/))
