### ISSUE TITLE
Give consistent names to transitivity between strict and non-strict orders

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#2087]
e.g. sometimes in `Data.Integer.Properties` its `≤-<-trans` and in `Data.Nat.Properties` its `<-transʳ`.

**Comment by jamesmckinna** [comment]
The `Integer` version of the name seems preferable? This may simply be my aversion to primed names, but I think usefully is also more self-documenting. 

But perhaps better would be in `Relation.Binary.Definitions` to define left- and right- closure of one relation `R` by another `S`, with the two lemmas at hand being instances of such concepts...?

**Comment by MatthewDaggitt** [comment]
> But perhaps better would be in Relation.Binary.Definitions to define left- and right- closure of one relation R by another S, with the two lemmas at hand being instances of such concepts...?

The problem is that the non-strict/strict numeric orders (for various good reasons) aren't usually defined as the closure of one another....

**Comment by MatthewDaggitt** [comment]
But I agree with your assessment that the first name is better!

**Comment by jamesmckinna** [comment]
Apologies for potential confusion arising from my
> ...left- and right- closure of one relation `R` by another `S`...
when what I had intended was the property of `R` being *closed* (under relational composition) on the left/right by `S` ie `Trans S R R` and `Trans R S R` and wanting to name those, say, `Transˡ R S` and `Transʳ R S`... which might in fact suggest the names we should standardise on should be a hybrid of each existing solution, viz. make those definitions and then name the lemmas `≤-<-transʳ` etc.?

**Comment by MatthewDaggitt** [comment]
Ah right, sorry misunderstood! Hmm so we spell out `Left` and `Right` in types in full, so it would have to be something like `LeftTransitive` and `RightTransitive`, but yes I'm on board!

**Comment by jamesmckinna** [comment]
Will assign myself... later. I've been doing too much here recently!

**Comment by jamesmckinna** [comment]
Oh... it seems better to put the relation symbols in suitable left-right order in the name, than actually use the superscripts, because the directions flip over! PR on way...
