### ISSUE TITLE
`Relation.Binary.Bundles.Preorder` declares the 'wrong' symbol for the ordering relation!!!

### ISSUE THREAD

**Issue by jamesmckinna** [agda/agda-stdlib#2096]
`Preorder`s are rarely `Symmetric`, unless they arise already from instances of `Setoid`/`IsEquivalence`.

So... why in the name of all that is holy do we declare them with a field name `_∼_` which is (notationally/syntactically/formally) *symmetric*. 

Consequences: 
* the converse (treated in `Relation.Binary.Properties.Preorder`) can't have a 'flipped' notation, so we have to make do with the (semantically) `flip`ped definition of the converse relation;
* the (underlying relation of the) converse of a `Poset` is declared in `Relation.Binary.Properties.Poset`, when that could simply be a renaming of the converse from `Relation.Binary.Properties.Preorder`, were that to be able to have a notation (*qua* definition, or else as `syntax` declaration);
* my head exploded while working on #1214 / #2095 as a result...

Refactoring PROPOSAL: that we rename (and appropriately deprecate, groan) the infix symbol/definition `_∼_` to be `_≲_`, which becomes `_≤_` in `Poset`, etc... and whose `Relation.Binary.Properties.Preorder.InducedEquivalence` be given by @laMudri 's `Relation.Binary.Construct.Interior.Symmetric` from #2071 applied to `_≲_`...

Just sayin'.

**Comment by laMudri** [comment]
I agree that `_∼_` is a bad name and plain old `_≤_` would be much better. Unfortunately, I think this is inevitably a breaking change because of all the `record { _∼_ = Leq }`-like code which exists. At least the error message you get out of that should be somewhat instructive.

**Comment by Taneb** [comment]
I agree that it's a breaking change. And I think that means if this is something we want to do, we ought to do it _now_. We're not going to have another major version increment any time soon

**Comment by jamesmckinna** [comment]
Two/three things to say to this:
* yes, as a major breaking change, I think it's important to do it sooner rather than later (thanks @Taneb !);
* I'm nearly done with the corresponding one for negated symbols, #2095 which exposed to me the larger problem concerning `flip`ped symbols as a whole; out of sheer rage last night I started work on it, but rolled back before I went completely berserk, but a follow-up PR in the spirit of my current one would be... very desirable I think ;-)
* regarding symbols, actually I think that there *is* value in distinguishing between the `Preorder` version of the symbol and the `Poset` version (and that there should be a third one by convention used for your `Proset`s @laMudri , I think, even if they never actually get materialised as `Bundle` in their own right...), and chose, somewhat arbitrarily, the one above. But it's a small(er) hill on which to die... perhaps.

**Comment by jamesmckinna** [comment]
Aaaargh... this may be worse than I haoped/thought/feared. Some great subtleties to do with renaming symbols in the signature of the `module` of a `record`, without being able to rename the corresponding defined field/method in a record in the record signature... as a result of which, `export`ed sub-derived records retain the old definition name, even though they can be renamed on `open`ing *qua* `module`s... blimey!

**Comment by JacquesCarette** [comment]
Agree with changing to `_≲_` now.

**Comment by jamesmckinna** [comment]
Closing this now after merge of #2114 . But NB discussion above about deprecation!
