### ISSUE TITLE
StrictTotalOrder  for Integer  and others

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#21]
I have a code for StrictTotalOrder  for Integer  and some others items
-- to propose as an addition to Standard library.   (the modules  Nat1 and Integer1).
But how to attach here  the  .zip file?

**Comment by MatthewDaggitt** [comment]
I'm in the process of merging your work in on PR #146. Would you like to be added to the list of contributors in `README.agda`? If so under what name?

**Comment by mechvel** [comment]
On Wed, 2017-06-28 at 09:40 -0700, MatthewDaggitt wrote:
> I'm in the process of merging your work in on PR #146. Would you like
> to be added to the list of contributors in README.agda? If so under
> what name?


Yes. Under the name of  Sergei Meshveliani.

**Comment by MatthewDaggitt** [comment]
Finished adding the proofs in f6b4b52
