### ISSUE TITLE
Regression in positivity checker

### ISSUE THREAD

**Issue by sstucki** [agda/agda-stdlib#210]
Agda rejects the definition of `TernRel` below with the following error message:

    TernRel is not strictly positive, because it occurs
    in the first argument to N.UniRel
    in the first clause
    in the definition of UniRel, which occurs
    in the type of the constructor c
    in the definition of TernRel.

This used to work in earlier versions of Agda (at least up to version 2.5.1.2). I spotted the regression first in 2.5.3 but it seems to still be present in 2.6.0.

```agda
module _ where

data D : Set where
  dummy : D

module M (R : D → D → Set) where
  data UniRel : D → Set where
    c : ∀ m n → R m n → UniRel m

module N (R : D → D → D → Set) where
  data BinRel : D → D → Set where
    d : ∀ m n k → R m n k → BinRel m n

  open M BinRel public

-- Error: TernRel is not strictly positive, ...
mutual
  UniRel : D → Set
  UniRel m = N.UniRel TernRel m

  data TernRel (m : D) : D → D → Set where
    c : ∀ n k → UniRel m → TernRel m n k

-- The example is accepted if we manually inline the definition of
-- module M into N instead of just importing M in N.

module MN (R : D → D → D → Set) where
  data BinRel′ : D → D → Set where
    d : ∀ m n k → R m n k → BinRel′ m n

  data UniRel′ : D → Set where
    c : ∀ m n → BinRel′ m n → UniRel′ m

mutual
  UniRel′ : D → Set
  UniRel′ m = MN.UniRel′ TernRel′ m

  data TernRel′ (m : D) : D → D → Set where
    c : ∀ n k → UniRel′ m → TernRel′ m n k
```
It's unclear to me why the indirection through two modules `M` and `N` causes an error, while the definition going through just `MN` does not.

**Comment by MatthewDaggitt** [comment]
I think you meant to open this on the main Agda repo?

**Comment by sstucki** [comment]
Whoops, yes sorry :-)
