### ISSUE TITLE
*Top-level* Record definitions need accompanying type signatures

### ISSUE THREAD

**Issue by jamesmckinna** [agda/agda-stdlib#2112]
Working on #2111 exposes a previously uncaught error: under `Data.Tree.AVL`, a number of modules (attempt to) declare 'local' instances of `StrictTotalOrder` *without declaring a suitable type signature for them*, which worked perfectly fine *as long as this record type was a leaf in the `Algebra.Bundles` hierarchy*...

... but adding `(Is)DenseLinearOrder` as a sub(structure)/bundle of `(Is)StrictTotalOrder` has now broken that. 

Remedy: identify all `record` definitions without a type signature, and supply it appropriately. 
UPDATED: issue only applies to *top-level* definitions; within the scope of an enclosing record, the type of the field being defined as a sub-record ensures that a suitable type is being supplied to the typechecker. 
UPDATED: I've attempted to identify any other instances in the library, but it seems just to have been these 'historical' examples. Suggest closing the issue now/for the time being.

**Comment by MatthewDaggitt** [comment]
Ooh interesting. Haven't come across that sort of bug before!

**Comment by jamesmckinna** [comment]
So the bug expressed itself in terms of unsolved `Level` meta variables... my diagnosis in terms of leaves in the hierarchy is post hoc inference, and there may be other possibilities, but inserting the type deck certainly solves/d the instances that came up. 

And yes, a weird one!
