### ISSUE TITLE
'Wrong' symbol for negated equality in `Data.Rational.Unnormalised.*`

### ISSUE THREAD

**Issue by jamesmckinna** [agda/agda-stdlib#2114]
The `Base` module introduces an ad hoc notation `_≠_` for the negated equality in the setoid `(ℚᵘ, _≃_)` .
But there is now no reason to:
* the Unicode symbol `_≄_` achieved via `\~-n`  is (now available as) the 'correct' negation-correlated version of  `_≃_`/`\~-`
* issues #1214 and #2096 and their associated PRs #2095 #2096 #2098 are aimed at rationalising the notation systems for all the negated/transposed equality/ordering symbols, so there's no need for an anomaly like this to persist.

**Comment by MatthewDaggitt** [comment]
So you'd propose to deprecate it in favour of `_≄_`?

**Comment by jamesmckinna** [comment]
Yes, I think so. It perhaps falls under a `bikeshedding` label, if we had one, but it seems like an avoidable wart in the 'fresh start' that (I think?) we want v2.0 to be... what's your view?

**Comment by JacquesCarette** [comment]
This seems quite sensible - using disparate symbols is confusing.

**Comment by jamesmckinna** [comment]
So there is a tension here (for me) between the 'formalistic' choice (take the formally negated symbol), and the 'semantic' choice (the negated equality is, in fact, a tight apartness relation, so that the rationals form a `HeytingField`, so a suitable choice would be `_#_` for an apartness relation). For me, formal beats semantic, but in the interests of discussion...

**Comment by JacquesCarette** [comment]
Hmm, wouldn't proving that it is a tight apartness relation satisfy the semanticist in you? i.e. you first name the concept with the 'obvious' name, and then show that it has quite a bit more structure than naively expected. So then if you want to use it as an apartness relation, you can do it via using the `HeytingField` bundle, thus regaining the 'right' name?

**Comment by jamesmckinna** [comment]
(I think so, but all those various parts of me are at present exploding in all directions...)

**Comment by jamesmckinna** [comment]
And, regarding the deprecation, I think that the symbol should arise by suitably renaming the default negated-equality introduced by `Setoid`... but perhaps those dependencies don't quite cash out the way I might hope?
