### ISSUE TITLE
Un-deprecating `inspect`, ctd.

### ISSUE THREAD

**Issue by jamesmckinna** [agda/agda-stdlib#2127]
Aaaargh! two/three bugs have crept into `master` after #1930, #2107:
- [x] `README.Inspect` no longer typechecks, because the `import` of `PropositionalEquality` fails to include the constructor name `[_]`; FIXED by #2128 
- [x] `README` no longer refers to `README.Inspect`, so the first bug goes un-noticed; PUSHED commit.
- [x] `README.Inspect` is marked as `DEPRECATED`; PUSHED commit.

The first should be fixed (my fault, I think, arising from #1930).
The second and third are, perhaps, moot, but should perhaps be reverted?

**Comment by MatthewDaggitt** [comment]
Yes the last two should be reverted :+1:
