### ISSUE TITLE
Add `IdempotentMonoid` and `CommutativeBand`

### ISSUE THREAD

**Issue by Taneb** [agda/agda-stdlib#2138]
These feel fairly obvious omissions to the algebra hierarchy.

A commutative band is the same thing as a semilattice but I think it's worth duplicating

Example of a commutative band that is not an idempotent commutative monoid: minimum on naturals

Example of an idempotent monoid that is not an idempotent commtuative monoid: first non-nothing element on `Maybe`

**Comment by jamesmckinna** [comment]
v2.1, as per our current cutoff policy?

**Comment by Taneb** [comment]
I don't think there's any backwards compatibility issues here so I'm fine with that

**Comment by jamesmckinna** [comment]
Also: ['tropical' semiring(s)](https://en.wikipedia.org/wiki/Tropical_semiring)?

**Comment by Taneb** [comment]
I think from skimming the page you linked, that that's a particular idempotent semiring, which we already have in Algebra

**Comment by MatthewDaggitt** [comment]
Indeed, it's my favourite idempotent semiring :smile:

**Comment by jamesmckinna** [comment]
Well, shortest-path routing... I guess it would be!?
