### ISSUE TITLE
Flipping equality in Relation.Binary.Flip

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#214]
In the proof `isPreorder` in `Relation.Binary.Flip` it not only flips the relation, but also the underlying equality. Surely this is a bug, not a feature? It means that I can't use it to flip my `DecTotalOrder` as the result is not parametrised over the same equality relation....

Anyone have any convincing reasons why it *should* flip equality? If not then I'd like to change it...

**Comment by andreasabel** [comment]
Here: https://github.com/agda/agda-stdlib/blob/29605d1e02badff284b589bf673c28c83f32fa70/src/Relation/Binary/Flip.agda#L79

I don't know, I have not used it.  Extensionally, flipping the underlying equality is a no-op, but of course, intensionally it is relevant.  Maybe you could search on the Agda list for users of `Flip` and whether they have an opinion.

**Comment by MatthewDaggitt** [comment]
Hmm okay so I guess the best solution is just to support both. There are two options here, both of which I'm struggling with naming for:
- Within `Relation.Binary.Flip` have both a flipped and unflipped version for every proof that involves equality. Any ideas for naming? The best I can do is `antisymᶠ` and `antisymᵘ` for `flipped` and `unflipped`, which isn't very clear at all.
- Have two separate modules, one for flipped and one for unflipped. The advantage of this is that the names within each module would be inline with the rest of the library. Unfortunately I don't have snappy names for the two modules either.

Anyone have any ideas?

**Comment by MatthewDaggitt** [comment]
Closed with 9cad6c2
