### ISSUE TITLE
Rename preorder reasoning syntax

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#2145]
https://github.com/agda/agda-stdlib/pull/2099 didn't change the name of the reasoning combinators in `Relation.Binary.Reasoning.Preorder`

**Comment by jamesmckinna** [comment]
I see you've self-assigned; probably quicker if you do it, but let me know if you'd rather someone else... but not entirely clear how it interacts/would interact with your design for #2146 ?

**Comment by MatthewDaggitt** [comment]
> but not entirely clear how it interacts/would interact with your design for https://github.com/agda/agda-stdlib/issues/2146 ?

Will fix this issue once the redesign has been merged in.

**Comment by MatthewDaggitt** [comment]
Also missed was `Preorder.∼-respˡ-≈` and friends.

**Comment by jamesmckinna** [comment]
Did you ever figure out an asnwer to my query about (failure of the) deprecation warning https://github.com/agda/agda-stdlib/pull/2099#issuecomment-1750146579 in `Relation.Unary.Closure.Preorder`?

**Comment by MatthewDaggitt** [comment]
Ah sorry, missed that comment. Yes it's an instance of https://github.com/agda/agda/issues/5617

**Comment by jamesmckinna** [comment]
Still, annoying-but-still-safe is an OK status quo, for the time being at least.
