### ISSUE TITLE
Discrepancies in Data.Nat.Divisibility

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#215]
The use of the characters '|' ([1] typed `|`) and '∣' ([2] typed `\|`) in `Data.Nat.Divisibility` is really confusing.

* `n|m*n` uses [1]
* `n∣n` uses [2]
* `∣m+n|m⇒|n` mixes both!

I'd be in favour of using [2] everywhere. It is, after all, the unicode character
precisely for divisibility, and the symbol used for the property (and can't be
changed: `VERTICAL LINE` would clash with notations for `with`-abstractions).

[1]
> name: VERTICAL LINE
  old-name: VERTICAL BAR
  general-category: Sm (Symbol, Math)
  decomposition: (124) ('|')

[2]

> name: DIVIDES
  general-category: Sm (Symbol, Math)
  decomposition: (8739) ('∣')

**Comment by MatthewDaggitt** [comment]
Good spot. I'll alter it to [2].

**Comment by MatthewDaggitt** [comment]
Closed with c3aadb8

**Comment by gallais** [comment]
Thanks!
