### ISSUE TITLE
Bug in re-exporting `_∷=_` and `_─_` from `Data.List.Membership.Setoid`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#2153]
Looking back through my huge backlog of standard library related emails, I found this comment by @gallais earlier this year

https://github.com/agda/agda-stdlib/commit/abbd3e7371d87d2141d23080a67bf8b8483030a9#r108952994

I assume this bug is still active.

**Comment by jamesmckinna** [comment]
A pity we didn't catch this during work on #2049 , but perhaps that offers a way out via `remove` etc.?
