### ISSUE TITLE
Problems with change of `Semilattice` operation name

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#2166]
First issue with RC 1. Changelog doesn't mention that the name of the operation in `Semilattice` changed from `_∧_` to `_∙_`.

More problematically the names in `IsSemilattice` have not been changed :cry: 

https://github.com/agda/agda-stdlib/blob/a7d23029ac94ba446d2cf2a6f4bf3859d7aa9506/src/Algebra/Lattice/Structures.agda#L39

**Comment by Taneb** [comment]
I'd like to address this more aggressively, by tying it with #2138 and removing the undirected `IsLattice` etc structures entirely.

**Comment by jamesmckinna** [comment]
Don't remove: deprecate!

**Comment by jamesmckinna** [comment]
@Taneb Any progress on this issue/PR?

**Comment by jamesmckinna** [comment]
Cf. #2178 what is the operator symbol supposed to be here?
I'm starting to wonder/panic whether that PR actually did the right thing?

**Comment by MatthewDaggitt** [comment]
Should be the dot symbol. In the interests of getting the next RC out the door I'm taking this one over.

**Comment by Taneb** [comment]
Sorry, I've been sick lately. I'm only just getting enough brainpower back to write Agda now

**Comment by MatthewDaggitt** [comment]
No worries, I hope you have a swift recovery!

**Comment by jamesmckinna** [comment]
Get well soon! I've approved Matthew's PR in the interim.
