### ISSUE TITLE
Upgrade of `filter` and `partition`: CHANGELOG typo?

### ISSUE THREAD

**Issue by asr** [agda/agda-stdlib#217]
In relation to the upgrade of `filter` and `partition` in `Data.List` the CHANGELOG says:

> The old versions can be implemented via the new versions with the predicate `λ v → f v ≡ true`.

Shouldn't  `_≟_` (or better, `Bool.≟`) be the relation used instead of `_≡_`?

**Comment by MatthewDaggitt** [comment]
Ah yes, you're right, poor wording on my part. The predicate **would be** `λ v → f v ≡ true`, but the proof that it's decidable would be `λ v → f v Bool.≟ true`. I'll update the wording...

**Comment by MatthewDaggitt** [comment]
Fixed in c3213cf
