### ISSUE TITLE
Typos in documentation/`README`/`README.*`

### ISSUE THREAD

**Issue by jamesmckinna** [agda/agda-stdlib#2175]
#2176 fixes:
- [x] `README`: Agda version number should be 2.6.4

See branch [documentation](https://github.com/jamesmckinna/agda-stdlib/tree/documentation) where I'm collecting these towards an eventual PR for rc1/rc2...:
- [x] `README`: Missing comma L10 at "Bradley Hardy Joachim Breitner,"
- [x] `Relation.Nullary.Decidable.Core`: corrected reference to `README.Design.Decidability`
- [x] `installation-guide` (thanks @Saransh-cpp !)
- [x] instance arguments discussion in `CHANGELOG`
- [ ] ...
- [ ] documenting the 'how to typecheck `README.agda` question/problem... UPDATED: now going to be handled in a separate PR by @gallais 

Now leaving this issue open, to accumulate any of the other documentation things we might find...?

**Comment by Saransh-cpp** [comment]
minor thing: [installation guide](https://github.com/agda/agda-stdlib/blob/master/notes/installation-guide.md) can be updated for v2.0 in the documentation branch (can also be updated for v1.7.3 in master, but v1.7.3 is already out)
