### ISSUE TITLE
lib-2.0-rc1: NonZero complication  

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#2177]
Using NonZero instead of  ``_≉ 0#`` complicates programming in Agda.
Having 
```
lemma :  ∀ {n} → n ≢ 0 → suc (pred n) ≡ n
```
I implemented it under   lib-1.7.3  as 
```
lemma n≢0 =  suc[pred[n]]≡n n≢0  
```
With a nicer standard denotation, it would  be   ``suc-pred n≢0``
And under   lib-2.0-rc1,  it is   `` suc-pred n ⦃ ≢-nonZero n≢0 ⦄``,
with strange parentheses, with studying instance search matters, with learning of how to set instances for other domains.
For example, division in Field:
```
div : (x y : Carrier) (y ≉ 0#) → Carrier
```
I have experience with this thing also with division with remainder in `EuclideanDomain`, with its  condition ``(divisor ≉ 0#)``.
My impression, is that it is simpler to use  ``NonZero = _≉ 0#``,
even though it is sometimes needed to prove (or set as axiom) irrelevance on the proof for   ``y ≉ 0#``
(but lib-2.0-rc1 also deals with irrelevance by setting the point denotation in NonZero,
 and  one can also  set the point denotation    ``(.nzy :  y ≉ 0#)``  
 I do not know of what will be the consequences).
And there are many functions which signature includes  things like  ``x  ∤ 1#``  (does not divide unity), so that the result depends on the proof.
Мy impression is that  ``NonZero = _≉ 0#`` is simpler for the further design.
Your discussion on NonZero was frightening me during years. And now it comes.

**Comment by MatthewDaggitt** [comment]
@mechvel this discussion does not contain a question or a suggestion.

If you would like help with adapting your code to the new `NonZero` predicate, then please post your code on the [Agda Zulip](https://agda.zulipchat.com/) and I'm sure people will be willing to help you.

**Comment by jamesmckinna** [comment]
Please also see the careful treatment of these matters (and justification for the eventual design and implementation decisions) in the v2.0-rc1 `CHANGELOG` (L507 et seq.)

**Comment by MatthewDaggitt** [comment]
Closing as no question or solution has been proposed. Feel free to re-open @mechvel if you have a specific question. Otherwise I would encourage you to ask on the Zulip channel.
