### ISSUE TITLE
Consistent use of symbol `•`: in `•-cong  : Congruent₂ _•_` in `Algebra.Consequences.Setoid`

### ISSUE THREAD

**Issue by jamesmckinna** [agda/agda-stdlib#2178]
Is this the *same* symbol as discussed in #1544 ? If not, why not? And do we need to fix this? 

Anywhere else that we might have 'identical' renderings of distinct symbols? cf #1544 on the potential for confusion...

**Comment by MatthewDaggitt** [comment]
Add entry to style guide describing how to type, and make one illegal.

**Comment by jamesmckinna** [comment]
Hmmm... it's not (all) quote what I previously believed/thought:
* `Algebra.Consequences.Setoid` *does* in fact seem to be internally consistent;
* but `Algebra.Morphism.Consequences` uses a different (but visually identical) symbol
* the `\.` of `\.-cong` fame, and #2166 , appears to be neither here nor there, it's 'just another different symbol'

So the question is/becomes: do/should we attempt to reconcile the symbols in the first two cases?

**Comment by MatthewDaggitt** [comment]
@jwaldmann , I closed this because the confusion complained about in this particular issue was closed by a PR. If you would like to open an issue to talk about more confusing instances or indeed general approaches to reducing confusion in general, then please do!

**Comment by jamesmckinna** [comment]
And as the "temporarily confused library developer" concerned, this issue/PR falls under "tidying up inconsistencies before a major release", where such inconsistencies inevitably arise over the course of the evolution of a large, long-lived, collaborative software project where not all such potential sources of inconsistency have been codified in a design, or style, document. 

So to echo @MatthewDaggitt , please do file issue(s) if you are aware of other sources of inconsistency, or conventions you think it would be worth documenting or codifying...
