### ISSUE TITLE
Broken link to installation instructions

### ISSUE THREAD

**Issue by patrick-nicodemus** [agda/agda-stdlib#2196]
The readme links to the installation instructions but the link is broken.

Note also here - https://agda.readthedocs.io/en/latest/getting-started/a-taste-of-agda.html
"Make sure that you installed agda and a compatible version of the standard library"
This link is also broken.

**Comment by jamesmckinna** [comment]
In lieu of an immediate PR to the main `agda` documentration:
The [former link](https://github.com/agda/agda-stdlib/blob/master/notes/installation-guide.md) was broken by PR #2184 fixing issue #1743 and needs updating to: https://github.com/agda/agda-stdlib/blob/master/doc/installation-guide.md
