### ISSUE TITLE
`⊥` is `Recomputable`

### ISSUE THREAD

**Issue by jamesmckinna** [agda/agda-stdlib#2199]
The current definition of `Data.Empty`, and its derivative sub-module `Data.Empty.Irrelevant` are the basis of the current (re-)definition of `Relation.Nullary.Negation` and ... everything else involving `⊥` and negation `¬ A` etc. 

What's at present missing, and responsible for the artificial distinction between 
* `Data.Empty.Irrelevant.⊥-elim : ∀ {w} {Whatever : Set w} → .⊥ → Whatever`
* `Data.Empty.⊥-elim : ∀ {w} {Whatever : Set w} → ⊥ → Whatever`
 
is the equivalence of `.⊥` and `⊥`... ie that `⊥` is `Recomputable`.

NB `Recomputable` seems to be the modern-dress version of the very old idea that certain types (negated formulae, among others) have no computational content, that is, we can't make essential use (eg by pattern-matching) of their inhabitants in order to define/prove... other things. 

Well, the use of pattern-matching against the empty pattern `()` ensures that `⊥` itself is `Recomputable`:
```agda
Recomputable : ∀ {a} (A : Set a) → Set a
Recomputable A = .A → A

-- ⊥ is Recomputable

⊥-recompute : Recomputable ⊥
⊥-recompute ()
```
... and this is already provable in the current formulation of the library... and hence that the above two elimination principles are interderivable (so: do we need both, or does one suffice? UPDATED: does the asymmetry in the use of irrelevant marks in types between assumptions and conclusions mean that this cannot precisely be the case?). See [branch](https://github.com/jamesmckinna/agda-stdlib/tree/recomputable-empty), with no (seemingly!?) wider knock-on consequences for the rest of the library. 

So: we should reconcile these things, and their many consequences; esp. wrt proving `Recomputable` for all kinds of types, notably product types (below), negated types, decidable types, ... in general at least (conjecture!?) the (hereditarily) *Harrop formulas*, and more generally, any 'Glivenko class' of formulas (ditto.). 

Question/Issue: Why haven't we done this before/already? cf. #645 / #652 / #762

**Comment by jamesmckinna** [comment]
Further evidence towards the identification of `Recomputable` and Harrop:
```agda
Recomputable : ∀ {a} (A : Set a) → Set a
Recomputable A = .A → A

_×-recompute_ : Recomputable A → Recomputable B → Recomputable (A × B)
(rA ×-recompute rB) p = rA (p .proj₁) , rB (p .proj₂)
-- NB this definition fails: (rA ×-recompute rB) (a , b) = rA a , rB b
-- Cannot pattern match against irrelevant argument of type A × B
-- when checking that the pattern a , b has type A × B
```

Suggest that this become a focus of effort on reconciling (the) 'classical' fragment(s) of type theory with the ambient intuitionistic. 

Or has this already been done somewhere (else) before?

**Comment by JacquesCarette** [comment]
This is definitely about Agda's handling of 'irrelevant' (which I've run into quite a bit too). A discussion about it should happen on the Agda side (either Zulip or git issues) as that's where the experts are for that.

**Comment by jamesmckinna** [comment]
Well, once upon a time I thought I was (moderately) expert in these areas... ;-) but yes, the particular way these things cash out in terms of definitional irrelevance is ... definitely challenging/interesting!

**Comment by jamesmckinna** [comment]
But the main content of the issue: namely reconciling 'irrelevant' `⊥-elim` and `⊥-elim`, still stands. So at some point I'll turn the branch into a small(er)-scale PR, leaving the 'other' issue: what/where/how should we define `Recomputable`, and refactor the library to make use of this definition? So... further comments on the issue welcome towards such an eventual 'design'.

**Comment by jamesmckinna** [comment]
Proposal: replace the type of `⊥-elim` with that of `⊥-elim-irr`:
```agda
⊥-elim : ∀ {w} {Whatever : Set w} → .⊥ → Whatever
⊥-elim ()
```
Would this constitute a breaking change?

**Comment by gallais** [comment]
> Would this constitute a breaking change?

Given that we don't have subtyping for functions whose domain is irrelevant (the following is rejected:
```agda
app : {A B : Set} → (.A → B) → (A → B)
app f = f
```
) then I'd say yes. It could break strange code that uses `⊥-elim` partially applied.

**Comment by JacquesCarette** [comment]
Good point: I think that the proposal goes one step too far. Indeed it would only break rather strange code, but the debugging pain would be quite something!

**Comment by jamesmckinna** [comment]
Thanks to both. Indeed, errors arising from (some) partial applications of `contradiction` was one reason I introduced its friend `contradictionᵒ` in #2243 , and I won't pursue the more radical proposal on that PR ... or nay other, until v3.0! But definitiely keen to push on with what's already there.
