### ISSUE TITLE
`Data.String` missing `map`

### ISSUE THREAD

**Issue by lemastero** [agda/agda-stdlib#2207]
Hi I was using Data.String and I could not find a way to map overs strings. I end up with:
```agda
map : (Char → Char) → String → String
map f = fromList ∘ List.map f ∘ toList
```

would it make sense to add to [Data/String/Base](https://github.com/agda/agda-stdlib/blob/master/src/Data/String/Base.agda)?

I would love to make such contribution 😄

**Comment by MatthewDaggitt** [comment]
Yes, such a contribution would be welcome!

**Comment by lemastero** [comment]
Thank you for help 🙇
