### ISSUE TITLE
Redefining `Data.Nat.DivMod.DivMod`

### ISSUE THREAD

**Issue by jamesmckinna** [agda/agda-stdlib#2221]
[tagged as v2.0, because this is a last opportunity to break this now before v3.0]

Why does the [`record` definition `DivMod`](https://github.com/agda/agda-stdlib/blob/42b2a1a77992f030d3b98d2401dd615735b7f63a/src/Data/Nat/DivMod.agda#L454-L459) not take an additional irrelevant `instance` argument `.{{_ : NonZero divisor}}` as part its definition?

Two potential knock-on consequences of the change:
* the entire section could then be defined in a single module (modulo fixing up the infix declarations)? (But such a refactoring could be done downstream in v2.(n+1))
* use of the specification and its implementation(s) then enforces an additional compile-time check on client modules (maybe there are pros and cons to this?)

Re: the last point. Only knock-on consequence appears to be the need to (re-)instate `{{_ : NonZero divisor}}` in the type of `_divMod_` in place of the current `{{ NonZero divisor }}` in `Data.Nat.DivMod.WithK`...

**Comment by andreasabel** [comment]
Maybe because this would be redundant?  `NonZero divisor` is a trivial consequence of `DivMod`:
```agda
------------------------------------------------------------------------
-- The Agda standard library
--
-- Properties of DivMod
------------------------------------------------------------------------

{-# OPTIONS --cubical-compatible --safe #-}

module Data.Nat.DivMod.Properties where

open import Data.Nat using (ℕ; suc; NonZero)
open import Data.Nat.DivMod using (DivMod)

divMod-non-zero-divisor : {dividend divisor : ℕ}
   → DivMod dividend divisor
   → NonZero divisor
divMod-non-zero-divisor {divisor = suc _} _ = _
```
Shall I PR this, @MatthewDaggitt ?

**Comment by jamesmckinna** [comment]
On second thoughts (and stifling the instinct to hide my stupidity 🤦 ), please feel free to file a PR... not sure what @MatthewDaggitt will say!

**Comment by andreasabel** [comment]
Maybe @MatthewDaggitt or @gallais has some advice where to place this lemma and how to name it...

**Comment by jamesmckinna** [comment]
Given I only tagged the issue as v2.0 for the sake of it being a breaking change, which it turns out not to be, I suspect this will in any case get pushed to v2.1 at the earliest.
Regarding naming: I'd be tempted by `divMod⇒nonZero` (plain `nonZero` seems a hostage to fortune)
Regarding placement: given the addition, it probably makes most sense to leave in-place in `Data.nat.DivMod`?

**Comment by andreasabel** [comment]
> So for starters, in the last 8 years I've never had any feedback that someone has actually used that specification.

Maybe @mechvel has?

> but @andreasabel how much do you want this now? If not that much, suggest we close, as I had originally...

Not much.  Sure.

**Comment by MatthewDaggitt** [comment]
As I understand it, @mechvel uses the binary representations of natural numbers and general algebraic structures in their project...
