### ISSUE TITLE
Tag 1.7.3 warns the use of the name `toℕ-injective` instead of deprecated `toNat-injective`

### ISSUE THREAD

**Issue by moritayasuaki** [agda/agda-stdlib#2223]
It should warn against the use of `toNat-injective` but it actually warn against the use of `toℕ-injective`.
It has already fixed in `master` branch  (the name `toNat-injective` and warning are both removed) but the problem remains on the stable tag 1.7.3.

https://github.com/agda/agda-stdlib/blob/0817da6877aa045932221134913d8511caa78d97/src/Data/Char/Properties.agda#L189C4-L189C4

**Comment by MatthewDaggitt** [comment]
@moritayasuaki thank you for spotting and reporting this! This is indeed a bug, but as it happens its already fixed itself, as we've removed all deprecated content before v1.2 as part of the imminent release of v2.0. So it should be fixed in the release happening next week.
