### ISSUE TITLE
updating `README.md`

### ISSUE THREAD

**Issue by jamesmckinna** [agda/agda-stdlib#2234]
Two (at least!) potential opportunities/obligations to update:
* discussion of the `experimental` branch vs. `master`: what's the current situation, and our current policy?
* discussion of the `--without-k` flag: should this become, or have added, a note about `--cubical-compatible`?

Also: in the instructions on how to obtain old versions of the library, do we (still) need to go as far back as v0.17?

**Comment by MatthewDaggitt** [comment]
> discussion of the experimental branch vs. master: what's the current situation, and our current policy?

See https://github.com/agda/agda-stdlib/blob/f0b24bef66dc5502b299d6eaaccdf29f4d42dfbc/doc/updating-experimental.txt#L1. You could link to that from the README and expand it there if you would like?

> discussion of the --without-k flag: should this become, or have added, a note about --cubical-compatible?

Yes! I don't think anything has drastically changed that would cause us to do anything except change the name...

**Comment by MatthewDaggitt** [comment]
While we're at it, we should change the Github label as well to `cubical-compatible`

**Comment by jamesmckinna** [comment]
> While we're at it, we should change the Github label as well to `cubical-compatible`

Well, if I understand you correctly, we should add a new such label,but we can't easily remove the old one (what happens to old issues labelled with no-longer existing labels? in any case, it seems bad for the coherence of the history?)

**Comment by MatthewDaggitt** [comment]
> Well, if I understand you correctly, we should add a new such label,but we can't easily remove the old one (what happens to old issues labelled with no-longer existing labels? in any case, it seems bad for the coherence of the history?)

Sorry, very old reply. I simply renamed the existing label, rather than create a new one and remove the old one.
