### ISSUE TITLE
Some recent additions to `Data.Nat.Divisibility` use vertical bar rather than dvisibility operator in their names

### ISSUE THREAD

**Issue by Taneb** [agda/agda-stdlib#2237]
e.g. `m|n⇒n≡quotient*m` and `m|n⇒n≡m*quotient`

It'd be nice if we could have a CI check for this but I don't know how we could do that (can we get `agda` to list all identifiers or definitions or similar?)

**Comment by jamesmckinna** [comment]
Apologies if I introduced these in recent refactoring PRs. 
I believed myself to have been consistently using `\|` as the correct symbol. But it's possible that
* it's _not_ the correct symbol (please advise if so!)
* I've not been consistent with `\`... (ditto!)

**Comment by Taneb** [comment]
`\|` should give the correct symbol. I fear it's the second option that happened - made worse because either my browser's ctrl-F function or GitHub seems to normalise the two symbols so they compare equally, meaning it can be hard to catch this in review.

**Comment by jamesmckinna** [comment]
Oops! Not a v2.0.1 bug, #2182 was a v2.1 PR...
