### ISSUE TITLE
Agda.Builtin.Sigma

### ISSUE THREAD

**Issue by Saizan** [agda/agda-stdlib#224]
I plan to add Agda.Builtin.Sigma to Agda builtin modules, defining sigma types and then import that from Data.Product.

It would make it easier to integrate modules from different agda libraries and it would also be useful for --cubical's Glue.

Any objections?

**Comment by gallais** [comment]
Sounds reasonable to me

**Comment by fredefox** [comment]
Wouldn't it be more appropriate to discuss it in https://github.com/agda/agda ?

**Comment by UlfNorell** [comment]
No objections from me.

**Comment by asr** [comment]
> Is it fine to make the agda/stable-2.5 submodule point to agda-stdlib/master as long as it checks?

Right now it is fine.

**Comment by fredefox** [comment]
I see that this was reverted a week later in

commit b9c8e02597751a1b15045cbc5108c221999bd540
Author: MatthewDaggitt <matthewdaggitt@gmail.com>
Date:   Fri Feb 23 12:17:47 2018 +0000

What is the reason for this? Has this proposal been dropped?

cc @MatthewDaggitt @Saizan

**Comment by gallais** [comment]
Cf. #227: we have decided to make `master` compatible with the *released* version
of Agda whilst `experimental` is `master` + patches for Agda's development version.

**Comment by fredefox** [comment]
Ah that's great. Thanks for the info.

However:

    git branch --contains 87d28d7d753f73abd20665d7bbb88f9d72ed88aa       
    * master

... which was reverted. Shouldn't all these be in `experimental`? Is this WIP?

**Comment by gallais** [comment]
> I guess the commit was not cherry-picked.

It was. Originally. But to maintain `experimental` = `master` + patches, we need
to rebase continuously. Which means these patches get different hashes on
`experimental` as `master` evolves (but also guarantees that as soon as a new
Agda is released, we can effortlessly dump the content of `experimental` on `master`).
