### ISSUE TITLE
``n ⊓ n`` 

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#229]
It looks like Data.Nat.Properties misses  
```
n⊓n :  (n : ℕ) → n ⊓ n ≡ n
```

**Comment by MatthewDaggitt** [comment]
Already exists. It's a proof that `⊓` is idempotent.

https://github.com/agda/agda-stdlib/blob/87d28d7d753f73abd20665d7bbb88f9d72ed88aa/src/Data/Nat/Properties.agda#L715
