### ISSUE TITLE
CHANGELOG for 1.7.3 missing on master

### ISSUE THREAD

**Issue by andreasabel** [agda/agda-stdlib#2291]
Probably this directory should also contain a `1.7.3.md`:
https://github.com/agda/agda-stdlib/tree/dfd57bd3ff00e48fc5e8641e3303db624b6330f8/CHANGELOG

**Comment by jamesmckinna** [comment]
I think @MatthewDaggitt managed that release (indeed all the releases back to ..201x?), so pinging him...
