### ISSUE TITLE
Update `Function.Endomorphism.*` to avoid use of deprecated `Function.Equality`

### ISSUE THREAD

**Issue by jamesmckinna** [agda/agda-stdlib#2299]
The #759 deprecation effort left some residues which still import (at least) `Function.Equality` (with a pragma to suppress the warning), notably:
- [x] `Function.Endomorphism.Setoid`
- [x] `Function.Endomorphism.Propositional`

which define the monoid etc. of endomorphisms (needed for [a development of `Foldable`](https://github.com/agda/agda-stdlib/pull/2300) cf. generalising #1281 , and also now #2350 ). 

UPDATED: ~~blocked on not-yet-merged #2240~~ each of the above also uses the long-since-deprecated (v1.5!) `Algebra.Morphism.Is*Morphism` definitions instead of updating to the ones in `Algebra.Morphism.Structures` ...

Should update to remove dependency on the deprecated module(s).

**Comment by JacquesCarette** [comment]
Unfortunately the PR itself is regarded as a breaking change (even though not doing this for v2.0 was an oversight), so this issue should also get that label.

**Comment by jamesmckinna** [comment]
So the non-`breaking` suggestion on #2342 would be (instead) to introduce `Function.Endo.*` as *new* modules, and deprecate the  `Function.Endomorphism.*` modules...?

**Comment by JacquesCarette** [comment]
Yes, I think that that name makes more sense than `.New`. I'll implement that.
