### ISSUE TITLE
Legacy HTML pages

### ISSUE THREAD

**Issue by shhyou** [agda/agda-stdlib#2302]
There are legacy HTML pages in <https://github.com/agda/agda-stdlib/tree/gh-pages> which are leftovers from #2147. These pages are still visible (possibly through Google search) like <https://agda.github.io/agda-stdlib/Everything.html> and <https://agda.github.io/agda-stdlib/README.html>, etc.

It might be a good idea to suggest the users to visit the new page, e.g. replacing their content by something like
```html
<!DOCTYPE html>
<html>
<head><title>Documentation page moved</title></head>
<body><p>
Documentation has been moved to <a href="https://agda.github.io/agda-stdlib/">https://agda.github.io/agda-stdlib/</a>
</p></body>
</html>
```

**Comment by shhyou** [comment]
Well, I was hoping that there could be some automatic redirection like
```javascript
window.location = window.location.href.replace("/agda-stdlib/", "/agda-stdlib/master/");
```
but this could lead to 404 errors if the redirected module no longer exists.

**Comment by MatthewDaggitt** [comment]
If someone was willing to do this that would be great, but unfortunately I don't have anywhere near the bandwidth at the moment.
