### ISSUE TITLE
move `_≗_` from `Relation.Binary.PropositionalEquality` to `*.Core`

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-stdlib#2331]
It has a very straightforward definition (if you unwind the current overly complex one) and is used a fair amount, which then drags in quite a bit more than is needed. In particular, `Data.Product.Properties` is otherwise very simple, but lies higher up in the dependency graph due to this single definition.

**Comment by MatthewDaggitt** [comment]
This is fine to do!

**Comment by MatthewDaggitt** [comment]
And yes that definition is definitely a little overly complex!

**Comment by jamesmckinna** [comment]
I agree with each of you!
