### ISSUE TITLE
`IsCommutativeMonoid` should use `IsMonoid` not `IsSemigroup`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#239]
~~Obviously~~ Maybe a case of mis-subclassing. It leads to unobvious requirements and also makes the record much longer than it needs to be.

https://github.com/agda/agda-stdlib/blob/a0bdb8e10e884809ba3ffa67812e50ca2172c80a/src/Algebra/Structures.agda#L45-L51

**Comment by MatthewDaggitt** [comment]
Likewise with `IsCommutativeSemiring`

**Comment by gallais** [comment]
I think the point of this is that an `IsCommutativeX` can be used anywhere an `X` is
expected thanks to subtyping. Not sure whether it'd still be the case if everything was
packed up in a subfield.

That being said, I'm not sure how useful the subtyping aspect is.

**Comment by MatthewDaggitt** [comment]
Ooh I hadn't considered that. Apologies for my too hasty comment. 

Hang on, does that mean `identityˡ   : LeftIdentity ε _∙_` is a subtype of `identity    : Identity ε ∙`?

**Comment by andreasabel** [comment]
I could imagine the reason is that in the presence of commutativity, left identity implies right identity, thus, there is less proof obligations to build a commutative monoid.

**Comment by MatthewDaggitt** [comment]
> Unless there are strong reasons for change, I'd advise to leave it as-is. (Maybe add documentation to not fall into the same trap again.)

Agreed.
