### ISSUE TITLE
Use the Monoid structure of Endomorphisms to define powering

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-stdlib#2394]
As was [commented](https://github.com/agda/agda-stdlib/pull/2342#discussion_r1603039032) by @jamesmckinna , we really ought to use the definitions from `Algebra.Definitions.RawMonoid` for the `RawMonoid` structure on `Endo`, both the `Setoid` and `Propositional` versions.

**Comment by jamesmckinna** [comment]
See [this commit](https://github.com/agda/agda-stdlib/commit/8b5b3037c6b7d2f463b7cc3789b416d39f02fbe5) based off #2342 for one approach: easily incorporated on top of what you have there!
