### ISSUE TITLE
Unify general algebraic definitions of Divisibility and Primarity with those in Nat and Integer

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#2416]
lib-2.1-rc1  has general definitions for ``Irreducible, Prime``  for Magma, CancellativeCommutativeSemiring,
and also some proofs for them  (see Algebra/Definitions/ and certain other places). 
And ``ℕ, ℤ`` do have their instances   *-magma, cancellativeCommutativeSemiring.
So, it has sense for  `ℕ` and `ℤ `to import the general definitions of ``Irreducible, Prime`` as specialization 
(by substituting the module parameters) and to use them instead of declaring ad-hoc definitions by new.  For example, the parts of `Nat.Primality.Prime ` can be derived from the general definition of `Prime`. 
If the ad-hoc local definitions occur  useful,  it would have sense to rename them and to hide them under `private`.
The matter is that the general definitions and many their related properties  work not only for  `ℕ`, but also for  `ℤ` and for polynomials over   `ℤ`  and for  many other domains. 
For example, I use `Nat.Factorization.factorise` , but I need to convert the parts of `PrimeFactorisation` to general ones,
say, to convert  `factorsPrime`  from the ad-hoc definition `Prime` to general `Prime`, and so on.
Such renaming and conversion complicates the code.

**Comment by mechvel** [comment]
It is even worse.
The general definition for  `_∣_` is not imported to Data.Nat.Divisibility.Core.
Instead Nat...Core  gives its own definition for  `_∣_`  in which the parts of  `equality`  are swapped.

**Comment by mechvel** [comment]
Changing  `_∣_` in Nat.Divisibiliy may break backwards compatibiliy greatly.
At least the team could add the conversion that allows people to use generic   `_∣_`  and the ad-hoc one for  Nat:
```
open Divisibility *-magma using (_∣_; _∤_; _,_)   -- generic

∣stdℕ⇒∣ :  _∣stdℕ_ ⇒  _∣_
∣stdℕ⇒∣ (dividesℕ q y≡qx) =  q , (sym y≡qx)             -- convert ad-hoc to generic

∣⇒∣stdℕ⇒∣ :  _∣_ ⇒  _∣stdℕ_                                       -- the reverse
∣⇒∣stdℕ⇒∣ (q , qx≡y) =  dividesℕ q (sym qx≡y)
```
As to `Irreducible` and `Prime` for Nat, they are probably more fresh, and they just can be changed to generic definitions as I asked above.

**Comment by MatthewDaggitt** [comment]
Yes, we should fix this in 3.0

**Comment by jamesmckinna** [comment]
Cf #679 #2115 (and perhaps others), so marking this as `status:duplicate`...

**Comment by mechvel** [comment]
It is better to use above the names  Irreducible-adHoc and Prime-adHoc  with using `-adHoc` instead of `-std`.
Because both versions are in Standard of lib-2.1-rc1, only one is ad-hoc for Nat, and another is the general  definition for Irreducible and Prime specialized by a setting parameter to the module.

**Comment by MatthewDaggitt** [comment]
Yes, okay closing as duplicate. Please feel free to continue the discussion in #2115
