### ISSUE TITLE
Sorting out closures

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#244]
Recently had reason to try and use some of the closure modules, and it turns out the organisation is a bit... strange:
* Reflexive closure - `Data.ReflexiveClosure`
* Symmetric closure - `Relation.Binary.SymmetricClosure`
* Transitive closure - `Data.Plus`
* Reflexive + transitive closure - `Data.Star`
* Equivalence - `Relation.Binary.EquivalenceClosure`

I propose moving their contents all to `Relation.Binary.Closure.(Reflexive/Symmetric/Transitive/ReflexiveTransitive/Equivalence)`. The old modules would be deprecated and would re-export the contents from the new location. Thoughts?

Edit: Just found transitive closure

**Comment by gallais** [comment]
I like that plan. :+1:

**Comment by MatthewDaggitt** [comment]
Closed with c39732e
