### ISSUE TITLE
Regression in the documentation of installation

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#2443]
The [installation guide](https://github.com/agda/agda-stdlib/blob/master/doc/installation-guide.md) is not mentioning [the compatibility table](https://wiki.portal.chalmers.se/agda/Libraries/StandardLibrary) anymore (it used to if I remember correctly). It's only saying "Use version v2.0 of the standard library with Agda 2.6.4 or 2.6.4.1." without giving any indication of what to do otherwise.

**Comment by jamesmckinna** [comment]
Hmmm... maybe we took the major-version breaking transition from v1.x to v2.y too far?
