### ISSUE TITLE
Reflection.AST.Definition doesn't compile in release candidate

### ISSUE THREAD

**Issue by alexarice** [agda/agda-stdlib#2462]
Pretty much as described in the title. There's a duplicate infixity, and after fixing that there are some more involved errors which I haven't tried to fix.

**Comment by alexarice** [comment]
It looks like the "more involved errors" is just me using the wrong version of Agda, though the duplicate fixity definition still makes the build fail for me with Agda 2.7.0

**Comment by MatthewDaggitt** [comment]
Thanks! I'm confused about how I missed that. I ran the tests before tagging it. Must have been on the wrong branch. I'll create a new one now.

**Comment by alexarice** [comment]
Is there not a CI pass that runs `runhaskell GenerateEverything.hs && agda Everything.agda -i .`? Feel like this would catch most issues

**Comment by MatthewDaggitt** [comment]
There is but until https://github.com/agda/agda-stdlib/pull/2444 is merged in, it didn't get run and I just ran the tests manually. I've just pushed a fix to the `v2.1-release` branch. Any chance you can quickly try downloading it and seeing if it works for you? I'll then a make a new release candidate.

**Comment by alexarice** [comment]
Works on my end

**Comment by MatthewDaggitt** [comment]
Thanks!
