### ISSUE TITLE
two proofs suggested for `Data.List.Membership.Setoid.Properties`

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#2463]
I suggest the following two proofs for standard library
(probably for Data.List.Membership.Setoid.Properties).
These are is over ``S : Setoid _ _``.
```
any∈sym :  ∀ {xs ys} → Any (_∈ ys) xs → Any (_∈ xs) ys
any∈sym {xs} {ys} any-xs∈ys =
  let (x , x∈xs , x∈ys) = find {P = (_∈ ys)} any-xs∈ys
  in
  lose {P = (_∈ xs)} (∈-resp-≈ S) x∈ys x∈xs

all∉sym :  ∀ {xs ys} → All (_∉ ys) xs → All (_∉ xs) ys
all∉sym {xs} {ys} all-xs∉ys =
                  ¬Any⇒All¬ ys (¬any-xs∈ys ∘ any∈sym)
  where
  ¬any-xs∈ys =  All¬⇒¬Any all-xs∉ys
```
I do not set dashes, for example, write `any∈sym` rather than `any-∈-sym`.
Because
(1) this makes the proof texts shorter,
(2) the symbols like ``∈, ∉, *, _≈_, ...`` denote operators and are distinguished themselves inside a word.
But if the team insists, let them set dashes.

**Comment by jamesmckinna** [comment]
The first lemma, purely concerning `Any`, has the direct proof as above, but may also be given, perhaps more indirectly, by appeal to `Data.List.Relation.Unary.Any.Properties.swap`, noting that symmetry of equality `_≈_` implies that `flip _≈_` is extensionally the same as `_≈_`...

**Comment by mechvel** [comment]
Thank you. I see. Let the team decide about this.
