### ISSUE TITLE
Equivalence of characterisations of `Data.List.Membership.Setoid._∉_`

### ISSUE THREAD

**Issue by jamesmckinna** [agda/agda-stdlib#2466]
Issue #2463 got me thinking... why do we not have the equivalence anywhere, for given `x` and `xs`, of:
* `x ∉ xs = ¬ x ∈ xs` defined in `Data.List.Membership.Setoid`
* `All (x ≉_) xs` defined via `Data.List.Relation.Unary.All`

Where would such a statement live? Currently `Data.List.Membership.Setoid.Properties` defines only a `private` (moreover: unidirectional) version, as:
```agda
  private
    ∉×∈⇒≉ : ∀ {x y xs} → All (y ≉_) xs → x ∈ xs → x ≉ y
    ∉×∈⇒≉ = All.lookupWith λ y≉z x≈z x≈y → y≉z (trans (sym x≈y) x≈z)
```
But for reflexive `_≈_` this would follow immediately from the equivalence...?

**Comment by MatthewDaggitt** [comment]
We don't really have a cohesive story for where the lemmas that relate relations tend to go, especially not when we have three different relations like this. Traditionally they've just gone wherever they don't cause dependency cycles...
