### ISSUE TITLE
somethig like a typo in  lib-2.1.1-rc2

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#2467]
Data/List/Relation/Unary/All.agda 
starts with 
```
All.agda:module _(S : Setoid a ℓ) ...
``` 
Probably it is better to set a space after `_`

**Comment by jamesmckinna** [comment]
Just a note for @MatthewDaggitt : #2468  has now been merged in to `master` (thanks @Taneb !) but should also be merged into your Agda-v2.7.0-compatible v2.1.1 branch?

**Comment by MatthewDaggitt** [comment]
I don't think a minor typo really needs to be merged in v2.1.1 unless there's some important bug that I'm missing?

**Comment by jamesmckinna** [comment]
Fine by me! No 'bug' as such at all...

**Comment by mechvel** [comment]
I do not know, may be to join to other changes and to merge to future versions.

**Comment by jamesmckinna** [comment]
@mechvel v2.1.1 is a compatibility release towards a mandatory upgrade from v2.2 onwards to Agda-v2.7.0, so I agree with @MatthewDaggitt that it's fine that the typo has been corrected (only) for v2.2...
