### ISSUE TITLE
suggested  "`concat` members are sublists"

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#2509]
I suggest for standard library a proof for that each member of ``(concat xss)``
is a sublist in the result:
```
import      Data.List.Relation.Binary.Sublist.Setoid.Properties
            as SublistProps
open import Data.List.Relation.Binary.Sublist.Propositional using ()
            renaming (_⊆_ to _⊆ₗ_; ⊆-refl to ⊆ₗrefl)
S = PE.setoid A  -- the propositional setoid

all⊆ₗconcat : (xss : List (List A)) → All (_⊆ₗ (concat xss)) xss
all⊆ₗconcat [] = []
all⊆ₗconcat (xs ∷ xss) =
  xs⊆ₗunion ∷ (AllM.map ⊆ₗunion'⇒⊆ₗunion all-xss⊆ₗunion')
  where
  union' = concat xss
  union = xs ++ union'
  xs⊆ₗunion = SublistProp.++⁺ʳ S {xs}{xs} union' ⊆ₗrefl
  all-xss⊆ₗunion' = all⊆ₗconcat xss
  ⊆ₗunion'⇒⊆ₗunion = \{ys} → SublistProps.++⁺ˡ S {ys}{union'} xs
```
The team can set a nicer implementation if any.

**Comment by jamesmckinna** [comment]
I think you want something a bit simpler:
```agda
import Data.List.Relation.Binary.Sublist.Propositional as Sublist
import Data.List.Relation.Binary.Sublist.Propositional.Properties as Sublist
all⊆concat : (xss : List (List A)) → All (Sublist._⊆ (concat xss)) xss
all⊆concat [] = []
all⊆concat (xs ∷ xss) =
  Sublist.++⁺ʳ (concat xss) Sublist.⊆-refl ∷ All.map (Sublist.++⁺ˡ xs) (all⊆concat xss)
```

It's possible that further simplification is possible?

**Comment by mechvel** [comment]
James wrote 
> It's possible that further simplification is possible?

You write in one line by composing of  what I wrote in seven lines.
To my mind, the reader would understand these seven lines more easily.
As to me, this difference is not important.
Let the team chose the variant as it likes.

**Comment by jamesmckinna** [comment]
Sergei, thanks for the feedback. 
There is a tension in `stdlib` between (any individual contributor's inclination towards) verboseness/didactic value, and the economy of expression which is much more the ambient style. And as a member of the `stdlib` maintenance team, my own style has evolved towards the more terse style.

**Comment by mechvel** [comment]
Anyway I am satisfied with your variant as well.
