### ISSUE TITLE
dependency on stdlib does not pass --safe

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-stdlib#255]
I am writing a toy project to make sure I understand agda properly, and this project is meant for proofs. With that in mind, I need to make sure the code is safe. From wiki, I learned that `--safe` from command line is currently the only way to be safe, so I ran it with my project, and boom:

```
...
/home/zs2hu/projects/agda-test/MultiMap.agda:5,13-21
Cannot use primTrustMe with safe flag
when scope checking the declaration
  open import Data.Nat renaming (ℕ to Nat; _⊔_ to max)
Unsolved interaction metas at the following locations:
  /home/zs2hu/projects/agda-test/MultiMap.agda:119,28-32
```

So I have several problems:

1.  above `...` is a list of loaded files, which is not very helpful to learn where the unsafety was introduced, if it's recursively introduced by further dependencies.
1. in the case of `Data.Nat`, it's fairly straightforward:
```agda
import Relation.Binary.PropositionalEquality.TrustMe as TrustMe
```
I blieve this line triggers the warning, and indeed, 
```agda
erase : ∀ {m n} → m ≤″ n → m ≤″ n
erase (less-than-or-equal eq) = less-than-or-equal (TrustMe.erase eq)
```
This function effectively calls `primTrustMe` and blocks the safety check.

Due to the essential role of `Data.Nat` and agda as a proof system, just importing this module introduces an unsafe spot does not look quite reasonable. On the other hand, commenting out this function indeed leads to a complete compilation with `--safe` flag(for my toy project).

----------------

I do agree that having the language both practical and rigorous must require unsafe code. However, at least there can be an effort to separate them. Might I suggest that for all  non-trivial implementation of something(Nat, List, Vec, etc), when involving unsafe components, we put them into separate `Unsafe.agda` files? I believe this is also quite idiomatic in Haskell universe as well. This definitely would help Agda code base grows very healthily.

**Comment by gallais** [comment]
Cf. #143

**Comment by MatthewDaggitt** [comment]
Closing, as #143 will serve.
