### ISSUE TITLE
Relation.Unary's implication associates to the left

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#260]
Cf. https://github.com/agda/agda-stdlib/blob/master/src/Relation/Unary.agda#L181

This looks wrong to me: implications usually associate to the right.
Is it a bug? (ping @UlfNorell who's blamed by git for this loc).

**Comment by UlfNorell** [comment]
Commit message says “Patch by @stevana”. I was just the messenger (don’t shoot).

**Comment by stevana** [comment]
I don't remember doing this, much less why -- feel free to change it, if you like.

**Comment by MatthewDaggitt** [comment]
Closed with b300b6b
