### ISSUE TITLE
`Relation.Binary.Indexed` to `Indexed.Heterogeneous`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#275]
Now that we have `Relation.Binary.Indexed.Homogeneous` I think `Relation.Binary.Indexed` should probably be renamed `Relation.Binary.Indexed.Heterogeneous`. I would propose doing this in v1.0. Anybody have any opinions?

**Comment by WolframKahl** [comment]
On Wed, Apr 11, 2018 at 12:42:23PM +0000, MatthewDaggitt wrote:
> Now that we have `Relation.Binary.Indexed.Homogeneous` I think `Relation.Binary.Indexed` should probably be renamed `Relation.Binary.Indexed.Heterogeneous`. I would propose doing this in v1.0. Anybody have any opinions?

I tend to think of homogeneous relations as a special case of ``heterogeneous'' relations.
I'd therefore consider that renaming as more confusing than helpful.

Just like endofunctors are a special case of functors...


Wolfram

**Comment by MatthewDaggitt** [comment]
Sorry its taken so long to reply. Been mulling this over. I agree that homogeneous is a special case of heterogeneous. But looking through, the library seems to nearly always flatten out such hierarchies rather than nesting them:

- `Function.Bijection` isn't inside `Function.Injection`.
- `Data.List.Membership` is (no longer) inside `Data.List.Any`.
- a monoid is a special case of a semigroup but the library doesn't put all the monoid related files inside a semigroup subfolder.
- partial orders property files aren't inside the preorder properties subfolder.

**Comment by MatthewDaggitt** [comment]
Closed with 918a932378405661eb82a54a40301fe997704baf
