### ISSUE TITLE
stdlib that compiles with "agda" master branch.

### ISSUE THREAD

**Issue by xekoukou** [agda/agda-stdlib#283]
The [Size](https://github.com/agda/agda-stdlib/blob/master/src/Size.agda) does not compile with agda master because of a renaming.

Maybe it would be helpful to have a branch that always compiles with agda master.

**Comment by gallais** [comment]
That is what `experimental` is for!

**Comment by xekoukou** [comment]
Nice. It is missing some commits from master but the change on ```Size``` exists.

**Comment by xekoukou** [comment]
Thanks.
