### ISSUE TITLE
More use of instance search

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-stdlib#290]
A search on the library shows that there isn't any use of `instance` search, while I believe it's a good idea, when we open a module, we should also automatically obtain the `instance` to assist development. I think starting with those `IsBlah` might be a good idea. Or is there any guideline that implies it might not be a good practice?

--------------------

Also things like `Decidable` can also be an `instance`, as I've encountered situation which might be quite helpful.

**Comment by HuStmpHrrr** [comment]
on the second point, I don't see how those instances are the same though, as instance shall be disambiguated when proper operator is used.

I do agree it's a larger design question. I am more on considering to make overloading and proving activities more transparent. arguably there are some definitions could be more useful to be instances than another.

**Comment by WolframKahl** [comment]
On Mon, Apr 23, 2018 at 02:40:59PM -0700, Jason Hu wrote:
> I do agree it's a larger design question. I am more on considering to make overloading and proving activities more transparent.

I think that proving is more transparent if there is no instance search going on.

(I have co-authored a paper on ``Named Instances'' in Haskell.
 In Agda, I am consciously not using instances at all.)


Wolfram

**Comment by MatthewDaggitt** [comment]
I think Wolfram has the crux of this. We'll leave instances out for the moment, unless anyone has any more strong arguments for? I understand that for those who do heavily rely on it, it might be a tad irritating that the library doesn't use them, but it should be easy enough for the users themselves to mark the desired terms as instances.
