### ISSUE TITLE
Add Order-Preserving Embeddings

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#293]
Seeing in #292 that the sublist relation is defined in an extensional manner,
I think it would be nice to also have an inductive characterization of what it
means to be a sublist. As the name suggests, it makes it easy to perform
*induction* on the proof.

This structure is commonly known as 'Order-Preserving Embedding' (OPE)
when formalising syntaxes with binding. The basic definition goes something
like this:

```agda
data OPE xs ys where
  base : OPE [] []
  drop : OPE xs ys -> OPE xs (y :: ys)
  copy : OPE xs ys -> OPE (x :: xs) (x :: ys)
```

Where should this go?

* Data.List.Relation.OrderPreservingEmbedding ?

**Comment by MatthewDaggitt** [comment]
Closed with #329
