### ISSUE TITLE
Check for potentially missing level-polymorphism

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#295]
Noticing in #291 that we can still find functions which are not as level-polymorphic
as possible, I have run a little test to find potential candidates. Putting it here to
remember to check them at some point. Contributions are welcome.

* [X] README/Function/Reasoning.agda:module _ {A B C : Set} {A→B : A → B} {B→C : B → C} where
* [X] README/Record.agda:PER = ∅ , "S"     ∶ (λ _ → Set)
* [X] README/Record.agda:        , "R"     ∶ (λ r → r · "S" → r · "S" → Set)
* [x] Coinduction.agda:  ℕ-rec : (P : ℕ → Set) →
* [x] Data/List/Relation/Sublist/Propositional/Properties.agda:module _ {A B : Set} {xs₁ ys₁ : List A} {xs₂ ys₂ : List B} where
* [X] Data/List/Relation/Lex/Core.agda:data Lex {a ℓ₁ ℓ₂} {A : Set a} (P : Set)
* [X] Data/List/Relation/Lex/Core.agda:module _ {a ℓ₁ ℓ₂} {A : Set a} {P : Set}
* [x] Data/List/Reverse.agda:data Reverse {A : Set} : List A → Set where
* [x] Data/List/Countdown.agda:  drop-inj₂ : ∀ {A B : Set} {x y} →
* [x] Data/List/Any/Properties.agda:⊥↔Any[] : ∀ {a} {A : Set a} {P : A → Set} → ⊥ ↔ Any P []
* [X] Data/List/NonEmpty.agda: module Examples {A B : Set}
* [x] Data/Graph/Acyclic.agda:record Context (Node Edge : Set) (n : ℕ) : Set where
* [x] Data/Graph/Acyclic.agda:data Graph (Node Edge : Set) : ℕ → Set where
* [x] Data/Graph/Acyclic.agda:foldr : ∀ {N E m} (T : ℕ → Set) →
* [x] Data/Graph/Acyclic.agda:foldl : ∀ {N E n} (T : ℕ → Set) →
* [x] Data/Graph/Acyclic.agda:  p : ∀ {E : Set} {n} (i : Fin n) → E × Fin n → Maybe (Fin′ (suc i) × E)
* [x] Data/Graph/Acyclic.agda:data Tree (N E : Set) : Set where
* [x] Data/Nat/InfinitelyOften.agda:Fin : (ℕ → Set) → Set
* [x] Data/Nat/InfinitelyOften.agda:Inf : (ℕ → Set) → Set
* [x] Data/Star/Pointer.agda:data Pointer {I : Set} {T : Rel I zero} (P Q : EdgePred T)
* [x] Data/Star/Pointer.agda:data Result {I : Set} (T : Rel I zero) (P Q : EdgePred T) : Set where
* [x] Data/Star/Decoration.agda:EdgePred : {I : Set} → Rel I zero → Set₁
* [x] Data/Star/Decoration.agda:data NonEmptyEdgePred {I : Set}
* [x] Data/Star/Decoration.agda:data DecoratedWith {I : Set} {T : Rel I zero} (P : EdgePred T)
* [ ] Data/Star/Environment.agda:module Data.Star.Environment (Ty : Set) where
* [ ] Data/Star/Environment.agda:Env : (Ty → Set) → Ctxt → Set
* [ ] Data/Star/Environment.agda:lookup : ∀ {Γ σ} {T : Ty → Set} → Γ ∋ σ → Env T Γ → T σ
* [X] Data/Sum/Relation/Core.agda:  data ⊎ʳ {ℓ₁ ℓ₂} (P : Set) (_∼₁_ : Rel A₁ ℓ₁) (_∼₂_ : Rel A₂ ℓ₂) :
* [x] Data/Fin/Substitution.agda:Sub : (ℕ → Set) → ℕ → ℕ → Set
* [x] Data/Fin/Substitution.agda:Subs : (ℕ → Set) → ℕ → ℕ → Set
* [x] Data/Fin/Substitution.agda:record Simple (T : ℕ → Set) : Set where
* [x] Data/Fin/Substitution.agda:record Application (T₁ T₂ : ℕ → Set) : Set where
* [x] Data/Fin/Substitution.agda:record Subst (T : ℕ → Set) : Set where
* [x] Data/Fin/Substitution.agda:record Lift (T₁ T₂ : ℕ → Set) : Set where
* [x] Data/Fin/Substitution.agda:record TermSubst (T : ℕ → Set) : Set₁ where
* [x] Data/Fin/Properties.agda:sequence : ∀ {F n} {P : Fin n → Set} → RawApplicative F →
* [x] Data/Fin/Properties.agda:  helper : ∀ n (P : Fin n → Set) → (∀ i → F (P i)) → F (∀ i → P i)
* [x] Data/Fin/Properties.agda:  sequence⁻¹ : ∀ {F}{A : Set} {P : A → Set} → RawFunctor F →
* [x] Data/Fin/Subset.agda:Lift : ∀ {n} → (Fin n → Set) → (Subset n → Set)
* [x] Data/Fin/Dec.agda:any? : ∀ {n} {P : Fin n → Set} →
* [x] Data/Fin/Dec.agda:decLift : ∀ {n} {P : Fin n → Set} →
* [x] Data/Fin/Dec.agda:  restrictSP : ∀ {n} → Side → (Subset (suc n) → Set) → (Subset n → Set)
* [x] Data/Fin/Dec.agda:  restrictS : ∀ {n} {P : Subset (suc n) → Set} →
* [x] Data/Fin/Dec.agda:anySubset? : ∀ {n} {P : Subset n → Set} →
* [x] Data/Fin/Substitution/Lemmas.agda:record Lemmas₀ (T : ℕ → Set) : Set where
* [x] Data/Fin/Substitution/Lemmas.agda:record Lemmas₁ (T : ℕ → Set) : Set where
* [x] Data/Fin/Substitution/Lemmas.agda:record Lemmas₂ (T : ℕ → Set) : Set where
* [x] Data/Fin/Substitution/Lemmas.agda:record Lemmas₃ (T : ℕ → Set) : Set where
* [x] Data/Fin/Substitution/Lemmas.agda:record Lemmas₄ (T : ℕ → Set) : Set where
* [x] Data/Fin/Substitution/Lemmas.agda:record AppLemmas (T₁ T₂ : ℕ → Set) : Set where
* [x] Data/Fin/Substitution/Lemmas.agda:record Lemmas₅ (T : ℕ → Set) : Set where
* [x] Data/Fin/Substitution/Lemmas.agda:record TermLemmas (T : ℕ → Set) : Set₁ where
* [x] Data/Fin.agda:fold : ∀ (T : ℕ → Set) {m} →
* [x] IO.agda:mapM′ : {A B : Set} → (A → IO B) → Colist A → IO (Lift ⊤)
* [x] Reflection.agda:  cong₂′ : ∀ {A B C : Set} (f : A → B → C) {x y u v} →
* [x] Reflection.agda:  cong₃′ : ∀ {A B C D : Set} (f : A → B → C → D) {x y u v r s} →
* [x] Reflection.agda:  cons₁ : ∀ {A : Set} {x y} {xs ys : List A} → x ∷ xs ≡ y ∷ ys → x ≡ y
* [x] Reflection.agda:  cons₂ : ∀ {A : Set} {x y} {xs ys : List A} → x ∷ xs ≡ y ∷ ys → xs ≡ ys
* [x] Function/Related/TypeIsomorphisms.agda:  test : (A B C : Set) →
* [x] Record.agda:module Record (Label : Set) (_≟_ : Decidable (_≡_ {A = Label})) where
* [X] README.agda:--   record IsPreorder {A : Set}

**Comment by MatthewDaggitt** [comment]
Good idea. I've put an `X` next to the ones that I know are fine off the top of my head and don't need to be checked.

**Comment by JacquesCarette** [comment]
You could turn the list into a set of checkboxes that people can tick when they've done it. There is a 'add a task list' button on the github interface to do just that.

**Comment by gallais** [comment]
Why is the one in `Data.List.Reverse` fine? `List` itself is level-polymorphic
so I assume `Data.List.Reverse` could also be.

**Comment by MatthewDaggitt** [comment]
> Why is the one in Data.List.Reverse fine? List itself is level-polymorphic
so I assume Data.List.Reverse could also be.

Sorry, you're right, I read `Data.List.Reverse` as `Data.List.Relation`.

**Comment by MatthewDaggitt** [comment]
We've now gone through all of them except `Data.Star.Environment`. It looks like these could be made polymorphic but something that I don't understand in `Data.Star.Decoration` is causing it to break when I try.

As these are very niche modules, I'm going to close this issue. Of course if someone else would like to try their hand at it, feel free.

**Comment by gallais** [comment]
There's a bunch of patches on branch issue295 that still need to be merged
for all the checked items to actually be fixed in the stdlib.

**Comment by MatthewDaggitt** [comment]
Ah okay, didn't realise you'd done your work on a branch. I'll try and merge it in if you don't have any objections?

**Comment by JacquesCarette** [comment]
Maybe make a new issue for the few remaining ones in `Data.Star`?
