### ISSUE TITLE
`make test` on a Mac (line ending issues)

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-stdlib#311]
Right now, `make test` on a pristine clone of the standard library fails on `cabal exec -- GenerateEverything` with the error

    GenerateEverything: src/Algebra.agda is malformed

I've tracked it down to all .agda files having `\r\n` line endings.  So of course the check in `GenerateEverything.hs` that (`all (== '-')` fails.

What is the recommended fix?  I know about git's `autocrlf` settings. The point of asking here is that, once this gets settled, I'll add something to `HACKING.md` for Mac users, so that they don't run into this.

[I'm trying to work on some of the low-hanging-fruit in my spare time]

**Comment by JacquesCarette** [comment]
I think the correct answer is: before doing a clone, make sure to have first executed

    git config --global core.autocrlf input

I may have had this set to `true` by mistake before, which would have caused my problems.

**Comment by JacquesCarette** [comment]
PR #315 should fix this.

**Comment by MatthewDaggitt** [comment]
Fixed with 2d5710df58390f29ba6fe0c99e4259984d439577
