### ISSUE TITLE
Release agda-stdlib 0.16

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#322]
Agda-2.5.4 is about to be released (cf. https://github.com/agda/agda/issues/2875) and it needs the changes in `experimental`.

**Comment by MatthewDaggitt** [comment]
On it. 

The only question is whether we make it an official 0.16 release? We probably have enough changes to make it worthwhile? Or should we save them all and try and release them in v1.0?

**Comment by gallais** [comment]
That's a good point: this won't just be 0.15 + fixes for Agda-2.5.4 so it probably needs a higher number.

**Comment by MatthewDaggitt** [comment]
Planning to release tomorrow afternoon (Australian time). Anything urgent that people need included or any bugs found by people using the experimental branch?

**Comment by gallais** [comment]
#264 maybe ?

**Comment by MatthewDaggitt** [comment]
Okay, included #264

**Comment by MatthewDaggitt** [comment]
Released!
