### ISSUE TITLE
Changelog: Missing `Data` prefix

### ISSUE THREAD

**Issue by asr** [agda/agda-stdlib#324]
@mechvel [wrote](https://lists.chalmers.se/pipermail/agda/2018/010325.html) in the Agda user mailing list:

In CHANGELOG.md  in

> * The `_⊆_` relation has been moved out of the `Membership` modules to
> new modules `List.Relation.Sublist.(Setoid/Propositional)`.
> Consequently the `mono` proofs that were in
> `Membership.Propositional.Properties` have been moved to
> `Relation.Sublist.Propositional.Properties`.

The prefix "Data." is needed in some module names. Maybe there are more such places.

**Comment by MatthewDaggitt** [comment]
Hmm this was deliberate, as I didn't want to clutter up the log too much. I hoped it might be obvious from the context that I was talking about the `Data.List` subtree... I should at least be consistent though and not have the `List` when referring to the `Sublist` relation.

**Comment by JacquesCarette** [comment]
It's only obvious if you are quite familiar with the standard library and its layout. So beginners could get quite befuddled as to the exact meaning. Furthermore, it is not very google-friendly.  Sometimes the CHANGELOG contains some of the most accessible documentation for some features, and a quick google is a good way to find it.  If the full module name isn't there, it could be missed.

**Comment by MatthewDaggitt** [comment]
Okay, thanks for the feedback. I'll change it to use the full names!

**Comment by MatthewDaggitt** [comment]
Fixed with b8e9a29

**Comment by asr** [comment]
Note that the above commit didn't fix *this* issue.

**Comment by MatthewDaggitt** [comment]
Eek, yes that was the merge commit. Nice spot, fixed.

**Comment by asr** [comment]
To avoid this type of errors, you can use some keywords in the commit messages to automatically close the issues in GitHub. See [Closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/).

**Comment by MatthewDaggitt** [comment]
Ah neat. Thank you!
