### ISSUE TITLE
Reflection missing some patterns?

### ISSUE THREAD

**Issue by identicalsnowflake** [agda/agda-stdlib#326]
When I do `open import Reflection` I get an error:
```
Incomplete pattern matching for showLiteral. Missing cases:
  showLiteral (Literal.word64 n)
```

It seems like there's a primitive missing (which may not be there on release Agda but is present on 2.5.4?). Not sure what the best way to handle that is.

**Comment by identicalsnowflake** [comment]
I think I have both `agda` and `agda-stdlib` on master. Are these not intended to go together?

**Comment by MatthewDaggitt** [comment]
So until Agda 2.5.4 officially releases, 'master' will remain compatible
with 2.5.3. All changes that ensure compatibility with future versions of
Agda are put on the 'experimental' branch. This to ensure we can release
new versions of the library without having to wait for new versions of Agda.

Therefore if you're using the Agda release candidate you need experimental
not master.

Don't worry, lots of people have asked. We should put this on the README...

**Comment by identicalsnowflake** [comment]
Ah ok, thanks for clarifying. I had thought the two master branches were moving together. I'll switch to `Experimental` then.

**Comment by MatthewDaggitt** [comment]
Updated the README so this information appears on the repository splash page.
