### ISSUE TITLE
Add WARNING_ON_USAGE to all of the deprecated names

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#331]
The title says it all. We can keep a list of modules we have taken care of down here:

Names

- [x] ./src/Data/Bool/Properties.agda
- [x] ./src/Data/Fin/Properties.agda
- [x] ./src/Data/Integer/Properties.agda
- [x] ./src/Data/List/All/Properties.agda
- [x] ./src/Data/List/Base.agda
- [x] ./src/Data/List/Relation/Pointwise.agda
- [x] ./src/Data/List/Relation/Sublist/Extensional/Propositional/Properties.agda
- [x] ./src/Data/List/Properties.agda
- [x] ./src/Data/List/Membership/Setoid.agda
- [x] ./src/Data/List/Membership/Propositional/Properties.agda
- [x] ./src/Data/Nat/Properties.agda
- [x] ./src/Data/Nat/Divisibility.agda
- [x] ./src/Data/Product/Relation/Lex/Strict.agda
- [x] ./src/Data/Product/Relation/Lex/NonStrict.agda
- [x] ./src/Data/Product/Relation/Pointwise/Dependent.agda
- [x] ./src/Data/Product/Relation/Pointwise/NonDependent.agda
- [x] ./src/Data/Sign/Properties.agda
- [x] ./src/Data/Vec/All/Properties.agda
- [x] ./src/Data/Vec/Relation/Pointwise/Inductive.agda
- [x] ./src/Data/Vec/Relation/Pointwise/Extensional.agda
- [x] ./src/Data/Vec/Properties.agda
- [x] ./src/Induction/WellFounded.agda
- [x] ./src/Induction/Nat.agda
- [x] ./src/Relation/Binary/NonStrictToStrict.agda
- [x] ./src/Relation/Binary/PropositionalEquality.agda
- [x] ./src/Relation/Binary/HeterogeneousEquality.agda
- [x] ./src/Relation/Binary.agda

Modules

- [ ] ./src/Data/ReflexiveClosure.agda
- [ ] ./src/Data/Star/Properties.agda
- [ ] ./src/Data/Plus.agda
- [ ] ./src/Data/Nat/Properties/Simple.agda
- [ ] ./src/Data/Integer/Multiplication/Properties.agda
- [ ] ./src/Data/Integer/Addition/Properties.agda
- [ ] ./src/Data/Star.agda
- [ ] ./src/Relation/Binary/EquivalenceClosure.agda
- [ ] ./src/Relation/Binary/Sigma/Pointwise.agda
- [ ] ./src/Relation/Binary/Sum.agda
- [ ] ./src/Relation/Binary/SymmetricClosure.agda
- [ ] ./src/Relation/Binary/List/NonStrictLex.agda
- [ ] ./src/Relation/Binary/List/Pointwise.agda
- [ ] ./src/Relation/Binary/List/StrictLex.agda
- [ ] ./src/Relation/Binary/Product/NonStrictLex.agda
- [ ] ./src/Relation/Binary/Product/Pointwise.agda
- [ ] ./src/Relation/Binary/Product/StrictLex.agda
- [ ] ./src/Relation/Binary/Vec/Pointwise.agda

**Comment by MatthewDaggitt** [comment]
Added the list of things to do to your original post. 

Can we somehow use the warning mechanism to mark the contents of deprecated modules? How does it interact with "open public"?

**Comment by gallais** [comment]
The current warning mechanism only supports `QName` that is names of definitions.
So you can't use it to deprecate whole modules I'm afraid. :/

**Comment by MatthewDaggitt** [comment]
> The current warning mechanism only supports QName that is names of definitions.
So you can't use it to deprecate whole modules I'm afraid. :/

Okay, no worries.

**Comment by MatthewDaggitt** [comment]
Carrying out the work on the `warning` branch.

**Comment by MatthewDaggitt** [comment]
]

**Comment by MatthewDaggitt** [comment]
I'm not going to add warnings directly to the `boolX` functions in `Data.List.Base` as they are used for other deprecated proofs throughout the library, and therefore would otherwise trigger a whole host of warnings for us every time we type checked anything.

**Comment by MatthewDaggitt** [comment]
Closed with 8b7490b. Modules have been moved to new issue #408
