### ISSUE TITLE
Breaking change: Lift's definition

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#335]
In [`Lift`](https://agda.github.io/agda-stdlib/Level.html#350) the first level parameter is the one that can be easily inferred from
the `Set` passed as an argument whereas the second one is the one that is
always hard (if not impossible) to infer and thus needs to be passed explicitly.

I'd suggest to:

* either make `ℓ` the *first* implicit `Level` parameter
* or make `ℓ` an *explicit* `Level` parameter

At the moment I favour the second option.

**Comment by JacquesCarette** [comment]
I would also prefer the second option.

**Comment by andreasabel** [comment]
My hunch would be that the first option is a bit more conservative, at least `Lift {l = b} A` would still pass.  However, the error one gets from an old `Lift {b} A` would be more confusing.

**Comment by gallais** [comment]
This should come after #343
