### ISSUE TITLE
Breaking change: renaming Data.Product's ,_

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#339]
Since operator sections have been introduced there's a conflict between [`,_`](https://agda.github.io/agda-stdlib/Data.Product.html#1900)
and the right section of the constructor [`_,_`](https://agda.github.io/agda-stdlib/Agda.Builtin.Sigma.html#139). It makes this section practically
impossible to use except by hiding `,_` altogether at import time.

I suggest to rename `,_` to `-,_`. The dash is meant to suggest a `_` meaning
that the first component is left for the unifier to figure out.

**Comment by MatthewDaggitt** [comment]
Go for it.
