### ISSUE TITLE
IrrelevantPred and IrrelevantRel

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#341]
@gallais I think we got the location of `IrrelevantPred` and `IrrelevantRel` wrong in the last version...

Have a look at the contents of `Data.List.All`:
https://github.com/agda/agda-stdlib/blob/95963e218b5ae81f6e2da23d8b8b4d76b6d8f4a1/src/Data/List/All.agda#L67-L88

To be consistent with other properties such as `Decidable`, `Universal` etc. shouldn't they both be called `Irrelevant` and live in Relation.Unary` and `Data.Binary.Core` respectively?

**Comment by gallais** [comment]
I agree!

**Comment by MatthewDaggitt** [comment]
Closed with 6c7965f
