### ISSUE TITLE
Adding symmetric combinators for equational reasoning

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#344]
This is very minor, but I often find myself writing 
```
w ≡⟨ sym (p1) ⟩
x ≡⟨ p2 ⟩
y ≡⟨ sym (p3) ⟩
z ∎
```
The `sym (...)` tend to add a lot of noise to the proof, particularly when `p1` and `p2` are things like `+-assoc` or `+-identity` where the symmetry of equality really isn't aiding understanding. 

How about adding a reasoning combinator that automatically performs `sym` automatically? My two suggestions at the moment would be `_≡⟨_⟩ₛ_` or `_≡⟨ₛ_⟩_`. It would then be possible to write the much cleaner:
```
w ≡⟨ p1 ⟩ₛ
x ≡⟨ p2 ⟩
y ≡⟨ p3 ⟩ₛ
z ∎
```
The only thing downside that I see is that it might confuse new users...

**Comment by gallais** [comment]
I like the idea. The only opinion I have with respect to naming is that the character
making it clear we're using symmetry should be placed _before_ the placeholder
for the proof. This way your eyes do not have to jump to the end of the line
to check whether it's the `sym`'d version or not.

**Comment by MatthewDaggitt** [comment]
Okay, I'm happy to adopt `_≈˘⟨_⟩_`.
