### ISSUE TITLE
Some code relies on the module `MAlonzo.Code.Data.Colist` existing

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#348]
I have just managed to reproduce agda/agda#3145 and it comes from us:
in [`IO.Primitive`](http://agda.github.io/agda-stdlib/IO.Primitive.html#2024) we explicitly refer to `MAlonzo.Code.Data.Colist` when we
should now refer to `MAlonzo.Code.Codata.Musical.Colist`.

I'll push a fix in a little bit.

This highlights once again the fact it'd be nice to also have compilation tests
on travis.

**Comment by MatthewDaggitt** [comment]
That's weird, I'm not sure that can be the source of @alhassy's problem, as that `Data.Colist` only disappeared yesterday... whereas they opened the bug report 6 days ago.

**Comment by gallais** [comment]
Oh you're right. I misremembered the original bug report: the `Not in scope: MAlonzo.Code.Data.Product.XXX` collapsed in my mind with the mention of
`Colist` and when I saw the `Not in scope: MAlonzo.Code.Data.Colist.XXX`
in my shell, I was pretty convinced it was the same error.

Oh well. We'll see what happens next.

**Comment by MatthewDaggitt** [comment]
Well nice fix anyway!
