### ISSUE TITLE
Breaking change: give `_$_` a fixity of `-1`

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#351]
The problem I'm currently facing is that both `_$_` and `_∋_` have the same level
however one associates to the right and the other to the left. This leads to a parse
error when I try to add the commented-out type annotation in `def`.

```agda
infixr 0 _$_ -- infixr -1 _$_
infixl 0 _∋_

_$_ : ∀ {a b} {A : Set a} {B : A → Set b} →
      ((x : A) → B x) → ((x : A) → B x)
f $ x = f x

_∋_ : ∀ {a} (A : Set a) → A → A
A ∋ x = x

postulate
  M : Set → Set
  A : Set
  _>>=_ : ∀ {A B} → M A → (A → M B) → M B
  return : ∀ {A} → A → M A
  ma : M A
  join : ∀ {A} → M (M A) → M A

def = join $ {- M (M A) ∋ -} do
  a ← ma
  return ma
```

Insisting that `_$_` binds strictly more than `_∋_` would fix that problem. Note
that there is a similar issue with the interaction of `_$_` and `_|>_`, however
I don't know if it's sensible to mix them in the same expression.

**Comment by gallais** [comment]
For the record, my current work-around to avoid putting parentheses around the whole
`do` block is to use `_∋_`'s right section and write `join $ (M (M A) ∋_) $ do (...)`.

**Comment by MatthewDaggitt** [comment]
I'm happy with the suggested fixity adjustment. I also agree that using `_|>_` in the same expression as `_$_` is probably going to be pretty uncommon...

**Comment by andreasabel** [comment]
I agree that `$` should somewhat have the "lowest priority".
