### ISSUE TITLE
Foreign.Haskell: COMPILE pragma lacks data keyword

### ISSUE THREAD

**Issue by semenov-vladyslav** [agda/agda-stdlib#370]
I guess https://github.com/agda/agda-stdlib/blob/master/src/Foreign/Haskell.agda#L28 should be
`{-# COMPILE GHC Pair = data MAlonzo.Code.Foreign.Haskell.AgdaPair ((,)) #-}`

**Comment by gallais** [comment]
Sorry about that. Thanks for the report!
