### ISSUE TITLE
Replace MonadZero & MonadPlus with ApplicativeZero and ApplicativePlus

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#381]
The "zippy" applicative for `Codata.Delay` is not a monad but it is an `ApplicativeZero` and an `ApplicativePlus`.

Questions:

* Should `ApplicativePlus` be called `Alternative` as in Haskell?

**Comment by MatthewDaggitt** [comment]
> Should ApplicativePlus be called Alternative as in Haskell?

Not sure! I'm happy to defer to other people.

Why would this be a breaking change. Neither of those structures seem to exist right now?

**Comment by gallais** [comment]
> Why would this be a breaking change. Neither of those structures seem to exist right now?

I assume we would drop `RawMonad(Zero/Plus)` because every Monad is an Applicative.
So `RawMonadZero` is `RawMonad` + `RawApplicativeZero`.

**Comment by ice1000** [comment]
I like the name `Alternative`!

**Comment by MatthewDaggitt** [comment]
@gallais is this imminent or should I remove it from the v1.0 milestone?
