### ISSUE TITLE
Refactoring in Function.Related.TypeIsomorphisms

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#389]
* [x] lift semigroups (and related definitions) to the toplevel
* [x] Are `Σ-assoc` and `×-comm` instances of [`bijection`](https://agda.github.io/agda-stdlib/Function.Inverse.html#2377)?

**Comment by MatthewDaggitt** [comment]
I've tried to do this, but after refactoring, type checking takes 10 minutes on my computer. I've never come across something like it in the library. At some point I plan to play around with it a bit more, but feel free to have a go in the mean time!
