### ISSUE TITLE
Remove `Data.Char.Core`?

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#401]
It's empty, it's only used by `Data.String.Base` which could import the `Char` type
directy from `Agda.Builtin.Char` rather than via this one level of indirection.

Edit: [the module in question](https://agda.github.io/agda-stdlib/Data.Char.Core.html)

**Comment by MatthewDaggitt** [comment]
Yup seems good. As its `Core` module in theory no one should ever be using it!
