### ISSUE TITLE
List of deprecated modules

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#408]
Following up from #331. This is the list of currently deprecated modules:

Version 0.16

- [x] ./src/Data/Plus.agda
- [x] ./src/Data/ReflexiveClosure.agda
- [x] ./src/Data/Star.agda
- [x] ./src/Data/Star/Properties.agda
- [x] ./src/Relation/Binary/EquivalenceClosure.agda
- [x] ./src/Relation/Binary/SymmetricClosure.agda

Version 0.17

- [x] ./src/Data/Fin/Dec.agda

Version 1.0

- [x] ./src/Relation/Binary/EqReasoning
- [x] ./src/Relation/Binary/SetoidReasoning
- [x] ./src/Relation/Binary/PreorderReasoning
- [x] ./src/Relation/Binary/PartialOrderReasoning
- [x] ./src/Relation/Binary/StrictPartialOrderReasoning
- [x] ./src/Data/List/Relation/BagAndSetEquality.agda
- [x] ./src/Data/List/Relation/Equality/DecPropositional.agda
- [x] ./src/Data/List/Relation/Equality/DecSetoid.agda
- [x] ./src/Data/List/Relation/Equality/Propositional.agda
- [x] ./src/Data/List/Relation/Equality/Setoid.agda
- [x] ./src/Data/List/Relation/Lex/Core.agda
- [x] ./src/Data/List/Relation/Lex/NonStrict.agda
- [x] ./src/Data/List/Relation/Lex/Strict.agda
- [x] ./src/Data/List/Relation/Permutation/Inductive.agda
- [x] ./src/Data/List/Relation/Permutation/Inductive/Properties.agda
- [x] ./src/Data/List/Relation/Pointwise.agda
- [x] ./src/Data/List/Relation/Sublist/Propositional.agda
- [x] ./src/Data/List/Relation/Sublist/Propositional/Properties.agda
- [x] ./src/Data/List/Relation/Sublist/Propositional/Solver.agda
- [x] ./src/Data/List/Relation/Subset/Propositional.agda
- [x] ./src/Data/List/Relation/Subset/Propositional/Properties.agda
- [x] ./src/Data/List/Relation/Subset/Setoid.agda
- [x] ./src/Data/List/Relation/Subset/Setoid/Properties.agda
- [x] ./src/Data/List/All.agda
- [x] ./src/Data/List/All/Properties.agda
- [x] ./src/Data/List/Any.agda
- [x] ./src/Data/List/Any/Properties.agda
- [x] ./src/Data/Product/Relation/Lex/NonStrict.agda
- [x] ./src/Data/Product/Relation/Lex/Strict.agda
- [x] ./src/Data/Product/Relation/Pointwise/Dependent.agda
- [x] ./src/Data/Product/Relation/Pointwise/NonDependent.agda
- [x] ./src/Data/Sum/Relation/LeftOrder.agda
- [x] ./src/Data/Sum/Relation/Pointwise.agda
- [x] ./src/Data/Table/Relation/Equality.agda
- [x] ./src/Data/Vec/Relation/Equality/DecPropositional.agda
- [x] ./src/Data/Vec/Relation/Equality/DecSetoid.agda
- [x] ./src/Data/Vec/Relation/Equality/Propositional.agda
- [x] ./src/Data/Vec/Relation/Equality/Setoid.agda
- [x] ./src/Data/Vec/Relation/Pointwise/Extensional.agda
- [x] ./src/Data/Vec/Relation/Pointwise/Inductive.agda
- [x] ./src/Data/Vec/All.agda
- [x] ./src/Data/Vec/All/Properties.agda
- [x] ./src/Data/Vec/Any.agda
- [ ] ./src/Induction/WellFounded.Inverse-image
- [ ] ./src/Induction/WellFounded.Transitive-closure

Version 1.1

- [x] ./src/Induction/Nat.agda
- [x] ./src/Record.agda
- [x] ./src/Universe.agda
- [x] ./src/Data/Product/N-ary.agda
- [x] ./src/Data/Product/N-ary/Properties.agda
- [x] ./src/Data/Product/N-ary/Categorical.agda
- [x] ./src/Data/List/Relation/Binary/Permutation/Inductive.agda
- [x] ./src/Data/List/Relation/Binary/Permutation/Inductive/Properties.agda

Version 1.2

- [x] ./src/Data/Bin
- [x] ./src/Data/Bin/Properties
- [x] ./src/Data/BoundedVec
- [x] ./src/Data/BoundedVec/Inefficient
- [x] ./src/Data/Table
- [x] ./src/Data/Table/Base
- [x] ./src/Data/Table/Properties
- [x] ./src/Data/Table/Relation/Binary/Equality

Version 1.3

- [ ] ./src/Algebra/Solver/Monoid
- [ ] ./src/Algebra/Solver/Ring(/*)

It would be nice if we could have some warning mechanism for these as well, but its not exactly a priority.

**Comment by JacquesCarette** [comment]
I would google each one in turn.  Taking "Data.Fin.Dec" as an example,
[this search](https://www.google.com/search?num=20&newwindow=1&client=ubuntu&hs=bo1&channel=fs&ei=7OzpW93UKeri0gKE6r2IAg&q=filetype%3Aagda+%22Data.Fin.Dec%22&oq=filetype%3Aagda+%22Data.Fin.Dec%22&gs_l=psy-ab.3...7697.8529.0.8689.4.4.0.0.0.0.62.210.4.4.0....0...1c.1.64.psy-ab..0.0.0....0.VMzlotNyhWY)
returns few hits, most of them from @nad's online view of the library, and others from older code repos (copies of lib-0.5 for example).  The few people can then be warned.  If some such search turns up a lot of code, I would perhaps be less eager to remove it quite yet.

I think I may have code that uses a couple of these (such as `Data.Nat.Properties.Simple`), but it wouldn't be so hard to upgrade them.  If I got an official ping to do so, I probably would. Unlike a deprecation warning, which I might never see, because I might not have loaded that particular piece of Agda in 3 years!

**Comment by gallais** [comment]
Done. Except for `./src/Data/List/Relation/Sublist/Propositional/Solver.agda` which
does not seem to exist anymore.

**Comment by MatthewDaggitt** [comment]
Fantastic, thanks!

Hmm that one must have got lost in the reorganisation of sublist... As it was a fairly new module and fairly niche, I don't think it's a disaster.

I'll close this issue after merging in the PR as we can always find this list again via a quick grep.
