### ISSUE TITLE
Missing RawStructure in Algebra

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#425]
In `Algebra` we have `RawMonoid` and `RawRing` but we are missing `RawSemigroup`, `RawBand`, etc.

It's useful to have both:
* implement the functions with the `Raw` version (cf. [`Data.Product.Categorical.Left`](https://agda.github.io/agda-stdlib/Data.Product.Categorical.Left.html))
* use the other version when proving (cf. [`Data.Product.Categorical.Examples`](https://agda.github.io/agda-stdlib/Data.Product.Categorical.Examples.html))

In #424 I've used a full `Semigroup` to write `toSemigroup : These A A → A` but in practice I really just want a `RawSemigroup`.

**Comment by MatthewDaggitt** [comment]
Hmm in the case of #424 do you even want a raw semigroup as I don't think you use equality? Couldn't you make do with an `Op₂`?

I agree we should probably add them though!

**Comment by gallais** [comment]
> Couldn't you make do with an `Op₂`?

I could. And maybe I should.
