### ISSUE TITLE
Standardise use of ~ symbol

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#428]
As pointed out by @mwageringel in #427, in some modules we're inconsistent with our use of `~` and `\sim`.

* [ ] Relation.Unary
* [ ] Relation.Unary.Properties
* [x] Relation.Binary.HeterogeneousEquality.Quotients.Examples
* [x] Data.List.Relation.Permutation.Inductive.Properties
* [x] Data.Vec.Relation.Pointwise.Inductive
* [x] Data.Vec.Relation.Pointwise.Extensional

(list generated using `find src/ -name "*.agda" | xargs grep "~" | sed -e "s|^src/\(.*\)\.agda.*$|\1|" | sed "s|/|.|g" | uniq`)

**Comment by gallais** [comment]
This is the sort of thing we should be checking with scripts on travis to maintain consistency.

Is there anywhere we actually want `tilde`?

**Comment by MatthewDaggitt** [comment]
Hmm so we use `tilde` in the following places:

- `Data/List/Relation/Permutation/Inductive/Properties` - inconsistent usage
- `Data/Vec/Relation/Pointwise/Inductive` - inconsistent usage
- `Relation/Binary/HeterogeneousEquality/Quotients/Examples` - inconsistent usage
- `Relation.Unary` - consistent usage
- `Relation.Unary.Properties` - consistent usage
