### ISSUE TITLE
Setoid version of `Data.List.Relation.Sublist.Inductive`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#432]
At the moment it is only propositional. The propositional version should probably be an instance of the setoid version.

**Comment by gallais** [comment]
I've just realized that there is no reason in particular to *demand* the relation is a `Setoid`.
I think I will generalize it further to an heterogeneous relation and implement the `Setoid`
version as a specialization of the core module.

**Comment by MatthewDaggitt** [comment]
Removing this from the upcoming release as currently blocked by issue. I've left a space for it in the hierarchy in #499.
