### ISSUE TITLE
Why just check for whitespaces instead of fixing them?

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-stdlib#442]
In makefile: https://github.com/agda/agda-stdlib/blob/master/GNUmakefile

```
check-whitespace:
    cabal exec -- fix-agda-whitespace --check
```

I have two questions:

1. why `cabal exec`? it will end up calling the one installed to my `$PATH` anyways, so why not just call it directly?
2. why just `--check`? if it fails, I would have to call `fix-agda-whitespace` to fix the spaces anyways, so why just not fix it?

So I would propose to turn this rule simply as following:

```
.PHONY: check-whitespace
check-whitespace:
    fix-agda-whitespace
```

what do you think?

**Comment by asr** [comment]
> 2. why just `--check`? if it fails, I would have to call `fix-agda-whitespace` to fix the spaces anyways, so why just not fix it?

Because when it fails you know *what* was *your* mistake. Moreover, if the whitespace issues were automatically fixed, it could be tedious *always* and *immediately* note it (in order to save the changes in your repository).

**Comment by HuStmpHrrr** [comment]
@asr you are absolutely right. I also realized that `--check` is also used in CI, so it would be terrible if CI fixes problems for commits.

**Comment by asr** [comment]
> 1. why `cabal exec`?

See `cabal exec --help`.
