### ISSUE TITLE
Split up `Data.Maybe` into the standard hierarchy.

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#446]
Into:

- `Data.Maybe.All`
- `Data.Maybe.Any`
- `Data.Maybe.Properties`
- `Data.Maybe.Relation.Pointwise`
- `Data.Maybe.Relation.Equality.Setoid`
- `Data.Maybe.Relation.Equality.DecSetoid`

**Comment by gallais** [comment]
I don't think we have anything to put in `Data.Maybe.Properties` at the moment.
Are `Data.Maybe.Relation.Equality.Setoid` and `Data.Maybe.Relation.Equality.DecSetoid`
wrappers around `Data.Maybe.Relation.Pointwise` instantiating the Relation to
the one contained in the `(Dec)Setoid`?

**Comment by MatthewDaggitt** [comment]
> I don't think we have anything to put in `Data.Maybe.Properties` at the moment.

`just-injective`?

> Are `Data.Maybe.Relation.Equality.Setoid` and `Data.Maybe.Relation.Equality.DecSetoid`
> wrappers around `Data.Maybe.Relation.Pointwise` instantiating the Relation to
> the one contained in the `(Dec)Setoid`?

Yes.

**Comment by gallais** [comment]
I guess `Pointwise` could be made heterogeneous.
