### ISSUE TITLE
CI seems broken

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-stdlib#448]
CI build fails when there is no reason to: https://travis-ci.org/agda/agda-stdlib/builds/424476021?utm_source=github_status&utm_medium=notification

```
...
Generating HTML for Data.AVL.IndexedMap (html/Data.AVL.IndexedMap.html).
Generating HTML for Data.AVL.Key (html/Data.AVL.Key.html).
Generating HTML for Data.AVL.NonEmpty (html/Data.AVL.NonEmpty.html).
Generating HTML for Data.AVL.Sets (html/Data.AVL.Sets.html).
Generating HTML for Data.Bin (html/Data.Bin.html).
Generating HTML for Data.Bin.Properties (html/Data.Bin.Properties.html).
Generating HTML for Data.Bool (html/Data.Bool.html).
Generating HTML for Data.Bool.Base (html/Data.Bool.Base.html).
Generating HTML for Data.Bool.Properties (html/Data.Bool.Properties.html).
/home/travis/.travis/job_stages: line 78:  4436 Killed                  agda -i . -i src/ --html index.agda
The command "agda -i . -i src/ --html index.agda" exited with 137.
```

Running it locally was successful:

```
$ agda -i . -i src/ --html index.agda
...
$ echo $?
0
```

**Comment by gallais** [comment]
Cf. #416 

We have been experiencing these for a few weeks now.

**Comment by HuStmpHrrr** [comment]
I see. Interestingly, indeed generating HTML uses way more memory than type checking.

**Comment by gallais** [comment]
> indeed generating HTML uses way more memory than type checking.

Did you use some magic command line incantation to get numbers?

**Comment by HuStmpHrrr** [comment]
@gallais 
https://unix.stackexchange.com/questions/5783/is-there-a-tool-that-allows-logging-of-memory-usage

```sh
top -d 1 -b | grep agda
```

on my 64-bit machine, it went up to 3.69GB for html, while 2GB for type checking.
