### ISSUE TITLE
No longer exporting propositional equality from `Relation.Binary`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#451]
This an issue retroactively asking for permission, as I got confused and accidentally pushed to master (cff09f0 ) :cry: My apologies, but hopefully it's not too contentious.

At the moment we had the bizarre situation where `Relation.Binary.Core` exported `_≡_`, `_≢_` and `refl` but `Relation.Binary.PropositionalEquality.Core` did not. This was causing some nasty dependency cycles when trying to rearrange indexed relations.

This is technically a breaking change as `Relation.Binary` no longer exports propositional `_≡_`, `_≢_` and `refl`. Everyone should have been importing them from `Relation.Binary.PropositionalEquality` anyway (it took me several years to even notice that they were exported by `Relation.Binary`).

Once again, my apologies.

**Comment by MatthewDaggitt** [comment]
Another thought. The new structure means we can actually keep backwards compatibility by having `Relation.Binary` export `Relation.Binary.PropositionalEquality.Core` publicly. It would be a little bizarre, but maybe we should and mark them as deprecated to delete later. Thoughts?

**Comment by HuStmpHrrr** [comment]
I find it's strange already that `Relation.Binary.Core` needs propositional equality. It's only used in two places:

```agda
Irrelevant : ∀ {a b ℓ} {A : Set a} {B : Set b} → REL A B ℓ → Set _
Irrelevant _∼_ = ∀ {x y} (a : x ∼ y) (b : x ∼ y) → a ≡ b

record IsEquivalence {a ℓ} {A : Set a}
                     (_≈_ : Rel A ℓ) : Set (a ⊔ ℓ) where
  field
    refl  : Reflexive _≈_
    sym   : Symmetric _≈_
    trans : Transitive _≈_

  reflexive : _≡_ ⇒ _≈_
  reflexive ≡-refl = refl
```

For the first one, I'd imagine this definition can be pulled out of `Relation.Binary.Core`, and then re-import from the new module.

For the second one, do we actually need `reflexive` in `IsEquivalence`? It's already a straightforward induction. We can probably define that `≡-setoid` induces any equivalence, so we have better implication in that case. Then we can have `Relation.Binary.PropositionalEquality.Core` export  `_≡_`.

**Comment by JacquesCarette** [comment]
I think that @HuStmpHrrr is onto something here.

But as to the title question: I think this breaking change is fine. `_≡_` should be gotten from `Relation.Binary.PropositionalEquality` for most purposes.

**Comment by MatthewDaggitt** [comment]
> Then we can have `Relation.Binary.PropositionalEquality.Core` export `_≡_`.

Ah no, I think there might a misunderstanding. Commit cff09f0 fixes this problem and `Relation.Binary.PropositionalEquality.Core` now exports `_≡_`. So the problem is already fixed, but I opened this issue as I accidentally pushed to `master` rather opening a PR for a review.

As for the issues below, cff09f0 gets around it by having `Relation.Binary.Core` import `_≡_` directly from the `Builtin` module. 

> For the second one, do we actually need reflexive in IsEquivalence? It's already a straightforward induction. We can probably define that ≡-setoid induces any equivalence, so we have better implication in that case.

Removing `reflexive` from `IsEquivalence` would be an enormous breaking change, so I think that's probably off limits. As an aside it is now possible to move `IsEquivalence` to `Relation.Binary` if we wanted to. 

`Irrelevant` definitely belongs in `Relation.Binary.Core` in my opinion.

**Comment by MatthewDaggitt** [comment]
Given that nobody seems unhappy with the core change, I'm closing this. Feel free to open a new issue @HuStmpHrrr if you'd like to continue to discuss the design of `Relation.Binary.Core`.
