### ISSUE TITLE
Inconsistent naming convention: id-is-fold vs. idIsFold

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#465]
The first one is in `Data.Nat.GeneralisedArithmetic`, the other in `Data.List.Properties`.

**Comment by MatthewDaggitt** [comment]
Hmm so the second variant is definitely wrong. I'm pretty sure the first is as well. I think they should probably be `id-isFold` as we're not referring to a specific fold function. Or if we think that we need both variants then we should use `id-is-foldr` and `id-is-foldl`...

**Comment by MatthewDaggitt** [comment]
Closed with d77a0ed
