### ISSUE TITLE
A predicate on lists that knows the tails

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-stdlib#467]
Please suggest a proper name on this predicate. It's a reinforced `All` which I find missing.

Consider a predicate on checking `List` to be unique:

```agda
data Unique : List Carrier → Set (c ⊔ ℓ) where
  nil : Unique []
  cons : ∀ {x xs} → x ∉ xs → Unique xs → Unique (x ∷ xs)
```

This pattern is very general, and can be expressed using a more general prediate:

```agda
data Predicate (P : Carrier → List Carrier → Set ℓ₂) : List Carrier → Set (c ⊔ ℓ) where
  nil : Unique []
  cons : ∀ {x xs} → P x xs → Predicate P xs → Predicate P (x ∷ xs)
```

This is effectively,

```agda
Predicate′ P l = All (λ { [] → ⊤ ; (h ∷ t) → P h t}) (tails l)
```

but this definition is obscure and its meaning is not as immediate as an inductive definition. I have several occasions requiring this predicate so I guess I am not alone. How do you think such relation should be named?

**Comment by gallais** [comment]
Given that it's equivalent to an `All` applied to `tails`... `AllTails`?

**Comment by MatthewDaggitt** [comment]
See #147 as well for an alternative predicate for formulating `Unique` (and `Sorted`, `Ascending`, `Descending` etc.).

**Comment by HuStmpHrrr** [comment]
wow that was a year ago. so i guess a small technical decision to make is whether we want to make it a relation between heads and tails, or adjacent pairs. I find heads and tails is better, because if we want this predicate, the chances are we want to express relations between any pairs, and it's immediate from this predicate.

**Comment by gallais** [comment]
Thinking about this and II/IR, I realised this pattern can also be used to define
the inductive-(inductive/recursive) versions.

The typical example of such a list is one where `R` is a (decidable) equivalence
relation. We get the definition of fresh lists (what Jason calls `Unique`).

```agda
open import Level
open import Data.Empty
open import Data.Unit
open import Data.Bool
open import Relation.Binary using (Rel; Decidable)
open import Relation.Unary using (Pred)
open import Relation.Nullary.Decidable using (⌊_⌋)

module II {a r} {A : Set a} (R : Rel A r) where

  data ListR : Set (a ⊔ r)
  data AllR (a : A) : ListR → Set r

  data ListR where
    []     : ListR
    _∷_by_ : (a : A) (as : ListR) → AllR a as → ListR

  data AllR a where
    []  : AllR a []
    _∷_ : ∀ {b bs allbbs} → R a b → AllR a bs → AllR a (b ∷ bs by allbbs)


module IR {a r} {A : Set a} (R : Rel A r) (R? : Decidable R) where

  data ListR : Set (a ⊔ r)
  AllR : A → ListR → Set r

  data ListR where
    []     : ListR
    _∷_by_ : (a : A) (as : ListR) → AllR a as → ListR

  AllR a []             = Lift r ⊤
  AllR a (b ∷ bs by pr) = if ⌊ R? a b ⌋ then AllR a bs else Lift r ⊥
```

I don't know if it's worth adding one of these to the stdlib.

**Comment by HuStmpHrrr** [comment]
Isn't `AllR R a` just `All (R a)`?

**Comment by gallais** [comment]
`ListR` and `AllR` are defined mutually; you wouldn't be able to use `All (R a)` here.
But yeah it's basically `All (R a)`.

**Comment by gallais** [comment]
It's the usual extrinsic vs. intrinsic debate (is it better to have a `Fin n` or a nat `k`
such that `k < n`?). And quite often one is not better than the other, they are just
more or less suited to the problem at hand.
