### ISSUE TITLE
Records in `Relation.Binary.Lattice` should have internal `Eq` module

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#469]
See `Relation.Binary` for details.

**Comment by HuStmpHrrr** [comment]
my latest PR #470 added `setoid` into  `Lattice`, which effectively is an `Eq` module.

**Comment by MatthewDaggitt** [comment]
Great! Although we should keep it consistent with `Relation.Binary` and keep naming and implementation the same.

**Comment by HuStmpHrrr** [comment]
Right, they are actually not exactly the same. Indeed adding `Eq` can avoid renaming everywhere.

**Comment by HuStmpHrrr** [comment]
In fact, the `Eq` module got exported all the way along from `IsPreorder` to `Lattice`, so it's there already.
