### ISSUE TITLE
Distinguishing Reasoning of Preorder and Partial Order

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-stdlib#471]
Currently, PartialOrderReasoning is defined is be (almost) identical to PreorderReasoning: 
https://github.com/agda/agda-stdlib/blob/master/src/Relation/Binary/PartialOrderReasoning.agda

It makes sense but I do not find this API should end here. Poset has given enough information to also talk about equivalence. I find PartialOrderReasoning should also be effectively a combination of PreorderReasoning and EqReasoning, and potentially makes use of antisymmetry to derive equivalence from ordering.

Is there any idea on how the API should look like to make the syntax look smoother?

**Comment by MatthewDaggitt** [comment]
See #185. Using @UlfNorell's starting point, I've worked out how to integrate true strict inequality reasoning. It'll be added in when I get the time...

**Comment by HuStmpHrrr** [comment]
great. will it be about strict order only or enrich poset as well using the same idea? I can see the pattern is quite applicable in making reasoning APIs more flexible in general.

**Comment by HuStmpHrrr** [comment]
I think we can add another case to this definition:

```agda
  data _≲_ (x y : A) : Set (ℓ₂ ⊔ ℓ₃) where
    strict    : x < y → x ≲ y
    nonstrict : x ≤ y → x ≲ y
    eq : x = y → x ≲ y
```

Then the reasoning steps can maintain the variance that `eq` can convert to `nonstrict`, `nonstrict` can convert to `strict`. We then should be able to obtain an API on all three relations.

**Comment by MatthewDaggitt** [comment]
Hmm interesting idea! Not sure off the top of my head if that would work. Feel free to copy my code and give it a go at integrating it.

Even if it does work out, then I'm undecided at first glance whether we should include in a module for reasoning about orders. I'll give it some thought. Also can we transfer this discussion to #185 please!
