### ISSUE TITLE
Pointwise lifting of relations to Sums

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#472]
Where should we put the following?

```agda
data Pointwise {a b c d r s} {A : Set a} {B : Set b} {C : Set c} {D : Set d}
               (R : REL A C r) (S : REL B D s)
               : REL (A ⊎ B) (C ⊎ D) (r ⊔ s) where
  inj₁ : ∀ {a c} → R a c → Pointwise R S (inj₁ a) (inj₁ c)
  inj₂ : ∀ {b d} → S b d → Pointwise R S (inj₂ b) (inj₂ d)
```

The current [`Data.Sum.Pointwise`](https://agda.github.io/agda-stdlib/Data.Sum.Relation.Pointwise.html) is

* lifting homogeneous relations
* awkwardly defined in terms of `Core.⊎ʳ` which has an extra case for `(inj₁ x, inj₂ y)` which packs a `P : Set` (so stuck at the bottom level and not taking into account `x` and `y`!) and no case for `(inj₂ y, inj₁ x)`.

**Comment by MatthewDaggitt** [comment]
Yes, I remember thinking that `Pointwise` for `Sum` looked very strange. I assume we'll have to sort it out at some point. I think re-implementing it in the above form makes a lot of sense.
