### ISSUE TITLE
Release of v0.17

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#475]
Given the torrent of changes over the past few months I feel a release of v0.17 is probably approaching. As there's still a few outstanding design decisions under discussion, we can keep the promised stability of v1.0 to coincide with the next major release of Agda. Thoughts?

**Comment by gallais** [comment]
The CHANGELOG is about as big as the ones for v0.14, v0.15, and v0.16 so I think it's
very reasonable.

**Comment by MatthewDaggitt** [comment]
Apologies all for being not very responsive for the past couple of weeks, busy trying to write up my thesis. I'll try and get the release ready at AIM in a couple of weeks.

**Comment by MatthewDaggitt** [comment]
I've updated all the milestone tags. If something doesn't have the v0.17 tag, it's not currently planned to make it into the next release (at the end of this week). If anyone has anything they'd desperately like to add to the release, now's the time to mention it.
