### ISSUE TITLE
About 0.16.1 and Agda 2.5.4.2

### ISSUE THREAD

**Issue by asr** [agda/agda-stdlib#479]
We are planning release Agda 2.5.4.2:

* I couldn't find the CHANGELOG for 0.16.1.

* Why didn't you update the submodule commit including the changes in 0.16.1 in the Agda repository? Which commit should I use for testing 2.5.4.2?

**Comment by asr** [comment]
Note that you are not testing the *current* master of the standard library in the master of Agda.

**Comment by gallais** [comment]
Yes but AFAIK there are no breaking changes (I typically use 2.6.0 on my laptop because of agda/agda#3199).

**Comment by asr** [comment]
Did you run the Agda test-suite with the current master of the standard library?

**Comment by MatthewDaggitt** [comment]
Hmm, yes I seem to have omitted adding a specific changelog for 0.16.1 for some reason. Apologies. As @gallais pointed out the tag v0.16.1 is the right commit though.

**Comment by asr** [comment]
> I can see the tag `v0.16.1` on github but not locally. This seems suspicious.

Run `git fetch --tags`.

**Comment by asr** [comment]
Thanks. I updated the submodule commit to 0.16.1 in the `release-2.5.4.2` branch.

**Comment by asr** [comment]
> Did you run the Agda test-suite with the current master of the standard library?

I did. Please see https://github.com/agda/agda/issues/3237.
