### ISSUE TITLE
Inconsistent naming convention: irrelevant vs. irrelevance

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#485]
The vast majority of the library uses `irrelevance` except for 3 proofs:

* [ ] Data/List/Relation/Sublist/Inductive/Properties.agda:  []∈-irrelevant : U.Irrelevant {A = List A} ([] ⊆_)
* [ ] Data/List/All.agda:  irrelevant : Irrelevant P → Irrelevant (All P)
* [ ] Data/Vec/All.agda:  irrelevant : Irrelevant P → ∀ {k} → Irrelevant (All P {k})

**Comment by MatthewDaggitt** [comment]
Hmm well in this case the majority is in the wrong? Given that the property is called `Irrelevant` the name should be `irrelevant`...
