### ISSUE TITLE
Add a -Reasoning module for compatible posets & strict partial orders

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#493]
Cf. https://github.com/agda/agda-stdlib/pull/491/commits/bb2b7ab08791fce538de7c307425e071d3390fcf for an idea of how to implement something like this.

We should get this kind of proofs:

```agda
x<a : x < a
x<a = begin
  x ≤⟨ _ ⟩
  y <⟨ _ ⟩
  z ≡⟨ _ ⟩
  a ∎
```

**Comment by MatthewDaggitt** [comment]
I'm pretty sure this is a duplicate of #185.
