### ISSUE TITLE
Inconsistency:  ∈-map⁺ in (Vec/List).Membership

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#503]
In [List](https://agda.github.io/agda-stdlib/Data.List.Membership.Propositional.Properties.html#3428) the function is implicit

In [Vec](https://agda.github.io/agda-stdlib/Data.Vec.Membership.Propositional.Properties.html#1165) it is explicit.

**Comment by MatthewDaggitt** [comment]
Looks like it should be explicit in both cases.
