### ISSUE TITLE
Inconsistency: `map-compose` vs. `map-∘`

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#509]
In [`Data.List.Properties`](https://agda.github.io/agda-stdlib/Data.List.Properties.html#2896) we use `map-compose` whereas in [`Data.Vec.Properties`](https://agda.github.io/agda-stdlib/Data.Vec.Properties.html#5621) we use `map-∘`.

**Comment by gallais** [comment]
And in `Codata.*` we use `map-map-fusion`.

**Comment by jamesmckinna** [comment]
Suggest `map-∘` throughout?

**Comment by gallais** [comment]
:+1:  That is consistent with the convention we use

**Comment by gallais** [comment]
I see that we also have [map-++-commute](https://agda.github.io/agda-stdlib/Data.List.Properties.html#3178) instead of `map-++`.

**Comment by jamesmckinna** [comment]
And similarly [sum-++-commute](https://agda.github.io/agda-stdlib/Data.List.Properties.html#20000). 
I'll open a PR.

**Comment by jamesmckinna** [comment]
Fixed them in `Data.Maybe.Properties`.

**Comment by JacquesCarette** [comment]
I wonder if `map-++-commute` might have been my doing. I like that name... but I'm completely fine with `map-++` if that's the library convention.

**Comment by jamesmckinna** [comment]
@JacquesCarette I take your point about 'small' PRs: but #626 and #509 are about consistency/uniformity of names *according to a systematic library convention* (whose stipulation to a large extent is neither here nor there; consistency is the main consideration here); the case of `map-id(entity)` was, at least on my reading, of the same order of need for consistency, as that of `map-∘` which started this issue for milestone 2.0...

I'm certainly open to the possibility that `Codata.*` properties might better want distinct names, to draw attention to the fact that 
* in the case of `-identity`, the relation is that of bismilarity, not equality
* in the case of `-∘`, that the direction of the equation is opposite to that in `Data.*`
For this reason, I have stopped pushing commits regarding the `Codata` changes.

**Comment by JacquesCarette** [comment]
@jamesmckinna it is indeed a philosophical disagreement. You see this PR as achieving consistency/uniformity as a complete unit, while I'd be quite happy with a sequence of PRs whose union would achieve that. Moving closer to the goal is worthwhile, even if the ultimate goal (for whatever reason) is not ultimately achieve for 2.0. [I use this philosophy quite strongly in my Drasil project.]

Ultimately the person who is actually doing the work gets to decide, as this is all volunteer work. I believe in that 'philosophy' even more strongly than in the above!

**Comment by jamesmckinna** [comment]
Thanks for clarification. Given our discussion on Monday about the 2.0 milestone, I was indeed keen to achieve 'completeness' in closing these two issues. But yes, experience with git(hub) has taught me that small(er) steps are usually better. But this one, 'bigger' as it may seem, has proved largely routine. Updating `CHANGELOG` is perhaps another matter.

**Comment by jamesmckinna** [comment]
Updated `CHANGELOG`.

**Comment by jamesmckinna** [comment]
Outstanding instances of `-commute`:
- [ ] `Data.Sum.Properties` affecting `Data.Fin.Properties` and `Data.Vec.Properties` through `[,]-map-commute`, plus a couple of other `map-commute`-like lemmas not used elsewhere
- [ ] `Data.Vec.Recursive.Properties` with a single lemma `append-cons-commute` used only internally
- [ ] `Data.Tree.Binary.Zipper.Properties` with a number of `toTree-*-commute` lemmas
- [ ] `Data.Integer.Properties` affecting `Data.Integer.Coprimality`, `Data.Integer.Divisibility.Signed`, `Data.Integer.Divisibility`, `Data.Integer.DivMod` through `abs-*-commute` and `pos-+-commute`, which I therefore do not propose tackling until issue #501 is resolved
- [ ] `Data.Rational.Properties`, affected by `ℤ.abs-*-commute`, ditto.
Only the first really seems worth tackling; the second two are leaf modules in the library dependency graph; and the last two seem to require some prior work on #501 before proceeding. Suggestions as to how to proceed further?

**Comment by JacquesCarette** [comment]
Did these naming conventions ever make it into a style guide (or the like)?

**Comment by jamesmckinna** [comment]
@JacquesCarette  writes:
> Did these naming conventions ever make it into a style guide (or the like)?

Not that I'm aware of. Probably worth revisiting as part of the `library-design` discussions. The invocation of the *implied* style rules in #3060 seems, to me, debatable at the very least, so it would be good to try to 'standardise'. Unsurprisingly, I have Opinions on the matter, and my position may very well have evolved from whatever I was doing on this issue and associated PRs 4+ years ago, or indeed from whatever principles the library designers from 2018 had in mind... ;-)
