### ISSUE TITLE
Deploy doc for released versions

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#513]
I have deployed to the gh-pages branch the html documentation for v0.17.
As with the dev documentation there are a few entry points:

* https://agda.github.io/agda-stdlib/v0.17/
* https://agda.github.io/agda-stdlib/v0.17/safe.html
* https://agda.github.io/agda-stdlib/v0.17/README.html
* https://agda.github.io/agda-stdlib/v0.17/Everything.html
* https://agda.github.io/agda-stdlib/v0.17/EverythingSafe.html

It may be worth deploying similar documentation for v0.16 and maybe even a couple
of earlier versions for people still stuck a few versions in the past (debian only has
v0.14 for instance).

Otherwise questions:

* Should we point to this from the wiki?
* Should we mention it in the README?
* Should we document somewhere how to do it?

**Comment by MatthewDaggitt** [comment]
All of those suggestions sound good.

**Comment by gallais** [comment]
Updates:

* I have added docs for v0.16 (7cd645c26af8a1618f1751b30d5ea677cdc84a5c)
* We need to explicitly tell travis to not erase these (c265cc9911e92870345291052e37712fc7067327)

**Comment by jamesmckinna** [comment]
Can this be closed now, or is it still undocumented
* how/what to do for a new release?
* what our position is on `experimental` vs. `master` now? (Ob which, is there any branch development off experimental at the moment? Any more?)

**Comment by gallais** [comment]
> * how/what to do for a new release?

We do have [this step in the release guide](https://github.com/agda/agda-stdlib/blob/master/doc/release-guide.txt#L64-

**Comment by jamesmckinna** [comment]
And also https://github.com/agda/agda-stdlib/blob/master/doc/updating-experimental.txt so closing this issue now!
