### ISSUE TITLE
Argument order of Codata.Delay.Delay

### ISSUE THREAD

**Issue by andreasabel** [agda/agda-stdlib#515]
We have currently
```agda
data Delay {ℓ} (A : Set ℓ) (i : Size) : Set ℓ where
```
but I think swapping `A` and `i` would be more natural; then `Delay {ℓ} i` would be a monad.

**Comment by gallais** [comment]
The same applies to `Stream`, and `Colist`.

**Comment by gallais** [comment]
Note however that the current order of arguments allows us to write clean types for
functions which have a guarded argument such as:

```agda
 _⁺++_ : ∀ {i} → List⁺ A → Thunk (Stream A) i → Stream A i
interleave : ∀ {i} → Stream A i → Thunk (Stream A) i → Stream A i
```

and we are only forced to use a λ-abstraction in `Codata.X.Categorical` AFAIK:

```agda
functor : ∀ {ℓ i} → RawFunctor {ℓ} (λ A → Stream A i)
```

**Comment by MatthewDaggitt** [comment]
After discussion it's not clear that this is an improvement over the current definition so marking as won't fix.
