### ISSUE TITLE
Extract Algebra.Construct.Polynomial from Algebra.Solver.Ring?

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#519]
These polynomials can be useful in their own right, outside of the context of the solver.

**Comment by MatthewDaggitt** [comment]
More difficult that it looks. Extracting it causes unsolved metas when using the ring solver in `Function.Related.TypeIsomorphisms.Solver`...

**Comment by gallais** [comment]
Weirdly enough, if we write `module ×-⊎-Solver {ℓ} (k : Symmetric-kind) = ...` instead
of `module ×-⊎-Solver (k : Symmetric-kind) {ℓ} =` the unsolved metas go away.

I'll push what I have at the moment.

**Comment by MatthewDaggitt** [comment]
Oh because it won't be accessible from the same module. Silly question, sorry.

**Comment by gallais** [comment]
Cf. #536:

> Given that the datatype defines `:-_`, we can't give it a semantics with a basic
ring, we need the solver-specific AlmostCommutativeRing which I find too specific.
I am giving up on this.
