### ISSUE TITLE
Finding a solution to the CHANGELOG merge-conflict-hell

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#521]
Most of the conflicts we are getting these days AFAICT are from the CHANGELOG. This is
rather annoying as the conflicts shouldn't exist in the first place and the process of manually
merging is rather error prone. I often feel overwhelmed by the size of these changes; especially
across a release boundary.

This blog post details a possible solution:

https://about.gitlab.com/2018/07/03/solving-gitlabs-changelog-conflict-crisis/

* Have a file per PR (we could have more; e.g. one for each of the major / othermajor / minor change categories)
* Merge these files using a script around release time

**Comment by MatthewDaggitt** [comment]
Hmm so I hadn't noticed it before we separated out all the CHANGELOGs, but yes the transition from v0.17 it has been painful. I'm hoping its going to get easier once this round of merges have been done.

Hmm that automated stuff looks cool, but pretty heavy duty. I guess it wouldn't be too infeasible to do it by hand though if we didn't get the automation up and running.

**Comment by gallais** [comment]
We are again in CHANGELOG hell even though we are not transitioning between two
different versions. So it would be nice to come up with a good design and solve
this once and for all.

**Comment by MatthewDaggitt** [comment]
Yup agreed, it is particularly bad at the moment. In principle I'm in favour of adding a new file per PR, but I do worry about findability. It's a) time consuming to scan them all and b) it's hard to notice that you may need to update a previous CHANGELOG entry.

The naming scheme for the files would also need to be solved as well. Presumably the Github issue number followed by something like the commit message?

On the other hand I'm not so fussed if we don't get a completely automated solution for the merging up and running. I'm happy enough to do it by hand at release time. I guess therefore I can handle problem b) at release time.

**Comment by gallais** [comment]
The advantage of having a script doing the merging is that we could get travis
to build and deploy an updated CHANGELOG automatically. This way we have the best
of both worlds.

**Comment by MatthewDaggitt** [comment]
That's true! Aside from the task of writing the script itself, I would guess we'd also need to be more standardised in our labelling of different types of changes. I have to admit at the moment the section headings change from release to release depending on how I feel it best fits together. Hardly ideal I know.

**Comment by gallais** [comment]
Abandoned.

**Comment by gallais** [comment]
Related: https://github.com/agda/agda-stdlib/pull/1039
