### ISSUE TITLE
Make use of new features in Agda 2.6.0

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#527]
We could either wait for it to be released or resurrect `experimental`.

* [x] Check the library with the `--safe` flag on
* [x] Use `primEraseEquality` (in `Agda.Builtin.Equality.Erase`)
* [x] Use generalisation
* [x] Use smarter coverage checker
* [ ] The warnings for missing fixities should now work properly

**Comment by MatthewDaggitt** [comment]
Given the problems we've had in the past, my gut feeling is that we should hold off for a while until 2.6.0 has a more firm release date? Unless I've missed something and it's coming out soon?

**Comment by UlfNorell** [comment]
We're aiming for a Christmas release, but as usual, no promises.

**Comment by MatthewDaggitt** [comment]
Hmm in that case we probably should get on it.

**Comment by MatthewDaggitt** [comment]
@gallais what does the last point on the list refer to?

**Comment by gallais** [comment]
It refers to #207

**Comment by MatthewDaggitt** [comment]
> It refers to #207

Okay thanks. Closing this as it has its own issue.
