### ISSUE TITLE
Add `Relation.Binary.PropositionalEquality.Properties`

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#531]
Cf. https://github.com/niccoloveltri/agda-clott/blob/0c1b3a656bea623f3cc1ef28f5f9fa2abb2520dc/code/Prelude/Basics.agda#L39 for some results we are missing

**Comment by MatthewDaggitt** [comment]
The module in question was added in https://github.com/agda/agda-stdlib/commit/acdad6ca3fb66846f2e81857addbcac50fc2fcba#diff-dc83cb768c1798ca009e932272034bb2f3cb77d5bce69b2364078fd0444bbb12 and we have at least one of the properties, so I'm closing this.
