### ISSUE TITLE
Inconsistent naming: toList(⁺/⁻) in `Data.Vec.All.Properties`

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#545]
Usually we use ⁺ when the codomain contains the function and ⁻ when it's the domain.
In this case we are doing the opposite: https://agda.github.io/agda-stdlib/Data.Vec.All.Properties.html#3410

(In Data.Vec.Any.Properties, we are doing the right thing)

**Comment by MatthewDaggitt** [comment]
Fixed with e27a146
