### ISSUE TITLE
Add --safe option

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#547]
Now that all (?) modules have an `OPTIONS` pragma at the top, should we
add the `--safe` one wherever we can?

**Comment by MatthewDaggitt** [comment]
Yup!

**Comment by gallais** [comment]
I'm guessins a sed script ought to do the trick though.

**Comment by dkrejsa** [comment]
Using current experimental branch of agda-stdlib with master branch of agda, upon loading code, AgdaInfo complains that

    /home/me/git/agda-stdlib/src/Data/Empty.agda:16,1-66
    COMPILE pragma not allowed in safe mode.
    when scope checking the declaration
      open import Data.Empty hiding (⊥-elim)

Should I be using a different branch for agda / agda-stdlib?

**Comment by ice1000** [comment]
Probably the `experimental` branch.

**Comment by dkrejsa** [comment]
Yes, I'm using the 'experimental' branch of agda-stdlib.
I don't see an 'experimental' branch of agda.

**Comment by ice1000** [comment]
Oh I'm sorry, I didn't read your comment correctly.
Yes, this should be a problem to be solved.

**Comment by xekoukou** [comment]
There are many ```safe``` options in files that have compile pragmas, so they fail.
examples : 
src/Codata/Musical/Colist.agda
src/Foreign/Haskell.agda

**Comment by dkrejsa** [comment]
For what I'm doing now, checking out v0.17 of agda-stdlib will be enough for me.  Thanks for confirmation, anyhow.

**Comment by identicalsnowflake** [comment]
Is there a reason this foreign binding is necessary? If not, I'd rather get rid of it or move it to a whitelisted builtin module (which seems justified - bottom is an awfully primitive type) than remove the safe flag.

**Comment by gallais** [comment]
I should have anticipated that agda/agda#2880 meant I needed to update experimental.

**Comment by mietek** [comment]
Removing the `COMPILE` pragmas for `Maybe`, specifically, has broken my code.

As there is no way to add a `COMPILE` pragma for `Maybe` outside of the `Data.Maybe` module (https://github.com/agda/agda/issues/3688), it seems that the only workaround is to stop using the stdlib for programs that are intended to be compiled and executed.

**Comment by gallais** [comment]
The [`Foreign.Haskell`](https://agda.github.io/agda-stdlib/experimental/Foreign.Haskell.html) modules give you access to an FFI-friendly `Maybe`.

The use-case is:

```agda
postulate
  foreignHead : List a -> Foreign.Haskell.Maybe a
{-# COMPILE GHC head = (...) #-}

head : List a -> Maybe a
head xs = fromForeignMaybe (foreignHead xs)
```

#826 discusses ways to make this translation smoother.
