### ISSUE TITLE
Rearranging `Data.X.Relation`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#558]
We need somewhere to put propositions not just binary relations over compositional data such as `List`. The suggestion from #556 is to move the existing `Data.X.Relation` hierarchy to `Data.X.Relation.Binary` and so make room for `Data.X.Relation.Unary` (and even `Data.X.Relation.Trinary` in the case of #529).

The old modules would be deprecated but still exist and at some point we'll get around to creating a `WARNING_ON_IMPORT` pragma that can be used to encourage people to migrate away from them.

Thoughts?

**Comment by gallais** [comment]
> Thoughts?

Trinary or Ternary?

**Comment by JacquesCarette** [comment]
Ternary!
