### ISSUE TITLE
Proposal on development version identification

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#561]
It has sense to assign an identifier to each Development version of Standard library, 
and to provide for an user a simple way to print out this version. 
Currently development versions often have different interfaces but declare the same version number when installed.

**Comment by HuStmpHrrr** [comment]
how do you use it? I normally put stdlib in my ~/.agda folder, so revision numbers automatically serve this purpose.

**Comment by mechvel** [comment]
I have not any ~/.agda folder.  Please, where to read about what to set there?
Will this folder help to distinguish any two Development library versions?
For example, I see two certain Development library versions that say that they are 0.17, while they have different item sets in the interface.

I often use Development version because it often occurs that I am stuck with a bug in the official version. So I download the library by  git  and give its folder a name after the date of downloading,
say,  dec7-2018/.

**Comment by gallais** [comment]
If you have obtained the library via `git clone`, you can go into that folder and use
`git log -n 1` to see which was the latest commit.

As for libraries management via text files in the `.agda` folder, you can read all about
it in the docs: https://agda.readthedocs.io/en/v2.5.4.2/tools/package-system.html

**Comment by MatthewDaggitt** [comment]
Responding to your question on the mailing list. We can change the build process to report the development version of the library to report `dev` instead of `v0.17`, but I don't know how to add the date.

**Comment by fredrikNordvallForsberg** [comment]
> We can change the build process to report the development version of the library to report dev instead of v0.17, but I don't know how to add the date.

Perhaps one could use the [gitrev package](http://hackage.haskell.org/package/gitrev) just as in the Agda development version (in `GenerateEverything.hs`?), but I'm not sure if this is worth the effort compared to @gallais's suggestion of `git log -n 1` above?

**Comment by HuStmpHrrr** [comment]
if it's just one or two projects that are sensitive to revisions of stdlib, I guess one thing you can do is to make stdlib a submodule of your projects, and twist a bit of your library file. Then automatically, when you switch projects, you will be using potentially different stdlibs, and when you switch branches, stdlibs can change to the right versions too. you will have full control over whether you need to update your stdlib, etc in this way.
