### ISSUE TITLE
Add the POSTULATE[_↦_] trick by Alan Jeffrey to TrustMe

### ISSUE THREAD

**Issue by np** [agda/agda-stdlib#57]
The definition @asajeffrey proposes is the following:

```
  POSTULATE[_↦_] : ∀ {ℓ m} {A : Set ℓ} {B : A → Set m} → ∀ a → B a → (∀ a → B a)
  POSTULATE[ a ↦ b ] a′ with trustMe {x = a} {a′}
  POSTULATE[ a ↦ b ] .a | refl = b
```

I propose to name it `postulate[_↦_]` because:
- it is a valid name as well
- will trigger if one "grep postulate"
- looks less loud

**Comment by asajeffrey** [comment]
The name change is fine by me. I just used all-caps so I could spot 
postulates easily.

**Comment by MatthewDaggitt** [comment]
Any chance either of you could write a quick description of what it does/what it's useful for? Something similar to that of `trustMe` and `erase` in `Relation.Binary.PropositionalEquality.TrustMe`.

**Comment by MatthewDaggitt** [comment]
Can anyone write a description for this and why its useful? Otherwise I'm going to assume that it's not needed anymore, and I'll close the issue.
