### ISSUE TITLE
 Broken invariant: the branch 2.4.2.1 is a subset of the master branch

### ISSUE THREAD

**Issue by asr** [agda/agda-stdlib#58]
The commits https://github.com/agda/agda-stdlib/commit/a85ed0ef2d57023982fdee7ea623f48921da82f2 and https://github.com/agda/agda-stdlib/commit/58ce7669ec5a0654cd21d2f0f7afcbb6e3440dc8 broke the invariant.

**Comment by nad** [comment]
On 2015-02-19 14:18, Andrés Sicard-Ramírez wrote:
> Assigned #58 <https://github.com/agda/agda-stdlib/issues/58> to @nad
> <https://github.com/nad>.

I didn't know about this invariant, but I think I've fixed the problem
now.

-- 
/NAD

**Comment by asr** [comment]
Yes, you fixed the issue.
