### ISSUE TITLE
Release v1.0

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#585]
The CHANGELOG is already 900+ lines long

**Comment by JacquesCarette** [comment]
This seems to be such a huge change that indeed waiting for 2.6.0 seems to 'make sense'. One big jump is better than two back to back.

**Comment by MatthewDaggitt** [comment]
Okay with the release candidate out for 2.6.0 we'd better get our socks on. I'll be doing a sweep of the issues.

**Comment by MatthewDaggitt** [comment]
Release happening on Monday (https://github.com/agda/agda/issues/3391)

**Comment by MatthewDaggitt** [comment]
Note that the release is ready and I'm only waiting to check that there are no more unforeseen changes in Agda 2.6.0 itself (e.g. 4a53aea5c67e69e894c011f2c27b387d2e08c44f). This means that the master branch no longer works with Agda 2.5.4.2.

**Comment by xuanruiqi** [comment]
When is the release happening?

**Comment by MatthewDaggitt** [comment]
> When is the release happening?

The short answer is whenever Agda 2.6.0 releases. Presumably later this week. I'm waiting in case there are any more breaking changes before it does so (the library needed changes between release candidate 1 and release candidate 2).

There are also two last minute bug fixes in the pipeline here.

**Comment by MatthewDaggitt** [comment]
Version 1.0 of library has been released. Thank you everyone for all your hard work, couldn't have been done without everyone's help!

**Comment by gallais** [comment]
Thanks a lot Matthew!
