### ISSUE TITLE
foldl-≗foldr∘reverse

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#59]
It is probably natural  to add to Standard library the following two lemmas.
```
  foldr-ys++y-eq : ∀ {α β} {A : Set α} {B : Set β} →
                            (f : A → B → B) → (x : B) → (y : A) → (ys : List A) →
                           foldr f x (ys ∷ʳ y) ≡ foldr f (f y x) ys

  foldl-≗foldr∘reverse : ∀ {α β} {A : Set α} {B : Set β} →
                                     (f : A → B → B) → (x : B) → (ys : List A) →
                                    foldl (flip f) x ys ≡ foldr f x (reverse ys)
```
Need them to be added?

**Comment by andreasabel** [comment]
Yes, this probably would make sense (if nothing comparable is there).

**Comment by mechvel** [comment]
So, I suggest for Standard library (if nothing comparable is there):

foldr-ys++y-eq : ∀ {α β} {A : Set α} {B : Set β} →
  (f : A → B → B) → (x : B) → (y : A) → (ys : List A) →
  foldr f x (ys ∷ʳ y) ≡ foldr f (f y x) ys

foldr-ys++y-eq _ _ _ []       =  PE.refl
foldr-ys++y-eq f x y (z ∷ ys) =  PE.cong (f z) $ foldr-ys++y-eq f x y ys

--------------------------------------------------------------------------------------------
foldl≗foldr∘reverse : ∀ {α β} {A : Set α} {B : Set β} →
                              (f : A → B → B) → (x : B) → (ys : List A) →
                              foldl (flip f) x ys ≡ foldr f x (reverse ys)

foldl≗foldr∘reverse _ _  []       =  PE.refl
foldl≗foldr∘reverse f xs (y ∷ ys) =  
       PE.sym $
       ≡begin
         foldr f xs (reverse (y ∷ ys))      ≡[ PE.cong (foldr f xs)
                                                            rev-yys≡rev-ys++y ]
         foldr f xs ((reverse ys) ∷ʳ y)     ≡[ foldr-ys++y-eq f xs y
                                                                   (reverse ys) ]
         foldr f (f y xs) (reverse ys)       ≡[ PE.sym $ foldl≗foldr∘reverse
                                                                              f (f y xs) ys ]
         foldl ff (f y xs) ys
       ≡end
       where  rev-yys≡rev-ys++y =  unfold-reverse y ys
                   ff = flip f

(the implementation can be changed to something appropriate).

**Comment by MatthewDaggitt** [comment]
Added in 45c59f4 (named `foldr-reverse`)
