### ISSUE TITLE
extend Rational to Fraction 

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#590]
I propose to introduce to Standard the Fraction domain constructor for arbitrary GCDRing.
This will replace  Rational with Fraction Integer,
and it also will provide rational functions (ratios of polynomials), and many other fraction domain instances.

i have a small code for this that is based on Standard library, only it adds the structures of certain
DecIntegralRing and GCDRing. 
There are two obstacles for submitting this code to GitHub as a proposal. First, it runs under a Development Agda and a certain experimental branch of Development library. Probably I need to wait for something more stable (?). 
Second,  it uses in a couple of places my home-made CommutativeSemiringSolver. Probably, it can be replaced with applying SemiringSolver of Standard, but it is difficult for me to use such. I gave a simple example on using SemiringSolver in a letter to the Agda list a couple of weeks ago, with asking for help. But nobody responded.

There also remains the problem of performance of <-cmp and divMod on Nat. It will bite the arithmetic performance of Fraction Integer (I expect that it bites the existing arithmetic on Rational of Standard as well).  
It can be solved by merging the Fraction library with the Binary-4.2 library for binary naturals. But Standard currently ignores all binary libraries for natural numbers.

**Comment by mechvel** [comment]
> Do you have a link?

I have, but it works under unstable Development versions.

>>  Second, it uses in a couple of places my home-made CommutativeSemiringSolver. Probably, it can >> be replaced with applying SemiringSolver of Standard, but it is difficult for me to use such. I gave a >> simple example on using SemiringSolver in a letter to the Agda list a couple of weeks ago, with 
>> asking for help. But nobody responded.

> Sorry I'm not really an expert on the Solvers. Maybe someone else can help.

There are two large modules:   ``InFreeSemiring, InSemiring``. 
If I knew how to use (Semi)RingSolver of Standard, these two module could be eliminated.

>> It can be solved by merging the Fraction library with the Binary-4.2 library for binary naturals. But 
>> Standard currently ignores all binary libraries for natural numbers.

> Given that there doesn't seem to be much usage of the current implementation of Data.Bin, I think it's > fair game to be revamped if you would like to try and incorporate some of your Binary-4.2 library.
>
> To do this, I'd recommend opening a small pull request that only implements the new alternative form > of the Bin datatype and _+_. I think the reason why your previous PR didn't get included was that it 
> was too big. Also please can you try and ensure that the code obeys the conventions found 
> elsewhere in the standard library.

The new binary library part is in any case bigger than the Bin part of Standard. Because it _needs_ to have additional items of  ``minus, divMod, gcd, <=DecTotalOrder`` (or may be ``<-strictTotalOrder``),
and a proof for a bijection and isomorphism to Nat. 
The Standard Bin part is fairly insufficient. 

Further, Binary-4.2 totally removes the Bin part of  Standard.
It has the modules
``` BPrelude.agda, LtReasoning.agda,  Nat0.agda, Bits.agda, Bin0.agda,  Bin1.agda, Minus.agda,        Ord0.agda, Ord1.agda, OfDivMod.agda, GCD.agda
 ```
about 150 Kbyte.  Standard Bin part has about 13 Kbyte. But it is very insufficient.

I fear I cannot make Binary-4.2 less that 150 Kbyte. So, has  this Binary-4.2 a chance?

**Comment by MatthewDaggitt** [comment]
I assume the discussion is continuing in #757, so closing this as a duplicate.
