### ISSUE TITLE
Split-up `Data.Container` in the standard hierarchy

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#599]

**Comment by gallais** [comment]
I have departed from the current state on a number of occasions.

* `All` and `Any` are now record types: they define a predicate over `⟦ C ⟧ X` and
  there is simply no way Agda is going to be clever enough to infer `C` if it's not
  right there for it to pick up.

* In the same spirit the `Π` and `Σ` combinators now takes the index `I` explicitly.
  Even something as basic as the non-dependent product [`const[_]⟶_`](https://agda.github.io/agda-stdlib/Data.Container.Combinator.html#2111) needed
  us to pass the implicit argument explicitly!

* I have changed the definiton of the container combinators to a copattern-style,
  this should guarantee that they are not unfolded eagerly in goal types (thus
  making them more readable).

**Comment by MatthewDaggitt** [comment]
Closed with 65a94be
