### ISSUE TITLE
naming in All.Properties.filter*

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#601]
What mnemonic is in the name of ``filter⁺₂ `` in ``Data.List.All.Properties`` in 
```
filter⁺₂ : ∀ {q} {Q : A → Set q} {xs} → All Q xs → All Q (filter P? xs)
```
?
Is it better to call it, say,  ``filter-preserves-All`` ?

Considering `` filter⁺₁ : ∀ xs → All P (filter P? xs)``,

Is it better to call it   ``all-P-filter-P?`` ?

**Comment by JacquesCarette** [comment]
I quite like the name `filter-preserves-All` for `filter⁺₂`.
I don't like either the current name, nor the proposed name (sorry!) for `filter⁺₁`

**Comment by mechvel** [comment]
> ``all-filter : All P (filter P? xs)``
> ``filter⁺    : All Q xs → All Q (filter P? xs)``

I think, the first is all right.
The second is not. Because when the reader sees ``filter⁺ `` in  the code, one has not a chance to guess of its meaning. I think  ``filter-preserves-All`` is better.

**Comment by JacquesCarette** [comment]
> We have been consistently using _⁺ as a suffix to indicate that we add a function
acting on the thing being talked about by the predicate. 

I had no clue that this was a convention.  Is it documented somewhere? I'm still undecided whether I like it or not but regardless, such information really ought to be documented in a place that all library devs ought to read when getting started.

**Comment by MatthewDaggitt** [comment]
> I had no clue that this was a convention. Is it documented somewhere? I'm still undecided whether I like it or not but regardless, such information really ought to be documented in a place that all library devs ought to read when getting started.

So we do have a document for [this](https://github.com/agda/agda-stdlib/blob/master/notes/style-guide.md) but it's pretty rough. I'll try and go through and add a few more of the conventions.

**Comment by JacquesCarette** [comment]
Rough is better than void. And it's hooked-in to `HACKING.md` too -- perfect.

**Comment by MatthewDaggitt** [comment]
Opened a PR that makes @gallais suggested changes and added note to the style guide.
