### ISSUE TITLE
 Proposal to replace  ``⇒``  with ``→``  in names

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#604]
I propose to replace  ``⇒``  with ``→``  in names.

For example, to rename  ``n≤0⇒n≡0``   to  ``n≤0→n≡0``  in Nat.Properties:
``n≤0⇒n≡0 :  ∀ {n} → n ≤ 0 → n ≡ 0``.

There are many such names.
Motivation:
(1) ``→`` is already in the type,   and ``→`` is a part of the language, it is known before studying 
     of  any library.
(2) Each programmer knows that  ``→`` can be understood as implication.
(3) ``→`` is easier to input from keyboard.
(4) Seeing ``A⇒B``, a beginner would think: "probably it is implication, but now I need to search for its   
      definition in the library''.
(5) Generally it is good to avoid introducing new unnecessary notions.

**Comment by mechvel** [comment]
May be the exception is needed for the cases when ``⇒`` is right in the corresponding signature.

**Comment by MatthewDaggitt** [comment]
I'm not keen on this idea I'm afraid.

> (1) → is already in the type, and → is a part of the language, it is known before studying of any library.

Lots of things are in the language, and the → symbol denotes a function type, not an implication (although they are equivalent via Curry-Howard).

> (2) Each programmer knows that → can be understood as implication.

Sadly this is definitely not true. I had a long discussion about this with a reviewer recently who had never come across the concept before.

> (3) → is easier to input from keyboard.

Not much. The first time you enter it in emacs, it takes one extra key press. After that emacs remembers which arrow you're using.

> (4) Seeing A⇒B, a beginner would think: "probably it is implication, but now I need to search for its
definition in the library''.

The first part is great. In contrast I don't think the same beginner would see `→` and think "ah that's definitely implication".

> (5) Generally it is good to avoid introducing new unnecessary notions.

I think logical implication is hardly a "new" or "unnecessary" notion.

Finally it a quick "grep" for it turns up well over 200 names in the library. That means it would be a massive change for not much benefit in my opinion.

**Comment by HuStmpHrrr** [comment]
this is too breaking. I bet people will scream so I guess it's not really the best name change there can be.

regarding point 2, I always type `\to` for single arrow and `\=>` for double arrow. both are easy to input.
