### ISSUE TITLE
Add .agda-lib file for README/

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#613]
Various constraints:

* `README/*` shouldn't be in scope for users of the standard library
* Loading one of the `README` files in emacs should work nonetheless

I can't find a way to make this work:

* If I put the `.agda-lib` file in `README/`, it's ignored (the module names start
  with `README.` thus telling Agda to look at the directory above `README/` for an
  `.agda-lib` file)

* If I put the `.agda-lib` file in the root of the repository, `README/` becomes
  available from modules in `src/` & opens the window for users picking the wrong
  `.agda-lib` file during installation.

If we were to move `README` inside e.g. `doc/`, then we could have an `.agda-lib` file
sit in `doc` & I believe it would work. Unfortunately this makes `README` less
prominent in the repo... :(

**Comment by MatthewDaggitt** [comment]
With respect to the conclusion of #595, would it make sense to turn all the README files into `Example` files and do away with the README folder entirely? It seems weird to have two parallel sets of documentation.

**Comment by gallais** [comment]
Fair enough, I had some tunnel vision because I was working on #608. Having them
right there in the directory tree will make discoverability a lot better too. Nice!
