### ISSUE TITLE
Proposal of cong1, cong2

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#616]
I propose to add to ``Magma`` these definitions:
```  
  ∙cong1 : {y : C} → (_∙ y) Preserves _≈_ ⟶ _≈_
  ∙cong1 x=x' =  ∙-cong x=x' ≈refl

  ∙cong2 : {x : C} → (x ∙_) Preserves _≈_ ⟶ _≈_
  ∙cong2 =  ∙-cong ≈refl
```
-- congruence with respect to the first (secong) argument.

Motivation.
For example, in ``Monoid`` one can write
```
  foo : ∀ (x y) → x ≈ ε → x ∙ y ≈ y
  foo x y x≈ε =
              begin x ∙ y       ≈⟨ ∙cong1 x≈ε ⟩     -- instead of    ≈⟨ ∙-cong x≈ε ≈refl ⟩
                        ε ∙ y       ≈⟨ ε∙ y ⟩  
                       y
              ∎
```
1) This gives a certain simplification. Because skips  ``≈refl``,  and often skips  ``≈refl {foo}``.
2) It does not break any existing code.

**Comment by JacquesCarette** [comment]
I would probably write the first one using `flip`, but otherwise, I agree.

**Comment by MatthewDaggitt** [comment]
This is a good suggestion, and I've actually already added these recently in the development version of the library. They're called `∙-congˡ` and `∙-congʳ`. See the CHANGELOG for details!

**Comment by mechvel** [comment]
> This is a good suggestion, and I've actually already added these recently in the development version > of  the library. They're called ∙-congˡ and ∙-congʳ. See the CHANGELOG for details!

Then,  a similar treating need  ``_+_`` and  ``_*_`` of Semiring, and  ``_-_`` of Ring.

**Comment by gallais** [comment]
Given these renamings such as the following in [Algebra.Structures](https://agda.github.io/agda-stdlib/Algebra.Structures.html#3974)
I'm guessing it's already the case:

```agda
  open IsMonoid +-isMonoid public
    renaming
    ( assoc       to +-assoc
    ; ∙-cong      to +-cong
    ; ∙-congˡ     to +-congˡ
    ; ∙-congʳ     to +-congʳ
    ; identity    to +-identity
    ; identityˡ   to +-identityˡ
    ; identityʳ   to +-identityʳ
    ; isMagma     to +-isMagma
    ; isSemigroup to +-isSemigroup
    )

  open IsSemigroup *-isSemigroup public
    using ()
    renaming
    ( assoc    to *-assoc
    ; ∙-cong   to *-cong
    ; ∙-congˡ  to *-congˡ
    ; ∙-congʳ  to *-congʳ
    ; isMagma  to *-isMagma
    )
```

**Comment by MatthewDaggitt** [comment]
> Then, a similar treating need `_+_` and `_*_` of Semiring, and `_-_` of Ring.

Yup done already.
