### ISSUE TITLE
reopen 616

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#618]
I have added a comment to a closed issue of 616. But I do not know how to reopen it. Will it  reopen automatically?

**Comment by MatthewDaggitt** [comment]
Everyone still sees your comments even when the issue is closed. If we come up with something that needs doing I'll reopen it. 

In future questions like this should have been made in #616 not as a new issue. Please reserve new issues for actual issues about the contents of the library, thanks!
