### ISSUE TITLE
Use `-local` consistently for properties

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#626]
In `Data.List.Properties` we use

* `map-id₂ :  All (λ x → f x ≡ x) xs → map f xs ≡ xs`
* `map-cong₂ : All (λ x → f x ≡ g x) xs → map f xs ≡ map g xs`
* (we do not have `map-compose₂`)

I think that we should instead use the `-relative` suffix introduced in #510

**Comment by MatthewDaggitt** [comment]
What does `relative` refer to?

**Comment by gallais** [comment]
The fact the equality constraint is relative to a specific domain (in order to be
as tight a constraint as possible) rather than absolute.

**Comment by MatthewDaggitt** [comment]
Hmm looking at this again, I'd probably prefer the prefix -locally (or -local) instead of  -relative, as in _the equality constraints hold locally_.  Thoughts?

**Comment by JacquesCarette** [comment]
To be honest, I don't like either -locally or -relative.  Isn't this rather a 'lifting' property? You're lifting an equality to hold at a list. In some ways, this is a generalization of `ap`.

**Comment by MatthewDaggitt** [comment]
So `map-id-lift`? I like it better than -relative but less than -local. I'd be fine with it though....

**Comment by MatthewDaggitt** [comment]
Going to leave this out of v1.0, as I don't think we've reached consensus yet.

**Comment by MatthewDaggitt** [comment]
@jamesmckinna thinks the suffix should be `at` e.g. `map-id-at`

After discussion we're going with `local`

**Comment by jamesmckinna** [comment]
Is it the case, for `List`s at least, that the 'global' property `map-id` is (definitionally equal to; or merely equivalent to?) `\forall xs \r (map-id-local xs)` (modulo the actual arguments in order to fix the property)?

That is, do we uniformly have that `property` is `All (property-local)` for `property`s of interest? Should we?

**Comment by jamesmckinna** [comment]
@MatthewDaggitt this could also be linked to issue #509 (or at least, to a single PR which will knock them both off). You or me?

**Comment by jamesmckinna** [comment]
I think this bit of PR #1822 is now ready.

**Comment by jamesmckinna** [comment]
I was too hasty. There is a very large raft of `updateAt-*` properties, each with a `-relative` version, in:
- [ ] `Data.Vec.Properties`
- [ ] `Data.Vec.Functional.Properties`
- [ ] `Data.List.Relation.Unary.All.Properties`
Turning to those now.

**Comment by jamesmckinna** [comment]
Updated `CHANGELOG`.

**Comment by jamesmckinna** [comment]
Problem: type of `map-updateAt` in `Data.Vec.Functional.Properties` is in fact the 'local' statement, not the 'global' as suggested by the name...

**Comment by jamesmckinna** [comment]
Is this issue now closed, or does there need to be an addition somewhere (`HACKING`?) to document the intention behind the name change?

**Comment by MatthewDaggitt** [comment]
I guess if you're keen you can add a note to 

https://github.com/agda/agda-stdlib/blob/master/notes/style-guide.md#naming-conventions

**Comment by jamesmckinna** [comment]
I'll ponder what would be the most helpful way to introduce, exemplify, and reinforce the new agreed convention. But it seems 'small' compared to the gross-scale global conventions listed there. Too much thinking required perhaps!

**Comment by jamesmckinna** [comment]
So: I think the issue/discussion of how to document the various already-merged PRs in `HACKING`, can be deferred to v2.1. I can't organise my thoughts properly about the right narrative approach here.

**Comment by MatthewDaggitt** [comment]
Opened https://github.com/agda/agda-stdlib/pull/2109 to knock this off as it's definitely low hanging fruit.

**Comment by jamesmckinna** [comment]
OK, but I'll pass the baton on this one :-(
