### ISSUE TITLE
mono --> monot

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#63]
The abbreviation   'mono'   in the function names 

```
                      '+-mono', 'pred-mono',  and such
```

looks a bit ambiguous. And  'monot' 

 will point more definitely to the monotonicity property with respect to _<=_.

**Comment by MatthewDaggitt** [comment]
Ambiguous with respect to what? I don't see how adding a "t" will make it less ambiguous.

All new `mono` properties in the library should have the order appended to the end of the name (i.e. `+-mono-<`). Hopefully this will clear it up?

**Comment by mechvel** [comment]
On Mon, 2017-06-26 at 02:56 -0700, MatthewDaggitt wrote:
> Ambiguous with respect to what? I don't see how adding a "t" will make
> it less ambiguous.

I mean a mnemonic ambiguity.
The are notions like "monomorhism", "monomial" , mono-this,
mono-that ...
So, "mono" refers to many notions,
while "monot" refers to few notions, I know only "monotonous". 


> All new mono properties in the library should have the order appended
> to the end of the name (i.e. +-mono-<). Hopefully this will clear it
> up?

Generally, uniformity is desirable. Say,

     <operation of function name> - monot - <ordering symbol>

------
Sergei

**Comment by MatthewDaggitt** [comment]
> There are notions like "monomorhism", "monomial" , mono-this, mono-that ...

But none of them are relevant to `Data.Nat`, I feel that context is key. For example there are at least 5 different `_+_` defined in the standard library but you know which one they refer to by the module imports. Similarly no one is going to think that something of the form `+-mono-<` refers to monomorphisms or monomials.

Ultimately I think the justification for this change is not strong enough to warrant the backwards compatibility issues it would introduce.

> Generally, uniformity is desirable.

 I agree. We will try and rename `_+-mono_` and `_*-mono_` to `+-mono-≤` and `*-mono-≤` respectively.

**Comment by mechvel** [comment]
On Wed, 2017-06-28 at 02:51 -0700, MatthewDaggitt wrote:
>         There are notions like "monomorhism", "monomial" , mono-this,
>         mono-that ...
>         
> 
> But none of them are relevant to Data.Nat, I feel that context is key.
> For example there are at least 5 different _+_ defined in the standard
> library but you know which one they refer to by the module imports.
> Similarly no one is going to think that something of the form +-mono-<
> refers to monomorphisms or monomials.

Formally, this is so.


> Ultimately I think the justification for this change is not strong
> enough to warrant the backwards compatibility issues it would
> introduce.

Agda  is not currently stable enough to care much for backwards
compatibility, the developers admit this.
But it needs to care -- a bit.
So that I do not care much about this "monot" affair. 

------
Sergei
