### ISSUE TITLE
--safe can't be combined with both --guardedness and --sized-types

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#633]
As a consequence the build on experimental fails (#632). We need to distinguish
between `EverythingSafeGuardedness.agda` and `EverythingSafeSizedTypes.agda`.

**Comment by MatthewDaggitt** [comment]
Sorry maybe I'm not seeing the big picture but now that options are correctly infective/coinfective do we need special `EverythingX` modules at all? I thought their point was to guarantee consistency between modules, but Agda 2.6.0 now does that for us.

**Comment by gallais** [comment]
It would be nice to ensure that we do not forget to set the `--safe` flag to every
module except for the few we have explicitly listed as unsafe.

**Comment by MatthewDaggitt** [comment]
I agree but wouldn't it be better to hook that into the same system that we use to ensure every file has the library header?

**Comment by gallais** [comment]
I am indeed planning to add a classifier inside `GenerateEverything.hs` to produce these
files (instead of simply `Everything.agda` and `EverythingSafe.agda` like it does right now).
