### ISSUE TITLE
on proof names in standard library  

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#639]
For any occasion:
here are my impressions about proof naming conventions in
Standard library lib-0.17.

With short names it is easier to read/write proofs.
When you write many proofs, you start to dislike extra symbols in names. 
Each symbol in a name need not appear without a strong need.

1. The style of full explicitness in names makes names too long. 

For example,  ``m+n∸n≡m``  can be replaced with  ``m+n∸n``.

The reader understands this mnemonic this way.
"What might mean ``m+n∸n`` ?
It is not   ``m + (n ∸ n)``,  because one would write  ``m + 0``  instead.
It is not  ``(m + n) ∸ n``,  because one would write  ``m`` instead.
Evidently it means a proof for  ``(m + n) ∸ n ≡ m``.
"

There are many similar items.

Another example: I write     ``suc∘pred :  (n : ℕ) → n ≢ 0 → suc (pred n) ≡ n``
instead of  
```suc-pred-n≡n-ifNonzero-n :  ...```

Its mnemonic is understood as follows.
"``suc∘pred``  would hardly mean  ``suc ∘ pred``,  because this is  ``id``  on nonzero
naturals, and 1 for zero.
Can this be a proof for   ``(n : ℕ) → suc (pred n) ≡ n``  ?
It is almost so, only the condition  ``n ≢ 0``  needs to be added.
"

2. For   ``m + 0 ≡ m``,

a proof  ``(+0 m)``  looks nicer that  ``(+-identityʳ m)``. 
``(ε∙ x)``  looks good for a proof for  ``ε ∙ x ≈ x``  in Monoid.

3. I would write  ``rDistrib``  instead of  ``*-distribʳ-+``
because of the following reasons. 
a) Distributivity is by default for ``(_*_, _+_)``, by tradition.
   And for other operations their names can be set explicitly,
   say,  ``⊓-rDistrib-⊔``.

b)  ``ʳ``  is difficult to input and difficult to read, so that
   ``rDistrib``  looks better than  ``distribʳ``.

4. ``-`` is used too widely.
For example,
``≈sym,  +comm,  *assoc``,  and such,   does not look less clear than
``≈-sym, +-comm, *-assoc`` ...

**Comment by MatthewDaggitt** [comment]
> 2. The style of full explicitness in names makes names too long.
> 
> For example, `m+n∸n≡m` can be replaced with `m+n∸n`.

The name may be long but it's much clearer. You've removed the equality. How would a user know that it is not a an **in**equality?

> 1. For   `m + 0 ≡ m`,
> 
> a proof `(+0 m)` looks nicer that `(+-identityʳ m)`.
> `(ε∙ x)` looks good for a proof for `ε ∙ x ≈ x` in Monoid.

Unfortunately "looking better" is not a good enough excuse to break hundred's of peoples code.

> 3. I would write  `rDistrib`  instead of  `*-distribʳ-+`
>    because of the following reasons.
>    a) Distributivity is by default for `(_*_, _+_)`, by tradition.
>    And for other operations their names can be set explicitly,
>    say,  `⊓-rDistrib-⊔`.

I disagree. Currently every name for distributivity proof has the same convention and users simply fill in their desired operator and hence it is predictable. Under your suggestion they'd have to guess what the "most common" operators were in the opinion of the standard library. I disagree that `_+_` and `_*_` are the default. For instance I've written 100,000 lines of Agda code and never once used `_*_` whereas I use `_+_` and  `_⊓_` all time.

> 4. `-` is used too widely.
>    For example,
>    `≈sym,  +comm,  *assoc`,  and such,   does not look less clear than
>    `≈-sym, +-comm, *-assoc` ...

This would involve changing EVERY proof in the standard library. So I'm afraid it's... unlikely to happen :smile: 

**Summary**

You've opened a lot of issues recently about naming conventions in the library. I really do understand that your preference for naming does differ from that used by the standard library but we do need to maintain backwards compatibility as much as possible, so any wide-scale aesthetic-only changes are unlikely to be accepted. Broadly speaking suggestions for changes to names will only be accepted if:
1. The current name is actively wrong or misleading
2. The current name is inconsistent with other existing naming conventions in the library.
(and even then they not be changed if doing so breaks too much code).
