### ISSUE TITLE
_+-mono_   vs    ∸-mono

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#64]
_+-mono_   is declared as infix  in  Dat.Nat.Properties -- unlike   ∸-mono.

But  they probably need to have the same format.

**Comment by MatthewDaggitt** [comment]
I agree. At some point I think we should try and phase the infix notation out to bring it into line with the rest of the `Properties` files. Possibly by having both versions for a while.

**Comment by MatthewDaggitt** [comment]
Done in 0773163. Added `*-mono-≤` and `+-mono-≤` but left `_+-mono_` and `_*-mono_` in place marked as deprecated.
