### ISSUE TITLE
fix ``_-_`` 

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#642]
In standard library of January 1, 2019, 
``_-_`` is defined  in somewhere in IsGroup, and implemented via inversion.
Inversion has precedence 7, and  ``_-_`` in IsRing (Ring) is brought by renaming from  ``_-_`` of IsGroup. So that it occurs, for example, that the library parses ``x - x* y``  to  ``(x - x) * y``.
The tradition is the folloiwing : 
1) ``_-_`` has the same precedence as ``_+_``, and smaller than ``_*_``,
    so that,  ``x - x* y`` needs to be parsed to  ``x - (x * y)``.
 2) in abstract Group  ``x  ∙ (inverse y)``  is named as  ``x div y`` (division) rather than subtraction.

Probably,  ``_-_`` in IsGroup needs to be renamed to some  appropriate ``div-foo``,
and  ``_-_`` to appear in IsRawRing,  with precedence equal to precedence of  ``_+_``,
and implemented there as   ``x + (- y)``.

?

**Comment by mechvel** [comment]
I meant that  ``x - x * y`` is parsed to ``(x - x) * y`` in the Ring environment,
while it needs to be `` x - (x * y)``.

**Comment by MatthewDaggitt** [comment]
So as I understand it you are proposing two changes:
1. Match the precedence of `_-_` and `_+_` in `Ring`
2. Rename `_-_` to `_/_` in `IsGroup`

The first I agree with. I think the best way of doing so is probably bumping up the precedence of each of: 
```
infix  8 -_
infixl 7 _*_
infixl 6 _+_
``` 
by 1 in the definition of `Ring`.

The second point might come under my answer #639. I agree with you that in my experience it's probably more common to call the operation division rather than subtraction in a group. However I don't think it's unheard of, and again it might be argued that its another cosmetic change at the expense of backwards compatibility. I'm on the fence though, and would welcome other opinions? @JacquesCarette ?

**Comment by mechvel** [comment]
MatthewDaggitt  writes
> The first I agree with. I think the best way of doing so is probably bumping up the precedence of each > of:
```
> infix  8 -_
> infixl 7 _*_
> infixl 6 _+_
```
> by 1 in the definition of Ring.

What does this mean: "to bump up something by 1" ? To decrease it by 1 ?
If you decrease or increase all the three by 1, this will remain parsing  ``x - x * y`` to
``(x - x) * y``.  Because ``_-_`` is defined via ``-_``. 
To match the goal, one needs ``-_`` to have a lower precedence than  ``_*_`` has.  
Also 
1) as I recall, there are RawSemiring, Semiring, RawRing, the first two also declare ``_+_`` and ``_*_``,
and the third declares also ``-_``,
2) generally, I do not understand why many operations are re-declared in standard library this way
    (see my last letter to the Agda list).

So that there is a danger to make an unlucky change.

Still  it is evident that  parsing the things like ``x - x * y`` in a Ring needs to agree with tradition.

**Comment by JacquesCarette** [comment]
(sorry for the slow response, I was away).  Yes, it is most usual to use `_*_` and `1/_` for `Group` and then `_+_` and `-_` for `AbelianGroup`. Mathematics is 'transparent' to renaming. Agda is too, but only in one direction -- it is hard to get that an `AbelianGroup` is a `Group` (for free) once renaming has happened. The nice record projections don't work well in the presence of renamings.

**Comment by MatthewDaggitt** [comment]
@mechvel Current we have
```
infix  8 -_ (from Ring)
infixl 7 _*_ (from Ring)
infixl 6 _+_ (from Ring)
infixl 7 _-_ (from IsAbelianGroup)
```
Increasing all the ring operators by 1 would result in:
```
infix  9 -_ (from Ring)
infixl 8 _*_ (from Ring)
infixl 7 _+_ (from Ring)
infixl 7 _-_ (from IsAbelianGroup)
```
which would fix your problem right?

**Comment by mechvel** [comment]
> which would fix your problem right?

I understand now.
Hopefully this will parse  ``x - x * y`` in a traditional way, that is to ``x - (x * y)``.
But it is difficult to predict parsing when it is mixed with other operations, such as 
``inversion,  _^_,  _⊔_, _⊓_`` ... 
(?)
You can, say, set the above precedences and try to type-check the whole library.
If no error occurs, this will give a hope.

**Comment by mechvel** [comment]
But ``lib-1.0``  still has a bug of parsing  ``x - x * y``  to  ``(x - x) * y``  in the Ring environment.
?

**Comment by MatthewDaggitt** [comment]
> But lib-1.0 still has a bug of parsing x - x * y to (x - x) * y in the Ring environment.?

As I said in #664, fixing this was bumped to version 1.1.
