### ISSUE TITLE
Generalize Heterogeneous Equality to handle Sets with different universes.

### ISSUE THREAD

**Issue by xekoukou** [agda/agda-stdlib#646]
```agda
infix 4 _≅_

data _≅_ {ℓ1} {A : Set ℓ1} (x : A) : ∀ {ℓ2} → {B : Set ℓ2} → B → Set ℓ1 where
   refl : x ≅ x
```

There are times where we need to prove that two levels are equal. For example , #608 has functions that compute the Level inductively. For these cases, we need this generalization.

Consider this simple example : 

```agda
lemma5 : ∀ l1 l2 → l1 ≡ l2 → Set l1 ≅ Set l2
lemma5 l1 .l1 refl = refl
```

This is only possible with this generalization.

**Comment by gallais** [comment]
Are you looking for [Heterogeneous equality](https://agda.github.io/agda-stdlib/Relation.Binary.HeterogeneousEquality.Core.html)?

**Comment by MatthewDaggitt** [comment]
In principle this sounds good, I wonder how often the extra level would be inferrable if we changed the definition in `Relation.Binary.HeterogeneousEquality` accordingly?
