### ISSUE TITLE
has it   (DecTotalOrder Bin)  ?

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#65]
has it   (DecTotalOrder Bin)  ?

**Comment by MatthewDaggitt** [comment]
Can you elaborate a bit more? Do you mean `Fin` instead of Bin?

**Comment by mechvel** [comment]
I see         strictTotalOrder : StrictTotalOrder _ _ _
in Data.Bin,
but I do not find there   decTotalOrder : DecTotalOrder _ _ _

Probably it has sense to add such.

------
Sergei

**Comment by MatthewDaggitt** [comment]
Correct me if I'm wrong, but `_<_` in `Data.Bin` is not a total order or even a preorder because it is a strict inequality and therefore is not reflexive...

**Comment by mechvel** [comment]
On Mon, 2017-06-26 at 05:27 -0700, MatthewDaggitt wrote:
> Correct me if I'm wrong, but _<_ in Data.Bin is not a total order or
> even a preorder because it is a strict inequality and therefore is not
> reflexive...
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 

Data.Bin  defines and exports  StrictTotalOrder  for _<_.

And similarly, it is also desirable to have there  
DecTotalOrder for _≤_ for Bin.

Such is possible to define, but I do not find such.

-----
Segei

**Comment by MatthewDaggitt** [comment]
Ah, well at the moment the relation `_≤_` isn't even defined in `Data.Bin`. Adding such a definition would probably mean that the existing definition of `_<_` would want to be reworked in terms of it and that would entail making large changes to the rest of the file. 

As it's a fairly niche part of the library and a reasonably large piece of work, I don't think that it's likely it'll be done any time soon. However if you need this and have already written the necessary code then please do feel free to submit a pull request with it!

**Comment by mechvel** [comment]
On Mon, 2017-06-26 at 08:18 -0700, MatthewDaggitt wrote:
> Ah, well at the moment the relation _≤_ isn't even defined in
> Data.Bin. Adding such a definition would probably mean that the
> existing definition of _<_ would want to be reworked in terms of it
> and that would entail making large changes to the rest of the file.
> 
> As it's a fairly niche part of the library and a reasonably large
> piece of work, I don't think that it's likely it'll be done any time
> soon. However if you need this and have already written the necessary
> code then please do feel free to submit a pull request with it!


I have its code inside DoCon-A-0.04.1.
I am going to separate it and to suggest for Standard, 
may be, in July 2017.

Also, please, consider

  ftp://ftp.botik.ru/pub/local/Mechveliani/agdaNotes/bin2.zip
(of February 2013 !).

This is a very essential addition to Bin. 
Threre are proved some properties from the list that constitutes the
_correctness_ of the binary coding.
Correctness of the binary coding means that
(1) this coding is a bijective map,
(2) it preserves the operations _+_, _*_.

Without this correctness proof, Bin is not a proved program. 

This  bin2.zip  contains a proof for that the binary coding is injective
and that it preserves  suc <--> addC,  may be something else.

But I am not sure that I am the only one who proved things on Bin in
Agda. The e-mail archive may contain the related announcements from
other people (they may be in the segment of 2012 -- 2015). It may have
sense to directly ask the Agda email list.  

------
Sergei

**Comment by mechvel** [comment]
Please, take a fresh version from there:
ftp://ftp.botik.ru/pub/local/Mechveliani/agdaNotes/bin2.zip 

Ii is tested under Agda 2.6.0-207bde6.

**Comment by mechvel** [comment]
Also 
ftp://ftp.botik.ru/pub/local/Mechveliani/agdaNotes/bin3.zip

includes  the items of  bin2.zip  + the instance of  DecTotalOrder for Bin 
for  
``x ≤ y``  defined on Bin as   ``x < y ⊎ x ≡ y``.

**Comment by MatthewDaggitt** [comment]
Thank you for your contribution! It would be great if you could submit some of it as a pull request rather than a zip file. If you need any pointers on creating a pull request please feel free to ask!

As for the ordering `x ≤ y = x < y ⊎ x ≡ y`, defining `_≤_` in terms of `_<_` is backwards with respect to the rest of the standard library. I'm reluctant to accept it as I feel its likely to cause confusions for users and further problems down the line. As I mentioned before, I'd be much more comfortable rewriting the implementation of `_<_` in terms of a new native `_≤_` relation.

**Comment by mechvel** [comment]
On Wed, 2017-07-05 at 09:59 +0000, MatthewDaggitt wrote:
> Thank you for your contribution! It would be great if you could submit
> some of it as a pull request rather than a zip file. If you need any
> pointers on creating a pull request please feel free to ask!


Please, how to make a pull request in this my particular case?

I have done a fork from the project 'Standard library'.
In this fork I enter into  scr/Data/Bin/
I have the files
  Bin2.agda Nat2.agda readme.agda

to pull, where readme.agda contains a general description and comment.

I set "Create new branch", click "Upload files", and 
"Choose your files".
This brings me to the files on my computer.
I click at  Nat2.agda  on my computer.
This returns me to the repository, and nothing happens, no message of
any file being uploaded.

Please, how to improve?



> As for the ordering x ≤ y = x < y ⊎ x ≡ y, defining _≤_ in terms of
> _<_ is backwards with respect to the rest of the standard library. I'm
> reluctant to accept it as I feel its likely to cause confusions for
> users and further problems down the line. As I mentioned before, I'd
> be much more comfortable rewriting the implementation of _<_ in terms
> of a new native _≤_ relation.

This is a further question to consider.

------
Sergei

**Comment by MatthewDaggitt** [comment]
> Please, how to make a pull request in this my particular case?

1. In a suitable directory, on the command line call `git clone https://github.com/mechvel/agda-stdlib stdlib-clone`. This will copy the standard library into a new folder called `stdlib-clone`.
2. Make the changes you want to in `Data.Bin` and `Data.Bin.Properties` within `stdlib-clone`, (including updating `CHANGELOG.md` with the changes you've made)
3. Whilst in the top level of the directory `stdlib-clone`, run the command `make test` from the  command line to check that your changes haven't broken anything.
4. Add the files you've made changes to using the commands `git add src/Data/Bin.agda`, `git add src/Data/Bin/Properties.agda`, `git add CHANGELOG.md` etc.
5. Commit the files you've added using `git commit`.
6. Push all your changes to your fork on github using `git push origin master`
7. Go to `https://github.com/mechvel/agda-stdlib` and there should be a button to create a pull request from your new commit.

**Comment by mechvel** [comment]
I put  Nat2.agda  into the folder Data/Nat/,
and put  Bin2.agda  into Data/Bin

And   ``module Data.Bin.Bin2``  
imports items  from  ``Data.Nat.Nat2''.

And   ``make test"  reports

-------------------------------------------------
cabal clean && cabal install
cleaning...
Resolving dependencies...
Configuring lib-0.13...
Building lib-0.13...
Preprocessing executable 'GenerateEverything' for lib-0.13...
[1 of 1] Compiling Main             ( GenerateEverything.hs, dist/build/GenerateEverything/GenerateEverything-tmp/Main.o )
Linking dist/build/GenerateEverything/GenerateEverything ...
Preprocessing executable 'AllNonAsciiChars' for lib-0.13...
[1 of 1] Compiling Main             ( AllNonAsciiChars.hs, dist/build/AllNonAsciiChars/AllNonAsciiChars-tmp/Main.o )
Linking dist/build/AllNonAsciiChars/AllNonAsciiChars ...
Installing executable(s) in /home/mechvel/.cabal/bin
Installed lib-0.13
cabal exec -- GenerateEverything
GenerateEverything: src/Data/Bin/Bin2.agda is malformed
---------------------

I reduce this module to two lines (by commenting out all the rest):
 ------------------------------ 
``module Data.Bin.Bin2 where   --  ℕ <-->  Bin⁺  isomorphism ``

``open import Level    using () renaming (zero to 0ℓ)``
---------------------------

and still it is reported "malformed".

I wonder what might this mean.

**Comment by mechvel** [comment]
> As for the ordering x ≤ y = x < y ⊎ x ≡ y, defining _≤_ in terms of _<_ is backwards with respect 
> to the rest of the standard library. I'm reluctant to accept it as I feel its likely to cause confusions 
>for users  and further problems down the line. As I mentioned before, I'd be much more 
> comfortable rewriting the implementation of _<_ in terms of a new native _≤_ relation.

Currently, Bin has the following implementation to ``_<_ ``:

``data _<_ (b₁ b₂ : Bin) :  Set where``
``    less : (lt : (Nat._<_ on toℕ) b₁ b₂) → b₁ < b₂``

Do you suggest to replace this with

``data _≤__ (b₁ b₂ : Bin) :  Set where``
``    leq : (le : (Nat._≤__ on toℕ) b₁ b₂) → b₁ ≤_b₂``

and then, to define ``_<_`` as
``   x < y =    x ≤ y   ×   x ≢ y``             
?

**Comment by MatthewDaggitt** [comment]
> I put Nat2.agda into the folder Data/Nat/ and put Bin2.agda into Data/Bin

So the changes that you're making shouldn't be put inside their own files. They should be incorporated into the existing `Data.Bin` and `Data.Bin.Properties` files. This should bypass your current problem with the tests.

> Currently, Bin has the following implementation to _<_:
> 
> data _<_ (b₁ b₂ : Bin) : Set where
> less : (lt : (Nat._<_ on toℕ) b₁ b₂) → b₁ < b₂
> 
> Do you suggest to replace this with
> 
> data _≤__ (b₁ b₂ : Bin) : Set where
> leq : (le : (Nat._≤__ on toℕ) b₁ b₂) → b₁ ≤_b₂
> 
> and then, to define _<_ as
> x < y = x ≤ y × x ≢ y

That certainly seems better. In fact, as we're reworking the implementation and the changes aren't going to be backwards compatible anyway, I might be tempted to copy the style of `_≤_` in `Data.Fin` and get rid of the `data` declaration entirely so that it reads as follows:
```agda
_≤_ : Rel Bin Set
x ≤ y = toℕ x Nat.≤ toℕ y

_<_ : Rel Bin Set
x < y = x ≤ y × x ≢ y
```
The notes say that the existing data declaration is to aid in pattern matching. It might be worth experimenting with the two different definitions of `_≤_`: your new version and mine and see which is easier to work with.

**Comment by mechvel** [comment]
On Sun, 2017-07-09 at 06:20 -0700, MatthewDaggitt wrote:
>         I put Nat2.agda into the folder Data/Nat/ and put Bin2.agda
>         into Data/Bin
>         
> 
> So the changes that you're making shouldn't be put inside their own
> files. They should be incorporated into the existing Data.Bin and
> Data.Bin.Properties files. This should bypass your current problem
> with the tests.

I incorporate them there.
Now it reports

--------------------------
...
Installed lib-0.13
cabal exec -- GenerateEverything
cabal exec -- fix-agda-whitespace --check
cabal: The program 'fix-agda-whitespace' is required but it could not be
found.
--------------------------

On the other hand,  Agda 2.6.0-207bde6  does work on my machine, and it
uses  Standard library of  April 13 2017
(which is probably lib-0.13).

Please, how to fix?

------
Sergei

**Comment by mechvel** [comment]
I incorporate them there. Now it reports
-------------------------------
``...
Installed lib-0.13
cabal exec -- GenerateEverything
cabal exec -- fix-agda-whitespace --check
cabal: The program 'fix-agda-whitespace' is required but it could not be
found.``
------------------------------------------------

On the other hand,  Agda 2.6.0-207bde6  does work on my computer, and it uses
Standard library of April 2017
(which I think is lib-0.13).

I wonder, how to fix.

--------
Sergei

**Comment by asr** [comment]
You can install `fix-agda-whitespace` from your Agda *upstream* directory:

```bash
$ cd my-agda-upstream-directory
$ cd src/fix-agda-whitespace/
$ cabal install
```

**Comment by mechvel** [comment]
Now, the commands

``> cd ~/agda/apr13-2017/src/fix-agda-whitespace``
``> cabal install``
``> make test``
 
lead to the report
----------------------------------------
``...``
``Installed lib-0.13``
``cabal exec -- GenerateEverything``
``cabal exec -- fix-agda-whitespace --check``
``Whitespace violation detected in /home/mechvel/agda/stLib/stdlib-clone/CHANGELOG.md.``
``Whitespace violation detected in /home/mechvel/agda/stLib/stdlib-clone/src/Data/Bin.agda.``
``Whitespace violation detected in /home/mechvel/agda/stLib/stdlib-clone/src/Data/Nat/Properties.agda.``
-----------------------------------------------

These three files are exactly the files to which I have added certain needed comments and code.
I wonder, what is wrong there.

**Comment by mechvel** [comment]
Now, the commands

``> cd ~/agda/apr13-2017/src/fix-agda-whitespace``
``> cabal install``
``> make test``
 
lead to the report
----------------------------------------
``...``
``Installed lib-0.13``
``cabal exec -- GenerateEverything``
``cabal exec -- fix-agda-whitespace --check``
``Whitespace violation detected in /home/mechvel/agda/stLib/stdlib-clone/CHANGELOG.md.``
``Whitespace violation detected in /home/mechvel/agda/stLib/stdlib-clone/src/Data/Bin.agda.``
``Whitespace violation detected in /home/mechvel/agda/stLib/stdlib-clone/src/Data/Nat/Properties.agda.``
-----------------------------------------------

These three files are exactly the files to which I have added certain needed comments and code.
I wonder, what is wrong there.

**Comment by gallais** [comment]
Usually it's because you have trailing whitespace on some lines. IIRC `cabal exec -- fix-agda-whitespace` should fix the problem.

**Comment by asr** [comment]
> I wonder, what is wrong there.
You have whitespace issues (but your editor is not showing them). Run `fix-agda-whitespace` on the offending directory and commits the changes.

**Comment by asr** [comment]
@mechvel it is difficult read your messages in GitHub because the format is awful. Please edit your messages and fix their format.

**Comment by gallais** [comment]
@mechvel You don't need 2 opening and 2 closing backticks on every line, you can simply use 3 backticks on a single line before the block and 3 backticks on a single line after the block like so:

```
　```
　code
　block
　```
```

gives:

```
code
block
```

**Comment by mechvel** [comment]
About pull requests:
the restriction of not providing new files in a proposal extending Standard library is unnatural.
Thus, my proposition  works when added as a new file, while adding it to Nat/Properties.agda 
leads to import circles. So that one needs to split the addition between Nat.agda, Nat.properties,
Fin, Fin.Properties, Nat.DivMod ...  A headache.

**Comment by MatthewDaggitt** [comment]
> The restriction of not providing new files in a proposal extending Standard library is unnatural.
> Thus, my proposition works when added as a new file, while adding it to Nat/Properties.agda
> leads to import circles. So that one needs to split the addition between Nat.agda, Nat.properties,
> Fin, Fin.Properties, Nat.DivMod ... A headache.

So its not impossible to add new files, it's just that by keeping everything organised logically it helps users. Adding new files for each user would lead to chaos where no-one would know where to look for each property.

The fact that you are getting import cycles means that as it is your code could be structured better, but it sounds like you've already worked out how to fix it by putting your changes in the relevant files!

If I may make the suggestion that you start off creating a pull request for only a small set of changes? Maybe only the basic changes to `Data.Nat`, `Data.Nat.Properties` and `Data.Nat.DivMod`, and then we'll add those in and you can work on the rest.

**Comment by mechvel** [comment]
I cancel my complaint about restriction on .agda files for pull requests for Standard library.

So far, I propose the two main backwards compatible items for Bin.
Their implementation needs several (backwards compatible) additions to Nat.Properties, Nat.DivMod.  
I am going to do all this (may be, later, in August or such), and then, we shall see. 

I do not care much of adding things to Standard library, I just use them as non-standard.
But earlier I happened to make proposals there, and now suddenly have a response -- after  3-4 years. 
So that I do not know, may be it has sense to try to reach a result.

**Comment by mechvel** [comment]
I have  committed a pull request for the above features.

Further improvement for Bin can be as follows.
1) To define ``_≤_`` on Bin as the lexicographic order  on bit lists.
2) To prove that ``_≤_`` on Bin is logically equivalent to ``_≤_`` on the corresponding Nat values.
3) To define  ``b < b1 =   b ≤ b1   ×  b ≢  b1``.
4) To implement ``compare`` respectively  to this ordering definition.
5) To implement DecTotalOrder and StrictTotalOrder respectively.

This will make the ordering witnesses for Bin an explicit data, with also preserving fast comparison.

**Comment by MatthewDaggitt** [comment]
Okay great. Now if you go to your forked repository on Github to the right of the text "This branch is 1 commit ahead of agda:master." there is a button called "Pull request". This allows you to submit your pull request to the main repository.

**Comment by mechvel** [comment]
I clicked this "Pull request". But I am not sure that it is submitted to the main repository.
How to check this.
Also there is a strange matter of the "committer" email address, it is somehow expanded, and I suspect that this address does not work.

**Comment by MatthewDaggitt** [comment]
Okay, after clicking that you then need to click the green "Create pull request" button at the top of the page, and then again on the next screen.

**Comment by mechvel** [comment]
On Tue, 2017-07-11 at 06:17 -0700, MatthewDaggitt wrote:
> Okay, after clicking that you then need to click the green "Create
> pull request" button at the top of the page, and then again on the
> next screen.

After clicking the green "Create pull request" nothing happens. 
It stays there, silent.

Also I need to change in my part in CHANGELOG.md
the name  `Data.Nat'  to  `Data.Nat.Properties',

because the items are added not to the former file but to the latter
(this does not effect "make test").

Is it possible to change this CHANGELOG.md in the pull request?

------
Sergei

**Comment by MatthewDaggitt** [comment]
> After clicking the green "Create pull request" nothing happens. It stays there, silent.

Is this the first or the second "Create pull request" button? Does the page say "Comparing changes" or "Open a pull request" at the top?

> Is it possible to change this CHANGELOG.md in the pull request?

Yes, it's possible to make modifications to the pull request at any point. Simply repeat steps 2, 3, 4, 5 and 6 in the instructions I gave you earlier. Any changes you make will automatically be added to the pull request (once you've succeeded in making it).

**Comment by mechvel** [comment]
> Is this the first or the second "Create pull request" button? Does the page say "Comparing changes" 
> or "Open a pull request" at the top?

First I stay at 
    ``https://github.com/mechvel/agda-stdlib``
There is the headline of
   "This branch is 1 commit ahead of agda:master."      "Pull request"    "Compare".
   
The last two are the buttons at the right end. I click "Pull request".
 And it shows now differently. 
At the right end it shows green "View pull request".
And it prints  "	 Committer: Sergei Meshveliani  ......"
--  in one left column, leaving  blank the rest of the page on screen. 
One  page lower it shows in green "Create new pull request", 
and below  shows in green a responsible part of my CHANGELOG.md.
No "Create pull request" button is visible 

Clicking at "Create new pull request"  does not change anything.
Lower it is visible a small ring with running segment  in it.
The page ends with   "No commit comments for this range".
And this way it stays.

**Comment by MatthewDaggitt** [comment]
> The last two are the buttons at the right end. I click "Pull request".

So after clicking "Pull request" you should see this:
![image](https://user-images.githubusercontent.com/2076434/28074905-c4047c56-6651-11e7-97fa-c0747ca589e9.png)

.
.
.

> Clicking at "Create new pull request" does not change anything.

Clicking the "Create new pull request" button should then allow you to enter the description of the pull request. The screen should now look like this:
![image](https://user-images.githubusercontent.com/2076434/28074949-e367f53c-6651-11e7-94ae-6910b9319547.png)

Do you get this screen? After editing the details, you then need to click the green "Create pull request" button at the bottom.

**Comment by mechvel** [comment]
On Tue, 2017-07-11 at 15:02 +0000, MatthewDaggitt wrote:
>         The last two are the buttons at the right end. I click "Pull
>         request".
>         
> 
> So after clicking "Pull request" you should see this:
> image
> 
> .
> .
> .
> 
>         Clicking at "Create new pull request" does not change
>         anything.
>         
> 
> Clicking the "Create new pull request" button should then allow you to
> enter the description of the pull request. The screen should now look
> like this:
> image
> 
> Do you get this screen? 




The "Create new pull request" button is followed in its line with the
comment
"Create another pull request to discuss and review the changes again". 

And I probably do not need to create _another_ pull request.
Anyway clicking it changes nothing.

Lower, on the right, there is the button "View".
Clicking it shows CHANGELOG


> After editing the details, you then need to click the green "Create
> pull request" button at the bottom.

I cannot edit there anything, and there is not "Create pull request"
button at the bottom.

I do not know, may be, the pull request is already done?

May be it tries to contact me by the expanded email address (which I
suspect is wrongly expanded), and hangs because does not get a
response? 
(my address is  mechvel@botik.ru,  but Git inserts there `mechvel2' in
the middle, which is suspicious).

**Comment by gallais** [comment]
> And I probably do not need to create _another_ pull request.

Yes you do. The pull requests are [listed here](https://github.com/agda/agda-stdlib/pulls) so yours most definitely has not been created yet. If you want to make some more edits, you need to commit them and push them to your fork *before* you start the pull request.

**Comment by asr** [comment]
> (my address is  mechvel@botik.ru,  but Git inserts there `mechvel2' in
the middle, which is suspicious).

On the directory where you are doing the commits, please show me the output of

```
$ git log -5
```

**Comment by mechvel** [comment]
On Tue, 2017-07-11 at 13:30 -0700, Andrés Sicard-Ramírez wrote:
>         (my address is mechvel@botik.ru, but Git inserts there
>         `mechvel2' in
>         the middle, which is suspicious).
>         
> 
> On the directory where you are doing the commits, please show me the
> output of
> 
> $ git log -5


For any occasion:
in this log the first "Committer" field has an extra period after @ in
my address.    

-------------------------------------------------------------------
commit cf2a0cf113b80d4ec10b81df392ffcfc4d6f42c1
Author: Sergei Meshveliani <mechvel@botik.ru>
Date:   Tue Jul 11 13:54:19 2017 +0300

    Committer: Sergei Meshveliani <mechvel@.botik.ru>
    On branch master
    Changes to be committed:
    	modified:   CHANGELOG.md
    	modified:   src/Data/Bin.agda
    	modified:   src/Data/Bin/Properties.agda
    	modified:   src/Data/Char.agda
    	modified:   src/Data/Nat/DivMod.agda
    	modified:   src/Data/Nat/Properties.agda
    
    Author:    Sergei Meshveliani <mechvel@botik.ru>
    Committer: Sergei Meshveliani <mechvel@botik.ru>
    Changes to be committed:
    	modified:   CHANGELOG.md
    	modified:   src/Data/Bin.agda
    	modified:   src/Data/Bin/Properties.agda
    	modified:   src/Data/Char.agda
    	modified:   src/Data/Nat/DivMod.agda
    	modified:   src/Data/Nat/Properties.agda

commit 7205fba80a8739d5852018d02fb360ee5ed4862c
Author: Matthew Daggitt <mld46@cl.cam.ac.uk>
Date:   Wed Jul 5 14:45:37 2017 +0100

    Added some additional properties to `Data.List.All.Properties`

commit 315262b40efb9799d661677745230de7fd5e14b7
Author: Matthew Daggitt <mld46@cl.cam.ac.uk>
Date:   Wed Jul 5 13:34:09 2017 +0100

    Added some additional proofs to `Data.List.Any.Properties`

commit 878b375a9c4ba5b90779b3c80593857fbf18c53b
Author: MatthewDaggitt <matthewdaggitt@gmail.com>
Date:   Wed Jul 5 10:45:31 2017 +0100

    Added a properties file for Data.Bin (#142)

commit 76b99a749f612892fa3112a2e5076a124a712d74
Author: Matthew Daggitt <mld46@cl.cam.ac.uk>
Date:   Tue Jul 4 16:58:46 2017 +0100

    Added extra ordering relations to `Data.Integer` and improved
compatability of `Data.Integer.Properties` with planned changes to
`Data.Integer`
-----------------------------------------------------------------------

**Comment by mechvel** [comment]
I have sent an email reply to the last request here. But Github replaced 1 page log text with "..." .
Can you see  this text anywhere?

**Comment by MatthewDaggitt** [comment]
Okay, let's try again.

1. Go to https://github.com/mechvel/agda-stdlib
2. Press "Pull request"
![image](https://user-images.githubusercontent.com/2076434/28110833-7377260e-66eb-11e7-83dd-bfecc72a43a5.png)
3. Press "Create new pull request"
![image](https://user-images.githubusercontent.com/2076434/28110904-abc8b1da-66eb-11e7-9b16-b6ccf1030e86.png)
4. Change the title of the pull request to something sensible
![image](https://user-images.githubusercontent.com/2076434/28111053-1d13814e-66ec-11e7-8f34-a6cf18df64ff.png)
5. Click "Create pull request"
![image](https://user-images.githubusercontent.com/2076434/28111061-24a425e4-66ec-11e7-96a4-3caffb02e815.png)

**Comment by fredrikNordvallForsberg** [comment]
@mechvel The email address used is not important for the success of the creation of the pull request, but if you want to change it, you can execute the following command on the command line:

```git config --global user.email "mechvel@botik.ru"```

Afterwards git will use your correct email address (see e.g. https://help.github.com/articles/setting-your-email-in-git/#setting-your-email-address-for-every-repository-on-your-computer).

**Comment by mechvel** [comment]
On Wed, 2017-07-12 at 02:24 -0700, MatthewDaggitt wrote:
> Okay, let's try again.
> 
>      1. Go to https://github.com/mechvel/agda-stdlib
>      2. Press "Pull request"
>         image
>      3. Press "Create new pull request"
>         image
>      4. Change the title of the pull request to something sensible
>         image
>      5. Click "Create pull request"
>         image
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 


The step 

>  3. Press "Create new pull request"

does not produce any effect. And I do not see how can I change there
anything in the title, there is no possibility.

The page 
https://github.com/mechvel/agda-stdlib
shows which files are changed in the commit: 6 files 
(CHANGELOG.md and five .agda files).
May be you can take these files and make a pull request instead of me?

------
Sergei

**Comment by MatthewDaggitt** [comment]
> The step
>    3. Press "Create new pull request"
> does not produce any effect. And I do not see how can I change there
> anything in the title, there is no possibility.

Okay, well that's deeply bizarre. Fine, I guess I'll go ahead and create the pull request for you.

**Comment by MatthewDaggitt** [comment]
Closing this issue, as users seriously interested in binary computation can use the release of @mechvel 's new library.
