### ISSUE TITLE
COMPILE pragma not allowed in safe mode.

### ISSUE THREAD

**Issue by riaqn** [agda/agda-stdlib#653]
As the title suggests. I'm using the master branch of `agda-stdlib` on master branch of `agda`. The error message is:
```
/home/riaqn/agda-stdlib/src/Data/Empty.agda:16,1-66
COMPILE pragma not allowed in safe mode.
```

**Comment by gallais** [comment]
Quoting the README:

> If you're using a development version of Agda rather than the latest official release you should use the `experimental` branch of the standard library rather than master.
