### ISSUE TITLE
``m≢0⇒suc[pred[m]]≡m --> n``

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#663]
``m≢0⇒suc[pred[m]]≡m`` has index ``m``, 
while in other single-variable function names in Data.Nat.Properties.agda it is used the letter ``n''.

**Comment by MatthewDaggitt** [comment]
Yup, ideally we should go through and make the whole file consistent. Especially the names of implicit arguments.

**Comment by MatthewDaggitt** [comment]
Closed with 3d0d5fb
