### ISSUE TITLE
parsing Nat

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#667]
To parse to ``ℕ`` from String I write
``stringToNat (filterStr decimalDigit? str)``,

where ``stringToNat, filterStr, decimalDigit?``  are my home-made functions.
Is there a `standard' way to parse to ``ℕ`` from String ? 
If it is not, then standard library probably needs such.

**Comment by gallais** [comment]
In agdarsec, we have [combinators for nat / int written in decimal](https://gallais.github.io/agdarsec/Text.Parser.Combinators.Numbers.html)
