### ISSUE TITLE
hyphenated name in Universe

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-stdlib#668]
https://github.com/agda/agda-stdlib/blob/master/src/Universe.agda

not sure if there is a good regex to grep this sort of names?

**Comment by gallais** [comment]
This should probably be split up into the modules `Universe` and `Universe.Indexed`
(cf. `Container`, `Monad`, etc.)

**Comment by HuStmpHrrr** [comment]
yeah, this module seems untouched for quite a while. looking at the blaming history, the last significant development was 8 years ago.

@gallais  do you have an idea what this module is for?

**Comment by gallais** [comment]
It's the kind of pair you get when defining universes by induction-recursion.
So maybe a bunch of names to structure such code?
