### ISSUE TITLE
Release version compatible with Agda 2.4.2.3

### ISSUE THREAD

**Issue by asr** [agda/agda-stdlib#67]
We'll release Agda 2.4.2.3 (see https://code.google.com/p/agda/issues/detail?id=1482). It's necessary to release a version of the library compatible with this version of Agda.

I think it's desirable back-port some commits from the master branch into the 2.4.2.3 branch before the release.

**Comment by asr** [comment]
I think it's a bad idea to have a released version of Agda (i.e. Agda 2.4.2.3) without a compatible and *released* version of the standard library. Something similar will happen with Agda 2.4.2.4.

In a past discussion we disagreed on the work-flow in the standard library:

a)  Push the commits into the master branch and before the release back-port the appropriate commits in the "maintenance" branch or

b) Push the commits in the "maintenance(s)" branch(es) and merge this(these) branch(es) into master.

I agreed with option b) but the current work-flow is using option a). Does someone according to option a) will release a new version of the library?

**Comment by andreasabel** [comment]
I think we should have a version of the Agda library that type-checks correctly with 2.4.2.4.  Having new functionality in the library is nice-to-have, but optional.

Maybe we can find someone to act as maintainer of the std-lib again? @nad told me as long as there is no decision about the direction the library will be developed, he does not want to do it.  @np, would you be interested?

**Comment by nad** [comment]
On 2015-09-24 18:54, Andreas Abel wrote:
> @nad <https://github.com/nad> told me as long as there is no decision
> about the direction the library will be developed, he does not want to
> do it.

I don't remember saying this. (Maybe I did, I don't know.) However, at
the moment I'm mostly in --without-K mode, so I have little interest in
working on the standard library right now.

-- 
/NAD

**Comment by asr** [comment]
While we find a maintainer for the library, I propose to make a release using the 2.4.2.3 branch in its *current* state. This release will be the compatible version of the library with Agda 2.4.2.3.

I can make this task.

**Comment by asr** [comment]
Done.
