### ISSUE TITLE
constructors of `Level` collide with ones of `Nat`

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-stdlib#677]
Why deliberately rename the constructors of `Level` to collide with `Nat`? This is not quite natural, as usage of `Level` and `Nat` are quite frequent, so whenever it happens, users will need to rename one of them (chances are `Level`) to other names. I think `lzero` and `lsuc` are not bad names. What was the intention?

**Comment by gallais** [comment]
Not that you can `import Level as L` and use `L.zero` and `L.suc` rather than
renaming upon import.

**Comment by HuStmpHrrr** [comment]
right. that's true, but why though? what's the problem with lzero and lsuc?

**Comment by gallais** [comment]
Should we also have `l[]`, and `v[]` rather than `[]`?

**Comment by MatthewDaggitt** [comment]
When I first started using the library I used to agree with @HuStmpHrrr, but I've come around to @gallais point of view. There are lots of "suc" operations in the standard library: Level, Bin, Nat, Int, Fin, and we'd have to come up with names for all of them: "lsuc" "bsuc" "nsuc" "isuc" "fsuc".

Maybe you'd disagree with me, but for the majority of the time I'm only ever using one of these modules (not to say I don't get clashes, but they're not as frequent) and I think the improvement in code clarity is worth the occasional need to rename the less commonly used constructors.

**Comment by oisdk** [comment]
I think I mainly agree with @gallais here, but I did want to point out that levels tend to behave differently from the other things mentioned. For instance, this doesn't work:

```agda
open import Level
open import Data.Nat

data Ty {a} (A : Set a) : Set (suc a) where
```

With an ambiguity error. But this does:

```agda
open import Data.Nat
open import Data.Fin

fs : ∀ {n} → Fin n → Fin (suc n)
fs x = suc x
```

As a result, I rarely need to rebind `suc`, `zero`, `_∷_`, or `[]`; but I *always* have to rebind the `suc` from `Level`.

(I don't actually know why this is the case)

**Comment by gallais** [comment]
> (I don't actually know why this is the case)

May come from the fact that the others are data constructors whereas Level's `zero`
and `suc` are postulates (i.e. definitions).

Note that the type-directed currently fails in some cases, forcing you once again
to use the constructors qualified:

```agda
open import Data.Fin.Base
open import Data.Nat.Base
open import Relation.Binary.PropositionalEquality

_ : ∀ {m n : ℕ} → suc m ≡ suc n → m ≡ n
_ = λ where refl → refl
```

yields a lot of unsolved metas. We are discussing this in agda/agda#3227

**Comment by HuStmpHrrr** [comment]
OK, thanks. I am convinced.
