### ISSUE TITLE
*-mono   for _<_  (for Nat).

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#68]
I need the following analogue for   Data.Nat.Properties.*-mono  :

  _suc<-monot :  (n : ℕ )  → (___ (suc n)) Preserves _<_ ⟶ _<_

Its proof has 18 nonempty lines and uses  the representation   m' + d  ≡ k   for  m'  ≤ k  
(and  d = k  ∸ m').

Need Standard library to have something additional related to  _*_ and  (Preserves _<_ ⟶ _<_) ?
I am missing some nice way to implement  *suc<-monot ?

**Comment by mechvel** [comment]
I do not recall  how to print underscore. Also one * has disappeared. Trying once more:

  *suc<-monot : (n : ℕ ) → (*  (suc n)) Preserves < ⟶ <

**Comment by mechvel** [comment]
Asterisk is not printed in some positions, and underscore is never printed.
I wonder, how people uset this github.

**Comment by mechvel** [comment]
Trying backqotes:
 
  `*`suc<-monot : (n : ℕ ) → (`_*_`  (suc n)) Preserves < ⟶ <

**Comment by pthariensflame** [comment]
Put the entire thing in backquotes.  :)

**Comment by mechvel** [comment]
Thank you. 
The signature is

  `*suc<-monot : ∀ n → (_*_ (suc n)) Preserves _<_ ⟶ _<_`

**Comment by MatthewDaggitt** [comment]
This is on my list of things to push to the standard library soon.

**Comment by MatthewDaggitt** [comment]
Added as `*-monoʳ-<` in 0773163
