### ISSUE TITLE
how to pull-request?

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#685]
Please, how to do a pull request for standard library?
I 
1) have installed the Experimental lib version of April 3 into  libRoot/apr3/ ,
2) changed (in this folder) the file  Data.Nat.Show.agda   by replacing the implementation for  
    "show",
3) inserted there the corresponding reference to CHANGELOG.md.

What do I need to do next?

**Comment by jespercockx** [comment]
You need to create a fork of the `agda-stdlib` project on your own github page and then press the "create pull request" button from there. Here is a more detailed explanation: https://help.github.com/en/articles/creating-a-pull-request

**Comment by mechvel** [comment]
The question is how to create a fork in a simple way.
Clicking at "fork" brings me to an certain old fork of mine, which I would like to remove (how to remove it, how to make it empty?).
As I understand, I need to _copy_ Experimental branch to my fork and to change the two files there by applying _upload_.
The question is
how to start a new fork, and to copy there Experimental branch in an easy way?
I need to copy Experimental and upload there the _two files_ from my computer.
Need I to remove 300 files by repeating the "delete" command and then to upload 300 files from my computer by repeating the upload command?

**Comment by jespercockx** [comment]
If you already have a fork, you don't have to delete it or create a new one. Instead, you can just push a new branch to your current fork (if you already have an old branch with the same name you may have to force push with `git push -f`). This should bring it up-to-date with the latest commit you have locally on your computer.

You definitely should never remove and copy files manually to github. If you have pulled the latest changes from `agda/agda-stdlib`, then pushing to your own fork will bring it automatically up-to-date with those changes.

**Comment by mechvel** [comment]
The situation is as follows. I went to https://github.com/agda/agda-stdlib, then -- to the Experimental branch, and clicked "Download ZIP file" of the branch. I unzipped it to  libRoot/apr3/  on my computer.
Then I have changed the two files in libRoot/apr3/,  
and made sure that everything works. 
Then I go to https://github.com/agda/agda-stdlib, to Experimental branch, 
and there click "fork".
It brings me to my 2 year-old fork -- an old version of the standard library, which I do not need now.
Then what need I to do? 
Need I to go to my computer, and command
```
> cd libRoot/apr3
> git push -f
```
?
May be I need to download the Experimental branch not as zip file but by some git command issued on my computer (what is this command?) ?

Thanks.

**Comment by jespercockx** [comment]
I'm sorry, I assumed you had used git before. I could try to explain the commands here, but it would be easier if you could ask someone who knows git to help you the first time. There is also a good tutorial at https://git-scm.com/book/en/v2 (which helped me a lot when I started using git). If you cannot find anyone to help you, please send me a message and I'll try to walk you through it.

**Comment by mechvel** [comment]
Now, I have downloaded it by
```
> git clone https://github.com/agda/agda-stdlib.git
> cd agda-stdlib
> git checkout experimental
```
Then changed there two files, and commanded
```
> cd agda-stdlib
> git push -f
----------------------
Username for 'https://github.com': mechvel
Password for 'https://mechvel@github.com':  ********
remote: Permission to agda/agda-stdlib.git denied to mechvel.
fatal: unable to access 'https://github.com/agda/agda-stdlib.git/': The requested URL returned error: 403
----------------------
I put there the same password as I put when I am required to get here for issuing comments.
Can anybody, please, help?

```

**Comment by jespercockx** [comment]
You're trying to push to the main agda repository instead of to your own fork. You first have to add your fork as a remote:
```
> git remote add my-fork https://github.com/mechvel/agda-stdlib
```
Then you should be able to push using `git push -f my-fork`.

Before you push, you will also have to create a commit for your changes. The easiest way is with the commands
```
git add .
git commit
```
and then follow the instructions for creating a commit message.

**Comment by mechvel** [comment]
After "git commit" it suggested me 
* to enter e-mail address and user name
* to edit the commit message (in the emacs window appeared). 
I have done all thist. And obtained the message to my terminal:
-------------------------------------------
[experimental 35ace3a9] 
(the next line I translate from Russian)
On the branch experimental your branch is updated according to «origin/experimental».

 2 files changed, 94 insertions(+), 15 deletions(-)
-------------------------------------------

Is the commit done? Where to see the result?
Thanks.

**Comment by jespercockx** [comment]
`git log` will give you a list of all commits on the current branch in reverse chronological order, yours should be on top of that list.

**Comment by mechvel** [comment]
How can I see on https://github.com/agda/agda-stdlib/...
the files of the branch that I have commit?
Thanks.

**Comment by jespercockx** [comment]
When you 'commit' a patch in git, it is created locally. You first have to push it to your fork (using `git push ...` as I described) and then go to https://github.com/mechvel/agda-stdlib and click the button "create pull request" that should show up. Once you create the PR, one of the maintainers of the library will review it and eventually merge it, which will make it show up on the main repository https://github.com/agda/agda-stdlib/.

**Comment by mechvel** [comment]
After all the "commit" matters (that look successful), I command  
```
> cd agda-stdlib
> git push -f
----------------------------------------------------------------------
Username for 'https://github.com': mechvel
Password for 'https://mechvel@github.com': ********
remote: Permission to agda/agda-stdlib.git denied to mechvel.
fatal: unable to access 'https://github.com/agda/agda-stdlib.git/': 
The requested URL returned error: 403
---------------------------------------------------------------------
```
?

**Comment by mechvel** [comment]
Somewhere in my "profile" on GitHub it is written a strange long email address including the word "scico", instead of my regular email  address  mechvel@botik.ru
May be, this is the reason for the denial?

**Comment by jespercockx** [comment]
The error message says you're trying to push to https://github.com/agda/agda-stdlib, which you don't have permission to do. Instead you should first push to your fork at https://github.com/mechvel/agda-stdlib (by adding it as a remote as I described above) and then create a pull request from there.

**Comment by xekoukou** [comment]
For example I use this : 
```
git push https://github.com/xekoukou/agda-stdlib eqN:eqN
```

You should use this
```
git push https://github.com/mechvel/agda-stdlib experimental:experimental
```

Though it would be better to create a new branch like I did.

**Comment by mechvel** [comment]
I did
``> git  push  -f  my-fork``
and it responded 
```
...
Total 7146 (delta 5084), reused 6725 (delta 4719)
remote: Resolving deltas: 100% (5084/5084), completed with 202 local objects.
remote: 
remote: Create a pull request for 'experimental' on GitHub by visiting:
remote:      https://github.com/mechvel/agda-stdlib/pull/new/experimental
remote: 
To https://github.com/mechvel/agda-stdlib
 * [new branch]        experimental -> experimental
```
Now I visit  https://github.com/mechvel/agda-stdlib/pull/new/experimental,
and it says
```
------------------------------------------------------------------------------
Comparing changes
                                    There isn’t anything to compare.
master is up to date with all commits from experimental. Try switching the base for your comparison.
------------------------------------------------------------------------------
                               No commit comments for this range
---------------------------------------------------------------------------------
```
Who can guess of what to do here?
Trying a luck I clicked at "Pull requests" somewhere (do not recall precisely), and finally have been suggested to do a new pull request.
And now it indeed shows the needed files on 
https://github.com/mechvel/agda-stdlib/tree/experimental
!!
A very complex process! Needs help, and needs even a luck. 

Many thanks to Jesper and to Apostolis!

I have to write down all the process.

**Comment by MatthewDaggitt** [comment]
There are full instructions in the [HACKING](https://github.com/agda/agda-stdlib/blob/master/HACKING.md) file, as advertised on the front page of the repository. This file gives the **exact** commands you need to run.
