### ISSUE TITLE
Problems with the HACKING documentation

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#689]
I follow the instructions of HACKING.md to commit a pull request to standard library, to "master"
(from ghc-8.6.3, Ubuntu Linux 18.04, Firefox browser).
1) It says to apply  the "git add" command, while it needs to be  "git add  .". 

2) "make test" does not report of any errors, "git commit" and "git push" perform all right.
Then I go (via Firefox) to my fork 
                         https://github.com/mechvel/agda-stdlib

HACKING.md says "click the green `Compare & pull request` button to open a pull request".
But there is not such a button.
There are two buttons  close to the right-upper corner: "Pull request" and "Compare", none of them is green.
I click "Compare", and it shows the info about the commit which looks correct.
I return to https://github.com/mechvel/agda-stdlib and click "Pull request".
It shows the title "Comparing changes" and writes
"Choose two branches to see what’s changed or to start a new pull request. ..."
 
I do not understand of whether the PR has been done.
If it is not done, then, please, how to accomplish it?
It shows the commit of April 04, which had errors of "whitespace", and which I need to remove.
And it shows the commit of April 05,  which, I hope, will be all right.

Thanks.

**Comment by MatthewDaggitt** [comment]
You're right, the instructions could have been clearer. I've updated them now. In order to make a pull request I suggest you follow the official Git instructions [here](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork)

**Comment by MatthewDaggitt** [comment]
Was closed with 20cef93dbd6f52d83761d88c9caeccf1c4667c45
