### ISSUE TITLE
Reader monad?

### ISSUE THREAD

**Issue by iitalics** [agda/agda-stdlib#690]
Is there a reader monad (transformer) located anywhere in the stdlib? I'm guessing it should be in `Function.Categorical` perhaps? I can work on implementing that unless there's a specific reason it doesn't exist yet.

**Comment by gallais** [comment]
I'd expect it to be in `Category.Monad.Reader` based on [where `StateT` is defined](https://agda.github.io/agda-stdlib/Category.Monad.State.html).
