### ISSUE TITLE
Change the definition of the free monad on a container?

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#693]
Currently the definition is:

```agda
_⋆C_ : ∀ {x s p} → Container s p → Set x → Container (s ⊔ x) p
C ⋆C X = const X ⊎ C

_⋆_ : ∀ {x s p} → Container s p → Set x → Set (x ⊔ s ⊔ p)
C ⋆ X = μ (C ⋆C X)
```

However Agda can't see that the `Set x` argument is used in a strictly
positive manner (it would need to partially evaluate the specialised type
of `μ`'s constructor (what a mouthful) to see so).

This means that if we try to write the kind of translations we can see in
@ichistmeinname's [Monad to prove them all](https://github.com/ichistmeinname/free-proving) we get a strict positivity
error when defining:

```agda
data List {s p a} (C : Container s p) (A : Set a) : Set (a ⊔ s ⊔ p) where
  []  : List C A
  _∷_ : C ⋆ A → C ⋆ (List C A) → List C A
```

However if we decide to define the free monad directly:

```agda
data _⋆_ {s p a} (C : Container s p) (A : Set a) : Set (s ⊔ p ⊔ a) where
  pure   : A → C ⋆ A
  impure : ⟦ C ⟧ (C ⋆ A) → C ⋆ A
```

Then the fact it's using `A` in a strictly positive manner is self-evident
and our effectful-list is accepted.

We could / should prove that there is a bijection between the old and the new
definitions.

**Comment by JacquesCarette** [comment]
Wouldn't it be even better to fix the positivity checker? Being able to go through layers of descriptions (shades of a current twitter conversation) is quite useful.
