### ISSUE TITLE
Aren't the definitions of LeftCongruent and RightCongruent swapped?

### ISSUE THREAD

**Issue by TheAspiringHacker** [agda/agda-stdlib#695]
https://github.com/agda/agda-stdlib/blob/20cef93dbd6f52d83761d88c9caeccf1c4667c45/src/Algebra/FunctionProperties.agda#L117-L121

This definition of left congruence says, "For all x, you can multiply x on the right and preserve the relation." Vice versa for right congruence. To my understanding, these definitions are switched.

**Comment by MatthewDaggitt** [comment]
Doing a quick search though, you're absolutely right. My fault, clearly my intuition about leftness and rightness needs some work!

Thanks for pointing this out before the release, much appreciated. Would have been a pain to fix otherwise :fearful:

**Comment by MatthewDaggitt** [comment]
Closed with 505cc14

**Comment by mechvel** [comment]
Let  ``_**_ : A  ⟶ B  ⟶ C``
Then
```
 (_** x) Preserves _≈'_ ⟶ _≈''_  
```
means that the map  ``(_∙ x)`` is congruent. And this map is defined on the domain of the _left_ argument of ``_**_``. 
I always thought that for this reason the definition of lib-0.17 agrees with intuition.
?

**Comment by MatthewDaggitt** [comment]
That was my intuition as well. But the only source I can find defines it the other way:

https://groupprops.subwiki.org/wiki/Left_congruence

> both are correct: lib-0.17 and lib-1.0.

lib-0.17 did not [contain](https://github.com/agda/agda-stdlib/blob/v0.17/src/Algebra/FunctionProperties.agda) left or right congruence. The definition is new to v1.0.

**Comment by mechvel** [comment]
> https://groupprops.subwiki.org/wiki/Left_congruence

It writes  "... preserved on left multiplication by any element of the group".
Does "left multiplication by x" mean that x is set on the left side?

I do not expect that there is formed a real classical tradition for this point. 
But your reference somehow makes lib-1.0 winning 1:0.
And I need to swap cong-s in many places in the applications.

**Comment by TheAspiringHacker** [comment]
That page has this picture: https://groupprops.subwiki.org/w/images/math/9/7/8/978d7a892eadc293b6097b72e3150193.png

For left congruence, the c is being multiplied on the left of each side.

**Comment by MatthewDaggitt** [comment]
> But your reference somehow makes lib-1.0 winning 1:0.
And I need to swap cong-s in many places in the applications.

Sorry to hear that, but that is one of the dangers of using an unreleased version of the library!
