### ISSUE TITLE
Why isn't Data.Unit universe-polymorphic?

### ISSUE THREAD

**Issue by benjamin-hodgson** [agda/agda-stdlib#71]
This recursive universe-polymorphic definition of vectors fails to compile with [the `⊤` defined in `Data.Unit`](https://github.com/agda/agda-stdlib/blob/master/src/Data/Unit/Base.agda):

``` agda
Vec : ∀ {α} -> Set α -> ℕ -> Set α
Vec A zero = ⊤
Vec A (suc n) = A × Vec A n
```

```
Set != Set .α
when checking that the expression ⊤ has type Set .α
```

I had to make my own universe-polymorphic copy of `⊤`.

``` agda
record ⊤ {α} : Set α where
  constructor ⟨⟩
```

Why doesn't the version in the library look like this? Would you be open to a pull request to change it?

**Comment by andreasabel** [comment]
Maybe it is not polymorphic since this would produce a lot of unsolved metas?  Do you need to supply level arguments in your uses of the polymorphic \top?  Have you a representative set of sample uses?

**Comment by np** [comment]
What about changing the record type to be universe polymorphic but as a different name and with an explicit level. Then the type ⊤ could be an alias with level 0. The use of a universe polymorphic unit type arise when working with isomorphisms (same level on both sides).

**Comment by asr** [comment]
> Maybe it is not polymorphic since this would produce a lot of unsolved metas?

Right. Using the universe-polymorphic version I got the following unsolved metas:

```
$ make install-bin
Generating Agda library interface files...
Failed to solve the following constraints:
  _236 = .Agda.Primitive.lzero
  _230 = .Agda.Primitive.lzero
  _167 = .Agda.Primitive.lzero
  _250 = .Agda.Primitive.lzero
Unsolved metas at the following locations:
  /.../Agda-2.5.3/lib/prim/Agda/Builtin/Reflection.agda:227,33-37
  /.../Agda-2.5.3/lib/prim/Agda/Builtin/Reflection.agda:240,37-41
  /.../Agda-2.5.3/lib/prim/Agda/Builtin/Reflection.agda:241,40-44
  /.../Agda-2.5.3/lib/prim/Agda/Builtin/Reflection.agda:245,19-23
WARNING: Failed to typecheck Agda.Builtin.Reflection!
```

**Comment by asr** [comment]
> This recursive universe-polymorphic definition of vectors fails to compile with [the `⊤` defined in `Data.Unit`](https://github.com/agda/agda-stdlib/blob/master/src/Data/Unit/Base.agda):

>``` agda
>Vec : ∀ {α} -> Set α -> ℕ -> Set α
>Vec A zero = ⊤
>Vec A (suc n) = A × Vec A n

You can fix the problem using `Lift`(see the answer to [this](http://stackoverflow.com/questions/42416192/lifting-a-type-to-higher-universe) question):

```agda
open import Level

Vec A zero = Lift ⊤
```
