### ISSUE TITLE
Generalise the inductive definition of Permutation

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#713]
The current definition of `Data.List.Relation.Binary.Permutation.Inductive`
is for propositional equality. It would be nice to have it over heterogeneous
relations and then special cases for setoid, propositional equality, etc.

**Comment by MatthewDaggitt** [comment]
I have a Master's student whose done this already a couple of months back.
I'll get him to make a pull request.

**Comment by MatthewDaggitt** [comment]
We now have `Setoid` permutations. What remains is to define propositional permutations in terms of setoid permutations.

**Comment by gallais** [comment]
Also missing `fromPointwise : Pointwise R -> Permutation R`.
Indeed `refl` only talks about propositional equality.

It may also be worth naming the fact that `Permutation` preserves `Pointwise` on both
sides (which is a direct consequence of `fromPointwise` + `trans`)
