### ISSUE TITLE
Unsolved metas when using Relation.Binary.Reasoning.MultiSetoid

### ISSUE THREAD

**Issue by JLimperg** [agda/agda-stdlib#715]
Agda version: 2.6.0
Stdlib version: 1.0
Test case:
```
open import Level using (zero)
open import Relation.Binary using (Setoid)
open import Relation.Binary.Reasoning.MultiSetoid using (begin⟨_⟩_ ; _≈⟨_⟩_ ; _∎)
open import Relation.Binary.Reasoning.Setoid using (_IsRelatedTo_ ; relTo)

module Bug (S : Setoid zero zero) where

  open Setoid S

  bug₁ : ∀ x → x ≈ x
  bug₁ x = begin⟨ S ⟩ x ≈⟨ refl ⟩ x ∎

  bug₂ : ∀ x → x ≈ x
  bug₂ x = begin⟨ S ⟩ (relTo refl)
```

Agda reports unsolved metas of type `Relation.Binary.Symmetric _≈_` in `bug₁` and `bug₂`. Perhaps this is because `Reasoning.MultiSetoid` is ultimately defined in terms of `Reasoning.Base.Single`, whose `_IsRelatedTo_` does not mention symmetry.

**Comment by MatthewDaggitt** [comment]
Thanks for reporting this. I'll look into it when I have a moment.
