### ISSUE TITLE
Back-port new library features to 2.4.2.4

### ISSUE THREAD

**Issue by asr** [agda/agda-stdlib#72]
Agda 2.4.2.4 has been released. We haven't  a *released* version of the library that type-checks with this version of Agda.

I think it's desirable back-port some commits from the master branch into the 2.4.2.4 branch before the release.

**Comment by mietek** [comment]
Ping.

**Comment by mietek** [comment]
It seems that the [2.4.2.4 branch](https://github.com/agda/agda-stdlib/tree/2.4.2.4) works fine with Agda 2.4.2.4, without any changes.

**Comment by asr** [comment]
No surprise, this is the idea.

**Comment by andreasabel** [comment]
I guess the issue title was a bit misleading, so I changed it...

**Comment by asr** [comment]
> I guess the issue title was a bit misleading, so I changed it...

You are right.

**Comment by asr** [comment]
Starting...

**Comment by asr** [comment]
Blocking #74.

**Comment by asr** [comment]
Fixed.

**Comment by asr** [comment]
I tested the previous changes using `make test` in the standard library directory.  I just found some problems running the Agda test-suite...

**Comment by asr** [comment]
The problem was fixed by https://github.com/agda/agda/commit/9f71437acbca4e5fb6572e1c192a8eea13a16328.
