### ISSUE TITLE
"constant time"

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#725]
When we write in the current master branch that ``Nat.Properties.<-cmp`` "runs in constant time"
we assume that each built-in in it runs in constant time.
But in reality it may be  ``c*(log (min m n))`` where ``c`` is a certain small constant -- something of this kind.   
I wonder what needs to be the standard library commentary here.

**Comment by MatthewDaggitt** [comment]
Hmm I was going off the convention that in most programming languages basic arithmetic operations are assumed to be constant, but I guess most programming languages don't work with arbitrarily large data. Will fix.

**Comment by MatthewDaggitt** [comment]
Fixed with a492ea3121b7fc627b0b397213294cb367445664

**Comment by mechvel** [comment]
Consider this Haskell program:
```
n  = 8 :: Integer
p  = n ^ (n ^ n)
p' = rem p 10
main = putStrLn (show p')
```
Making and running:
```
> ghc -O --make Foo
> time ./Foo
```
For n = 8  it runs 0.3 sec on a 3 GHz machine, for n = 9 it runs 16 sec. 
There are processed millions of marcro-digits.
A language, like Haskell or Agda, has nothing to do with basic arithmetic. This is a matter of standard library. And standard library calls built-in functions. The latter's are written, may be in C, they perform arithmetic by processing, may be, a list of macro-digits. And such lists are of arbitrary lengths. As to operations on a macro-digit, some of them are done by a single machine command.

**Comment by JacquesCarette** [comment]
examples such as this are why in certain CAS, one first 'represents' the computation $n ^ (n ^ n)$ and then you perform it in the 'context' of computations mod 10.

**Comment by mechvel** [comment]
The goal was to demonstrate _with example_ that arithmetic built-ins on Integer do not perform in constant time. And the example was not lucky. Here is a more convincive one:
```
n  =  9 :: Integer
p  =  n ^ (n^n);     p' =  succ p
b  =  p == p';        b' =  p*p' == p' * p

main = putStrLn (show b)  -- b'
{-
 n | time(b)  time(b')  difference 
 8 |  0.3      1.4           1.1
 9 | 16.4     46.4        30.0
-}
Set to ``main`` b, and then b', and measure time(b), time(b'). 
Then  d = time(b') - time(b)  is approximately the time spent to  computing  p*p',  p' * p and comparison of their values. The two multiplications and one comparison, while the time for ``_^_`` is cancelled. 
And the table shows that the cost of these two multiplications and comparison depends essentially on the value of p.
