### ISSUE TITLE
Make decidable equality safe for `Data.Float`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#726]
From @gallais 

> I think the more principled way would be to have 2 primitives:
> 
> primitive
>   primFloatEqualitySound    : ∀ (e f : Float) → primFloatEquality e f ≡ true → e ≡ f
>   primFloatEqualityComplete : ∀ (f : Float) → primFloatEquality f f ≡ true

**Comment by L-TChen** [comment]
I am working on this now. I propose to have a built-in conversion from `Float` to the underlying raw data `Word64` based on IEEE 754 standard (binary64) but mapping two `NaN` to the same one. 

A Haskell implementation http://hackage.haskell.org/package/data-binary-ieee754-0.4.4/docs/Data-Binary-IEEE754.html converting `Double` to `Word64` exists already.

**Comment by MatthewDaggitt** [comment]
Fixed in 7eb3cc0
