### ISSUE TITLE
Naming conventions: (from/to)Nat vs. (from/to)ℕ

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#730]
In `Data.Char.Base` we re-export `fromNat` and `toNat`
In `Data.Word.Base` we re-export `fromℕ` and `toℕ`

We should pick one style and stick to it.

**Comment by JacquesCarette** [comment]
I prefer `fromℕ` and `toℕ`, but I prefer consistency way more than the particular choice.
