### ISSUE TITLE
Add tag for v1.0.1

### ISSUE THREAD

**Issue by mcoblenz** [agda/agda-stdlib#742]
It looks like the currently-recommended version is 1.0.1, but there is no tag for v1.0.1, so the installation instructions don't work. The tags should be in sync with the documentation.

**Comment by mcoblenz** [comment]
Regarding instructions, I'm referring to this: https://github.com/agda/agda-stdlib/blob/master/notes/installation-guide.md

**Comment by MatthewDaggitt** [comment]
There is a tag for v1.0.1. See https://github.com/agda/agda-stdlib/tree/v1.0.1.

If you've downloaded the repository before v1.0.1 was released then you'll need to run `git pull` to get the tag.

**Comment by mcoblenz** [comment]
It appears that the tag is only available after `git fetch` if you pass `-t`. Otherwise `git fetch` does not actually retrieve the new tag.
