### ISSUE TITLE
Remove +0 and +[1+_] patterns from `Data.Rational`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#747]
They now also exist in `Data.Integer`. It's going to have to wait until v2.0 as I can't think of a way to do this in a backwards compatible manner, and it's not possible to deprecate syntax.

**Comment by gallais** [comment]
```agda
open import Data.Integer.Base using (+0; +[1+_]) public
```

in `Data.Rational.Base` seems to work just fine for me. Am I missing something?

**Comment by MatthewDaggitt** [comment]
Nope, just being slow! We will still need to remove the "public" keyword in v2.0 though.

**Comment by gallais** [comment]
Wait, we can actually attach a `WARNING_ON_USAGE` to a constructor.
But the corresponding warning is not raised by Agda, which is a bug.

**Comment by MatthewDaggitt** [comment]
Ooh neat. Though if we attach it to the syntax in `Data.Rational.Base` then won't it also be raised when we use it from `Data.Integer.Base`?

**Comment by gallais** [comment]
I'm not sure about this type of corner case to be honest. :D

**Comment by MatthewDaggitt** [comment]
Okay, I've added a comment to them in b1b10c20b027aabb09b55aea7572eb1c06afe1d7. If you're bored, feel free to play around :smile:
