### ISSUE TITLE
Syntax for small `Fin`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#748]
Now that we don't have to worry about pattern matching for absurd `Fin`, it would be really nice if we could define some syntax for common `Fin`, e.g. 0-9
```
pattern 0F = zero
pattern 1F = suc 0F
pattern 2F = suc 1F
...
```
Anyone have any strong preference for what the letter afterwards should be? I've chosen `F` rather than `f` to avoid making them look like floats. For reference we're using `ℓ` for levels, and `ℚ` for rationals at the moment.

**Comment by gallais** [comment]
Of course I'd rather have agda/agda#2851 but in the meantime sounds like a good idea.
The name works for me.
