### ISSUE TITLE
≡-dec for non-dependent product (×)

### ISSUE THREAD

**Issue by iitalics** [agda/agda-stdlib#755]
It would be very simple to implement `≡-dec` for the non-dependent product type, and more importantly it would be valid `--without-K`.

**Comment by gallais** [comment]
I think we have it in `Data.Product.Relation.Binary.Pointwise.NonDependent` under
the name [`≡?×≡?⇒≡?`](https://agda.github.io/agda-stdlib/Data.Product.Relation.Binary.Pointwise.NonDependent.html#9325)

**Comment by MatthewDaggitt** [comment]
I've actually been going around deprecating these lemmas in the Pointwise modules, e.g. [Sum](https://agda.github.io/agda-stdlib/Data.Sum.Relation.Binary.Pointwise.html#9325), [List](https://agda.github.io/agda-stdlib/Data.List.Relation.Binary.Pointwise.html#9325), as I don't think they were very findable as they actually have nothing to do with `Pointwise`. 

So yes, please do open a PR @iitalics.
