### ISSUE TITLE
the BF library proposal

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#757]
Please, consider the project of BFLib-0.1
```
      http://www.botik.ru/pub/local/Mechveliani/bfLib/,
or   https://github.com/mechvel/BFLib-0.1
```
-- see there  announcement.txt.
This is for 
1) improving the Bin part,
2) and for generalizing Rational arithmetic to the Fraction domain constructor.
It is minimal over standard library. That is I tried to follow the rule  
"no item to be introduced if a similar item is in standard (lib-1.0)".
Also this is minimal (simplest) extension with which it is possible for formulate the Fraction constructor.

I could start, say, with the new Bin. The first pull request can be the initial parts of Prelude0.agda  and  Bin/Bin0.agda.
This is the new Bin data, the functions ``_≟_, suc, pred, _+_,  _*_,  2*`` for Bin, and a couple of their properties.  
These changes  will be proposed for the current master branch, probably aiming at lib-1.1
(?).

What do you think of this?

**Comment by gallais** [comment]
[insert rant about a repository being all about a .zip archive rather than source files]

Please consider the idea of submitting **small** and **self-contained** PRs using
the **git versioning system**.

Although it may seem like a daunting task at the very beginning (it was for us all!),
learning a little bit about git will both provide you *and the maintainers* with a
common language (and merging strategy) to communicate in. This means less frustration
for everyone involved an a quicker turnaround.

**Comment by mechvel** [comment]
Let us make it more clear.
The zip archive of the announced BFLib  is an extension of  the ``lib-1.0`` library.
It works under ``lib-1.0``, it would not work under the current _master_ branch.
Now, I can try to _merge_ BFLib-0.1 into _master_ by small parts, with changing each of such part according to the advises of the library team.

The Bin part has to be totally replaced.
And I need a confirmation from the team: do you agree with the whole proposal idea of new Bin 
(see the ``Bin/`` folder of the project) ?
Do you accept that it is not backwards compatible?  is not it too large? and so on.
If the team does not accept the approach, then it would not have sense to start with PR tips, to spend effort (this is a messy work).
Because the Bin part is for a different data representation, it can be merged by small parts, but it cannot be merged partially. 

And having the archive, you can look into  announce.txt  and into the ``Bin/`` folder, and tell. 
The Bin and the Fraction parts of BFLib can be merged-in independently, we can choose what to start with.

As to the git versioning, we have managed with two PRs of mine by following HACKING.md, these were for the agda-stdlib repository. And I hope I can do further PRs in the same style.
As to the current BFLib archive on GitHub, it is not in the Agda repository, it is not a PR, it is just an additional place to refer for an archive of a certain published project.

**Comment by MatthewDaggitt** [comment]
Apologies I'm on holiday in the Australian outback for the next 8 days with
very limited signal (currently on top of a mountain!). I will have a look
at it when I get back.

**Comment by MatthewDaggitt** [comment]
Hi @mechvel, I've had a look at your library. I'll just focus on the `Bin` part of it at the moment.

I was wondering if you could describe the advantages of your formalisation of `Bin` over the existing implementation of `Bin` already in the standard library? What is easier to represent/prove with it?

**Comment by mechvel** [comment]
> I was wondering if you could describe the advantages of your formalisation of Bin over the existing 
> implementation of Bin already in the standard library? What is easier to represent/prove with it?

1) In Bin of lib-1.0 is proved almost nothing. ``ℕ`` has an instance of CommutativeSemiring.
So, Bin also needs to provide such.
It is needed a proof for that  ``fromℕ`` and ``toℕ`` are mutually inverse bijections, and also isomorphisms by _+_ and _*_. Without this, introducing Bin even has not any explained reason, it occurs kind of a senseless construction.
DecTotalOrder is needed for  _≤_.
``ℕ`` has certified ``_∙_ divMod, gcd``. And Bin is another model of  ``ℕ``. So Bin also needs to have such important operations.
Nothing of the above are in lib-1.0, and all this is in BFLib (see the signatures in the source in  Bin/*.agda).
There is nothing to compare, because Bin of lib-1.0 contains almost nothing.

2) The needed items are already contained in Binary-3.2 (it is on GitHub).
 And there is used the Bin representation of lib-0.16. 
Now, BFLib-0.1 rewrites Bin to a new representation -- by certain three constructors.
And the code for Bin in  BFLib-0.1 occurs much simpler than of Bin of Binary-3.2.
The main reason for this is that if a number is represented as a bit list (Bin⁺ in lib-1.0), then many 
bit lists (containing zeroes in the higher end) correspond to the same number. The Bin data in lib-1.0 fixes this by introducing the constructor ``_1#``. But in various further proofs it is difficult to avoid operating with the ``(List Bit)``. This complicates proofs and algorithms.
Probably, there is another reason, but I do not realize it explicitly. 

So: I suggest the Bin part as it is in BFLib-0.1, I am not ready to suggest any other version. 
And everyone is free to suggest other versions.

**Comment by MatthewDaggitt** [comment]
> And the code for Bin in BFLib-0.1 occurs much simpler than Bin of Binary-3.2. The main reason for this is that if a number is represented as a bit list (Bin⁺ in lib-1.0), then many bit lists (containing zeroes in the higher end) correspond to the same number. The Bin data in lib-1.0 fixes this by introducing the constructor _1#. But in various further proofs it is difficult to avoid operating with (List Bit). This complicates proofs and algorithms.

Okay thanks, that was what I was after. That's a good reason for replacing the current implementation. Feel free to submit a pull request with the initial contents of `Bin0.agda`. I suggest the first PR **only** replaces the existing functions in `Bin.agda`. A second PR can then add in your new proofs.

**Comment by mechvel** [comment]
There remains the point of the _license_. The suggested Binary part is an essential part in BFLib-0.1,
and the latter has a certain (free enough) license. As soon as standard library includes a couple of essential methods from  BFLib-0.1, it has to 
* refer to BFLib-0.1 somewhere on the top of its documents
  ("there are used (with modification) the methods from the ... part of BFLib-0.1 library"  -- like this),
* include a copy of the license of BFLib-0.1 (see this license).
Do the Agda library owner (team?) agree with this?

**Comment by MatthewDaggitt** [comment]
> Does the Agda library owner (team?) agree with this?

I'm afraid not. The license you've attached to the BFLib-0.1 is more restrictive than the license accompanying the standard library. People contribute to the library under the understanding that all code is contributed under the terms of the standard library's own license.

As the author of BFLib-0.1 you can of course change the re-license the code as you wish. If you wish to do so and include the code in the standard library than that's fine. Otherwise I'm afraid we can't accept your code, apologies.

**Comment by WolframKahl** [comment]
On Tue, May 14, 2019 at 04:50:53AM -0700, mechvel wrote:
> There remains the point of the _license_. The suggested Binary part is an essential part in BFLib-0.1,
> and the latter has a certain (free enough) license. As soon as standard library includes a couple of essential methods from  BFLib-0.1, it has to 
> * refer to BFLib-0.1 somewhere on the top of its documents
>   ("there are used (with modification) the methods from the ... part of BFLib-0.1 library"  -- like this),
> * include a copy of the license of BFLib-0.1 (see this license).
> Do the Agda library owner (team?) agree with this?

I'd argue that material contributed to agda/agda-stdlib by the owner of BFLib-0.1 does not necessarily count as “taken from BFLib-0.1”; but the contributor is certainly free to attempt to negotiate with agda/agda-stdlib the way the previous publication should be referenced.

The above was the start of that negotiation?

(IANAL.)

**Comment by mechvel** [comment]
??
I am not a lawyer. About two years ago I asked a lawyer in our institute to formulate a possibly free and standard license for my various program libraries, with also a reasonable respect to Institute. Because for all my libraries written in Agda our PSI Institute paid me salary during seven years, and I wrote reports of the project.
I believed the license in BFLib-0.1 is free enough. It is  
"Copyright © 2019  Program Systems Institute of Russian Academy of Sciences ...
GNU General Public License ...
".
So, a) copyright is of PSI,  b) I am the only author.
And who is the owner?
How can I re-license  BFLib-0.1 so that to enable merging it into Standard library and also not to offend the PSI institute?
Merging a considerable part of BFLib-0.1 to Standard library will require some changes in its code, but I expect that 90% of the design will be of  BFLib-0.1.

> I'd argue that material contributed to agda/agda-stdlib by the owner of BFLib-0.1 does not 
> necessarily count as “taken from BFLib-0.1”; but the contributor is certainly free to attempt to 
> negotiate [..]

I expect they will be somewhat 90% taken from there, I intended them to be taken from there.

I wrote BFLib-0.1 for double aim. 1) May be to make it a part of the year report to PSI, to refer to it in the report. 2) After it is released, to negotiate about merging it to Standard, in order for me and others to use its parts in future projects on the basis of standard.
And I tried to write it so that make this merging possibly easy, to have possibly less objections from the library team.
Now I am looking at the two licenses and wonder what concretely to change in order to remove the contradiction. And I do not understand which points precisely make a contradiction, of what need I to ask our lawyer, my institute.
To release BFLib-0.2 which differs from 0.1 only in the license?

Please, advise,
SM.

**Comment by WolframKahl** [comment]
At least theoretically, another option could be that the standard library decides to depend on BFLib, just like it depends on certain ``libraries'' included in the Agda distribution.

**Comment by gallais** [comment]
@mechvel 

You can see the differences between MIT (what agda-stdlib is licensed under) and
GPL3.0 (what BFLib is licensed under) by looking at e.g. the following summaries:

* https://tldrlegal.com/license/mit-license
* https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)

For instance MIT is less restrictive in that it allows users to redistribute the
(potentially modified) work under a more restrictive license (they still need to
include the original copyright and license though).

I understand your struggle as I personally tend to license all my (independent)
research work under GPL3.0 too by default.

You may want to check with your institute's lawyer that you are allowed to relicense
your work under a more permissive license. That being said, I am not aware of any
law constraining researchers receiving public funding to only produce software under
a copyleft license. In fact I am not aware of a law forcing researchers to only produce
free software either (but note that the MIT license is considered [free by the FSF](https://www.gnu.org/licenses/license-list.html#X11License) even
though not copyleft so if such a law were to exist it wouldn't be a problem here).

**Comment by mechvel** [comment]
I look into ``master/LICENSE``, and find it strange. Really does it allow anyone, say, to download lib-1.1, to insert some rubbish and cussing there, say, into the file Data/List.agda, and then to distribute it under the name of lib-1.1 and under the same author list? What the users would think of the authors?

Sorry for may be a silly question, it is too difficult to understand licenses.

**Comment by mechvel** [comment]
Thanks to people for their advises.
I was proud of my wise plan of "release independently an applied lib + then commit it for standard".
But it bites, a bit.
So, if the license is changed to MIT, then it will agree with the Agda standard  library?

**Comment by MatthewDaggitt** [comment]
> At least theoretically, another option could be that the standard library decides to depend on BFLib, just like it depends on certain ``libraries'' included in the Agda distribution.

I don't think the main Agda team would be too keen on this, as the Agda repository has a dependency on the standard library. We don't want to add other dependencies that we can't maintain in the long term. 

> I look into master/LICENSE, and find it strange. Really does it allow anyone, say, to download lib-1.1, to insert some rubbish and cussing there, say, into the file Data/List.agda, and then to distribute it under the name of lib-1.1 and under the same author list? What the users would think of the authors?

As far as I'm aware nothing in your current GPL3.0 license prevents someone from doing this either? In any case, that's kind of a risk you take making things available on the internet, and I doubt that such a v1.1 would be widely recognised.

> So, if the license is changed to MIT, then it will agree with the Agda standard library?

In theory yes. Though I'm not sure what the legal consequences of granting copyright to an institution would be? Does anyone have a (non-lawyer's) opinion? I'm pretty sure that my own university has strict rules about anything it owns the copyright of, including some that definitely conflict with the MIT license.

**Comment by mechvel** [comment]
> As far as I'm aware nothing in your current GPL3.0 license prevents someone from doing this either? 

Due to the requirement of _listing main changes_, the user will know who could change the content, and hopefully even know, in which places. But this not so important now. 

I hope that my institute can change the license for BFLib-0.1. May be, to set into new license the point that a certain exclusion is made for the code committed to Agda standard library.

I have to talk to our lawyer and administration.
I keep in mind something of this sort.
1) BFLib-0.1 to mention the institute in the license and to declare a certain exclusion for Agda standard    library (to include any part without referring to the license and to the institute).
2)  Agda standard library to merge a considerable part (the more the better) of BFLib-0.1 and to mention my name (as a contributor?), and the Agda lib owner to decide whether to mention anything else.
This is my fantasy, a naive stuff.

**Comment by MatthewDaggitt** [comment]
> I keep in mind something of this sort.
> 
> 1. BFLib-0.1 to mention the institute in the license and to declare a certain exclusion for Agda standard library (to include any part without referring to the license and to the institute).
> 2. Agda standard library to merge a considerable part (the more the better) of BFLib-0.1 and to mention my name (as a contributor?), and the Agda lib owner to decide whether to mention anything else.

That would work if you can get your institution to agree to it.

**Comment by mechvel** [comment]
Can anybody correspond with me by e-mail on the subject of the these licenses on behalf of the Agda library team (owner?) ? 

Our director enables me to negotiate about the license question (with me consulting with our patent specialist).
He says that we can re-license BFLib in many ways. And his main wish is:
our Program Systems Institute of Russian academy of sciences  needs to be mentioned somewhere in the documents on the corresponding versions of the Agda standard library
(may be without referring to the BFLib license, without copying it).
Just to mention this organization, may be together with my name as of a contributor. 
Is it possible to mention this institute in the standard library license (copyright?) ?

**Comment by MatthewDaggitt** [comment]
> Can anybody correspond with me by e-mail on the subject of the these licenses on behalf of the Agda library team (owner?) ?

I'd prefer to continue to discuss it in this issue if that's okay with you? The more minds the better in this case.

> our Program Systems Institute of Russian academy of sciences needs to be mentioned somewhere in the documents on the corresponding versions of the Agda standard library

Is this in all documents or just somewhere in the license file? The latter is fine, the former would not be.

> Just to mention this organization, may be together with my name as of a contributor. Is it possible to mention this institute in the standard library license (copyright?) ?

Yup, if we end up replacing `Data.Bin` with your implementation you'll be added as a contributor. As I said above, in principle adding RAS to the copyright is fine as it doesn't give them any rights that the MIT license doesn't already give them. My concern is about anything you might have signed which not only places certain IP obligations on you, but which in turn requires you to place IP obligations on anyone you share the copyright of BFLib-0.1 with?

**Comment by mechvel** [comment]
> I'd prefer to continue to discuss it in this issue if that's okay with you? 
All right.

> As I said above, in principle adding RAS to the copyright is fine as it doesn't give them any rights that > the MIT license doesn't already give them. 

Please, express more clearly. To which copyright? We have copyright of StdLib and the one of BFLib-0.1, and are going to change the latter ....

> does not give _them_ any rights [..]
Who is "them" ?
> IP obligations ...
What is IP? Intellectual Property? 

> My concern is about anything you might have signed which not only places certain IP obligations on 
> you, but which in turn requires you to place IP obligations on anyone you share the copyright of 
> BFLib-0.1 with?

I doubt of whether its meaning can ever be made clear to me. May be only by giving a couple of examples. 
Meanwhile let me try to simplify the negotiation.
 
Myself, and most probably my institute admin, shall be satisfied, for example, with the following.
As I see, the file LICENSE in the Stdlib distribution has the form of
```
Copyright (c) 2007-... Nils Anders Danielsson, Ulf Norell, Shin-Cheng
Mu, Bradley Hardy, Samuel Bronson, Dan Doel, Patrik Jansson,
...
Sandro Stucki, Milo Turner and some anonymous contributors.

Permission is hereby granted, free of charge, to any person obtaining a
...
The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT 
...
```
Right?
It starts with the contributor name list (and copyright holder list?).  
Now, if we agree about a commit of a considerable part of my new ``Bin/``, 
will it be possible to do with the _contributor name list in the file LICENSE_ the following?
To insert  ``Sergei D. Meshveliani`` in this list,
and to add from new line (with new paragraph, if possible) after this list the reference to my institute, 
like this:
```
...
Sandro Stucki, Milo Turner and some anonymous contributors.

(The design of the contribution by Sergei D. Meshveliani was supported by the 
Ailamazyan Program systems institute of Russian academy of sciences).
```
(It is desirable to print the institute name on a separate line).

Under which condition is this possible?  
If this is possible, then _my part_ will need to do with BFLib-0.1 and its license something that enables Stdlib to merge the needed code without mentioning BFLib-0.1 and without mentioning the license or copyright of BFLib-0.1. 

With this do?

The story was that the whole BFLib-0.1 was intended as a proposal for standard library. Justice required me to refer to the institute as to a supporter. And I thought the license is free enough for any reasonable purposes.

**Comment by gallais** [comment]
This seems reasonable to me.

**Comment by mechvel** [comment]
>  then my part will need to do with BFLib-0.1 and its license something that enables Stdlib to merge 
> the needed code without mentioning BFLib-0.1 and without mentioning the license or copyright of 
> BFLib-0.1.

Suppose that I change the BFLib-0.1 distribution in the two places where it resides on the Web by
a) removing the LICENSE folder and the license content, and removing from everywhere the words    
    "copyright" and  "license",
b) adding to  ``announcement.txt``  the paragraph 
    "Author: Sergei D. Meshveliani.
     The design of this library was fully supported by ... Institute of RAS.
    "    

Would this enable the Agda lib owner to do the proposed above change to the file LICENSE in the new standard library?

(a naive thought, I do not understand any in the license matters).

**Comment by MatthewDaggitt** [comment]
Hi @mechvel, yes your proposal in the most recent two posts sounds fine.

**Comment by mechvel** [comment]
Our part agrees.
So, we have concluded an agreement with the Agda library team, as above Right? 

I have made the above changes to the BFLib-0.1 distribution in its public places on the web:
```
   http://www.botik.ru/pub/local/Mechveliani/bfLib/,
   ftp://ftp.botik.ru/pub/local/Mechveliani/bfLib/,
   https://github.com/mechvel/BFLib-0.1
```
Please, check them.
I am now in the process of committing Data.Bin.Bin0.

Then, if and after any essential part of BFLib-0.1 is merged to standard library, you will have, according to our agreement change the LICENSE file as follows.

To insert  Sergei D. Meshveliani in the contributor list,
and to add from new line (with new paragraph, if possible) after this list the reference to my institute,
like this:

(The design of the contribution by Sergei D. Meshveliani was fully supported by the 
Ailamazyan Program systems institute of Russian academy of sciences).

Right?

**Comment by mechvel** [comment]
HuStmpHrrr  wrote
> have you added remote?
> git remote add upstream https://github.com/agda/agda-stdlib
>
Now, I try
```
> git remote add upstream https://github.com/agda/agda-stdlib
(passed silently)
> git checkout master
(following the instruction for Syncing)
"Already on  «master»
Your branch is updated according to «origin/master»".

> git merge upstream/master
(following the instruction)
merge: upstream/master — is not something that can be merged.
```
?
1) What will happen if I do a commit now?
2) What bad will happen if I delete my fork and start a fork by new, in order to PR with Ordering (and may be Minus) for Bin ?

**Comment by MatthewDaggitt** [comment]
You haven't followed step 3 in the instructions and run `git fetch upstream`. This fetches all the changes in the standard library and puts them onto your computer. Then retry `git merge upstream/master`.

**Comment by MatthewDaggitt** [comment]
As for your questions, don't run 1. as it won't include the latest changes in the standard library yet. As for 2. nothing per se, it's just very inefficient as you'll have to download the entire library plus every change that's ever been made to it (hundreds of MB) all over again. Much better to learn the tools to do it properly.

**Comment by mechvel** [comment]
Please, consider the proposal
     http://www.botik.ru/pub/local/Mechveliani/inAgda/gcdProp1.zip

for the design for  divisibility and GCD  for standard library.
The _master_ branch approaches now the part of  divisibility and GCD in new Bin
(it remains to merge Bin.Minus, Bin.GCD).
At this point it has sense to consider the proposal for generalization for this design.

See   
* Readme.lagda  in the archive, 
* then, Structures.agda, NatGCD.agda, Int1.agda, GCDTest.agda,  run GCDTest.

**Comment by MatthewDaggitt** [comment]
Hi @mechvel, I'm not quite sure what your question is here so  I'll try and reply to what I see as the main points of your email [here](https://lists.chalmers.se/pipermail/agda/2019/011279.html).

1) Adding a binary representation of integers is fine. If we're going down this path though I think the new representation of `Data.Bin` should be moved to `Data.Nat.Bin` and the old version reinstated to `Data.Bin` but marked as deprecated. We can then add binary integers as `Data.Integer.Bin`. I also like your notation of `ℕb` and `ℤb` for the types.

2) Adding a generic notion of GCD is also fine in principle. Although I'm not entirely convinced by your argument that it should replace the existing implementation for `Data.Nat.GCD`. I'd be very surprised if the generic version was anywhere near as efficient as the new version.

First of all we should finish merging in your order pull request. It's very close to being finished I think. If you address my last round of comments then I'll touch it up and then merge it in.

After that, please, please, please though can you make sure you submit only **small** pull requests. Your last couple of pull requests have both had over 200 comments on them and have been very time consuming to review. If they're smaller then I think they'll get merged in much quicker and the overall process will be quicker too. Ideally no pull request should be more than 100-200 lines of code.

**Comment by mechvel** [comment]
> I'm not quite sure what your question is here so I'll try and reply to what I see as the main points 
> of your email here.

No, this "here" is an old letter to a wrong list, it is dismissed.
Please, consider  Readme.lagda  in the proposal
http://www.botik.ru/pub/local/Mechveliani/inAgda/gcdProp1.zip.

It is improved, more concrete, and it has been implemented and tested. 

> Although I'm not entirely convinced by your argument that it should replace the existing 
> implementation for Data.Nat.GCD. I'd be very surprised if the generic version was anywhere near > as efficient as the new version.

Please, see  in this proposal Readme.lagda,  GCD notion in Structures.agda,  
see NatGCD.agda, Int1.agda, GCDTest.agda

> After that, please, please, please though can you make sure you submit only small pull requests. > Your last couple of pull requests have both had over 200 comments
> [..]

This is not a pull request. This is a prelude, a proposal for the team to invite a possible next pull request.
The current pull request is only Data.Bin.Properties, I am waiting your solution/notes.

Then, Bin.Minus.agda is on the queue. Then, Bin.DivMod.

And only after this it will come _divisibillity_ and GCD for Bin.
But for this last point, I would suggest a generalization as it is described in Readme.lagda in the 
proposal.  Because it needs to be not only for Bin but for any CancellativeSemiring.

**Comment by MatthewDaggitt** [comment]
Closing as we now have `Data.Nat.Binary` plus a reasonable part of the suggestions here. Adding the rest I think has stalled.
