### ISSUE TITLE
Add Text.Printf

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#767]
Can't believe we don't have this classic example of a dependently-typed primitive! :D

Technical remark: for the catchall-case to reduce in the type of the function, it is important not to define the type by induction on the list of characters but rather on a list of tokens which will have been generated from the list of characters.

i.e. the beginning of the library looks something like this:

```agda
data Chunk : Set where
  Nat : Chunk
  (...)
  Raw : String -> Chunk

toChunks : List Char → List Chunk
toChunks ('%' ∷ 'u' ∷ cs) = Nat ∷ toChunks cs
(...)

-- and then:

Printf : List Chunk → Set
Printf (...)

printf : (cs : List Chunk) → Printf cs
```

**Comment by iitalics** [comment]
Giving it a try [here](https://github.com/iitalics/agda-stdlib/blob/printf/src/Text/Printf.agda).

**Comment by gallais** [comment]
Nice start. A few questions:

* I'm surprised we can't use the character '%' in a string and have it simply mean '%' (no idea whether it would have to be explicitly escaped all the time or whether any pair of consecutive characters starting with '%' and not decoding to a valid spec would mean the '%' is considered raw).

* I'm not sure the added complexity of `Formattable` brings much to the table: in all cases we could generate a `String` (or a list of `Strings` if we want to keep the possibility to use a monoid on `A` to perform the concatenation) and call `fromString` afterwards

* `printf` looks quadratic to me given that we repeatedly call `mapPrintf` to push the newly formatted value under a lot of binders. I think we ought to be able to write a linear version using an accumulator `printfAcc : (fmt : Format) -> List A -> fmt -Printf-> A`.

* An alternative for the definition of `printf` is to define a [`Sets`](https://github.com/agda/agda-stdlib/pull/608/files#diff-6914f76210bd7f1db4b1c03265e9fbbdR57) (more precisely a pair of a natural number and a `Sets` using the `Levels n` which is `0ℓ` everywhere) as the semantics of a `Format`, to write `assemble : (fmt : Format) -> Product _ ⟦ fmt ⟧ -> List String` and then use 
[generic currying](https://github.com/agda/agda-stdlib/pull/608/files#diff-6914f76210bd7f1db4b1c03265e9fbbdR102) to turn that into `(fmt : Format) -> Arrows _ ⟦ fmt ⟧ (List String)`.

**Comment by erydo** [comment]
> I'm surprised we can't use the character '%' in a string and have it simply mean '%'

In every (?) implementation of `printf` I've seen, a literal `%` is escaped as `%%`. Otherwise other kinds of formatting args (like padding, alignment, precision, etc) become ambiguous very quickly.

**Comment by gallais** [comment]
The alternative I was suggesting was not really tractable with the current `Product`
so I have resurrected `Product⊤`. Something like this seems to work:

```agda
{-# OPTIONS --without-K --safe #-}

module Text.Printf where

open import Level using (0ℓ)
open import Data.Char.Base
open import Data.List.Base
open import Data.Nat.Base
import Data.Nat.Show as NatShow
open import Data.Product
open import Data.Product.N-ary.Heterogeneous
open import Data.String.Base
open import Function

data Chunk : Set where
  Nat : Chunk
  Raw : String → Chunk

Format = List Chunk

format : List Char → List Chunk
format = go [] where

  push : List Char → List Chunk → List Chunk
  push [] ks = ks
  push cs ks = Raw (fromList (reverse cs)) ∷ ks

  go : List Char → List Char → List Chunk
  go acc []               = push acc []
  go acc ('%' ∷ '%' ∷ cs) = go ('%' ∷ acc) cs
  go acc ('%' ∷ 'd' ∷ cs) = push acc (Nat ∷ go [] cs)
  go acc (c ∷ cs) = go (c ∷ acc) cs

size : Format → ℕ
size []           = 0
size (Nat   ∷ cs) = suc (size cs)
size (Raw _ ∷ cs) = size cs

⟦_⟧ : (fmt : Format) → Sets (size fmt) 0ℓs
⟦ []           ⟧ = _
⟦ (Nat   ∷ cs) ⟧ = ℕ , ⟦ cs ⟧
⟦ (Raw _ ∷ cs) ⟧ = ⟦ cs ⟧

assemble : ∀ fmt → Product⊤ _ ⟦ fmt ⟧ → List String
assemble []              vs       = []
assemble (Nat     ∷ fmt) (n , vs) = NatShow.show n ∷ assemble fmt vs
assemble (Raw str ∷ fmt) vs       = str ∷ assemble fmt vs

module _ (str : String) where

  private
    cs  = toList str
    fmt = format cs
    n   = size fmt

  Printf : Set (⨆ n 0ℓs)
  Printf = Arrows n ⟦ fmt ⟧ (List String)

  printf : Printf
  printf = curryₙ n (assemble fmt ∘′ toProduct⊤ n)
```

**Comment by JacquesCarette** [comment]
I definitely hope the `assemble`-based version can be made to work. It 'feels right' in a DTL to do it this way.
