### ISSUE TITLE
Document branch structure in HACKING

### ISSUE THREAD

**Issue by phile314** [agda/agda-stdlib#77]
When fixing #75, #76, I wasn't really sure in which branches I should make the commits. I think we should add a HACKING file documenting how the branches should be used.

**Comment by asr** [comment]
> When fixing #75, #76, I wasn't really sure in which branches I should make the commits.

Please back-port your fixes  into the 2.4.2.5 and 2.4.2.6 branches.

**Comment by asr** [comment]
> When fixing #75, #76, I wasn't really sure in which branches I should make the commits.

~~Please back-port your fixes  into the 2.4.2.5 and 2.4.2.6 branches.~~


Please follow these steps:

1. Back-port your fixes into the 2.4.2.5 branch.
2. Merge the 2.4.2.5 branch into the 2.4.2.6 branch.
3. Merge the 2.4.2.6 branch into the master branch.
