### ISSUE TITLE
``+-*-suc`` ?

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#773]
Is not ``m*[1+n]``  a better name for ``+-*-suc`` ?

**Comment by MatthewDaggitt** [comment]
I'm not sure `m*[1+n]` is that much clearer than `+-*-suc`. 

Perhaps `m*[1+n]≡m+m*n` is clearer, but it's much longer...

**Comment by gallais** [comment]
It is a bit strange though that we have `+-suc` vs. `+-*-suc`. I understand that 
the second one makes `_+_` appear but it's essentially a lemma about `_ * (suc _)`
just like `+-suc` is essentially about `_ + (suc _)`.

**Comment by MatthewDaggitt** [comment]
And to make matters more confusing in `Data.Integer.Properties` it's called `[1+m]*n≡n+m*n`.

**Comment by gallais** [comment]
That would be `suc-*` though rather than `*-suc`. ;)
