### ISSUE TITLE
separate "Properties" requirement

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#786]
It does not look natural for contributions to standard library.
Imagine an operation ``minus`` on a type Foo in  Foo1.agda, returning a value in Foo and a 
certain proof. Its implementation calls for ``lemma`` that builds a certain proof. 
``lemma`` uses operations defined in Foo1.agda and also uses some properties of these operations. Now, the standard style requires ``lemma``  to be in Foo-Properties.agda. And Foo-Properties needs to import Foo1,  which makes it an import cycle. Further one will need to split Foo1 and Foo-Properties each to several parts.
 
I think this style with separating the module for Foo and its related operations and the module  for properties of these operations a) is not universal, b) often does not look natural.
In many cases it is simpler to implement "operations" and their property proofs for the type 
Foo in several  .agda modules in the ``Foo/`` folder, without separating "methods" and proofs  
to different modules. 

I suggest to treat this separating style as not obligatory.

**Comment by gallais** [comment]
We already have modules mixing definitions and properties. See [`Data.Integer.Divisibility.Signed`](https://agda.github.io/agda-stdlib/Data.Integer.Divisibility.Signed.html)
for instance.

The split usually happens when a file becomes intractably large. It is then nice to
have the definitions in one place and the properties by its side.

When we have dependencies cycles we typically introduce a `Data.X.Base` with the core
definitions, a `Data.X.Properties` with the properties + remaining definitions which
depend upon the properties and a toplevel `Data.X` re-exporting both the content of
`Data.X.Base` and the functions defined in `Data.X.Properties`. This way programmers
can `open import Data.X` and have access to all the definitions. See e.g. the
Data.Nat hierarchy.

**Comment by mechvel** [comment]
I wrote
> I suggest to treat this separating style as not obligatory.

It occurs to me now that  I do not recall of whether is has ever been announced as obligatory.

**Comment by MatthewDaggitt** [comment]
> Imagine an operation minus on a type Foo in Foo1.agda, returning a value in Foo and a
certain proof.

That's your problem right there. Why should minus return a proof? It should be a binary operation over Foo. Once you change that then all the dependency problems should disappear.

> It occurs to me now that I do not recall of whether is has ever been announced as obligatory.

It is for the size of file you're proposing for Data.Bin!

**Comment by MatthewDaggitt** [comment]
I should add that one of the main problems with mixing all the proofs and properties together as you do in your libraries is that it's quite difficult up find if a given proof exists. If I want to find a particular lemma about multiplication, will it be in Bin0? Bin1? Bin6?

**Comment by mechvel** [comment]
>>  Imagine an operation minus on a type Foo in Foo1.agda, returning a value in Foo and a
>>    certain proof.

>> That's your problem right there. Why should minus return a proof? It should be a binary operation >> over Foo. Once you change that then all the dependency problems should disappear.

For the New Bin commit to stdlib:
please, let us delay the  Bin.Properties  matter and its code change to the end of the commit.

Continuing discussion.
1) There are  ``divMod, gcd, ext-fromℕ``  that include proofs.
2) My claim is general, not only for Bin/.
3) d = a - b  is originally defined in algebra as a solution for x of the equation  x + b = a.
   So it is natural for ``minus`` to also return the corresponding proof.
   And ``∸`` returns Bin, it is implemented via ``minus``.  See Bin/ in BFLib-0.1. 

> It is for the size of file you're proposing for Data.Bin!

> I should add that one of the main problems with mixing all the proofs and properties together as you > do in your libraries is that it's quite difficult to find if a given proof exists. If I want to find a particular 
> lemma about multiplication, will it be in Bin0? Bin1? Bin6?

In the New Bin case, I suggest the following files in  Bin/ :
```
Bin0.agda  Decimal.agda      GCD.agda           LogarithmTest.agda   Ord1.agda
Bin1.agda  DivMod.agda      GCDTest.agda     Minus.agda
Bits.agda   DivModTest.agda  Logarithm.agda  Ord0.agda
```
DivModTest, GCDTest, Logarithm, LogarithmTest  can be canceled, if you care much for the size.

For example, if you search for  *-comm,  only Bin0 and Bin1  fit by name.
Additive items are simpler, they come earlier, so, probably, most multiplicative items are in  Bin1.
Minus needs additive items and ordering (Bin0, Ord0, may be Ord1).
Ord*  are for ordering. In Ord0, the ordering also meets with +, *, ∸, so it imports Bin* and Minus.
DivMod and GCD import everything of the above.
Binary.agda (external to Bin/) reexports everything needed from Bin/.
The names are so that it is clear what each file contains.

Now,  if you introduce  Bin/Properties.agda,   then you will have a file Properties.agda  almost as large as all the above modules in Bin/ together.  You will have to search the needed proof in this file.
For example, observe the file  Data.Nat.Properties.agda:  is it easy to find there a particular proof?

**Comment by MatthewDaggitt** [comment]
> Now, if you introduce Bin/Properties.agda, then you will have a file Properties.agda almost as large as all the above modules in Bin/ together. You will have to search the needed proof in this file.
For example, observe the file Data/Nat/Properties.agda: is it easy to find there a particular proof?
(though Bin.Properties will be considerably smaller).

At least you know that they'll be in that file and therefore they are searchable easily via `ctrl-s`. Also `Data.Nat.Properties` has quite a lot of structure that makes it easy to at least locate the right section of the file.

It's fine to keep more advanced operations in their own file (e.g. DivMod, GCD).

**Comment by mechvel** [comment]
As you use ``ctrl s``, similarly it works  ``grep <string> *.agda``.

A program system (or library) must provide tools (and needs to be organized so as) to support search for needed definitions, functions, proofs.
And even for the best advanced libraries such a search remains a great problem. The search method, or a search engine needs to be too clever and cultured. Even the best human experts sometimes are not able to find in Web the needed articles on the subject which must be familiar to them.
Because for the same notion there are many ways to express it via other notions, and they get very different names, so that the key words often do not help.
In Agda, the same notion or property can be formulated as different type expressions, and get different names. But in standard library, the names and notions are expressed more or less standard, or classically. ``WithoutZeroDivisor`` can denote the same as ``IntegralRing``,
``x∙x≈x`` can also be denoted ``∙-idempotent``, and so on. The user does not know initially the denotation choice.

**Comment by gallais** [comment]
I don't understand how a discussion about search engines is relevant in the debate
on whether the `Data.X.Base` & `Data.X.Properties` is a clearer separation strategy
than `Data.X.X0`, `Data.X.X1`, etc.

**Comment by mechvel** [comment]
> I don't understand how a discussion about search engines is relevant in the debate
> on whether the Data.X.Base & Data.X.Properties is a clearer separation strategy

Because Matthew writes about when things are easier to search. 

I do not  suggest a natural-indexed system for stdlib.
I discuss of what to do, for example with the modules like Nat.Properties of about 2000 lines.
And also what to do when Properties.agda is forced to include computing usual values. The name 
Properties somehow does not characterize it any more. Then, one could consider inclusion of all the Bin library part into a single module called Properties.

As to New Bin, I an going to suggest something like the following .agda files:
```
  Base,  Properties,  Ord-I,  Ord-II,  Minus,  DivMod,  GCD
``
The name  ``Base`` gives few information. The name ``Properties`` does not indicate, for example, of whether the properties related to ``Ord-I`` or say ``GCD`` are proved in this module.      
The naming problem is similar with such of Data/Nat/.

And consider the textbook "Algebra I" &  "Algebra II". It is a spot of natural indexing, and no one objects.

**Comment by MatthewDaggitt** [comment]
> And also what to do when Properties.agda is forced to include computing usual values.
The name Properties somehow does not characterize it any more.

What do you mean by this?

> As to New Bin, I an going to suggest something like the following .agda files:
> Base,  Properties,  Ord-I,  Ord-II,  Minus,  DivMod,  GCD

Let's get the current PR merged in first, and then we can discuss the rest.

**Comment by mechvel** [comment]
>>  And also what to do when Properties.agda is forced to include computing usual values.
>>   The name Properties somehow does not characterize it any more.

> What do you mean by this?

Generally, it is possible that there are written many functions that compute and return proofs together with ordinary values.  All of them can be put to Foo.agda and also to Properties.agda.

But I think that in our concrete case of new ``Bin/``, it is better to try first to PR
``Base, Properties`` in ``Bin/``, then probably to try to add ``Ordering`` and ``Minus``,  and then to see.

**Comment by MatthewDaggitt** [comment]
> Generally, it is possible that there are written many functions that compute and return proofs together with ordinary values. All of them can be put to Foo.agda and also to Properties.agda.

It is possible, but in general the standard library tries to avoid this pattern as it often leads to cyclic dependencies. Though as you say we'll discuss this in the next PR.

I'll close this issue for now as I think we've finished the discussion.
