### ISSUE TITLE
Question on naming in Data.Fin.Base

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-stdlib#804]
consider two functions in
https://github.com/agda/agda-stdlib/blob/master/src/Data/Fin/Base.agda#L65

```agda
fromℕ≤ : ∀ {m n} → m ℕ.< n → Fin n
fromℕ≤″ : ∀ m {n} → m ℕ.<″ n → Fin n
```

why are the names of these functions using `≤` instead of `<`? I know `<` is defined in terms of `≤` but still this is puzzling.

**Comment by MatthewDaggitt** [comment]
No idea, they predate me by quite a long way. I agree it's a little odd. Not sure if it's worth changing...

**Comment by HuStmpHrrr** [comment]
yeah, I am on the side to change them.

**Comment by JacquesCarette** [comment]
There's been a big push on consistency of naming, now's not the time to give up!
