### ISSUE TITLE
Ordering  properties in Data.Nat.Properties is inconsistent

### ISSUE THREAD

**Issue by Taneb** [agda/agda-stdlib#81]
`≤pred⇒≤` and `≤⇒pred≤` have the numbers explicit, `<⇒≤pred` implicit, and `≰⇒>` uses `⇒`.

I believe these should be edited to all use `⇒`.

**Comment by MatthewDaggitt** [comment]
I agree, it's confusing as it stands. 

As they can always be inferred, the arguments to `≤pred⇒≤` and `≤⇒pred≤` have been changed in a08036f so they are now implicit rather than explicit.
