### ISSUE TITLE
Cyclical module dependencies due to changes in Propeq.

### ISSUE THREAD

**Issue by xekoukou** [agda/agda-stdlib#812]
https://github.com/agda/agda-stdlib/blob/ab0adc54233f836396b51a9e41f460c0f937ebe8/src/Relation/Binary/PropositionalEquality.agda#L20

Fin.Base cannot use Nat.Properties dues to circular dependencies because NonDependent uses Fin.Base. Maybe move the N-ary version in a different file?

**Comment by gallais** [comment]
I think I am going to refactor `substₙ` and `congₙ` based on `Equalₙ` defined in
#811. I can move the definitions at the same time.

**Comment by MatthewDaggitt** [comment]
Closed with 9b5b63e84241f6e08f3ef0e493e38c9d64e9505f
