### ISSUE TITLE
Fixity error when using StarReasoning

### ISSUE THREAD

**Issue by sstucki** [agda/agda-stdlib#814]
The following snippet using `StarReasoning` (preorder reasoning for reflexive transitive closures) does not typecheck because of a fixity issue:

```agda
open import Relation.Binary.Construct.Closure.ReflexiveTransitive
open import Relation.Binary.Construct.Closure.ReflexiveTransitive.Properties

module _ {A : Set} where

data _~_ : A → A → Set where
  step : ∀ {a} b → a ~ b

_~⋆_ : A → A → Set
_~⋆_ = Star _~_

open StarReasoning _~_

dummy : (a b : A) → a ~⋆ b
dummy a b = begin
  a    ⟶⟨ step b ⟩
  b    ⟶⋆⟨ ε ⟩
  b    ∎
```

if the last reasoning step is enclosed in parentheses, the proof typechecks:

```agda
dummy : (a b : A) → a ~⋆ b
dummy a b = begin
  a    ⟶⟨ step b ⟩
  (b   ⟶⋆⟨ ε ⟩
  b    ∎)
```

The  problem seems to be that the`_⟶⟨_⟩_` combinator introduced in `StarReasoning` has fixity 2 while the other combinators for preorder reasoning have fixity 0. This used to work fine in earlier versions of the standard library, so I suspect it's a regression introduced by #586.

I would have submitted a pull request to fix this, except I'm not sure whether the "right" fixity for both combinators should be 0 or 2. The combinators used in `StarReasoning` are those defined in `Relation.Binary.Reasoning.Base.Double` where they are declared to have fixity 0, but there's a similar set of combinators in `Relation.Binary.Reasoning.Base.Single` with fixity 2, which seems to have been the fixity for preorder reasoning prior to #586. Is there a reason for this inconsistency? Why was the fixity changed in #586?

**Comment by MatthewDaggitt** [comment]
Nice find!

> Why was the fixity changed in #586?

Unintentional. I must have copied and pasted it from somewhere. I think the best course is to revert it back to fixity 2. The preorder reasoning module (and partial order reasoning which was based on it) formed the basis of almost every reasoning module in the library and it all seemed to work fine. Additionally the propositional equality reasoning module also seems to use fixity 2. 

If you submit a PR in the next few days, I'll make sure to get it in for v1.1.

**Comment by sstucki** [comment]
PR submitted: #817.
