### ISSUE TITLE
Add category laws for sublists

### ISSUE THREAD

**Issue by andreasabel** [agda/agda-stdlib#816]
` Data.List.Relation.Binary.Sublist.Setoid` defines the preorder of order-preserving embeddings of lists,
```agda
⊆-isPreorder : IsPreorder _≋_ _⊆_
⊆-isPreorder = record
  { isEquivalence = ≋-isEquivalence
  ; reflexive     = ⊆-reflexive
  ; trans         = ⊆-trans
  }
```
but it does not prove the category laws, which are very useful if one wants to use sublist-proofs as renamings in lambda calculus.
These laws would be:
- left unit: `⊆-trans ⊆-refl = id`
- right unit
- associativity of `⊆-trans`

Further, it would be useful to have the functor laws for `Data.List.Relation.Binary.Sublist.Propositional.lookup` in Data.List.Relation.Binary.Sublist.Propositional.Properties:
- identity: `lookup ⊆-refl = id`
- composition: `lookup (⊆-trans p q) = lookup q . lookup p`

**Comment by jamesmckinna** [comment]
Amazed that this hasn't been tackled in the last 5 years!?
