### ISSUE TITLE
Relations over construction?

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-stdlib#828]
I somewhat want a `All` relation on transitive closure now. I am wondering how usual people quantify over free constructions of relations?

**Comment by MatthewDaggitt** [comment]
Sorry, any chance you could give a brief example of what you're after?

**Comment by HuStmpHrrr** [comment]
for example, I defined something like this in the categories library:

https://github.com/agda/agda-categories/blob/90fed129c953162629dfd2375fa55159d775d76d/Categories/Morphism/Isomorphism.agda#L72-L74

but this can be generalized as a relation over transitive closure

```agda
    data AllPlus : ∀ {R} → A [ R ]⁺ B → Set _ where
      [_]     : ∀ {a b} (r : R a b) → AllPlus [ r ]
      _∼⁺⟨_⟩_ : ∀ a {r+ : a [ R ]⁺ b} {r+′ : b [ R ]⁺ c} → AllPlus r+ → AllPlus r+′ → AllPlus (a ∼⁺⟨ r+ ⟩ r+′)
```

something like this would be preferable.

**Comment by MatthewDaggitt** [comment]
I haven't personally come across anything like that before.

**Comment by WolframKahl** [comment]
I first thought that `AllPlus` asserts that some edge predicate holds for all edges in a `Plus`-path, but looking more closely it appears to me that `AllPlus` is just an isomorphic re-wrapping of `Plus`. What am I missing?

(I find that the variable names `r+`, `f⁺`,... feel wrong: I'd probably have `{aR⁺b : a [ R ]⁺ b}` or even just `{a~b : a [ R ]⁺ b}`.)

**Comment by MatthewDaggitt** [comment]
In a weird conincidence, I've just found that I need an `Any` type over `Closure.Transitive` similar to the lines that @WolframKahl suggests. I'll code it up and might submit it depending on how general I can make it.

**Comment by HuStmpHrrr** [comment]
I think Wolfram is right. it's just a wrapper. I need to revise and see if I actually need this definition.

**Comment by MatthewDaggitt** [comment]
Closing as I don't think we actually came to a conclusion about what was needed. @HuStmpHrrr feel free to reopen if you have a concrete suggestion.
