### ISSUE TITLE
≡-Reasoning produces garbled goals

### ISSUE THREAD

**Issue by andreasabel** [agda/agda-stdlib#83]
```agda
open import Data.Nat
open import Relation.Binary.PropositionalEquality

open ≡-Reasoning

test : 0 ≡ 0
test = begin
  0 ≡⟨ {!!} ⟩
  0
  ∎

-- Goal is garbled:
--
-- ?0 : (.Relation.Binary.Setoid.preorder (setoid ℕ)
--  .Relation.Binary.Preorder.∼ 0)
-- 0
```
With `C-u C-u C-c C-,` I am getting the readable goal `0 ≡ 0`.  However, I'd prefer to see readable goals already in my goals list, and not only after normalization.
What speaks against a native implementation of equality reasoning for propositional equality, as opposed to instantiating preorder-reasoning?  A native implementation should give us readable goals without relying on Agda's heuristics to print goals.

**Comment by andreasabel** [comment]
Now the goal is nicely displayed as `0 == 0`.

**Comment by nad** [comment]
@andreasabel, did you try using a DISPLAY pragma?

**Comment by nad** [comment]
I tried using a DISPLAY pragma, but didn't get it to work.

> What speaks against a native implementation of equality reasoning for propositional equality, as opposed to instantiating preorder-reasoning?

The usual arguments against copying and pasting code?

**Comment by andreasabel** [comment]
Generality and readability seem to be opposing goals, as long we have no revelation how to get good printing of instantiated constructions.
Ideally, we could define most list operations via `foldr` but that does not work for similar reasons.
I think in this case, the amount of cut-and-paste is minimal, as the operations for equality chains are either the identity, or aliases for trans and refl.  I hope duplication is forgiveable here.  The benefits seems to outweight the lack of idealism in this case.

**Comment by nad** [comment]
In this case one could also argue that there is little need to display the goal in the right format, because the goal type is already present in the source text.

If you decide to stick with this change, then I suggest that you update the documentation in Relation.Binary.EqReasoning, which mentions Relation.Binary.PropositionalEquality.≡-Reasoning.

**Comment by andreasabel** [comment]
I was mainly worried to shock newcomers in my Agda tutorial by these garbled goals showing the worst sides of Agda's printer.

**Comment by asr** [comment]
I guess the standard library shouldn't be used by newcomers, so modify the library for teaching purposes is not a good idea.

**Comment by andreasabel** [comment]
Which library then?  We are still shipping it as the "standard library", and this is what most people use.

**Comment by nad** [comment]
> I guess the standard library shouldn't be used by newcomers, so modify the library for teaching purposes is not a good idea.

Andreas didn't cripple the library for power-users, or something like that. He replaced one implementation with one that is (hopefully) functionally equivalent (except that things may be printed in a more readable way).

**Comment by jespercockx** [comment]
Well, one could imagine a power user proving some general lemma about the result produced by Preorder-reasoning and then wanted to apply this lemma to a proof produced by equality-reasoning. That said, I think that's pretty rare and we should keep at least a portion of the std-lib accessible to newcomers, so I'm in favor of this change.
