### ISSUE TITLE
Data.Fin should not export pattern synonyms

### ISSUE THREAD

**Issue by mietek** [agda/agda-stdlib#830]
Before case splitting on `m`:
```agda
open import Data.Fin using (Fin ; zero ; suc)
open import Data.Nat using (ℕ ; zero ; suc)

foo : ℕ → ℕ → ℕ
foo zero m = {!!}
foo (suc n) m = {!!}
```
After case splitting on `m`:
```agda
open import Data.Fin using (Fin ; zero ; suc)
open import Data.Nat using (ℕ ; zero ; suc)

foo : ℕ → ℕ → ℕ
foo Data.Fin.0F Data.Fin.0F = {!!}
foo Data.Fin.0F (suc m) = {!!}
foo (suc n) m = {!!}
```

There are at least three problems here.  **This issue is about problem 3.**

1. Case splitting on `m` changes a part of the line that is not `m`. (https://github.com/agda/agda/issues/3878)
2. Pattern synonyms are imported even though they are not requested. (https://github.com/agda/agda/issues/3879)
3. **The Agda standard library includes pattern synonyms in `Data.Fin` without considering the impact of problems 1 and 2.**

Checked in Agda 2.6.0.1 with standard library 1.1.

**Comment by MatthewDaggitt** [comment]
Hmm I agree this far from ideal. How serious do people think this is? I know that this is perhaps shirking responsibility but I do feel this is a problem with the language rather than the library...

**Comment by gallais** [comment]
Just like we have `X.Literals`, we could have `X.Patterns`.
Breaking change given that 1.1 has been released but may be worth it still.

**Comment by mietek** [comment]
I think that until the language is improved, the standard library should avoid the language’s pitfalls.

**Comment by MatthewDaggitt** [comment]
> I think that until the language is improved, the standard library should avoid the language’s pitfalls.

Yup I agree. I also like @gallais's suggestion. The question is, is this worth creating a `v1.1.1` for or is it `v1.2`?
