### ISSUE TITLE
Syncing a fork

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#831]
After my last PR is merged to ``master``, I need to suggest a next PR starting with a fresh ``master``.
Matthew writes that the best way to do this is to follow the instructions of
https://help.github.com/en/articles/syncing-a-fork
("Syncing a fork").
Following these instructions, I command  ``> cd .../agda-stdlib-fork``
to get to my local project that has been last committed (where CHANGELOG.md resides).
Then I command
```
> git fetch upstream
```
It reports
```
fatal: 'upstream' does not appear to be a git repository
fatal: failed to read from the remote repository
Make sure that you have access rights and the repository exists. 
```
May be, I better proceed in a simple way: delete the fork and start a new one?
I wonder, what harm may this do.

Please, advise.

**Comment by HuStmpHrrr** [comment]
have you add remote?

```
git remote add upstream https://github.com/agda/agda-stdlib
```

**Comment by MatthewDaggitt** [comment]
Yup, @HuStmpHrrr's answer should put you on the right track. Also @mechvel please could you not open a new issue for every problem you have with git. We want to keep the `Issues` focused on the Agda. If you do need help, it'd be much better to ask on the existing issue about the Agda feature you're working on (i.e. #757 in this case).
