### ISSUE TITLE
Bin constructors in `master`

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#832]
This is on new Bin of `master`.
Please, return the Bin constructors from  ``2[1+_], 1+[2_]`` to ``2suc, suc2*``.
Compare
```
suc2*-x<2suc-x :   ∀ x → suc2* x < 2suc x
```
to new
```
1+[2-x-<-2[1+-x :   ∀ x → 1+[2 x ] < 2[1+ x ] 
1+[2-x-<-2[1+-x x =  ...
```
Is not it clear that the last name is ugly and difficult to read?
One can try the name  ``odd-x-<-even-x`` for the property.  But this will mislead the reader. 
Because it looks like a memo for "any odd x", while it is in fact ``1+2x``.
One can try  ``1+[2x]<2[1+x]``. 
But this looks like a mnemonic for  ``1B + 2B * x < 2B * (1B + x)``,  which is not the goal.

Now an then there appear ugly effects in using these  ``2[1+_], 1+[2_]``, while ``2suc, suc2*`` 
look all right everywhere.

**Comment by MatthewDaggitt** [comment]
Sorry for not replying for a while. I actually think that for this example your suggestion of `1+[2x]<2[1+x]` is the best solution. You say that it might clash with `1B + 2B * x < 2B * (1B + x)` but the latter would never be added to the library as it's too specific so I don't think that's a problem.

Would you post a list of the names that you're having difficulty with below and we'll have a look at them? If we can't come up with suitable names for some of them, then yes we can switch back. However I haven't found a problematic example yet.
