### ISSUE TITLE
``0<1+n``

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#834]
This is on the ``master`` branch.
I suggest to add this to Data.Nat.Properties:
```
0<1+n :   ∀ {n : ℕ} → 0 < suc n
0<1+n {n} =  m≤m+n 1 n
```
Because it is much easier to understand the expression ``0<1+n`` in a program than   
``m≤m+n 1 n``.
Am I missing something?

**Comment by MatthewDaggitt** [comment]
Yup, good suggestion!
