### ISSUE TITLE
Glorious clickable HTML with versioning for v1.1

### ISSUE THREAD

**Issue by wenkokke** [agda/agda-stdlib#836]
The glorious clickable HTML pages for the Agda standard library seem to be maintained for older versions, e.g., the following pages exist:

https://agda.github.io/agda-stdlib/Data.Nat.html
https://agda.github.io/agda-stdlib/v0.17/Data.Nat.html
https://agda.github.io/agda-stdlib/v1.0/Data.Nat.html

However, the following page does not exist:

https://agda.github.io/agda-stdlib/v1.1/Data.Nat.html

I think it's unlikely that Data.Nat was deprecated between v1.0 and v1.1, and therefore it seems likely that this is a bug.

**Comment by gallais** [comment]
Fixed by d14883bdfb666df82c6f48580eb1525447b608a0
