### ISSUE TITLE
Decidable equality for some builtins requires K

### ISSUE THREAD

**Issue by JLimperg** [agda/agda-stdlib#837]
The proofs of decidable equality for certain builtins (`Float`, `Word`, various types in `Reflection`) rely on `Agda.Builtin.Equality.Erase.primEraseEquality`. `primEraseEquality` is safe only when axiom K is enabled, so these modules currently require `--with-K`. That's obviously a problem if you want to write K-free code; in particular, I'd like to be able to use reflection in a K-free context.

As far as I can tell, there's no reason in principle why these decidable equality proofs should require K. Indeed, for the types in question, equality should be a proposition in the HoTT sense anyway, so K shouldn't make a difference. The reliance on K therefore seems like an unfortunate artefact of the implementation. However, I don't understand the primitive magic that's going on, so I don't know whether this stuff could be made K-free.

**Comment by MatthewDaggitt** [comment]
As I understand it this problem has already been fixed on the `experimental` branch of the standard library. See for example decidable equality in `[Data.Float.Properties](https://github.com/agda/agda-stdlib/blob/experimental/src/Data/Float/Properties.agda)`. I think issue #698 was the motivating issue. The changes will be added to the next version of the standard library after Agda-2.6.1 is released.

**Comment by JLimperg** [comment]
Beautiful, thank you! Sorry for the duplicate, I was only looking at K-related issues.
