### ISSUE TITLE
Add a universe polymorphic Unit type?

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-stdlib#839]
Issue #71 explains quite well why `⊤` in `Data.Unit` is not universe polymorphic.

But sometimes, one just needs a universe polymorphic unit type - see https://github.com/agda/agda-categories/pull/22 in particular.  Yes, one could use `Lift` all over the place, resulting in very ugly code, while the current code is quite clean.  I've also had to define it in the pi-dual repository, and I think also elsewhere too.

So the idea would be to add a new Unit type, which would be universe polymorphic. It could go into `Data.Unit` under a new name or `Data.Unit.Polymorphic` (or ???). But I think it is sufficiently useful to define it. [And likely the same for `Data.Empty`].

**Comment by WolframKahl** [comment]
I call it `Data.Unit.Generalised`.

**Comment by MatthewDaggitt** [comment]
I think I prefer to `Data.Unit.Polymorphic` but I'm happy with `Data.Unit.Generalised` if people prefer.

**Comment by TOTBWF** [comment]
In a similar vein, it would be quite handy to have a universe polymorphic Empty type as well.

**Comment by JacquesCarette** [comment]
So, in theory, this is now fixed - there is now `Data.Unit.Polymorphic` and `Data.Empty.Polymorphic`.  However the situation is still somewhat sub-optimal: these definitions do not interact very well with the ones in `Data.Unit` and `Data.Empty`.  In the sense that many uses of `Lift` on these in the rest of the library cannot be removed as there would be knock-on effects.

I think that for `Data.Empty`, this can be fixed be having `⊥` be an alias for `⊥ {0ℓ}`. Less sure how well that would work for `Data.Unit` since that's really `Agda.Builtin.Unit`, and I think that would mean having the `Level`-polymorphic `⊤` all be translated uniformly to Haskell.

**Comment by MatthewDaggitt** [comment]
Added in 4aecce2

**Comment by MatthewDaggitt** [comment]
@JacquesCarette feel free to open another issue if you'd like to continue to explore where they can be used.
