### ISSUE TITLE
Missing Monoid for Maybe and Add Point

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#845]
For Maybe: empty is nothing and append is the first-just.

For [Add.Point](https://agda.github.io/agda-stdlib/Relation.Nullary.Construct.Add.Point.html), empty is nothing and append is assuming the set we added a point to is a semigroup.

**Comment by lexvanderstoep** [comment]
I'm planning to have a go at this issue. Could you explain what the first-just operator refers to?

**Comment by gallais** [comment]
`Maybe` is typically used for representing errors. As a consequence the sensible
notion of monoid is one where unit is `nothing` and multiplication is the function
which returns the first (left to right) value to be a `just`.

**Comment by lexvanderstoep** [comment]
If I'm not mistaken, it seems to be that the _<|>_ operator is the first-just operator. The corresponding monoid is <|>-isMonoid in Data.Maybe.Properties.

**Comment by jamesmckinna** [comment]
So... should this issue now be closed, since #1751 and @lexvanderstoep 's observation above?
Notwithstanding my own concerns under #1957 and the abandoned (for the time being) #1958 and #1963 , which we might revisit in the future...

**Comment by JacquesCarette** [comment]
It feels like there is nothing left to do for this particular issue, so that keeping it open does not help us?

**Comment by jamesmckinna** [comment]
@JacquesCarette i agree, but had been leaving this open for someone to reach the same conclusion...
... I think this falls under a time when issues weren't linked for automatic closure when PRs were merged addressing them. I've wasted some time on issues that seemed open, but were in fact already 'morally' closed... so let's do this here...
