### ISSUE TITLE
Add properties of ⌊_⌋

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#846]
We do not have of the properties of [`⌊_⌋`](https://agda.github.io/agda-stdlib/Relation.Nullary.Decidable.Core.html) as far as I can tell.

E.g. `⌊ Dec.map′ t f d ⌋` is equal to `⌊ d ⌋`.

**Comment by jamesmckinna** [comment]
For your example result: 
```agda
⌊⌋-map′ : ∀ t f (a? : Dec A) → ⌊ map′ {B = B} t f a? ⌋ ≡ ⌊ a? ⌋
⌊⌋-map′ t f (true  because _) = refl
⌊⌋-map′ t f (false because _) = refl
```
or else
```agda
⌊⌋-map′ : ∀ t f (a? : Dec A) → ⌊ map′ {B = B} t f a? ⌋ ≡ ⌊ a? ⌋
⌊⌋-map′ t f a? rewrite isYes≗does (map′ t f a?) | isYes≗does a? = refl
```
using the existing `Relation.Nullary.Decidable.isYes≗does`. 

Another instance of the [Fairbairn threshold](https://wiki.haskell.org/Fairbairn_threshold) not being met?

**Comment by JacquesCarette** [comment]
I think that, in Agda, the Fairbairn threshold is quite a complex affair: one should really be counting the (implicit) number of reductions and delta-expansions that are needed for the result to be trivial.  I'd add these properties explicitly.

**Comment by jamesmckinna** [comment]
Agree it's not a straightforward question, apologies for suggesting it might be... but there has been quite a lot of recent invocation of the criterion in relation to such matters ...
