### ISSUE TITLE
``abs-*-commute``

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#858]
Data.Integer.Properties declares ``abs-*-commute : ...``.

This overlaps with using the ``-homo`` denotation in the ``master`` branch, for example,  
Data.Bin.Properties  has ``toℕ-homo-+, toℕ-homo-*``.

I suggest not to use "commute" instead of  "homo", and in particular, to set  ``abs-homo-*``.

**Comment by jamesmckinna** [comment]
Closing this issue now, after `abs-*-commute` was deprecated in favour of `abs-*` in v2.0...
