### ISSUE TITLE
Advertise the index more prominently

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#859]
The [index](https://agda.github.io/agda-stdlib/) lists pretty much all the modules defined in the stdlib.
Should we actively filter out the deprecated ones instead?

**Comment by MatthewDaggitt** [comment]
Sounds like a plan to me! I also had no idea the index even existed :laughing: we should probably put a link to it on the front page.

**Comment by JacquesCarette** [comment]
Agreed on filter. I also didn't know - so agreed on link on front page too!

**Comment by gallais** [comment]
Done a19c6a411d403a3dbbbd061e25fcb96c176ff586

Leaving this open for the link-related discussion
