### ISSUE TITLE
Keep definitional irrelevance out of the standard library as much as possible

### ISSUE THREAD

**Issue by andreasabel** [agda/agda-stdlib#862]
This is a reaction to PR #717 which exposed https://github.com/agda/agda/issues/3986 to the user of the standard library.

As definitional irrelevance is not a stable feature yet, I think we should keep it out of the standard library as much as possible.  (Exceptions may be developments that use irrelevance in a essential way, like where irrelevance is already integral part of the design of the data structures.)

(For a similar reason, instance arguments should not enter the standard library, except maybe in a dedicated layer.)

The standard library should rather err on the conservative side (being too slow to pick up features) than on the progressive.

**Comment by gallais** [comment]
Should Agda have a `--no-irrelevance` option? Otherwise maintaining the invariant
is a bit tricky.

**Comment by JacquesCarette** [comment]
Until we know irrelevance is a stable feature, maybe make it incompatible with `--safe` ? That would make `--no-irrelevance` a less urgent option to have.

**Comment by MatthewDaggitt** [comment]
I'm mostly happy with that. The only place I'm aware of which would really suffer is the definition of rationals. If the proof that they're normalised is not marked irrelevant, then it's going to make them much much harder to work with... So I'd be on the side of keep it out as much as possible but not completely.

Agree with @gallais that an option for enforcing this would be ideal. @JacquesCarette I'm not sure I agree about making it incompatible with `--safe`. It seems different from the other safe incompatible features in that we really do want it to be safe and as far as I'm aware no one can currently prove false with it?

**Comment by JacquesCarette** [comment]
It was a question rather than a recommendation...  Barring bugs, that feature probably is safe.

**Comment by HuStmpHrrr** [comment]
don't we rewrite categories just because the previous library with irrelevance completely fails to compile...? I am agreeing with @andreasabel's doubt on the usage of this.
