### ISSUE TITLE
where are properties of ``<`` and its ``≤`` in general ?

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#866]
This is on  lib-1.1.
Having  ``≈`` and  ``sto : StrictTotalOrder``, and ``≤`` defined via ``≈, <`` in Relation.Binary.Properties.StrictTotalOrder,
I define several relations and prove various general statements for ``<`` and  ``≈``:
```
x ≉ y =  ¬ x ≈ y;      _>_ =  flip _<_;      _≥_ ;     _≰_  ...

<⇒≤ :  ∀ {x y} → x < y → x ≤ y
≰⇒> :  ∀ {x y} → x ≰ y → x > y
<⇒≉ :  ∀ {x y} → x < y → x ≉ y
≈⇒≮ :  ∀ {x y} → x ≈ y → x ≮ y
≤∧≉⇒< :  ∀ {x y} → x ≤ y → x ≉ y → x < y
...
```
But probably such items are defined/proved somewhere in lib-1.1, 
are they?

**Comment by MatthewDaggitt** [comment]
In Relation.Binary.Construct.StrictToNonStrict

**Comment by mechvel** [comment]
I do not see there
```
_≥_ ,   _≰_,    _≮_,   _≯_,   _≱_,

≰⇒> :  ∀ {x y} → x ≰ y → x > y
<→≉ :  ∀ {x y} → x < y → x ≉ y
<⇒≱  :  ∀ {x y} → x < y → x ≱ y
≤⇒≯ :  ∀ {x y} → x ≤ y → x ≯ y
≮⇒≥ :  ∀ {x y} → x ≮ y → x ≥ y
x≮x :   ∀ {x} → x ≮ x
≤∧≉⇒< :   ∀ {x y} → x ≤ y → x ≉ y → x < y
```

**Comment by MatthewDaggitt** [comment]
Ah yes, sorry that's my own library I have them in. That's where they should go though. If you have proofs of them feel free to submit a PR adding them in :+1: 

They can then be re-exported by `Relation.Binary.Properties.StrictTotalOrder/StrictPartialOrder` with the preconditions filled in.

**Comment by mechvel** [comment]
> If you have proofs of them feel free to submit a PR adding them in 

I can commit only a single current PR (I feel it is difficult for to run various branches, too much to study about git).
So, I wait for you to process my last commit of August 5 on new Bin (Bin.Properties).
After it is corrected and merged in, I would do the next commit with Bin, and would include there the above proofs for ``_≥_ ,   _≰_,    _≮_,   _≯_,   _≱_``.
Is it all right?
Alternatively, if  you ask, I can send you the corresponding module by e-mail, so that it will be easy for you to edit and merge its code yourself.

**Comment by MatthewDaggitt** [comment]
@mechvel see #875 for the pattern you should follow if you do decide to do this.

**Comment by MatthewDaggitt** [comment]
Closing as I think the question has been answered.
