### ISSUE TITLE
Deprecating `Data.Table` in favour of `Data.Vec.Functional`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#870]
@gallais if you get to use James' [blog post](https://personal.cis.strath.ac.uk/james.wood.100/blog/html/VecMat.html) to argue for adding [Reflects](https://github.com/agda/agda-stdlib/issues/225#issuecomment-525622181) into the library, I'm going to use it to argue for fixing `Data.Table` :stuck_out_tongue_closed_eyes: 

I share @James's opinion that the record structure doesn't add anything for inference. Furthermore it's fairy difficult to work with. I've tried twice now to integrate into my own library  and failed because:
-  it makes it makes it very difficult to define recursive functions over it because you have to keep removing and adding the record constructor.
- it makes it much more difficult to compose them together to define matrices as again the record constructor gets in the way.

I propose leaving `Data.Table` in place, deprecating it, and add the non-record version as `Data.Vec.Functional`

**Comment by gallais** [comment]
I agree that insisting on making `Table` a record was a mistake on my part.
As james highlights, it would have made sense for a dependent function space
but the current definition is just needlessly painful to work with.

**Comment by laMudri** [comment]
I'd be happy to work on `Data.Vec.Functional` before AIM. For backwards compatibility, it might make sense to reimplement all of the definitions in the `Data.Table` hierarchy to just unwrap/wrap all `Table`s and then call stuff from `Data.Vec.Functional`. Minor matters: what should the type be called? `Table`? `Vec`? Something else?

**Comment by MatthewDaggitt** [comment]
> I'd be happy to work on Data.Vec.Functional before AIM

That'd be great, thanks! 

> For backwards compatibility, it might make sense to reimplement all of the definitions in the Data.Table hierarchy to just unwrap/wrap all Tables and then call stuff from Data.Vec.Functional

Hmm I'm not sure about that. The idea with backwards compatibility is not to change any observable behaviour. The problem with reimplementing `Data.Table` in terms of the new `Data.Vec.Functional` is that it'll probably change the reduction behaviour. To be honest I'd just leave `Data.Table` as is and slap a deprecated warning on it.

> Minor matters: what should the type be called? Table? Vec? Something else?

I've gone off `Table`. How about `Vector` as i) it distinguishes it from `Vec` and ii) I like `Matrix` better than `Mat`. Open to other suggestions though?

**Comment by laMudri** [comment]
Initial issues: though it's nice to define `Matrix A m n` as `Vector (Vector A n) m`, when you get to pointwise lifting of relations, a record wrapper *does* help with inference. So we (might) want this definition:

```
record Pointwise (R : REL A B ℓ) (u : Vector A n) (v : Vector B n) : Set ℓ where
  constructor mk
  field get : ∀ i → R (u i) (v i)
open Pointwise public
```

But with this, lifting relations pointwise over `Matrix` by using this `Pointwise` twice becomes annoying.

Something I've been considering is introducing this definition.

```
Indexed : ∀ {i u} {I : Set i} (U : I → Set u) {a} (A : Set a) → I → Set _
Indexed U A i = U i → A
```

For `Vector`, `U = Fin`, and for `Matrix`, `U (m , n) = Fin m × Fin n`. It feels a bit like containers, but with only one shape (avoiding lots of `tt , [...]` and `[...] .proj₂`), and more focus on `I` (the dimensions). The intention is that `U` is injective to make things work out. I haven't tried this out yet, though.

**Comment by MatthewDaggitt** [comment]
> Initial issues: though it's nice to define Matrix A m n as Vector (Vector A n) m, when you get to pointwise lifting of relations, a record wrapper does help with inference.

Really, that's disappointing... Can you give an example? I've got quite a full set of definitions in my library: [Pointwise](https://github.com/MatthewDaggitt/agda-routing/blob/master/RoutingLib/Data/Table/Relation/Binary/Pointwise.agda), [Equality](https://github.com/MatthewDaggitt/agda-routing/blob/master/RoutingLib/Data/Table/Relation/Binary/Equality.agda), [DecEquality](https://github.com/MatthewDaggitt/agda-routing/blob/master/RoutingLib/Data/Table/Relation/Binary/DecidableEquality.agda) etc. and for matrices [Pointwise](https://github.com/MatthewDaggitt/agda-routing/blob/master/RoutingLib/Data/Matrix/Relation/Binary/Pointwise.agda), and I don't remember anywhere where inference fell down unexpectedy.

I'd definitely prefer to avoid introducing records if at all possible, for exactly the reason that it makes lifting to matrices unpleasant. If the price to pay is that we need to include a couple of arguments explicitly then I think I'd be happy to pay it.

**Comment by laMudri** [comment]
To be honest, the only library definition I tripped up on was `++⁺`.

```
++⁺ : ∀ {xs ys xs′ ys′} →
      Pointwise {n = m} R xs ys → Pointwise {n = n} R xs′ ys′ →
      Pointwise R (xs ++ xs′) (ys ++ ys′)
```

`R` could be given explicitly to this, so maybe that's the way to go.

**Comment by wenkokke** [comment]
> I've gone off `Table`. How about `Vector` as i) it distinguishes it from `Vec` and ii) I like `Matrix` better than `Mat`. Open to other suggestions though?

If we're calling this `Vector`, why not put the code in `Data.Vector`?

**Comment by MatthewDaggitt** [comment]
We did have a very similar conversation recently (https://github.com/agda/agda-stdlib/pull/805#issuecomment-507034494) about where to put `Kleene` lists. The general consensus seemed to be to group isomorphic types together under one folder. 

To aid discovery, I plan to add references to other implementations in the top level files, e.g. `Data.Vec` will have a comment pointing to the existence of `Data.Vec.Functional`. I agree that long modules names are still kind of problem though. What do people feel about `Data.Vec.Func`?

**Comment by wenkokke** [comment]
That leaves us in a bit of a pickle regarding matrices, though. You seemed pretty happy with `Data.Matrix` (see [here](https://github.com/agda/agda-stdlib/pull/882#issuecomment-529063894))... but that'd be rather inconsistent with `Data.Vec.Functional`.

**Comment by MatthewDaggitt** [comment]
Hmm I see your point that it's inconsistent, but it doesn't explicitly go against the policy that isomorphic types should be grouped together. It's just that the primary implementation would be different... 

I don't know. I don't really have any good answers... I don't think exploding the every implementation out into its own top level folder is the right way to go, but at the moment we don't have a consistent scheme for when a datatype should or shouldn't be in a subfolder. If you do have a proposal for such a scheme we'd definitely be all ears? A few example subtypes such a policy should cover is:

- Data.Nat & Data.Nat.Binary
- Data.Vec & Data.Vec.Functional
- Data.List & Data.DifferenceList
- Data.List & Data.FreshList (constrained, not isomorphic)
- Data.Vec & Data.Vec.Bounded (contrained, not isomorphic)

**Comment by JacquesCarette** [comment]
I've been meaning to comment for a while:  I am very much in favour of the `Indexed` approach. The other approaches (such as `Pointwise`) are fundamentally 1-dimensional and don't generalize well. They are very convenient and less noisy when dealing with 1D things.  It also makes it easier to deal with the case where the index set is structured (think symmetric matrices) or sparse.  In fact, a whopping 14 years ago I wrote [a long post](https://haskell-cafe.haskell.narkive.com/E7AFcxtk/matrix-computations-based-on-the-gsl#post8) to the Haskell mailing list about this very design space.

It is also worth remembering [Parnas' admonition](https://sci-hub.tw/10.1007/978-1-4612-6315-9_24) to not venerate Hierarchies too much! Math and CS are not hierarchical, the 'dependency graph' is indeed a graph. No single tree will ever quite capture the real structure.

To me, it would actually make sense to pick an arbitrary spot in the tree (but in a deterministic way) to put the principal source, but then put in 'links' in the other just-as-good spots to where to find the actual source. This makes human findability much better!

**Comment by laMudri** [comment]
@JacquesCarette Thanks for the input. This is quite a crucial time to get these things right, given how close `Data.Vec.Functional` is to being merged, and the fact that we've done a lot of work about vectors this AIM that is dribbling out in pull requests as it can.

> The other approaches (such as `Pointwise`)

I'm not quite sure what you're referring to here. `Pointwise` is a construct rather than an approach in and of itself.

> are fundamentally 1-dimensional and don't generalize well

1-dimensional in the sense of having no dependencies? I think I'd call this “0-dimensional”, so maybe not. If you're talking about tensor rank, I'd argue that the `Indexed` approach is less compositional when we want to go to higher ranks.

> think symmetric matrices

You're thinking of only having a triangle of indices rather than a square? I'd imagine it's easier to work with full matrices, then have the extrinsic symmetry property. This way, we still have a definition of multiplication, for example.

> or sparse

I've said I don't currently care about performance, but this seems like a useful generalisation to keep open in case anyone does care about performance.

---

One quite neat pattern we've come across in implementing the algebra of vectors and matrices is that, given a (left/right semi)module, this can be lifted to a similar module with one more dimension. The type signature of this operation then looks pleasingly similar to the type signature of the `Vector` type former.

```
Vector : Set a → ℕ → Set a
Vector A n = Fin n → A

-- Lift addition to vectors
pointwise-abelianGroup : AbelianGroup c ℓ → ℕ → AbelianGroup c ℓ
pointwise-abelianGroup abelianGroup n = record
  { Carrier = Vector Carrier n
  ; ...
  } where open AbelianGroup abelianGroup

-- Lift addition and scaling to vectors
pointwise-module : {R : CommutativeRing c ℓ} → Module R m ℓm → ℕ → Module R m ℓm
pointwise-module module′ n = record
  { Carrierᴹ = Vector CarrierAᴹ n
  ; ...
  } where open Module module′
```

Noting that R gives rise to an R-module (the one with |M| = |R|), `pointwise-module n (unit-module R)` is the module of vectors over R, and `pointwise-module m (pointwise-module n (unit-module R))` is the module of matrices over R. This kind of construction would still be possible if we restrict to the single index of `Indexed`, but we'd end up wanting to deal with `Indexed (λ (_ : ⊤) → ⊤) A tt` to get the same uniformity.

**Comment by laMudri** [comment]
Thorsten notes that `Indexed` is also known as “representable functors” or “Napierian containers”. It seems that we could do a lot of linear algebra very generically over `U`.

 - The building up of pointwise stuff as described in my last reply is entirely generic.
 - Tensor products require dimensions to form a multiplicative monoid.
 - Biproducts require dimensions to form an additive commutative monoid.
 - Concrete matrices (including an algorithm for multiplication) require some way to fold over all `U d`.

The last point feels much more constraining than the rest, but maybe it would be a good idea to keep these four and their requirements separate as much as possible. However, this is saying little about the original problem with `Pointwise`, just that everything else might work out.

**Comment by JacquesCarette** [comment]
I've been meaning to get back to this for a while.  It's complicated.  The ideas in your second comment are much more along the lines of what I was thinking of.

By 1-dimensional, I really meant that the 'index space' has a linear order (like vectors often do), but a matrix isn't so much a 1+1 dimensional space as a more natively 2-dimensional space (in the same way space-time is 3+1 dimensional, not 4 dimensional, if that helps).  Another way to think of it is: don't repeat the Fortran vs C mistake of making a deep commitment to memory layout, when a matrix is really a representation of a linear operator over a basis - and that basis itself is presented in an arbitrary order.

**Comment by laMudri** [comment]
Thanks again for the comment. It seems that this project has stalled a little due to lots of small issues, and it'd be nice to get them sorted.

The way I read this a bit more concretely is that we're noticing that while `M i` looks superficially elegant as a way of selecting row `i` of matrix `M`, there's no reason to prioritise this over selecting column `j`, where we have to do `λ i → M i j` or `flip M j`. Somehow it makes more sense to me that matrices are indexed by a single pair, rather than two indices in turn. This is maybe why I was thinking of `Indexed` in the first place.

What I'd really like is to reuse the existing container infrastructure (`Data.Container`) rather than a new definition specialised to the `Shape = ⊤` case. If there's any way to do that without introducing too much noise (the `tt ,_` and `proj₂` I mentioned earlier), I'd be very interested. Otherwise, maybe I should make this definition.

**Comment by MatthewDaggitt** [comment]
We missed `Algebra.Operations.CommutativeMonoid` in the original deprecation. The new warnings are now flagging it. We need to fix that before v1.3.

**Comment by MatthewDaggitt** [comment]
Mostly done in #1075 except in `Algebra.Properties.CommutativeMonoid` which as we discussed will be deprecated in v1.4.

**Comment by MatthewDaggitt** [comment]
Finally finished in #1351
