### ISSUE TITLE
where is ``filter-cong`` 

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#877]
Please, where is in lib-1.1 congruence of  ``filter`` with respect to the pointwise equality?
I program it as below, but probably it is somewhere in lib-1.1:
```
module ListOverSetoid {α α=} (A : Setoid α α=) 
    where
    ...
    lSetoid = ListPoint.setoid A
    open Setoid lSetoid using () renaming (_≈_ to _≋_)

    filter-congʳ :  ∀ {β} {P : Carrier → Set β} {p? : Decidable P} → P Respects _≈_ →
                                                    (filter p?) Preserves _≋_ ⟶ _≋_
    filter-congʳ  ... =  ... 
```

**Comment by MatthewDaggitt** [comment]
`Data.List.Relation.Binary.Equality.Setoid.filter⁺`

**Comment by mechvel** [comment]
Thank you for the reference.
Now i doubt about the name ``filter⁺``.
This property means actually congruence of  ``filter`` when the first argument ``p?``  is fixed.
So, similarly to congruence of ``Magma.+`` it needs to be ``filter-congˡ ``.
