### ISSUE TITLE
Private properties used in records

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#88]
Currently in many of the Properties.agda files there are proofs hidden under the `private` that are then later bundled up into records. For example `⊔-assoc` etc. in [Data.Nat.Properties](https://github.com/agda/agda-stdlib/blob/master/src/Data/Nat/Properties.agda).

Currently, in order to use these the record has to be imported and then separately opened to extract the property. This can lead to a lot of clutter at the top of files with lots of additional records needing to be opened. It would be much easier if these were automatically imported when you imported the Properties file.

Is there any particular reason why these are hidden away behind `private` declarations? I can't see any namespace conflicts but maybe I'm missing something? If there isn't any particular reason, I'll submit a pull request to make them public...

**Comment by andreasabel** [comment]
I agree these properties should be public to make them easier accessible!  Please make a pull request (and remind me to merge it).

**Comment by asr** [comment]
@MatthewDaggitt please also add an entry in the CHANGELOG file.

**Comment by MatthewDaggitt** [comment]
Okay, I've submitted a pull request with an added entry in the CHANGELOG file as requested.

**Comment by andreasabel** [comment]
Merged some parts today.

**Comment by MatthewDaggitt** [comment]
All major examples sorted.
