### ISSUE TITLE
Support GHC 8.8.1: master or experimental

### ISSUE THREAD

**Issue by asr** [agda/agda-stdlib#884]
I'm working in https://github.com/agda/agda/issues/3725. Where should I push the required changes by GHC 8.8.1, into `master` or into `experimental`? I guess I should push the changes into `experimental` but Agda is actually using `master` so I'm confused.

**Comment by gallais** [comment]
If your changes are compatible with Agda 2.6.0.1 then `master`, if they make
use of features only available in the dev version of Agda then `experimental`.

**Comment by asr** [comment]
Why is not Agda using `experimental` then?

**Comment by gallais** [comment]
It could indeed.

**Comment by asr** [comment]
Thanks!
