### ISSUE TITLE
Add Membership cast

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#892]
```agda
cast : ∀ {A : Set} {x y : A} {xs} → x ≈ y → x ∈ xs → y ∈ xs
```

and its properties (e.g. `cast refl` is the identity, `cast (trans eq eq')` is
composition of casts, etc.

**Comment by gallais** [comment]
I guess this is a special case of `Any`'s `map` so we should be able to piggy-back
on that and the associated lemmas.

**Comment by MatthewDaggitt** [comment]
I think this is `∈-resp-≈ : ∀ {xs} → (_∈ xs) Respects _≈_` in `Data.List.Membership.Setoid.Properties` no?

**Comment by MatthewDaggitt** [comment]
Don't have the properties though. Doesn't seem like they'd hold for anything apart from propositional equality though, in which case isn't that just `subst`?
