### ISSUE TITLE
Direct product functor for algebra hierarchy

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#893]
Standard library needs the direct product functor  ``_×_`` (product) not only for (Dec)Setoid but also for 
Magma, (Commutative)Semigroup, (Commutative)Monoid, (Abelian)Group,
(Commutative)Semiring, (Commutative)Ring.

Has Standard library such?

This is as follows:  if G and H are Abelian groups with the carriers A and B, then the product functor supplies A × B with the instance of AbelianGroup with defining multiplication coordinate-wise.   
Similarly it is for other structures in the above list, and the implementation is simple.

(Causion: the product functor mainly stops at this point. For example, a product of two 
IntegralDomain's  is not of IntegralDomain).

**Comment by MatthewDaggitt** [comment]
> Has Standard library such?

Nope. They'd live under `Data.Product.Algebra.NonDependent` if you'd like to add them?

**Comment by MatthewDaggitt** [comment]
`Algebra.Construct.DirectProduct` was added in https://github.com/agda/agda-stdlib/pull/1109

**Comment by mechvel** [comment]
It has sense to add there the four instances: (Commutative)Semiring, (Commutative)Ring.

**Comment by MatthewDaggitt** [comment]
Feel free to open a PR with them :+1:
