### ISSUE TITLE
Turn Data.Product's -,_ into a pattern?

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#900]
At the moment [-,_](https://agda.github.io/agda-stdlib/Data.Product.html#2196) cannot be used on the LHS. :(

**Comment by MatthewDaggitt** [comment]
I know it's one less character, but is it clearer on the LHS than just leaving the underscore in place? No strong feelings, just that I suspect most readers will have to look up what it stands for.

**Comment by gallais** [comment]
In my use case I write something like:

```agda
f (c x y) = let (_ , (a , b)) = f x
            let (_ , (c , d)) = f y
            in -, ((a , c), (b , d))
```

It would be nice to have a clear common pattern between the matches in the `let`s
and the final expression.

**Comment by MatthewDaggitt** [comment]
Fair enough :+1:

**Comment by gallais** [comment]
I have just realised that because patterns are refolded automatically, this
would mean that all pairs `(a , b)` would be displayed as `-, b`. I think
this is not acceptable.

**Comment by jespercockx** [comment]
Reference to the corresponding Agda issue discussing whether pattern synonyms should automatically be refolded: https://github.com/agda/agda/issues/2902
