### ISSUE TITLE
`make test` problem with GHC 8.6.3, agda 2.6.0

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-stdlib#904]
In preparation for working on adding a few things to stdlib, I got a fresh clone of the master branch of stdlib, and tried to `make clean; make test` to ensure I was starting from something stable.  Instead I got
```
/Users/carette/Library/Haskell/ghc-8.6.3/lib/lib-1.2/bin/AllNonAsciiChars
cabal exec -- GenerateEverything
Warning: The exec command is a part of the legacy v1 style of cabal usage.

Please switch to using either the new project style and the new-exec command
or the legacy v1-exec alias as new-style projects will become the default in
the next version of cabal-install. Please file a bug if you cannot replicate a
working v1- use case with the new-style commands.

For more information, see: https://wiki.haskell.org/Cabal/NewBuild

GenerateEverything: src/Foreign/Haskell/Coerce.agda is not declared unsafe but not using the --safe option either.
CallStack (from HasCallStack):
  error, called at GenerateEverything.hs:149:33 in main:Main
```

Not quite sure what to make of that. [I'm on a Mac if that matters]

**Comment by MatthewDaggitt** [comment]
Hmm just tried it myself and I'm getting neither of those warnings. In fact I was getting a different warning (deprecated terms being used in `Data.Bin.Properties`).

The first error message sounds like cabal. What version are you using? I'm on `1.24.0.2`.

The second error is weird. It's [generated](https://github.com/agda/agda-stdlib/blob/a9b3af387a0a43ff5e21dcddb4ea7aa41f9baebc/GenerateEverything.hs#L188) when `Foreign.Haskell.Coerce` isn't explicitly listed as unsafe in `GenerateEverything.hs` but as you can [see](https://github.com/agda/agda-stdlib/blob/a9b3af387a0a43ff5e21dcddb4ea7aa41f9baebc/GenerateEverything.hs#L41) it definitely is. Furthermore `Foreign.Haskell.Coerce` was added at the same time as that line so it's not like you're on outdated commit...

**Comment by JacquesCarette** [comment]
I wasn't too worried about the `cabal` warning, I know what it's about.  I'm on `2.4.1.0`.
I'm wondering if it's another one of those Mac things where line endings get in the way.

**Comment by MatthewDaggitt** [comment]
Does `Foreign.Haskell.Coerce` have the `--safe` option in your version of the file? And is it listed in the safe list in your `GenerateEverything.hs`?

**Comment by JacquesCarette** [comment]
Answers: no. no.

**Comment by MatthewDaggitt** [comment]
Hmm from the sound of it, you haven't managed to pull the correct master branch. Have you managed to find the problem this week?

**Comment by JacquesCarette** [comment]
I'm still catching up - had major deadline for a monster of a paper yesterday. Between that and my elevated admin duties, I've been unable to get back to this.

But I don't understand: the version of `Foreign.Haskell.Coerce` on here (https://github.com/agda/agda-stdlib/blob/master/src/Foreign/Haskell/Coerce.agda) does not have `--safe`, and https://github.com/agda/agda-stdlib/blob/master/GenerateEverything.hs lists it as unsafe too. My copies are identical to that.

**Comment by JacquesCarette** [comment]
I've upgraded to `2.6.0.1`, and the problem went away. So I'm not going to fuss about it as things now work. I can now move on to making PRs, which is really what I was after.
