### ISSUE TITLE
Generalise `Data.Product.Relation.Binary.Pointwise.NonDependent` to REL

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#906]
Could then be used for  `zip⁺` in the new `Data.Vec.Functional.Relation.Binary.Pointwise`

**Comment by jamesmckinna** [comment]
When the range of applicability of a concept is 'widened' in this way (cf. making definitions more `Level`-polymorphic), I had understood that to be a `breaking` change... or not?

**Comment by MatthewDaggitt** [comment]
Unless it's know to generate new unsolved metas, then no such a change is not considered breaking as it doesn't require the user to alter their code. Therefore I don't think this qualifies?
