### ISSUE TITLE
`_/_` and `_%_` with irrelevant instance arguments

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#921]
Given #862 and the general policy to avoid using currently unstable features of Agda I know this isn't going to make it in anytime soon, but I thought I'd at least document for some point in the future that there are far superior definitions of `_/_` and `_%_` using instance arguments:

```
_/_ : (m n : ℕ) → .{{NonZero n}} → ℕ
m / suc n = div-helper 0 n m n
```

Current we have to write horrible things like this:
```
∀ m n {gcd≢0 : NonZero (gcd m n)} → Coprime ((m / gcd m n) {gcd≢0}) ((n / gcd m n) {gcd≢0})
```
but with the above the definition this becomes:
```
∀ m n {{NonZero (gcd m n)}} → Coprime (m / gcd m n) (n / gcd m n)
```

**Comment by JacquesCarette** [comment]
Clear, concrete and useful examples such as the above will hopefully drive features forward.

I wonder what the above would look like in cubical agda?

**Comment by mechvel** [comment]
As to me, it is better to write things plainly, with a proof argument and with proving irrelevance.
For example, I have
```
record EuclideanDomain α α≈ :  Set (sucL (α ⊔ α≈))                                
  where                                                                           
   field                                                                           
    divRem       : C → (y : C) → y ≉ 0# → C × C     -- Euclidean division: (quotient , remainder)          
    divRemEq< : (a b : C) → (nzb : b ≉ 0#) →                                      
                            let (q , r) = divRem a b nzb                          
                            in                                                    
                            a ≈ (q * b) + r  ×   ((nzr : r ≉ 0#) → ∣ r ,, nzr ∣ <ₙ ∣ b ,, nzb ∣)       
             -- again, ∣_,,_∣  is the norm operator, which is only for nonzeroes
             
    -- axiom of congruence and irrelevance of the quotient:                                                                                  
    quot-cong : {a a' b b' : C} (nz : b ≉ 0#) (nz' : b' ≉ 0#) → a ≈ a' →  b ≈ b' →         
                                                                  proj₁ (divRem a b nz) ≈ proj₁ (divRem a' b' nz')    
```
It works in many my examples.
Somehow unavoidable complication.
We have to patiently suffer of these irrelevance+congruence proofs.
Other approaches may give a shorter code, but will not be clear to understand.

And concerning relying on `suc`: 
many domains have ``≉ 0#`` but do not have `suc` which is sensibly related to this predicate.

**Comment by effectfully** [comment]
I like using the following trick (the whole issue is discussed in detail [here](https://raw.githack.com/effectfully/inference-in-agda/master/InferenceInAgda.html#computing-predicates-division)):

```agda
open import Data.Nat.Base

_`div-suc`_ : ℕ -> ℕ -> ℕ
n `div-suc` m = go n m where
  go : ℕ -> ℕ -> ℕ
  go  0       m      = 0
  go (suc n)  0      = suc (go n m)
  go (suc n) (suc m) = go n m

data Promote {A : Set} : A -> Set where
  promote : ∀ x -> Promote x

_`div`_ : ∀ {m} -> ℕ -> Promote (suc m) -> ℕ
n `div` promote (suc m) = n `div-suc` m

open import Relation.Binary.PropositionalEquality
open import Data.List.Base

_ : map (λ n -> n `div` promote 4) (0 ∷ 1 ∷ 2 ∷ 3 ∷ 4 ∷ 5 ∷ 6 ∷ 7 ∷ 8 ∷ 9 ∷ 10 ∷ 11 ∷ 12 ∷ [])
  ≡                                (0 ∷ 0 ∷ 0 ∷ 0 ∷ 1 ∷ 1 ∷ 1 ∷ 1 ∷ 2 ∷ 2 ∷ 2  ∷ 2  ∷ 3  ∷ [])
_ = refl
```

and ``n `div` promote 0`` gives a somewhat readable error about `0` not being a `suc`.

Although in more complicated cases it wrapping to / unwrapping from `Promote` might be clunky, I suppose.

**Comment by MatthewDaggitt** [comment]
Closed with https://github.com/agda/agda-stdlib/pull/1538

**Comment by MatthewDaggitt** [comment]
@mechvel we have an issue open already for creating a generic `NonZero` definition, and you'll be happy to know that the current definition of `NonZero` does not rely on `suc`:
https://github.com/agda/agda-stdlib/blob/3e64f6ca848696eb6eb434e758bb345fdc806840/src/Data/Nat/Base.agda#L89

@effectfully thanks for your comment, that is indeed a neat trick! However, I think the approach adopted in #1538 has some significant advantages over `Promote`. Firstly, as you say, `Promote` requires wrapping and unwrapping and secondly, `Promote` requires that your input argument to be in the form `suc _`. This means that you couldn't for example pass in `n !` into  it, as it's in the wrong form, even though `n !` is always non-zero.

**Comment by mechvel** [comment]
It suggests
```
record NonZero (n : ℕ) : Set where
   field
     nonZero : T (not (n ≡ᵇ 0))

instance
   nonZero : ∀ {n} → NonZero (suc n)
   nonZero = _
```


To my mind  NonZero  needs to be defined in Algebra.Definitions,
under the parameters  `≈` and `0#`  this way:
```
IsNonZero : Pred C α≈
IsNonZero = (_≉ 0#)

NonZero :  Set (α ⊔ α≈)
NonZero =  Σ C IsNonZero
```
Then it can be repeated in  Algebra.Properties.Semiring,
where ≈ and 0# are substituted from  Semiring.

Further, everywhere where (nz : NonZero) is needed as argument,
it has to be used  Algebra.Properties.Semiring.NonZero R,
where R is the needed instance for Semiring.
For example, Nat.DivMod imports  Data.Nat.Properties  and +-*-semiring
from it.
The same is for Integer.

And the matter of irrelevance to be treated directly and explicitly.
?

**Comment by MatthewDaggitt** [comment]
@mechvel please use https://github.com/agda/agda-stdlib/issues/1175, the issue that you yourself created, to discuss the issue of `NonZero` over arbitrary semirings.
