### ISSUE TITLE
More lemmas about `filter` in `Data.List`

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#933]
The following statement is usable and also trivial, but I fail to use it in a simplest way, somewhat like setting ``refl``. And I implement it as   
```
module _ ... {A : ...} {P ...} ... where
filter-step-positive :  (p? : Decidable P) {x : A} (xs : List A) → P x →         
                                                  filter p? (x ∷ xs) ≡ x ∷ (filter p? xs)      
filter-step-positive p? {x} xs Px  with  p? x                                    
...                               | yes _  =  refl                              
...                               | no ¬Px =  contradiction Px ¬Px              
```  
If a simpler proof is not possible, may be, the standard library needs the above proof?
A similar situation is with  ``filter-step-negatiive``.

**Edit**

- [ ] filter-++ :  filter p? (xs ++ ys) ≡  filter p? xs ++ filter p? ys
- [ ] filter-accept: P x → filter p? (x ∷ xs) ≡ x ∷ (filter p? xs)  
- [ ] filter-reject: \not P x → filter p? (x ∷ xs) ≡ filter p? xs
- [ ] filter-idem: filter p? ∘ filter p? ≗ filter p?

**Comment by MatthewDaggitt** [comment]
I don't think you're ever going to be able to prove something like that with `refl`. It's not as trivial as it looks, as it's always going to need to check the result of the decision procedure first. Feel free to open a PR with the lemmas. I would perhaps call them `filter-accept` and `filter-reject` though?

**Comment by mechvel** [comment]
On 2019-10-06 16:07, MatthewDaggitt wrote:
> I don't think you're ever going to be able to prove something like
> that with refl. It's not as trivial as it looks, as it's always going
> to need to check the result of the decision procedure first. Feel free
> to open a PR with the lemmas. I would perhaps call them filter-accept
> and filter-reject though?

I agree with  filter-accept and filter-reject.

--
SM

**Comment by MatthewDaggitt** [comment]
Added a list of the lemmas above. @mechvel feel free to add more suggestions below here if you find further lemmas you need.
