### ISSUE TITLE
Add `CommutativeSemigroup`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#938]
We're introducing `Algebra.Properties.CommutativeSemigroup` in v1.2, so it makes sense to avoid a backwards incompatibility later by adding `CommutativeSemigroup` now.

**Comment by mechvel** [comment]
But how to extract  commutativeSemigroup from CommutativeMonoid,
*-commutativeSemigroup and +-commutativeSemgroup  from CommutativeSemiring ?

CommutativeMonoid exports monoid, but now it is natural to add the export for commutativeSemigroup. 
Similar it is for   CommutativeSemiring.
?
