### ISSUE TITLE
Add `lift` for all the various monad transformers in the stdlib

### ISSUE THREAD

**Issue by gallais** [agda/agda-stdlib#939]
I needed `lift : M a -> StateT S M a` and could not find it. I suspect we also
miss it for numerous other monad transformers (e.g. `MaybeT` in `Data.Maybe.Categorical`).

Probably worth extending the whole [`RawIMonadT`](https://agda.github.io/agda-stdlib/Category.Monad.Indexed.html#1339) interface to always require
a `lift`.

**Comment by gallais** [comment]
Given that the PR was a breaking change not everyone is on-board with, I have
assigned it the milestone v2. Hopefully people will be more amenable to breaking
changes in a new major release.

**Comment by MatthewDaggitt** [comment]
Closed by #1841
