### ISSUE TITLE
Deprecate `_≤_` in `Data.Unit(.Polymorphic)`

### ISSUE THREAD

**Issue by MatthewDaggitt** [agda/agda-stdlib#946]
As discussed in #925 the order `_≤_` actually coincides with `_≡_` for `Data.Unit(.Polymorphic)`. We should deprecate `_≤_` and replace all proofs with `_≡_`.

**Comment by JacquesCarette** [comment]
So `_≤_` is actually not used internally in the library, nor any of the various things that depend on it.  I've got a check-in that just deletes it, I'll submit a PR.

But that's probably wrong, as the title of this issue talks about deprecation. Somehow I doubt that any code would actually be affected, as it's unlikely anyone relies on the ordering of `Data.Unit`. But I'm not sure how I would go about searching the wider internet for that.
