### ISSUE TITLE
map-cong generalization

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#95]
I have an impression that it is needed a generalizied version of map-cong.
1) The condition of  
`f ≗ g` 

needs to be relaxed to  
`All (\x → f x ≡ g x) xs`.

Because it often occurs that the latter condition is satisfied while the former is not.  

2) Similar it is with  map-id.
3) Another generalization for map-cong, map-id  can be for maps to a setoid, with  
`f x ≈ g x`

**Comment by MatthewDaggitt** [comment]
1. added in 5727880
2. I don't really understand how you would have a weaker version of `map-id`. Can you provide the envisaged type?
3. Might be added to the library later. Maybe when `All₂` gets added to lists.

**Comment by mechvel** [comment]
The whole proposition by new:

``open import Function using (id)``
``open import Relation.Binary.PropositionalEquality using (_≡_)``
``open import Data.List using (List; map)``
``open import Data.List.All using (All)``

``_≗_on_ :  ∀ {a b} {A : Set a} {B : Set b} → (A → B) → (A → B) → List A → Set _``
``f ≗ g on xs =``
             ``All (\x → f x ≡ g x) xs``

``map-cong-xs : ∀ {a b} {A : Set a} {B : Set b} {f g : A → B} → (xs : List A) →``
                          `` f ≗ g on xs → map f xs ≡ map g xs``
``map-cong-xs = ...``

`` map-id-xs :  ∀ {a} {A : Set a} {f : A → A} → (xs : List A) →``
                       ``f ≗ id on xs → map f xs ≡ xs``
`` map-id-xs = ...``

This introduces the denotation  ``_≗_on_`` and generalizations for  map-cong and map-id respectively.

**Comment by andreasabel** [comment]
I think `All (\x → f x ≡ g x) xs` is preferable to `f ≗ g on xs` in the standard library.  (Agda will expand it anyway in your proofs.)

**Comment by mechvel** [comment]
I like better  ``f ≗ g on xs``,
but let the developers decide.

**Comment by MatthewDaggitt** [comment]
These properties now exist as of 4ea2e1c
