### ISSUE TITLE
comments in Nat.Binary.Properties in lib-1.2

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#979]
It is written there
-- Comparisons and decidability are not implemented via the morphism so as        
-- to avoid reverting to linear time for the decision procedures.                 
```<-cmp : Trichotomous _≡_ _<_  
...
```
I would write 
"Comparisons and decidability for inequalities are not implemented via toℕ in order to preserve         
logarithmic evaluation cost for these decision procedures".

1) "reverting to linear time" causes the question "why reverting?"  
2) toℕ is more definite than "morphism".

Similar it is for ``_≤?_``.
?

**Comment by MatthewDaggitt** [comment]
Closed with a905fce0
