### ISSUE TITLE
names in Nat.Binary.Properties in lib-1.2

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#980]
This is about
```
2[1+_]-double-suc : 2[1+_] ≗ double ∘ suc                                         
...                               
1+[2_]-suc-double : 1+[2_] ≗ suc ∘ double 
```
Is not it more natural to call them ``2[1+_]≗double∘suc`` and  ``1+[2_]≗suc∘double`` 
respectively?

**Comment by MatthewDaggitt** [comment]
I agree in isolation those names would perhaps be better. However we don't use that naming convention anywhere else in the library. e.g. https://github.com/agda/agda-stdlib/blob/ff24628f43ad16bb4865e4e999d70e9062ffdefa/src/Data/Integer/Properties.agda#L953

is not called `suc∘pred≗id` and I think it's more important to be consistent.

I would be more open to a request to change it everywhere in the library, but I'm unsure of the cost-benefit analysis. The current names aren't bad per se...
