### ISSUE TITLE
Nat.Binary comments in CHANGELOG.md

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#981]
It is written there
> The current implementation of binary naturals in Agda has proven hard to work with.                                                 
> Therefore a new, simpler implementation which avoids using `List` has been added                                                                               > as `Data.Nat.Binary`. 

 I suggest to change this to 
"The current implementation of binary naturals in Agda has not enough functionality and 
has proven hard to work with.  Therefore a new, simpler implementation which is based on a different representation for binary numbers has been added as `Data.Nat.Binary`. 
"
I suggest this because 
* the main initial goal was to extend the functionality (more proofs etc.),
* the new implementation still may use List, but for a different purpose, while the main difference is in using another Bin representation.

**Comment by MatthewDaggitt** [comment]
Sorry this is too late to change. The CHANGELOG has been released.

**Comment by mechvel** [comment]
This is for the the next library release.

**Comment by MatthewDaggitt** [comment]
But that won't be in the next CHANGELOG...
