### ISSUE TITLE
Add `pred n ≤ n` to `Data.Nat.Properties` 

### ISSUE THREAD

**Issue by mechvel** [agda/agda-stdlib#992]
This is on lib-1.2, Data.Nat.Properties.
I suggest to add to further versions
```
pred-n≤n :  ∀ {n} → pred n ≤ n                                                     
pred-n≤n =   ≤⇒pred≤ ≤-refl                                                           
```
because this function is probably used quite often.

**Comment by MatthewDaggitt** [comment]
As always, feel free to open a PR.

**Comment by mechvel** [comment]
done

**Comment by Blaisorblade** [comment]
For onlookers: This is in #914.

**Comment by umazalakain** [comment]
Can be found in https://github.com/agda/agda-stdlib/blob/master/src/Data/Nat/Properties.agda#L1571
