### ISSUE TITLE
migrating proofs from List.Properties to Vec.Properties

### ISSUE THREAD

**Issue by MirceaS** [agda/agda-stdlib#997]
I noticed that Vec.Properties is missing a lot of the properties proved for Lists, such as the fact that map commutes with _++_.
Shouldn't most of the proofs in List.Properties be copied over to Vec and adapted (I believe most changes to the proof itself would be minimal)?

**Comment by MatthewDaggitt** [comment]
The library tends to expand organically with people adding proofs when they need them themselves. So if something obvious is missing it tends to mean that no-one has used it yet not that we shouldn't have it! We'd definitely welcome any pull request porting over any that you've found you've needed :smile:

**Comment by MatthewDaggitt** [comment]
Closing this, as it doesn't have any concrete suggestions.
